<?php
/**
 * ADMIN ONLY — LMFT California Clinical Form A answer key items 1–25 (PROMPT 13).
 * Secured answer + rationale mapping. Never exposed to learners.
 *
 * @package CTA_LMS
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'CTA-LMFT-CA-FA-001' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-DI-014',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The client has more than six months of marked gender incongruence, distress regarding sex characteristics, a persistent desire to be rid of those characteristics, and clinically significant occupational/social impairment. APA requires at least two manifestations of marked incongruence for adolescents/adults, persistence of at least six months, and clinically significant distress or impairment.',
			'B' => 'The distress is not merely a general reaction to an external stressor; it remains specifically related to sex characteristics even in affirming environments.',
			'C' => 'Major depression does not adequately explain the persistent incongruence-specific distress established in the stem.',
			'D' => 'Body dysmorphic disorder concerns a perceived defect in appearance; the concern here is specifically gender incongruence rather than a belief that a body feature is defective.',
		),
	),
	'CTA-LMFT-CA-FA-002' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-CE-036',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Distress and impairment should be assessed, but giving them primary emphasis can obscure the protective processes specifically demonstrated in the vignette.',
			'B' => 'Social support is an important protective factor, but resilience cannot be evaluated from interpersonal support alone.',
			'C' => 'Daily structure, exercise, and job-search behavior are relevant coping behaviors, but the option does not adequately integrate interpersonal and personal protective resources or remaining vulnerabilities.',
			'D' => 'The client is distressed but maintaining substantial functioning through routines, support, problem-solving, and personal strengths. The appropriate evaluation is to determine how those protective processes are working while also identifying areas that remain vulnerable.',
		),
	),
	'CTA-LMFT-CA-FA-003' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-CE-004',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => '“Communication problems” means different things to the two partners. Asking for concrete examples, subjective meaning, and desired change operationalizes the presenting concern before the therapist moves into explanations or interventions.',
			'B' => 'Conflict frequency and escalation are relevant, but this option begins defining the problem around conflict mechanics when one partner has already described emotional disconnection outside arguments.',
			'C' => 'Family-of-origin communication may later inform case formulation, but it does not first establish what each partner means by the current presenting problem.',
			'D' => 'Individual stress and mood can influence communication, but assessing them first risks reframing a relational presentation as primarily individual before the couple\'s concerns have been clarified.',
		),
	),
	'CTA-LMFT-CA-FA-004' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-CR-012-R1',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'School reentry planning may be useful, but the child\'s broader crisis picture includes separation fears, nightmares, and disrupted home routines; restoration of predictable routines and safety is the more immediate developmental priority.',
			'B' => 'A young child after school violence benefits from age-appropriate reassurance and coping, active caregiver support, predictable routines, and monitoring of recovery and functioning.',
			'C' => 'Therapeutic play can be useful, but organizing early care around trauma reminders is less direct than restoring safety, caregiver support, and ordinary routines.',
			'D' => 'Behavioral expectations may help structure routines, but framing regression primarily through behavior management underemphasizes the child\'s developmentally understandable trauma response.',
		),
	),
	'CTA-LMFT-CA-FA-005' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-TX5E-003-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Mapping the family pattern can increase awareness, but it keeps treatment at the observation level rather than increasing differentiated direct contact.',
			'B' => 'Practicing an I-position is useful preparation, but the sibling remains part of the communication system and direct contact has not yet replaced the triangle.',
			'C' => 'Ending messenger behavior and observing systemic reactions addresses triangulation, but it does not add the differentiated direct communication needed to work with emotional cutoff.',
			'D' => 'Best answer. Directly stating an I-position while maintaining self-definition and ending sibling mediation combines differentiation with reduction of cutoff and triangulation.',
		),
	),
	'CTA-LMFT-CA-FA-006' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-TX5F-004-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Separate consultations may clarify each provider\'s rationale, but the therapist would still be left to reconcile recommendations that should be coordinated among the treating providers.',
			'B' => 'Selecting whichever recommendation seems to fit the current flare does not resolve the interdisciplinary conflict and places the therapist in the role of choosing between medical recommendations.',
			'C' => 'A shared summary creates common information, but separate written replies can preserve the disagreement and leave integration to the therapist.',
			'D' => 'Best answer. Bringing both providers into a joint reconciliation allows the apparently conflicting recommendations to be clarified and translated into shared treatment parameters.',
		),
	),
	'CTA-LMFT-CA-FA-007' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-CE-041',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Psychiatric evaluation could be indicated if prominent mood, psychotic, or other psychiatric features suggested that direction, but those features are not established here.',
			'B' => 'Gradually worsening cognitive difficulties are affecting complex daily functioning, and a general medical evaluation has not resolved the concern. Specialized psychological or neurocognitive testing can characterize the pattern, severity, and functional implications of the deficits more precisely.',
			'C' => 'Repeated brief screening may document change but would delay the more comprehensive specialized assessment already supported by progressive functional decline.',
			'D' => 'Returning for another general medical evaluation repeats an assessment level that has already failed to clarify the specific cognitive concern.',
		),
	),
	'CTA-LMFT-CA-FA-008' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-CP-006-R2',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'An open monthly group for caregivers of varied progressive illnesses may provide useful peer support, but it does not match the specified population, closed format, time period, or planned psychotherapy purpose.',
			'B' => 'This is the strongest distractor. It matches the population, duration, and practical-skill goals, but it is primarily an education class with fixed lessons and home practice. It does not provide the peer-process and clinically screened psychotherapy structure needed for the stated isolation, coping, communication, and boundary outcomes.',
			'C' => 'Combining current and bereaved caregivers changes both the population and principal clinical focus. A grief-centered group would not provide the coherent caregiver-adjustment and practical-skills framework specified.',
			'D' => 'The requested service is a closed, time-limited psychotherapy group for current dementia caregivers. Its goals combine relational support, coping, communication and boundary work, and practical caregiving skills. D matches the intended population, includes a psychotherapy process rather than education alone, and screens for clinical fit and stability.',
		),
	),
	'CTA-LMFT-CA-FA-009' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-CE-027',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'focuses on identifying who starts conflict, which can obscure reciprocal maintenance.',
			'B' => 'may eventually illuminate formative influences but moves to historical explanation before establishing the current pattern.',
			'C' => 'evaluates individual vulnerabilities but similarly risks locating the problem within the partners rather than first clarifying their interaction.',
			'D' => 'The vignette presents a reciprocal pursue-withdraw pattern. Tracking a recent disagreement sequentially allows the therapist to identify each partner’s behavior, interpretation, escalation, and response to the other rather than assigning the pattern to one individual.',
		),
	),
	'CTA-LMFT-CA-FA-010' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-TX5C-006',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Choice and a timer can support engagement, but one sustained work period does not adequately match the child’s attentional difficulties and may leave the repeated-reminder pattern intact.',
			'B' => 'Reducing distraction may help, but extended independent work does not directly support task sequencing or replace the repeated verbal prompting that is escalating parent-child conflict.',
			'C' => 'Best answer. Short work intervals and a visible sequence support attention and executive functioning, while one neutral cue replaces repeated reminders that contribute to frustration and conflict.',
			'D' => 'A reward system can increase motivation, but the stem primarily reflects task-organization and prompting difficulties rather than a simple lack of reinforcement.',
		),
	),
	'CTA-LMFT-CA-FA-011' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-CP-010',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Trauma-memory exposure may eventually be appropriate, but it places trauma processing ahead of current dangerous and treatment-interfering behaviors.',
			'B' => 'The case includes recurrent self-injury urges, rapid emotional escalation, impulsive behavior, and treatment-interfering absences. B organizes treatment around a priority hierarchy, uses behavioral chain analysis to understand the problem behaviors, and develops regulation and crisis-survival skills. These are defining DBT planning structures.',
			'C' => 'Disputing rigid demands and global self-ratings is REBT planning. It does not provide the behavioral hierarchy and skills-acquisition structure indicated here.',
			'D' => 'Examining unconscious conflict and relational expectations is psychodynamic. Insight may be useful, but it does not directly organize the immediate behavioral priorities.',
		),
	),
	'CTA-LMFT-CA-FA-012' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-CE-012-R1',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Diagnoses, hospitalizations, clinicians, and medications provide historical data but do not establish how symptoms and functioning changed in relation to treatment.',
			'B' => 'A useful mental-health treatment history requires understanding what happened over time—symptom onset, severity, intervention, response, recurrence or remission, and functional change.',
			'C' => 'The hospitalization period is important, but focusing primarily on the most intensive episode produces an incomplete longitudinal history.',
			'D' => 'Medication response is an important component, but it captures only one part of a history that also includes psychotherapy, hospitalization, symptom course, and functioning.',
		),
	),
	'CTA-LMFT-CA-FA-013' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-CR-007-R1',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'The therapist should address immediate health needs, but waiting for corroborating records imposes a proof threshold that is higher than the reporting standard and delays the protective response.',
			'B' => 'Confronting the caregiver before reporting places investigation ahead of the mandated protective action and could also complicate the client\'s safety.',
			'C' => 'The presentation provides reasonable suspicion of neglect and possible financial abuse along with current health and safety concerns. The appropriate response is to address those needs and make the protective report without waiting for definitive proof.',
			'D' => 'Alternative care and resources may be necessary, but a mandated reporting duty is not optional based solely on the client\'s preference once the reporting threshold is met.',
		),
	),
	'CTA-LMFT-CA-FA-014' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-CR-004-R1',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Current intent to die, a specific plan, access to means, preparatory behavior, and inability to maintain safety constitute a high-acute-risk presentation. Direct observation and secure emergency psychiatric transfer match that level of risk.',
			'B' => 'Removing one means and relying on a support person for transport still depends on informal support despite the client\'s stated inability to maintain safety independently.',
			'C' => 'Additional consultation or fuller assessment delays disposition even though the stem already provides enough information to establish the need for secure emergency intervention.',
			'D' => 'Safety planning and discharge with continuous support are inadequate when current suicidal intent and inability to maintain safety are already established.',
		),
	),
	'CTA-LMFT-CA-FA-015' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-LE6-001',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'This identifies relevant goals and role concerns, but another private meeting can create additional expectations before the therapist jointly clarifies the proposed change with both members of the current conjoint treatment.',
			'B' => 'Separate meetings may sometimes be useful, but they can introduce new privacy expectations and are not necessary before the therapist jointly reviews the treatment-purpose and client-role change.',
			'C' => 'Best answer. A move from conjoint therapy to one partner\'s individual therapy changes the treatment purpose, client roles, privacy expectations, and record implications. Those expectations should be reviewed with both current clients before the structure changes.',
			'D' => 'Ending conjoint treatment may ultimately be appropriate, but automatic closure is not required simply because one partner requested a role change. The first task is clarification of the proposed treatment structure.',
		),
	),
	'CTA-LMFT-CA-FA-016' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-CE-026',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'substitutes network size and frequency for relationship quality.',
			'B' => 'Frequent interaction does not necessarily equal meaningful social connection. Assessing which relationships provide reciprocity, dependable contact, emotional support, and practical assistance determines how the client’s network actually functions during stress.',
			'C' => 'introduces social anxiety and avoidance as possible explanations before evaluating the existing relationships themselves.',
			'D' => 'appropriately assesses closeness but does not sufficiently examine the broader functional availability and reciprocity of the support network.',
		),
	),
	'CTA-LMFT-CA-FA-017' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-TX5F-001-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Specific requests may improve the immediate disagreement, but this option narrows the intervention to problem solving between two members rather than using the conflict as group-wide therapeutic material.',
			'B' => 'Best answer. In an interpersonal group, a safe live conflict can be examined in the here-and-now for both the dyadic process and its effect on participation throughout the group.',
			'C' => 'Prior interpersonal patterns may become relevant, but moving quickly to historical material bypasses the current interaction that is already available for therapeutic work.',
			'D' => 'Repair strategies may be useful later, but generating future responses moves away from examining the live relational process and its impact on the whole group.',
		),
	),
	'CTA-LMFT-CA-FA-018' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-TX5E-004',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. A behavioral experiment that tests the feared prediction while dropping the safety behavior provides direct evidence about both the belief and the role of repeated checking in maintaining anxiety.',
			'B' => 'Thought records can support cognitive restructuring, but completing them after repeated checking leaves the safety behavior intact and provides a weaker test of the feared prediction.',
			'C' => 'Graded practice can be appropriate, but retaining checking during the experiment prevents the client from learning whether the feared outcome occurs without the safety behavior.',
			'D' => 'Evidence review and coping statements are CBT-consistent, but they remain primarily verbal and do not directly test what happens when the client stops the maintaining checking behavior.',
		),
	),
	'CTA-LMFT-CA-FA-019' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-DI-003-R1',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Adjustment disorder would be less appropriate when a full major depressive syndrome is established.',
			'B' => 'For four weeks postpartum, the client has persistent depressed mood, anhedonia, worthlessness, concentration problems, psychomotor slowing, appetite reduction, insomnia independent of infant waking, and substantial impairment. This is a full depressive syndrome rather than a transient postpartum emotional reaction. APA describes major depression as involving persistent depressed mood and/or loss of interest with associated cognitive, somatic, and functional symptoms.',
			'C' => 'The course is far too brief for persistent depressive disorder, which APA defines as a depressive course of at least two years in adults.',
			'D' => 'No manic or hypomanic history is provided.',
		),
	),
	'CTA-LMFT-CA-FA-020' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-LE6-008',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'A balanced decision exercise may support autonomy, but it does not directly address the therapist\'s recognized pattern of allowing personal values to steer treatment recommendations.',
			'B' => 'Referral can become appropriate if the therapist cannot practice neutrally, but the first response is to manage the therapist\'s value interference rather than make referral the default.',
			'C' => 'Best answer. The therapist has recognized personal values influencing recommendations. Returning treatment to the client\'s goals, using outside clinical perspective as needed, documenting the direction, and monitoring later recommendations directly addresses the professional-management problem.',
			'D' => 'This respects the client\'s goals, but it does not directly examine or manage the therapist\'s own value interference, which is already affecting recommendations.',
		),
	),
	'CTA-LMFT-CA-FA-021' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-DI-009-R1',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The presentation does not establish the necessary mood-psychosis relationship for schizoaffective disorder.',
			'B' => 'There is no major depressive episode organizing the psychosis.',
			'C' => 'The corrected stem establishes more than six months of continuous disturbance, including social/occupational deterioration and negative symptoms, together with a clear active period containing hallucinations, delusions, and disorganized speech. Mood, substance, and medical explanations are not supported. APA identifies hallucinations, delusions, disorganized speech/thinking, and impaired functioning among schizophrenia\'s central features.',
			'D' => 'Schizophreniform disorder is the important duration distractor, but the continuous disturbance now exceeds the shorter schizophreniform course.',
		),
	),
	'CTA-LMFT-CA-FA-022' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-TX5E-007-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. Solution-oriented treatment emphasizes exceptions and what is already working. The successful week provides concrete evidence that can be examined and translated into a small, repeatable next step.',
			'B' => 'The miracle question is consistent with the approach, but an actual recent exception is already available and gives more immediately usable information than constructing a hypothetical preferred future.',
			'C' => 'Coping questions can highlight resilience, but they center on surviving the usual deadline-pressure pattern rather than expanding the successful exception the client has already demonstrated.',
			'D' => 'Compliments and scaling are solution-oriented tools, but setting a larger productivity goal skips the more useful task of discovering what made the successful week possible and repeatable.',
		),
	),
	'CTA-LMFT-CA-FA-023' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-CE-002-R1',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Reviewing the EAP structure and confidentiality is appropriate, but the response remains more administratively focused and does less to establish a working therapeutic alliance with the reluctant client.',
			'B' => 'Exploring what feels inaccurate is useful, but concentrating on what the client rejects or does not want is less effective than also identifying a possible personally meaningful purpose for participation.',
			'C' => 'The client\'s skepticism and external referral make engagement the immediate task. C acknowledges the referral without adopting the employer\'s interpretation, elicits the client\'s own perspective, and looks for a personally meaningful reason to use treatment.',
			'D' => 'Offering choices can support autonomy, but choosing between an incident and current stress before clarifying the client\'s own understanding of the problem moves into content selection before engagement is sufficiently established.',
		),
	),
	'CTA-LMFT-CA-FA-024' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-TX5C-003',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'A scheduled check-in may reduce frequency, but it can preserve reassurance as the primary way the client regulates anxiety rather than changing the maintaining cycle.',
			'B' => 'Validation is clinically useful and may reduce conflict, but exploring separation fears does not as directly target the repeated reassurance-seeking that is maintaining anxiety and relational strain.',
			'C' => 'Best answer. The intervention targets the anxiety-maintaining behavior while also changing the partner response that reinforces the cycle, directly addressing both symptoms and their effect on the relationship.',
			'D' => 'Tracking can improve awareness of triggers, but the client already recognizes the checking pattern and is ready for an intervention that changes it rather than another observation period.',
		),
	),
	'CTA-LMFT-CA-FA-025' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-CR-013',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'School attendance and routine restoration matter, but focusing primarily on attendance underaddresses the adolescent\'s grief, guilt, sleep disruption, and crisis response.',
			'B' => 'Peer death and guilt warrant continued direct safety assessment, but they do not by themselves establish imminent suicide risk requiring urgent crisis transfer.',
			'C' => 'Structured retelling of the death is not required as the first intervention and may exceed the adolescent\'s readiness during the early grief crisis.',
			'D' => 'Developmentally appropriate grief support, continued safety monitoring, caregiver involvement, and gradual restoration of functioning match the adolescent\'s current needs without overpathologizing or underresponding.',
		),
	),
);
