<?php
/**
 * ADMIN ONLY — LMFT California Clinical Form A answer key items 101–125 (PROMPT 17).
 * Secured answer + rationale mapping. Never exposed to learners.
 *
 * @package CTA_LMS
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'CTA-LMFT-CA-FA-101' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-CE-014',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The vignette already signals increased use, unsuccessful attempts to cut down, and occupational and relational consequences. Mapping those dimensions over time directly evaluates the problematic alcohol-use pattern.',
			'B' => 'Tolerance, withdrawal, and consumption pattern are relevant but too narrow because clinically significant substance problems are not defined only by physiological features.',
			'C' => 'Emotional triggers and coping motives may help explain use, but this option gives antecedents priority over the impaired control and consequences already evident.',
			'D' => 'Partner concerns, family history, and previous attempts to change provide useful context but are less direct than assessing the client\'s current use pattern and functional consequences.',
		),
	),
	'CTA-LMFT-CA-FA-102' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-CE-034',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Symptom intensity and functioning matter, but comparing the client primarily with generalized bereavement patterns risks imposing norms that may not fit the client\'s cultural grieving practices.',
			'B' => 'Family reactions are relevant, but this approach overemphasizes the relatives\' responses rather than evaluating the client\'s complete experience of grief.',
			'C' => 'Grief must be evaluated in relation to the meaning of the loss, cultural mourning practices, support, functioning, and interpersonal context. The family\'s criticism makes cultural and relational context particularly important rather than automatically indicating abnormal grief.',
			'D' => 'Prior loss experiences and spiritual beliefs may provide useful background, but they do not address the current interaction among grief, culture, support, functioning, and family expectations as directly.',
		),
	),
	'CTA-LMFT-CA-FA-103' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-DI-002',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'A medication-induced explanation cannot account for the earlier spontaneous manic episode.',
			'B' => 'Major depressive disorder with mixed features does not replace a bipolar I diagnosis once a manic episode is established.',
			'C' => 'The decisive evidence is the earlier spontaneous eight-day episode of expansive mood with decreased need for sleep, grandiosity, pressured speech, risky behavior, and serious occupational impairment. That episode predates antidepressant exposure and supports mania independently of the later medication-associated activation.',
			'D' => 'Cyclothymia involves chronic subthreshold symptoms rather than a full manic episode.',
		),
	),
	'CTA-LMFT-CA-FA-104' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-TX5A-005',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Transparency agreements may support trust repair, but they do not by themselves address the interaction pattern in which reassurance seeking and defensive withdrawal intensify each other.',
			'B' => 'Understanding pre-affair relationship problems may eventually be useful, but delaying trust-focused work can leave the current injury and escalating communication cycle untreated.',
			'C' => 'Positive interactions are important, but restricting discussion before the injured partner’s core trust concerns have been addressed may increase rather than reduce insecurity.',
			'D' => 'Best answer. The therapist can address the trust rupture while simultaneously changing the accusation-withdrawal pattern that is maintaining distress and preventing productive repair.',
		),
	),
	'CTA-LMFT-CA-FA-105' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-TX5D-001',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Immediate transfer of all responsibility may exceed the teen’s current confidence and turns developmental progression into an abrupt withdrawal of support rather than a scaffolded transition.',
			'B' => 'Maintaining the current arrangement can reinforce dependence and misses the teen’s stated readiness to practice developmentally appropriate autonomy while anxiety is improving.',
			'C' => 'Understanding the parent’s fears may be useful, but delaying behavior change leaves the developmental task unchanged despite a clear opportunity for supported progression.',
			'D' => 'Best answer. Graded autonomy with explicit parent step-back points supports adolescent developmental progression while preserving enough structure for the teen to learn from manageable mistakes.',
		),
	),
	'CTA-LMFT-CA-FA-106' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-LE6-011-R1',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'Best answer. The therapist should address the newly established pattern, move clinical exchanges to an appropriate treatment channel, define response expectations, assess any immediate needs already communicated, and create a clear plan for future between-session contact.',
			'B' => 'Documenting messages and reserving detailed work for sessions are reasonable, but continuing the same personal-number arrangement leaves the boundary, privacy, and response-expectation problem largely unchanged.',
			'C' => 'Moving to a secure option is plausible, but a blanket direction to stop messaging and a business-hours rule do not fully address the existing clinical material or create a broader mutually understood communication plan.',
			'D' => 'Blocking the channel and redirecting the client to emergency resources is unnecessarily restrictive because the stem does not describe an emergency or misuse requiring abrupt termination of contact.',
		),
	),
	'CTA-LMFT-CA-FA-107' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-CE-005',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Workplace functioning could become a useful goal, but the option anchors too strongly to the employer\'s concerns before determining whether the client sees them as relevant.',
			'B' => 'Clarifying documentation and confidentiality is necessary, but framing the decision around whether sessions should primarily address referral concerns does not adequately explore the client\'s own motivation or possible goals.',
			'C' => 'Consequences and reservations are appropriate to discuss, but identifying merely a practical goal can still bypass the distinction between mandatory attendance requirements and personally meaningful therapeutic work.',
			'D' => 'The therapist needs to distinguish the external conditions of the EAP referral from the client\'s own possible reasons for participating. D addresses both without assuming that the employer\'s concerns must become the client\'s treatment goals.',
		),
	),
	'CTA-LMFT-CA-FA-108' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-CE-029',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Reduced desire emerged during both a medication change and increased relationship conflict. Clarifying chronology across medical, relational, sexual, and distress variables allows the therapist to evaluate multiple plausible contributors without prematurely selecting one.',
			'B' => 'gives medication effects priority before the temporal relationship is established.',
			'C' => 'does the same with relationship tension.',
			'D' => 'adds useful historical and contextual information but is less directly responsive to the recent change and its competing possible contributors.',
		),
	),
	'CTA-LMFT-CA-FA-109' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-TX5D-004',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. The symptoms fit situational displacement stress without trauma reexperiencing or acute danger. Restoring disrupted routines and practicing brief relaxation directly addresses sleep, tension, irritability, and concentration.',
			'B' => 'Acceptance and social contact may reduce reactivity, but they underaddress the disrupted sleep and activity patterns identified in the stem.',
			'C' => 'Problem-solving around housing tasks is useful, but it focuses on the external problem more than the client’s physiologic and behavioral stress response.',
			'D' => 'Behavioral activation and social support may help functioning, but they are less directly matched to the immediate stress-response pattern than restoring routine and using stress-management skills.',
		),
	),
	'CTA-LMFT-CA-FA-110' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-CP-008',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Clarifying boundaries and strengthening subsystem leadership reflects structural family therapy. It may reduce the daughter’s immediate involvement but does not fully address the multigenerational repetition and differentiation process.',
			'B' => 'Prescribing tasks to interrupt a sequence is strategic. It emphasizes symptom interruption more than long-standing emotional-system reactivity across generations.',
			'C' => 'Accessing attachment fears and shaping responsive couple interactions is emotionally focused planning. It addresses the current partnership but underrepresents the broader family triangles and multigenerational transmission.',
			'D' => 'The daughter repeatedly becomes part of triangles, overfunctions when family anxiety increases, and reproduces the same pattern in her partnership. D therefore follows the formulation by mapping interlocking triangles, increasing differentiation, and promoting more direct, less reactive contact. Bowen theory identifies the family as an emotional unit and treats triangles, differentiation of self, and multigenerational transmission as central constructs.',
		),
	),
	'CTA-LMFT-CA-FA-111' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-TX5C-008-R3',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Balanced self-description can support body-image work, but keeping attention centered on preferred appearance features does not directly address the media-comparison and restrictive-behavior cycle described in the stem.',
			'B' => 'Best answer. It uses the emerging risk behavior and appearance-focused media exposure to shape treatment without turning the item into diagnosis or medical triage, and it broadens self-worth beyond body evaluation.',
			'C' => 'Regular eating and weight monitoring may belong in coordinated eating-disorder care, but using weight change as the body-image treatment metric can intensify weight focus and exceeds the stated psychotherapy target.',
			'D' => 'Family messages may contribute to body image, but delaying current behavior change leaves the active comparison and restriction pattern unaddressed while specialized consultation is already underway.',
		),
	),
	'CTA-LMFT-CA-FA-112' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-CE-010',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The vignette links worsening medical symptoms, inconsistent adherence, functional change, increased caregiving, and family conflict. Establishing the current medical/adherence pattern and its functional effects is necessary before determining how those factors are influencing the family system.',
			'B' => 'Relationship stress could affect adherence, but this choice reverses the assessment emphasis by beginning with the family conflict as a possible driver.',
			'C' => 'Family roles and support are relevant, but this option gives the relational consequences priority before the current health and adherence picture has been established.',
			'D' => 'Health literacy, access, and beliefs may help explain adherence but do not as directly assess the current relationship among adherence, symptoms, functioning, and caregiving burden.',
		),
	),
	'CTA-LMFT-CA-FA-113' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-DI-013-R1',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'ARFID may involve substantial restriction and low weight but lacks the weight/shape concerns central to this case.',
			'B' => 'Bulimia requires recurrent binge eating accompanied by compensatory behavior; those features are absent.',
			'C' => 'The client has significant food restriction resulting in low body weight, intense fear of weight gain, continued behavior preventing weight restoration, and explicit disturbance in body-weight/shape experience and self-evaluation. APA describes anorexia nervosa as restriction leading to low weight, driven by intense weight-gain fear and body-shape/weight concerns.',
			'D' => 'Although appearance concern occurs, the presentation is specifically organized around weight, shape, restrictive eating, and low body weight rather than an isolated perceived appearance defect.',
		),
	),
	'CTA-LMFT-CA-FA-114' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-TX5A-004',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. Premarital work should make implicit expectations explicit and give the couple a repeatable negotiation process for differences that are likely to recur after marriage.',
			'B' => 'Family-of-origin exploration may explain where expectations developed, but insight alone does not resolve the couple’s current need to negotiate concrete expectations and practice relationship skills.',
			'C' => 'A practical plan may be useful, but creating it before clarifying what the partners expect marriage and commitment to mean can produce agreements that do not address the underlying differences.',
			'D' => 'Communication skills are relevant, but postponing the actual decisions separates the skill from the commitment issues the couple is seeking help to negotiate.',
		),
	),
	'CTA-LMFT-CA-FA-115' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-LE6-006-R1',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'Delegating assignments is a meaningful safeguard, but the response waits to address broader treatment effects until the committee overlap is already affecting therapy.',
			'B' => 'Best answer. The therapist holds nonclinical authority over the client. Reducing that control where feasible, setting role and confidentiality boundaries, and monitoring clinical judgment directly manage the unavoidable overlap.',
			'C' => 'Client preference is important, but professional responsibility for evaluating and managing the power differential cannot be delegated to the client.',
			'D' => 'Documentation and later referral are plausible safeguards, but this option is more reactive and does not reduce the therapist\'s nonclinical authority as directly as the keyed response.',
		),
	),
	'CTA-LMFT-CA-FA-116' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-CR-016',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Anxiety and family functioning deserve attention, but a general mental-health-resource focus underaddresses the external separation threat, discrimination, practical needs, and systems barriers organizing the crisis.',
			'B' => 'The family faces possible forced separation, discrimination, fear of systems, disrupted routines, and reduced support use. Language-accessible, culturally responsive stabilization focused on practical needs and family functioning fits the crisis while preserving appropriate clinical role boundaries.',
			'C' => 'Migration and separation history may become clinically relevant, but requiring that history before stabilization makes immediate support depend too heavily on disclosure and prematurely prioritizes trauma-focused treatment.',
			'D' => 'Discrimination, institutional mistrust, and trusted community services are relevant, but this pathway underaddresses the broader practical separation, safety, resource, and role-boundary needs present now.',
		),
	),
	'CTA-LMFT-CA-FA-117' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-CE-028',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'compares too few relationships to establish the broader recurrence.',
			'B' => 'moves prematurely toward stable individual pathology.',
			'C' => 'Repeated ruptures across different friendships and romantic relationships suggest that the therapist should compare relationship sequences across time. Expectations, communication, repair attempts, and outcomes provide direct information about recurring interpersonal patterns.',
			'D' => 'appropriately looks for strengths and successful relationships but does not adequately evaluate the repeated rupture pattern that prompted the assessment.',
		),
	),
	'CTA-LMFT-CA-FA-118' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-CE-023-R1',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The presentation explicitly involves migration, evolving cultural identity, workplace discrimination, and family expectations. Evaluating these intersecting experiences and their functional impact most directly addresses the cultural and sociopolitical context of the presenting concerns.',
			'B' => 'Workplace power dynamics and discrimination deserve attention, but this option gives the occupational environment priority over the simultaneous family and acculturation issues.',
			'C' => 'Family values and intergenerational acculturation differences are important but represent only one side of the client\'s cross-context experience.',
			'D' => 'Mood, anxiety, and relative impairment can provide useful clinical information, but this option shifts emphasis toward symptom severity rather than first understanding the cultural and contextual processes described.',
		),
	),
	'CTA-LMFT-CA-FA-119' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-DI-006-R2',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'The assault is a qualifying traumatic exposure, and the presentation includes intrusion, avoidance, negative trauma-related beliefs and mood changes, hyperarousal, sleep disturbance, functional impairment, and persistence beyond one month. That pattern supports posttraumatic stress disorder.',
			'B' => 'Acute stress disorder is limited to the early post-trauma interval. The symptoms have persisted for seven weeks, beyond that acute period.',
			'C' => 'Panic disorder does not account for the organized trauma-linked intrusion, avoidance, negative beliefs, detachment, and hypervigilance described.',
			'D' => 'Adjustment disorder is not the best formulation when the more specific posttraumatic stress disorder syndrome is supported.',
		),
	),
	'CTA-LMFT-CA-FA-120' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-TX5E-005',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Diary-card review and target ranking are DBT-consistent, but they do not yet analyze the specific episode or identify where new skills can interrupt its behavioral sequence.',
			'B' => 'Mindfulness and distress-tolerance practice are plausible, but selecting skills generically is less precise than first linking them to the vulnerabilities and behavioral links in the completed episode.',
			'C' => 'Validation, pros-and-cons work, and commitment strategies can support treatment engagement, but they do not explain how the target behavior unfolded or where skills should be inserted.',
			'D' => 'Best answer. A behavior chain analysis traces vulnerabilities, the prompting event, links, and consequences, then supports a solution analysis in which skills are rehearsed at specific interruption points.',
		),
	),
	'CTA-LMFT-CA-FA-121' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-LE6-003',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. Paying the fee does not itself authorize disclosure of an adult client\'s treatment information. The therapist should preserve confidentiality and determine with the client whether any limited communication is authorized.',
			'B' => 'Attendance is itself protected treatment information. The absence of session detail does not create authority to disclose attendance or treatment status.',
			'C' => 'A general progress update is still a disclosure of protected treatment information. Financial responsibility does not create a general right to receive it.',
			'D' => 'The confidentiality limit is correct, but routing every future question through the client is unnecessarily categorical. The therapist can receive information and can clarify with the client whether any limited communication should be authorized.',
		),
	),
	'CTA-LMFT-CA-FA-122' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-LE6-009',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'This reduces some task burden, but the therapist is already missing clinically important information and follow-up. Preserving the full clinical caseload relies on workarounds rather than reducing practice demands to current functioning.',
			'B' => 'Shortening sessions and disclosing personal stress to clients do not directly correct the identified impairment and may unnecessarily shift the therapist\'s personal circumstances into treatment.',
			'C' => 'Administrative delegation and scheduling changes may help, but the stem shows impairment during clinical work itself. Keeping the full caseload is not the strongest protection.',
			'D' => 'Best answer. The therapist has evidence that current functioning is affecting attention and follow-through. Reducing workload to a manageable level, protecting continuity, and addressing the impairment directly prioritizes client welfare and competent practice.',
		),
	),
	'CTA-LMFT-CA-FA-123' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-CP-013',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The client repeatedly expects abandonment and interprets ordinary separation as evidence that close others will disappear. A addresses those recurring expectations within a consistent therapeutic relationship and strengthens reflective functioning when attachment fears become activated. Attachment-oriented psychotherapy links secure relationships with affect regulation, internal working models, reflective functioning, and change in painful relational repetitions.',
			'B' => 'Testing feared outcomes through planned separations and reducing reassurance through behavioral experiments is CBT.',
			'C' => 'Prioritizing self-harm and therapy-interfering targets, conducting chain analyses, and teaching distress-tolerance and interpersonal skills is DBT.',
			'D' => 'Exceptions, confidence scaling, and small changes from successful experiences are solution-focused.',
		),
	),
	'CTA-LMFT-CA-FA-124' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-TX5E-010-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Tracking and reframing the negative cycle are central EFT interventions, but the therapist has already slowed the cycle and accessed the primary vulnerable emotions beneath the positions.',
			'B' => 'Best answer. Once vulnerable fear and shame are accessible, EFT deepens those primary emotions and facilitates enactments in which partners communicate attachment needs directly, creating a new interactional experience.',
			'C' => 'Heightening can be useful in EFT, but intensifying the secondary positions of criticism and withdrawal would strengthen the cycle rather than deepen the vulnerable emotions already emerging beneath it.',
			'D' => 'Supportive behaviors may help outside session, but moving quickly to a behavioral agreement would bypass the attachment-based emotional engagement that the current EFT moment makes possible.',
		),
	),
	'CTA-LMFT-CA-FA-125' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-CE-018',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The clinically important fact is a marked change from previously strong academic functioning after relocation. Comparing baseline performance with the timing of the decline, the new educational environment, peer context, and organizational difficulties directly evaluates the academic change.',
			'B' => 'Attention or executive-functioning difficulties are possible, but this option begins testing a specific explanatory hypothesis before the broader academic change has been characterized.',
			'C' => 'Emotional and family factors may contribute, but the option similarly moves toward psychiatric or psychosocial explanation before fully evaluating academic functioning.',
			'D' => 'School data are useful, but the option focuses predominantly on the current school and does not adequately incorporate the student\'s previous academic baseline.',
		),
	),
);
