<?php
/**
 * ADMIN ONLY — LMFT California Clinical Form B answer key items 126–150 (PROMPT 24).
 * Secured answer + rationale mapping. Never exposed to learners.
 *
 * @package CTA_LMS
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'CTA-LMFT-CA-FB-126' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-DI-002-R1',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The elapsed time makes prolonged grief a legitimate competitor, but the client\'s dominant syndrome is not loss-centered yearning/preoccupation.',
			'B' => 'A full depressive syndrome is better supported than an adjustment response.',
			'C' => 'Sixteen months is shorter than the chronic adult duration required for persistent depressive disorder.',
			'D' => 'For six weeks, the client has generalized depressed mood, anhedonia, insomnia, concentration problems, global worthlessness, and impairment. Although bereavement remains contextually important, the syndrome is generalized rather than primarily organized around persistent yearning or preoccupation with the deceased. APA notes that major depressive episodes can occur in bereavement and distinguishes generalized depressive symptoms from loss-centered grief phenomena.',
		),
	),
	'CTA-LMFT-CA-FB-127' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-CE-038',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Pharmacy dates and the client’s calendar may help, but the strategy still depends substantially on the client’s uncertain reconstruction and may omit clinically relevant prescriber observations.',
			'B' => 'A complete prescribing record could contain the necessary information, but it is broader than needed for the focused assessment question.',
			'C' => 'The unresolved clinical question is the timing of medication changes in relation to mood symptoms. With authorization, focused consultation with the prescriber or targeted record review obtains exactly the collateral information needed without requesting unnecessarily broad material.',
			'D' => 'The prescriber may provide useful observations, but asking that clinician to determine whether medication caused the symptoms improperly transfers the therapist’s task of integrating the available clinical data.',
		),
	),
	'CTA-LMFT-CA-FB-128' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-TX5E-006-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. The recurrent cancellation follows vulnerable disclosure and is linked to an expectation about the therapist, making its defensive and relational function in the here-and-now treatment relationship especially important to explore.',
			'B' => 'Developmental history is psychodynamically relevant, but beginning there bypasses a repeated defense that is occurring directly in the therapeutic relationship and is already available for examination.',
			'C' => 'Free association may deepen access to unconscious material, but avoiding the recurrent cancellation pattern misses the clearest enactment connecting vulnerability, shame, and the therapist relationship.',
			'D' => 'A supportive approach may be appropriate when interpretation would overwhelm the client, but the stem does not establish that the client cannot tolerate exploration of the repeated defensive pattern now.',
		),
	),
	'CTA-LMFT-CA-FB-129' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-TX5B-001',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Private verbal processing can be offered without rejecting the family’s traditions, but the therapist should not assume that additional verbal disclosure is needed when the client has not identified it as a goal.',
			'B' => 'Examining different grieving contexts may increase awareness, but it still centers comparison of styles rather than first grounding treatment in the client’s own cultural definition of healthy mourning.',
			'C' => 'Imagery can be a legitimate grief intervention, but introducing a therapist-selected farewell exercise may not fit a client whose existing family practices already provide a meaningful mourning structure.',
			'D' => 'Best answer. The therapist should assess and support the client’s own cultural meaning of mourning rather than assuming that visible or verbal emotional expression is necessary for healthy grief.',
		),
	),
	'CTA-LMFT-CA-FB-130' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-CE-014-R1',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The client is exceeding the prescribed schedule, obtaining additional medication elsewhere, and experiencing functional consequences. Clarifying amount, source, control over use, co-use with other sedatives, and impairment directly evaluates the concerning use pattern.',
			'B' => 'Anxiety severity and intended prescription use are relevant but risk framing the extra doses primarily as symptom management rather than evaluating potentially problematic use.',
			'C' => 'Sedation and work impairment are important consequences, but this option focuses more on adverse effects than on the broader pattern of nonprescribed use.',
			'D' => 'Historical use and beliefs about medication may provide useful context but do not adequately assess the current pattern of obtaining and taking medication beyond the prescribed regimen.',
		),
	),
	'CTA-LMFT-CA-FB-131' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-TX5C-009-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Trigger work remains useful, but the current outpatient approach has not contained repeated return to heavy use or the resulting occupational and relationship impairment.',
			'B' => 'More frequent individual contact may add support, but the pattern shows a need for a more structured substance-use level of care rather than another small increase within the same treatment model.',
			'C' => 'Best answer. Repeated relapse with functional consequences despite engaged outpatient treatment supports stepping up to a structured intensive outpatient level while coordinating relapse-prevention work across services.',
			'D' => 'Couple treatment may eventually address relationship effects of substance use, but shifting away from the inadequately contained addictive behavior would leave the primary treatment need insufficiently addressed.',
		),
	),
	'CTA-LMFT-CA-FB-132' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-CE-025',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'gives depression premature explanatory priority.',
			'B' => 'The client’s social participation changed after the onset of chronic health limitations. Comparing prior and current functioning, desired connection, support availability, lost activities, and barriers allows the therapist to distinguish medically constrained participation from unwanted isolation and other possible contributors.',
			'C' => 'appropriately examines medical limitations but underrepresents the client’s social experience and desired connection.',
			'D' => 'assesses support quality but does not sufficiently characterize the larger change in social participation.',
		),
	),
	'CTA-LMFT-CA-FB-133' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-CP-001',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Attendance is a major functional concern and cannot be postponed, but the adolescent’s and family’s concerns must also meaningfully shape treatment. A creates a shared hierarchy that addresses attendance and lower-conflict problem solving while preserving adolescent and parent participation.',
			'B' => 'Attendance and compliance are measurable, but the parents and school are given controlling authority. The adolescent’s concerns are delayed until compliance has already been established.',
			'C' => 'Conflict reduction and autonomy are legitimate clinical priorities, but the plan makes school attendance contingent on the adolescent later endorsing it despite its current functional significance.',
			'D' => 'All identified concerns are included, but they are treated as equally urgent. Without a shared hierarchy, the plan lacks sequencing and may become difficult to implement and evaluate.',
		),
	),
	'CTA-LMFT-CA-FB-134' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-CR-004-R3',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'Intensive outpatient contact, means restriction, and support planning are active measures, but the client has escalating self-injury, impaired behavioral control, and no dependable immediate support; those facts make independent outpatient safety insufficient.',
			'B' => 'Medically serious self-injury can require a higher level of care, but relabeling the behavior as a suicide attempt disregards the client\'s stated nonsuicidal function and confuses T58 with T59.',
			'C' => 'Crisis consultation is useful, but discharging the client after consultation leaves unresolved the inability to interrupt escalating self-injury and the absence of dependable immediate support.',
			'D' => 'The acute injury has already been medically treated, leaving the core crisis question of escalating self-injury, loss of behavioral control, and unreliable independent safety. Same-day higher-level evaluation best matches that current risk state.',
		),
	),
	'CTA-LMFT-CA-FB-135' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-TX5D-001',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. The therapist first corrects the developmental expectation and then provides scaffolded co-regulation that can shift toward greater self-management as the child’s capacities develop.',
			'B' => 'Independent coping is a useful long-term goal, but the parents are already expecting more self-regulation than the child can reliably manage and need developmentally appropriate scaffolding first.',
			'C' => 'Clear limits on throwing are appropriate, but consequences alone do not address the parents’ inaccurate developmental expectation or teach the child the regulation skills needed before greater independence.',
			'D' => 'Family-of-origin exploration may clarify why the parents hold these expectations, but it does not directly answer what support is developmentally appropriate or provide an intervention for progression.',
		),
	),
	'CTA-LMFT-CA-FB-136' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-DI-017-R1',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The clinical concern is specifically the client\'s promotion, supervisory role conflict, workplace expectations, and strained peer relationships. Other areas remain stable, and no mental disorder is supported. DSM\'s “other conditions/problems that may be a focus of clinical attention” framework permits psychosocial and employment-related circumstances to be the reason for clinical care without requiring a psychiatric diagnosis. Current ICD-10-CM likewise maintains a dedicated category for problems related to employment and unemployment.',
			'B' => 'No intimate-partner relationship problem is identified as the treatment focus.',
			'C' => 'There is no educational problem.',
			'D' => 'Housing and financial circumstances are stable.',
		),
	),
	'CTA-LMFT-CA-FB-137' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-TX5A-007',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Individual parent-child processing may support adjustment, but it does not directly rebuild a sense of family continuity across the two households.',
			'B' => 'Separate household rituals can create predictability, but they may reinforce the children’s experience that the family exists as disconnected units rather than maintaining relationships across homes.',
			'C' => 'Best answer. Brief transition rituals and cross-home contact directly address the children’s sense of relational disappearance while acknowledging that family ties are changing rather than ending.',
			'D' => 'Improving schedules and handoff consistency can reduce tension, but the children’s stated problem is loss of relational continuity, not only logistical confusion.',
		),
	),
	'CTA-LMFT-CA-FB-138' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-CR-016-R2',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'Individual coping and school support can help, but this pathway still underrepresents the family-system disruption created by reunification after prolonged separation; the controlling need is family-centered communication and relational adjustment.',
			'B' => 'Household-role resources may be useful, but imposing or structuring roles too early can bypass the communication and relational adjustment problems created by the prolonged separation.',
			'C' => 'The family needs culturally and linguistically responsive, family-centered support that addresses reunification stress, communication, community connection, and current adjustment rather than locating the problem in one member.',
			'D' => 'Trauma processing may eventually be appropriate, but prioritizing it before current family communication and adjustment would not match the immediate reunification crisis.',
		),
	),
	'CTA-LMFT-CA-FB-139' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-CE-012',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Family stigma affected disclosure, attendance, support, and continuation of previous treatment. Those consequences are directly relevant to understanding the client\'s treatment history and expectations now.',
			'B' => 'Family beliefs and anticipated consequences are important, but this choice focuses primarily on current stigma rather than how it affected the prior course of treatment.',
			'C' => 'Treatment helpfulness and dissatisfaction should be reviewed, but the vignette specifically identifies family stigma as the factor that interrupted participation.',
			'D' => 'Privacy needs and secrecy burden matter, but this option is narrower than evaluating the full effect of stigma on prior help-seeking and treatment continuation.',
		),
	),
	'CTA-LMFT-CA-FB-140' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-CE-018',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Study habits and workload are plausible contributors, but this option narrows the evaluation toward performance-management factors.',
			'B' => 'Depression or anxiety could affect academics, but the available information does not justify making an emotional disorder the first explanatory frame.',
			'C' => 'Instructor data may clarify current academic difficulties but cannot by itself establish how current performance differs from the student\'s previous baseline or how other changes relate.',
			'D' => 'The student\'s academic decline occurs alongside changes in workload, health, and relationship stress. Comparing current performance with prior academic functioning while assessing these new conditions provides the strongest academic evaluation.',
		),
	),
	'CTA-LMFT-CA-FB-141' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-DI-003',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The client describes more than three years of depressed mood on most days, low energy, low self-esteem, poor concentration, hopelessness, and no substantial symptom-free period. That persistent course matches the chronic architecture of persistent depressive disorder.',
			'B' => 'Recurrent major depressive disorder implies discrete major depressive episodes rather than the continuous low-grade depressive course described.',
			'C' => 'No hypomanic-type periods are present.',
			'D' => 'The course is chronic rather than a time-limited reaction to an identifiable recent stressor.',
		),
	),
	'CTA-LMFT-CA-FB-142' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-TX5C-005',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. Predictable cues plus graded practice with manageable changes address rigidity around transitions, and a shared parent response reduces the inconsistent accommodation-versus-pushing pattern that is increasing family conflict.',
			'B' => 'Predictability can lower distress, but postponing flexibility practice may strengthen dependence on sameness and does not resolve the parents’ inconsistent responses to unavoidable changes.',
			'C' => 'Validation and limited choices can be useful during distress, but this primarily manages the moment rather than systematically increasing tolerance for change across repeated family situations.',
			'D' => 'Reinforcement may support adaptive behavior, but a reward plan alone does not provide the anticipatory structure and graded flexibility practice needed for the child’s transition difficulties.',
		),
	),
	'CTA-LMFT-CA-FB-143' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-CE-032-R1',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'centers the individual client’s caregiver burden and practical sustainability.',
			'B' => 'The caregiving conflict involves both historical sibling relationships and present roles, authority, resources, and support. Evaluating those variables together best characterizes how the primary support system is functioning around the aging parent’s care.',
			'C' => 'focuses primarily on recent disagreements and fairness.',
			'D' => 'emphasizes legal and practical decision authority. All are relevant, but none integrates the relational history and current caregiving organization as fully as required by T24.',
		),
	),
	'CTA-LMFT-CA-FB-144' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-CE-006',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Reviewing policies can reduce uncertainty, but administrative reassurance does not adequately assess the client\'s emotional and relational response to the earlier ending.',
			'B' => 'Reviewing what was helpful may inform treatment preferences but leaves the client\'s stated concern about abrupt termination largely unexplored.',
			'C' => 'Other abrupt losses could eventually be relevant, but moving immediately to a broader separation pattern risks overgeneralizing from the prior therapy experience before understanding it on its own terms.',
			'D' => 'The abrupt end of prior therapy is already affecting the client\'s trust and expectations. Exploring how it shaped expectations about continuity and future endings directly uses the prior therapy history to understand the current therapeutic process.',
		),
	),
	'CTA-LMFT-CA-FB-145' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-TX5E-007',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Linking current reactions to early object relationships can deepen understanding, but insight into origins does not by itself address the present inability to integrate positive and negative representations.',
			'B' => 'Transference can reveal similar representational shifts in therapy, but the central treatment task shown here is the client’s splitting of the partner into all-good and all-bad states.',
			'C' => 'Mourning an idealized image can support more realistic relating, but the goal is not simply to relinquish the positive representation; it is to integrate positive and disappointing aspects of the same person.',
			'D' => 'Best answer. Object relations treatment can facilitate integration of split representations so the client can maintain a more stable whole-object view and tolerate ambivalence when an important person disappoints.',
		),
	),
	'CTA-LMFT-CA-FB-146' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-CE-030',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'locates the concern primarily within the lower-desire partner.',
			'B' => 'A desire discrepancy is best understood through each partner’s desired frequency, meaning of sexual contact, expectations, initiation patterns, emotional responses, and degree of relational distress rather than by assuming one partner has a dysfunction.',
			'C' => 'appropriately evaluates relational context but is narrower than the sexual-interaction pattern itself.',
			'D' => 'contributes useful historical and cultural information but does not as directly evaluate how the current discrepancy is experienced and negotiated by the couple.',
		),
	),
	'CTA-LMFT-CA-FB-147' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-TX5B-003-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. The client identifies automatic agreement as a learned protective response that is now appearing in therapy. Naming its function and safely practicing a different preference directly works with that relational pattern.',
			'B' => 'Client-led agenda setting increases choice, but it does not explicitly help the client notice and revise the learned agreement response when it appears in the therapeutic relationship.',
			'C' => 'Exploring similar situations may clarify the pattern, but the behavior is occurring live in therapy and can be practiced safely within that relationship.',
			'D' => 'Grounding and structured choices can support safety and agency, but they do not directly rehearse expressing a preference that differs from the therapist’s suggestion.',
		),
	),
	'CTA-LMFT-CA-FB-148' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-CE-040',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Outpatient psychological testing could eventually provide useful information, but it is less directly situated to evaluate the academic demands, classroom behavior, and school-based functioning described.',
			'B' => 'Medical assessment may be indicated when relevant physical or developmental information suggests it, but the vignette does not establish a medical concern requiring priority over educational evaluation.',
			'C' => 'Family expectations and cross-setting differences deserve consideration, but continued family assessment alone does not provide the school-based educational and behavioral information still needed.',
			'D' => 'The student’s difficulties are persistent and especially apparent during classroom academic demands. A school-based evaluation is positioned to examine educational and behavioral functioning in the setting where the impairment is occurring.',
		),
	),
	'CTA-LMFT-CA-FB-149' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-CE-016',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Chronological age and classroom expectations are relevant comparison points but cannot alone establish the child\'s developmental functioning.',
			'B' => 'Home observations are useful but represent only one setting.',
			'C' => 'The child\'s abilities appear differently at home and school. Reviewing developmental history across domains while comparing task demands, supports, and performance in both settings provides the best basis for understanding that discrepancy.',
			'D' => 'School functioning is important, but focusing mainly on classroom information would repeat the same problem of privileging one environment.',
		),
	),
	'CTA-LMFT-CA-FB-150' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-TX5A-006',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. The client wants gradual physical closeness while maintaining control. A consent-based progression with clear stop and reconnection signals provides graded practice without overriding autonomy.',
			'B' => 'Opt-in nonsexual affection is appropriate and supportive, but it stays within already lower-intensity contact rather than providing a clear progression for approaching the touch responses the client wants to change.',
			'C' => 'Exploring meaning and coaching the partner’s response may improve emotional safety, but it does not directly provide the graded behavioral practice requested by the client.',
			'D' => 'Shared routines and already-safe touch can strengthen connection, but this approach largely remains inside the current comfort zone rather than building tolerance for desired physical closeness.',
		),
	),
);
