<?php
/**
 * ADMIN ONLY — LMFT California Clinical Form B answer key items 101–125 (PROMPT 23).
 * Secured answer + rationale mapping. Never exposed to learners.
 *
 * @package CTA_LMS
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'CTA-LMFT-CA-FB-101' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-TX5B-004',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. The intervention respects the military context in which emotional containment may have been adaptive while helping the couple develop a more flexible home-based relational response.',
			'B' => 'Emotion-labeling may be useful, but framing the problem primarily as a skill deficit risks ignoring the military context and the adaptive function the behavior previously served.',
			'C' => 'Additional space may reduce escalation, but it does not create a new communication pattern or help the couple translate deployment-based coping into a different relational environment.',
			'D' => 'Trauma assessment may be warranted if symptoms suggest it, but the stem does not establish trauma as the controlling problem and specifically presents a reintegration communication issue.',
		),
	),
	'CTA-LMFT-CA-FB-102' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-CE-023',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The client\'s vigilance occurs in the context of repeated racial microaggressions and a salient sociopolitical event. Exploring discrimination, racial identity, sociopolitical context, coping, support, and current functioning evaluates the experience without prematurely pathologizing it.',
			'B' => 'Anxiety symptoms may warrant assessment, but requiring symptoms to occur independently of discrimination-related triggers subtly shifts toward proving an internal disorder.',
			'C' => 'Workplace information is clinically useful but focuses too narrowly on the occupational setting.',
			'D' => 'The recent public event may have intensified distress, but emphasizing it risks minimizing the cumulative effect of repeated discrimination.',
		),
	),
	'CTA-LMFT-CA-FB-103' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-CR-003-R2',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'The remote suicide attempt is important historical risk information, but it does not by itself determine today\'s disposition when current intent, plan, preparation, and inability to maintain safety are absent.',
			'B' => 'The current presentation is dissociation-linked nonsuicidal self-injury with retained safety capacity. Direct suicide reassessment plus intensified outpatient work on the self-injury pattern appropriately responds to the present acute-risk state while incorporating the historical attempt.',
			'C' => 'Trauma-focused stabilization and attention to dissociation may be relevant, but keeping the usual session frequency underresponds to the current increase in self-injury; the remote attempt does not by itself require emergency transfer, but the present period warrants intensified outpatient follow-up.',
			'D' => 'Continuous partner monitoring improperly substitutes external surveillance for the client\'s own safety-management capacity and delays development of independent coping.',
		),
	),
	'CTA-LMFT-CA-FB-104' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-TX5C-007-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Body-neutrality work and self-care may support treatment, but they do not directly target the restriction-binge sequence that the stem identifies as the repeating behavioral mechanism.',
			'B' => 'Best answer. The client’s rigid restriction is immediately followed by binge episodes and renewed restriction. Directly changing the restrictive rules and eating pattern targets the mechanism maintaining the cycle.',
			'C' => 'Urge-surfing can help with binge impulses, but focusing only on the evening urge leaves the daytime restriction that repeatedly sets up the binge pattern.',
			'D' => 'Cultural meaning and self-compassion may reduce shame, but they do not directly interrupt the restrictive eating pattern that precedes the binges.',
		),
	),
	'CTA-LMFT-CA-FB-105' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-LE6-014-R1',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. When disclosure depends on an authorization under California\'s Confidentiality of Medical Information Act, Civil Code section 56.11 requires specified elements, including an expiration date or event. The stem expressly removes other disclosure authority.',
			'B' => 'The client\'s signature and identification of the parties are necessary but not sufficient when a required authorization element is missing.',
			'C' => 'Verbal confirmation does not cure the defective written authorization when the disclosure is being made pursuant to the authorization requirements in section 56.11.',
			'D' => 'Reducing the amount disclosed does not make an otherwise defective authorization valid.',
		),
	),
	'CTA-LMFT-CA-FB-106' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-TX5B-002-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Paced breathing and shorter segments can help arousal, but continuing before re-establishing present orientation does not adequately address dissociative disengagement.',
			'B' => 'Cognitive reappraisal is useful for fear-based misinterpretation, but the immediate problem is loss of present orientation and tracking during trauma processing.',
			'C' => 'Interoceptive exposure may be appropriate for panic-related fear of sensations, but deliberately evoking sensations is poorly matched to active dissociation in this moment.',
			'D' => 'Correct. Grounding first restores present orientation; trauma work can then continue in smaller segments that remain within the client’s tolerable range.',
		),
	),
	'CTA-LMFT-CA-FB-107' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-DI-014-R4',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'Gender dysphoria is not established merely by a nonbinary identity. The stem specifically states comfort with identity and body in an affirming setting and no distress about sex characteristics.',
			'B' => 'The anxiety remains temporally and contextually tied to family rejection rather than extending broadly across multiple unrelated life domains.',
			'C' => 'The anxiety began after an identifiable psychosocial stressor, causes significant impairment, and remains organized around that family-rejection stressor, supporting adjustment disorder with anxiety.',
			'D' => 'The symptoms are not organized primarily around fear of social scrutiny, embarrassment, or performance-based negative evaluation.',
		),
	),
	'CTA-LMFT-CA-FB-108' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-CR-005-R2',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'The interrupted attempt and continuing suicidal intent establish a high-acute-risk state that requires emergency psychiatric evaluation with direct observation rather than a pathway dependent on informal supervision or delayed disposition.',
			'B' => 'Means restriction and same-day psychiatric follow-up are important, and confirming a receiving appointment strengthens the plan, but continuing suicidal intent after an interrupted attempt requires emergency-level containment rather than a pathway that still depends on informal transport and outpatient transfer.',
			'C' => 'Additional consultation should not delay disposition when the interrupted attempt and continuing intent already establish a high-acute-risk state.',
			'D' => 'Roommate supervision places responsibility on informal support despite the client\'s stated intention to find another method and does not provide secure clinical containment.',
		),
	),
	'CTA-LMFT-CA-FB-109' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-CR-001-R3',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'Reduced responsiveness and slowed breathing after combined opioid, benzodiazepine, and alcohol exposure indicate potentially life-threatening CNS and respiratory depression. EMS transport and continued observation are the most direct response.',
			'B' => 'Prescriber contact and emergency-department transport are active responses, and a receiving handoff is useful, but relying on transport by a responsible adult is less appropriate than activating EMS when the client is already difficult to arouse and breathing is slowed.',
			'C' => 'Poison-control or medical guidance is reasonable in less unstable exposures, but consultation should not delay emergency transport once respiratory compromise is evident.',
			'D' => 'An urgent clinic-level evaluation is too slow and contingent on improvement despite current signs of possible overdose or severe toxicity.',
		),
	),
	'CTA-LMFT-CA-FB-110' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-TX5C-004',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Assertive communication and reduced criticism may help, but the family’s central misunderstanding about persistent symptoms remains unaddressed.',
			'B' => 'Reinforcement can support participation, but without symptom education it may continue to frame limited engagement mainly as a motivation or effort problem.',
			'C' => 'Best answer. Psychoeducation corrects the family’s inaccurate interpretation of symptom-related behavior, and concrete expectations translate that understanding into realistic household functioning.',
			'D' => 'Problem-solving is useful, but deliberately avoiding symptom discussion misses the client’s stated goal and leaves the family’s misattribution of behavior intact.',
		),
	),
	'CTA-LMFT-CA-FB-111' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-CE-019',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Legal facts may matter to the client\'s situation, but determining objective fairness would move the therapist outside the primary clinical assessment role.',
			'B' => 'Anxiety symptoms deserve evaluation, but separating them from the legal-system context would omit a major psychosocial factor.',
			'C' => 'The task is to evaluate how family-court involvement, parenting disruption, and perceived professional scrutiny are affecting the client\'s current functioning and relationships—not to determine whether the legal system acted fairly.',
			'D' => 'Legal resources may eventually be appropriate, but this option moves toward intervention before the clinical impact of legal-system involvement is sufficiently understood.',
		),
	),
	'CTA-LMFT-CA-FB-112' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-TX5A-004-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Attachment history may illuminate different expectations for closeness and independence, but the couple is asking for help with the immediate relational meaning and structure of cohabitation.',
			'B' => 'Existing agreements may eventually need revision, but changing them before the couple determines what cohabitation itself signifies could put implementation ahead of negotiation.',
			'C' => 'Values clarification is relevant and affirming, but the partners have already identified the concrete decision requiring attention: how shared housing would affect commitment, equity, and the wider relationship network.',
			'D' => 'Best answer. The therapist should facilitate explicit negotiation of the meaning and practical implications of cohabitation rather than assume a conventional hierarchy or treat consensual nonmonogamy as the problem.',
		),
	),
	'CTA-LMFT-CA-FB-113' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-CE-037-R1',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'A broad personality inventory addresses relatively stable traits and is poorly matched to tracking change in current depressive symptoms.',
			'B' => 'The therapist wants structured longitudinal information about fluctuating low mood. A validated depression measure used at planned intervals directly measures the target symptom domain and remains appropriately integrated with interview and functioning data.',
			'C' => 'A tailored daily checklist can generate useful self-monitoring data, but using its weekly average as the primary indicator of improvement gives a nonstandardized tool too much evaluative authority.',
			'D' => 'Functioning is an important outcome, but changes in functioning cannot be assumed to represent equivalent changes in depressive symptoms.',
		),
	),
	'CTA-LMFT-CA-FB-114' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-CP-003-R2',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Beginning step-down because the mood score improved gives symptom reduction excessive weight and risks ending before functional recovery has generalized.',
			'B' => 'Practical barriers deserve consideration, but continuing essentially the same plan for another four weeks delays modification despite clear evidence of a symptom–function discrepancy.',
			'C' => 'Adding another symptom-focused intervention does not fit the current evidence. Symptoms have improved; the unresolved problem is functional dependence rather than insufficient symptom reduction.',
			'D' => 'The symptom scores have improved, but work, valued activity, independent skill use, and reduced reassurance dependence have not. D modifies treatment around the remaining functional and maintaining processes and postpones step-down until those gains can be evaluated.',
		),
	),
	'CTA-LMFT-CA-FB-115' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-TX5E-003',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Testing alternative interpretations is a reasonable CBT strategy, but it does not directly test the safety behavior identified in the stem: mentally scripting sentences before speaking.',
			'B' => 'Best answer. The experiment deliberately removes internal rehearsal and compares the feared prediction with the coworker’s actual response, directly testing whether the safety behavior is necessary.',
			'C' => 'Graded exposure is appropriate for social anxiety, but the central maintaining process here is covert rehearsal; a broader hierarchy does not isolate that mechanism as cleanly.',
			'D' => 'Reducing self-focused attention may help, but it does not directly test the client’s belief that conversation will fail if internal rehearsal is not used.',
		),
	),
	'CTA-LMFT-CA-FB-116' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-DI-010',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Somatic symptom disorder is centered on one or more significant distressing physical symptoms plus excessive related thoughts or behavior; that is not the pattern here.',
			'B' => 'The anxiety is narrowly organized around acquiring or having serious disease rather than multiple life domains.',
			'C' => 'The client has minimal physical symptoms but persistent fear of serious illness, repeated body checking and reassurance seeking, and substantial health anxiety despite appropriate evaluations. APA differentiates illness anxiety disorder from somatic symptom disorder specifically by the absence or relative minimality of physical symptoms.',
			'D' => 'Repetitive checking can occur in OCD, but here it is part of a specific illness-preoccupation syndrome rather than a broader obsession-compulsion presentation.',
		),
	),
	'CTA-LMFT-CA-FB-117' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-CR-014-R3',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'Grief support and identifying practical options may be useful, but delaying implementation of needed accessibility and functional supports until distress decreases does not match the immediate adaptation demands created by the disabling injury.',
			'B' => 'Mood assessment may be relevant, but the stem does not establish a psychiatric disorder that should delay accessibility or functional adaptation.',
			'C' => 'Family-role history can inform adjustment, but the immediate crisis is the client\'s new disability-related functioning and access needs rather than longstanding family patterns.',
			'D' => 'The disabling injury has created immediate mobility, transportation, household, and work barriers. A client-centered plan that coordinates rehabilitation and accessibility resources while adapting daily roles directly addresses the current functional crisis.',
		),
	),
	'CTA-LMFT-CA-FB-118' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-DI-007',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'PTSD can include dissociative and memory symptoms, but the stem does not establish the broader PTSD syndrome required to make PTSD the better diagnosis.',
			'B' => 'Depersonalization/derealization centers on detachment from self or surroundings, not autobiographical memory loss.',
			'C' => 'The abrupt trauma-linked autobiographical gap and absence of neurological findings do not support an acquired neurocognitive disorder.',
			'D' => 'The client cannot recall important autobiographical information associated with the traumatic period, the memory loss exceeds ordinary forgetting, and head injury, substance use, and neurological causes are not supported. APA identifies amnesia/loss of memory as a core dissociative phenomenon and lists dissociative amnesia as a distinct dissociative disorder.',
		),
	),
	'CTA-LMFT-CA-FB-119' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-TX5F-004-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. The client is medically cleared but markedly deconditioned and wants to rebuild walking and household function. Physical therapy directly addresses progressive conditioning and restoration of functional movement.',
			'B' => 'Occupational therapy can support pacing and daily routines, but the primary treatment need described is physical deconditioning and graded restoration of movement capacity.',
			'C' => 'Pain psychology may be useful when catastrophizing or movement fear is the central barrier, but the stem emphasizes deconditioning after prolonged avoidance rather than a psychological obstacle requiring a separate pain-psychology referral.',
			'D' => 'A rehabilitation physician could reassess medical contributors or restrictions, but the client has already been medically cleared for gradual activity and the current need is functional reconditioning.',
		),
	),
	'CTA-LMFT-CA-FB-120' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-CE-011-R1',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Previous diagnoses and clinician formulations may provide background but can reproduce earlier labels rather than clarify the actual clinical course.',
			'B' => 'Comparing only prior symptoms closely matching the current presentation risks excluding clinically meaningful differences among episodes.',
			'C' => 'The client\'s uncertainty about whether earlier anxiety episodes occurred under similar circumstances requires a longitudinal reconstruction of onset, context, symptom pattern, duration, treatment response, and functioning.',
			'D' => 'Using the most severe episode as the reference point gives one period disproportionate weight and may distort comparison with the current presentation.',
		),
	),
	'CTA-LMFT-CA-FB-121' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-CE-003',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'School observations are important, but this option remains within one environment and therefore cannot adequately explain the home-school difference.',
			'B' => 'Home task behavior provides useful comparison data, but it similarly emphasizes only one side of the discrepancy.',
			'C' => 'The central finding is that the child\'s behavior varies substantially by setting. Comparing behaviors, task demands, supports, and consequences across settings allows the therapist to evaluate the discrepancy rather than decide prematurely which source is more accurate.',
			'D' => 'Sleep, stress, and routines could affect functioning, but this option selects contextual explanations before the actual differences in task demands and supports across settings are characterized.',
		),
	),
	'CTA-LMFT-CA-FB-122' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-TX5A-005',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Clarifying tasks may reduce ambiguity, but a written division of labor does not directly alter the criticism-defensiveness escalation that is maintaining the recurring conflict.',
			'B' => 'Family-of-origin meanings may deepen understanding, but the couple is asking for a better way to handle a current repetitive interaction rather than primarily exploring the origins of fairness beliefs.',
			'C' => 'De-escalation and time-out skills can reduce intensity, but they do not directly replace the criticism-defensiveness sequence with a collaborative problem-solving process.',
			'D' => 'Best answer. The therapist identifies the maintaining interaction pattern and coaches the couple through a new structured exchange using the exact type of disagreement that repeatedly triggers the cycle.',
		),
	),
	'CTA-LMFT-CA-FB-123' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-CP-005-R2',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Consultation and adaptation are responsible steps, but interpreter-assisted family treatment has already proved clinically insufficient in this case. Continuing that modality while waiting does not adequately address the indicated treatment need.',
			'B' => 'Individual treatment for the adolescent changes the unit and purpose of care. It substitutes an available service for the bilingual conjoint treatment supported by the assessment.',
			'C' => 'The indicated treatment is bilingual conjoint family care. A trial has already demonstrated that interpreter-mediated treatment loses clinically important relational meaning, and the therapist cannot independently provide the needed language-concordant service. C offers a limited stabilization bridge within competence, actively uses the payer’s network-gap process, coordinates suitable options, and keeps the family involved in access decisions.',
			'D' => 'Referrals and a transition session are insufficient when the family has already encountered a significant access barrier. Ending automatically when a bridge period expires prioritizes an administrative endpoint over the family’s clinical and continuity circumstances.',
		),
	),
	'CTA-LMFT-CA-FB-124' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-TX5D-004',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Historical meaning may be clinically relevant, but the immediate treatment target is a chronic stress cycle involving repetitive problem solving, physiologic tension, and disrupted sleep.',
			'B' => 'Best answer. Time-limited problem solving contains the practical stressor, relaxation addresses physiologic arousal, and bedtime structure reduces a behavioral pattern that is prolonging the chronic stress response.',
			'C' => 'Reducing discretionary activity may be financially practical, but repeatedly reviewing the budget whenever worry rises is likely to reinforce rumination rather than regulate the stress response.',
			'D' => 'Cognitive restructuring can be useful, but excluding practical problem solving and using it only when physical symptoms emerge is less comprehensive for a stressor that has both external and physiologic components.',
		),
	),
	'CTA-LMFT-CA-FB-125' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-LE6-001-R1',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Documenting the new purpose and reviewing privacy are useful, but simply retaining the prior agreement leaves the changed client-role and treatment-limit expectations insufficiently clarified.',
			'B' => 'Best answer. A substantial change in the purpose of conjoint treatment calls for explicit review of the new purpose, roles, confidentiality expectations, and limits. The therapist should document the updated informed-consent understanding without inventing a universal rule that a new signed form is always required.',
			'C' => 'A fully new episode and formal new consent process may be administratively possible, but it is not inherently required merely because the therapeutic purpose changes.',
			'D' => 'Separate meetings may sometimes be useful, but they can create additional privacy expectations and are not necessary before the couple jointly clarifies the changed purpose and roles.',
		),
	),
);
