<?php
/**
 * ADMIN ONLY — LMFT California Clinical Form A answer key items 126–150 (PROMPT 18).
 * Secured answer + rationale mapping. Never exposed to learners.
 *
 * @package CTA_LMS
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'CTA-LMFT-CA-FA-126' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-CE-019',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Mood and anxiety symptoms may accompany occupational problems, but this choice moves prematurely toward an individual psychiatric explanation.',
			'B' => 'Coworker and supervisor conflict are relevant but capture only one portion of the occupational change.',
			'C' => 'The occupational problem emerged after a workplace reorganization. Comparing previous functioning with changes in responsibilities, expectations, attendance, performance, and stress directly evaluates the employment-related change.',
			'D' => 'Career satisfaction and alternative employment may eventually be important, but this option begins moving toward occupational decision-making before the current employment stress has been adequately evaluated.',
		),
	),
	'CTA-LMFT-CA-FA-127' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-LE6-015',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'A work-readiness opinion is additional clinical information outside the authorization described in the stem. Reviewing observed functioning and omitting diagnosis do not bring that opinion within the authorized disclosure scope.',
			'B' => 'Best answer. The therapist should provide only the attendance and completion information already authorized and should not expand disclosure to a work-readiness opinion without separate authority.',
			'C' => 'This prevents overdisclosure, but it unnecessarily withholds attendance and completion information that the client has already authorized the therapist to provide.',
			'D' => 'A broader authorization and evaluative role could be discussed if the client independently wants that service and it is otherwise appropriate, but the therapist need not make expansion of the authorization the default response to an overbroad third-party request.',
		),
	),
	'CTA-LMFT-CA-FA-128' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-TX5E-001',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Mapping the sequence is consistent with systems thinking, but observation alone does not yet alter the reciprocal process that is maintaining the problem.',
			'B' => 'The couple relationship is part of the system, but shifting attention away from the adolescent does not directly change the repeated school-refusal interaction described in the stem.',
			'C' => 'Best answer. General systems treatment targets reciprocal interaction patterns. Changing the parents’ responses at the point where avoidance begins directly interrupts the repeating cycle rather than locating the problem in one family member.',
			'D' => 'A systemic reframe may reduce blame and increase curiosity, but exploring the possible function without changing the active sequence is less direct than intervening in the reciprocal pattern itself.',
		),
	),
	'CTA-LMFT-CA-FA-129' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-TX5C-002',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'In-session exposure may support learning, but simply sending home the same frightening assignment does not adequately address the client’s uncertainty, concerns, or poor follow-through.',
			'B' => 'Best answer. The therapist addresses the client’s concerns and treatment rationale while collaboratively reducing the assignment to a manageable exposure step, increasing the likelihood of engagement without abandoning the treatment mechanism.',
			'C' => 'Monitoring may provide information, but the problem is not lack of knowledge about panic triggers. The client needs a tolerable way to participate in the agreed exposure work.',
			'D' => 'Additional education and demonstration may help understanding, but retaining the same assignment does not sufficiently respond to the barrier the client has already identified.',
		),
	),
	'CTA-LMFT-CA-FA-130' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-CP-007',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Mapping triangles, strengthening differentiation, and reducing reactive involvement constitute a multigenerational/Bowen plan. Those interventions may illuminate the broader family emotional system but do not most directly reorganize the current parental and child subsystems.',
			'B' => 'Identifying maintaining sequences and prescribing directives is consistent with strategic family therapy. The item’s decisive formulation, however, is family structure rather than a symptom-maintaining sequence best altered through directives.',
			'C' => 'The clinical formulation concerns the family’s present organization: weakened parental leadership, poorly defined generational boundaries, and an adolescent participating in a cross-generational coalition. C directly targets those structural features by strengthening the parental subsystem, clarifying boundaries, and moving the adolescent out of an inappropriate relational position. Structural family therapy specifically conceptualizes families through subsystems, boundaries, hierarchy, coalitions, and interactional restructuring.',
			'D' => 'Increasing authentic emotional expression and congruent relational contact is an experiential family therapy plan. It does not directly correct the hierarchy, boundaries, and coalition specified in the stem.',
		),
	),
	'CTA-LMFT-CA-FA-131' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-DI-005',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Generalized anxiety involves excessive worry but does not best explain the intrusive obsession plus ritualized compulsion pattern.',
			'B' => 'Obsessive-compulsive personality disorder involves a pervasive personality style rather than unwanted obsessions and anxiety-reducing rituals.',
			'C' => 'The client experiences recurrent unwanted contamination thoughts and repetitive washing rituals performed to reduce distress. That obsession-compulsion relationship is characteristic of OCD.',
			'D' => 'The client recognizes that the contamination concern may be exaggerated, and the presentation is organized around obsessions and compulsions rather than a fixed psychotic belief.',
		),
	),
	'CTA-LMFT-CA-FA-132' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-CR-014-R1',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'The immediate crisis is loss of basic family organization after a serious diagnosis. Stabilizing routines and temporary responsibilities while mobilizing practical support directly addresses the current functional disruption.',
			'B' => 'Communication support can help, but delaying temporary role adjustments leaves the immediate childcare, meals, sleep, and responsibility problems unresolved.',
			'C' => 'Historical coping strengths may inform later work, but the family first needs present-focused stabilization of disrupted roles and daily functioning.',
			'D' => 'Individual symptom assessment and psychiatric consultation may be indicated for particular family members, but the stem does not establish an acute psychiatric problem as the organizing crisis.',
		),
	),
	'CTA-LMFT-CA-FA-133' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-TX5C-004',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Paced breathing may reduce distress, but using symptom reduction to determine whether the client remains can preserve fear of bodily sensations and escape as a safety strategy.',
			'B' => 'Cognitive reappraisal is helpful, but the maintaining pattern includes leaving the store and calling the spouse for reassurance, which this option does not directly reduce.',
			'C' => 'Less crowded periods and gradually longer visits may increase tolerance, but they can preserve situational safety modifications and do not directly address reassurance seeking.',
			'D' => 'Best answer. The response combines in-vivo exposure with reduction of the two maintaining safety behaviors identified in the stem: early escape and repeated reassurance calls.',
		),
	),
	'CTA-LMFT-CA-FA-134' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-TX5B-001',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. The client’s grief remains compatible with functioning, and the intervention respects culturally and spiritually meaningful mourning practices while supporting adaptation rather than pathologizing continuing bonds.',
			'B' => 'Narrative grief work can be useful, but the stem does not indicate avoided or unfinished material. Beginning there could overlook the client’s already meaningful spiritual mourning process.',
			'C' => 'Practical family adaptation may be useful after a death, but the client is already maintaining responsibilities and is seeking space for a culturally meaningful grief process rather than primarily logistical help.',
			'D' => 'A continuing-bond ritual and boundary-setting with relatives are reasonable interventions, but the client already has meaningful remembrance practices; treatment should first understand and support the existing mourning framework.',
		),
	),
	'CTA-LMFT-CA-FA-135' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-CR-002-R1',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'Intensive outpatient and case-management services still assume enough independent functioning to use community supports reliably. The stem establishes that the client cannot currently manage basic needs safely.',
			'B' => 'Medication evaluation and supervised community support may become useful components of care, but this pathway does not provide the staffed stabilization required by the client\'s present self-care incapacity.',
			'C' => 'Temporary housing, daily outreach, and basic-needs assistance address practical problems but still depend on a level of independent functioning the current presentation does not establish.',
			'D' => 'The client cannot reliably obtain food, maintain hygiene, or describe a viable basic-needs plan. A staffed crisis setting can provide observation, psychiatric assessment, and immediate stabilization of basic self-care.',
		),
	),
	'CTA-LMFT-CA-FA-136' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-CE-035',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The client reports a pattern of aggressive behavior without established current imminent danger. The therapist should evaluate frequency, triggers, escalation, consequences, relational effects, and whether present circumstances indicate any change in risk.',
			'B' => 'Impulsivity and emotion regulation may contribute to the behavior, but this option narrows the assessment toward one possible mechanism before the overall aggression pattern has been characterized.',
			'C' => 'Substance use, sleep, mood, and stress may influence aggressive behavior, but none is established as the primary explanation.',
			'D' => 'Legal consequences, family responses, and treatment history provide relevant contextual information but do not as directly characterize the current aggression pattern or clarify present danger.',
		),
	),
	'CTA-LMFT-CA-FA-137' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-CE-020',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Trauma symptoms should be assessed when indicated, but this response prematurely frames deployment primarily through a PTSD lens.',
			'B' => 'The client returned from deployment before the relationship difficulties intensified. Exploring military service, deployment, reintegration, military culture, and changes in family functioning evaluates whether those experiences are clinically relevant without assuming a trauma diagnosis.',
			'C' => 'Current couple interaction deserves assessment, but excluding military and reintegration context because the client minimizes its relevance would omit information specifically suggested by the chronology.',
			'D' => 'The partner\'s observations may be valuable, but they should supplement rather than determine whether military experiences are clinically relevant.',
		),
	),
	'CTA-LMFT-CA-FA-138' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-TX5D-002',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Returning to the prior equal split may sound fair, but it ignores the couple’s report that the old arrangement no longer fits their current capacities during the transition to parenthood.',
			'B' => 'Best answer. The conflict is occurring during a normative transition to parenthood. Redistributing responsibilities according to present capacity while protecting couple connection directly addresses role reorganization and relational strain.',
			'C' => 'Clarifying values and creating a new agreement are useful, but this option is less direct about adapting responsibilities to the capacity changes that are driving the current conflict.',
			'D' => 'Recovery periods and outside support may reduce fatigue, but they do not directly renegotiate the couple’s shared parenting roles or preserve the couple bond as clearly as the keyed response.',
		),
	),
	'CTA-LMFT-CA-FA-139' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-CR-003-R1',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Same-day crisis transfer is more restrictive than the established risk warrants because the stem does not establish suicidal intent, medically serious injury, inability to maintain safety, or another high-acute-risk feature.',
			'B' => 'Keeping the routine outpatient frequency underresponds to recurrent self-injury during an elevated-risk period, even though emergency disposition is not established.',
			'C' => 'The self-injury requires direct suicide reassessment and active intervention, but the stem does not establish suicidal intent, medically serious injury, inability to maintain safety, or another high-acute-risk feature. The overall acute-risk state supports intensified outpatient self-harm stabilization rather than automatic emergency transfer.',
			'D' => 'Restricting access to self-harm tools may be useful, but postponing coping work and relying mainly on means restriction incompletely addresses the current self-injury pattern.',
		),
	),
	'CTA-LMFT-CA-FA-140' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-TX5A-001-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Peer support can be protective, but relying on friends after family conflict does not strengthen the adoptive mother-adolescent attachment cycle that is destabilized by rejection fears.',
			'B' => 'Pairing reassurance with limits is helpful, but the response does not establish a clear repair process after conflict and may leave the mother’s disengagement pattern insufficiently changed.',
			'C' => 'Processing caregiver loss is clinically relevant, but individual exploration alone does not address the live dyadic sequence occurring when the mother sets limits.',
			'D' => 'Best answer. Predictable limits combined with reliable reconnection directly address the adolescent’s fear of abandonment while changing the mother’s withdrawal after conflict.',
		),
	),
	'CTA-LMFT-CA-FA-141' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-TX5B-003',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Deployment experiences may contribute to emotional distance, but the stem primarily describes family-role and routine disruption rather than a trauma-processing problem.',
			'B' => 'Best answer. Postdeployment reintegration requires renegotiating current parenting, household, alone-time, and couple routines so the family can reorganize around the service member’s return.',
			'C' => 'Communication practice can help one disagreement, but it is narrower than the role and routine reorganization required by the family’s broader reintegration transition.',
			'D' => 'Comparing roles and values can deepen understanding, but it is less direct than actively updating the present family structure and reconnection routines.',
		),
	),
	'CTA-LMFT-CA-FA-142' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-CE-021',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Emotional symptoms are relevant consequences but do not sufficiently assess the economic and housing circumstances producing the stress.',
			'B' => 'Family conflict is important, but this option risks treating the relationship process as the primary problem rather than assessing it within the socioeconomic context.',
			'C' => 'The family\'s housing and economic instability is occurring alongside disrupted access to necessities and changes in individual and family functioning. This option directly evaluates those socioeconomic stressors and their effects.',
			'D' => 'Practical resource needs matter and may require action, but this option moves toward resource intervention before adequately evaluating the broader clinical impact.',
		),
	),
	'CTA-LMFT-CA-FA-143' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-TX5A-006',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Separate authority domains may reduce some conflict, but they can formalize competing parent and grandparent hierarchies rather than strengthening the parental subsystem.',
			'B' => 'Best answer. The adolescent is using inconsistent adult authority. Restoring parental leadership and resolving adult disagreements outside the adolescent\'s involvement reduces triangulation and creates a coherent hierarchy.',
			'C' => 'Shared rules may increase consistency, but making all adults equal enforcers does not address the blurred hierarchy created when grandparents reverse parental decisions.',
			'D' => 'Four-adult consensus can sound collaborative, but it preserves the grandparents as coequal discipline decision-makers rather than clarifying parental authority.',
		),
	),
	'CTA-LMFT-CA-FA-144' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-CE-024',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The client\'s experiences differ dramatically across affirming and rejecting environments. Evaluating identity development, acceptance and rejection, available supports, minority stress, and changes in functioning directly addresses that contextual variation.',
			'B' => 'Family rejection and dependence are important, but this option gives the rejecting environment disproportionate explanatory weight.',
			'C' => 'Medical or social transition can be relevant for some clients, but the vignette does not establish transition status as the controlling issue.',
			'D' => 'Affirming peers and coworkers are genuine protective factors, but assessing whether they sufficiently “buffer” family stress narrows the evaluation toward resilience rather than the broader identity and minority-stress context.',
		),
	),
	'CTA-LMFT-CA-FA-145' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-CE-037',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Approach versus avoidance can be a useful distinction, but categorizing strategies first does not establish whether each response is actually adaptive in this client\'s circumstances.',
			'B' => 'The client uses both support-seeking and avoidance and experiences both as helpful. The therapist should evaluate each strategy according to its function and its short- and longer-term consequences rather than label coping solely by appearance or immediate relief.',
			'C' => 'Immediate emotional relief is clinically relevant but cannot by itself establish whether a coping strategy supports longer-term functioning.',
			'D' => 'Support, routines, sleep, and demands may influence coping choices, but the central unanswered question is what the coping behaviors accomplish and what consequences they produce.',
		),
	),
	'CTA-LMFT-CA-FA-146' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-TX5D-006-R2',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Stress reduction and boundaries can reduce overload, but they do not directly change the avoidance of delegation and difficult conversations that is impairing management performance.',
			'B' => 'Belief testing may help the client question over-responsibility, but the immediate functional deficit also requires practice of the interpersonal behavior the client avoids.',
			'C' => 'Correct. Live rehearsal directly targets avoidance of delegation and difficult conversations, while coping preparation supports follow-through when stress rises after the interaction.',
			'D' => 'Workload planning can reduce burden, but retaining the current communication approach leaves the central interpersonal management pattern unchanged.',
		),
	),
	'CTA-LMFT-CA-FA-147' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-TX5D-007-R3',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. This option integrates discrimination, acculturation differences, family loyalty, and the student\'s developmental push for independence, then uses those factors to guide family negotiation.',
			'B' => 'The migration story and cultural traditions may provide strengths, but this approach does not directly address the family\'s acculturation differences or negotiate the student\'s independence needs.',
			'C' => 'Bicultural validation and coping with microaggressions are appropriate, but the intervention remains primarily individual and does not sufficiently engage the family-level acculturation conflict.',
			'D' => 'A respectful family discussion is plausible, but it underemphasizes the school discrimination and the acculturation differences linking the student\'s experiences across home and school.',
		),
	),
	'CTA-LMFT-CA-FA-148' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-CE-039',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The therapist has identified a specific discrepancy between the client’s current recollection and prior professional documentation. With appropriate authorization, focused record review or consultation with the former provider can clarify that particular question without assuming either source is automatically correct.',
			'B' => 'Documentation created closer to the time may be informative, but temporal proximity does not make the former record inherently more accurate than the client.',
			'C' => 'The discrepancy affects the therapist’s understanding of functioning and therefore merits clarification even if it does not immediately change a diagnosis or create a safety concern.',
			'D' => 'Family collateral could eventually add perspective, but professional records already relevant to the discrepancy provide a more focused next source of clarification.',
		),
	),
	'CTA-LMFT-CA-FA-149' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-TX5C-005',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Grounding may help, and reducing repeated questioning is reasonable, but simply stopping questions does not provide the family with a coordinated response when residual symptoms occur.',
			'B' => 'Best answer. The intervention supports symptom management and modifies the family response that is contributing to withdrawal while remaining appropriate to ongoing outpatient psychiatric care.',
			'C' => 'Communication work may help, but separating family treatment from symptom management ignores how the family’s response to residual symptoms is affecting the client’s interpersonal functioning.',
			'D' => 'Reality-based discussion can sometimes help, but repeated family reassurance may intensify symptom monitoring and dependence rather than support a calm, consistent coping response.',
		),
	),
	'CTA-LMFT-CA-FA-150' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-TX5A-002-R2',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'This creates structure but preserves separate parenting systems, so the child can continue to triangulate between parents.',
			'B' => 'Correct. The clinical problem is stress-amplified co-parenting inconsistency. Addressing the differences and creating shared responses directly improves the parenting relationship and reduces split responding.',
			'C' => 'A sensory-informed behavior plan may help the child, but it does not directly repair the parents’ conflict about how they respond.',
			'D' => 'Conflict-management skills may reduce arguments, but allowing discipline to remain individualized leaves the controlling co-parenting inconsistency in place.',
		),
	),
);
