<?php
/**
 * ADMIN ONLY — LMFT California Clinical Form B answer key items 51–75 (PROMPT 21).
 * Secured answer + rationale mapping. Never exposed to learners.
 *
 * @package CTA_LMS
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'CTA-LMFT-CA-FB-051' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-DI-012',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The client does not report intrusive unwanted obsessions or compulsions performed to relieve anxiety.',
			'B' => 'Generalized anxiety does not account for the pervasive ego-syntonic personality style.',
			'C' => 'Rigidity alone is insufficient for autism, and the stem does not establish the required developmental social-communication and restricted/repetitive pattern.',
			'D' => 'The pattern begins in early adulthood and is pervasive: perfectionism, preoccupation with rules and schedules, reluctance to delegate, excessive work devotion, and inflexibility. APA describes OCPD as a long-term pattern of orderliness, perfectionism, control, stubbornness, and inflexibility and explicitly distinguishes it from OCD.',
		),
	),
	'CTA-LMFT-CA-FB-052' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-CE-033-R1',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Driving confidence and transportation limitations are relevant consequences, but this choice centers the behavioral restriction rather than adequately evaluating the broader trauma response.',
			'B' => 'Panic symptoms, sleep, and substance use could be clinically relevant, but the option moves toward an alternative anxiety formulation despite a clear temporal relationship with traumatic exposure.',
			'C' => 'Coping, support, and functional consequences deserve assessment, but this option underrepresents the trauma-specific reactions already evident in the vignette.',
			'D' => 'The client witnessed a serious collision and subsequently developed intrusive recollections and avoidance associated with reminders. Assessing trauma-related reactivity, avoidance, changes in mood or beliefs, and functional impact most directly evaluates the effects of the traumatic exposure.',
		),
	),
	'CTA-LMFT-CA-FB-053' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-CE-008-R2',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Cognitive assessment could be appropriate if other findings suggest impairment, but the vignette does not indicate that cognition is the most likely source of the rapid speech.',
			'B' => 'Rapid speech is an observed MSE finding. Pressure, interruptibility, thought organization, psychomotor activity, and activation are the most directly related features needed to characterize it.',
			'C' => 'Psychotic symptoms represent another MSE domain. Rapid but coherent, responsive speech does not by itself make psychosis the most relevant clarification.',
			'D' => 'Mood, affect, and anxiety may eventually help explain the finding, but the speech and activation characteristics should first be described directly.',
		),
	),
	'CTA-LMFT-CA-FB-054' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-CP-012',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'A decisional matrix may organize information but positions the process around selecting the objectively least regrettable option rather than clarifying personally meaningful choice.',
			'B' => 'Unconscious conflict, authority transference, and formative relationships are psychodynamic concepts.',
			'C' => 'Preferred-future description, confidence scaling, and building from prior decisiveness is solution-focused.',
			'D' => 'The client feels disconnected from personal values and asks the therapist to decide which life choices are correct. D provides empathic and congruent presence, clarifies the client’s perspective and meaning, and supports self-directed choice without replacing the client’s authority. Person-centered therapy emphasizes therapist presence, empathic attunement, acceptance, affirmation, and congruence; existential-humanistic approaches additionally emphasize choice, freedom, meaning, and responsibility.',
		),
	),
	'CTA-LMFT-CA-FB-055' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-TX5B-005-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'A time-out can reduce immediate escalation, but it does not directly modify the shame and threat interpretation driving the anger response.',
			'B' => 'Consequences may affect behavior, but the stem identifies an internal mechanism contributing to aggression that is more directly treatable.',
			'C' => 'Best answer. It targets the underlying shame/threat meaning that precedes anger and pairs insight with a replacement response before conflict resumes.',
			'D' => 'Partner communication can influence conflict, but placing the main intervention on the partner leaves the client’s identified aggression mechanism insufficiently addressed.',
		),
	),
	'CTA-LMFT-CA-FB-056' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-TX5C-008',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Urge management and support are useful relapse-prevention components, but the plan does not sufficiently address predictable exposure to former using peers or how the client will leave if risk increases.',
			'B' => 'Reducing exposure may lower risk, but relying primarily on environmental avoidance and supervision provides less preparation for direct offers, changing cravings, or an unexpected high-risk situation.',
			'C' => 'Best answer. The intervention anticipates specific relapse risks and establishes rehearsed refusal responses plus exit and transportation decisions before exposure occurs rather than relying on willpower in the moment.',
			'D' => 'Recovery motivation and follow-up are valuable, but they do not provide enough concrete planning for foreseeable cues and substance offers during the reunion itself.',
		),
	),
	'CTA-LMFT-CA-FB-057' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-CP-010',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Assertive communication, behavioral testing, and revision of authority-related beliefs is CBT.',
			'B' => 'The client repeats conflict with supervisors and begins responding to the therapist as though disagreement will lead to humiliation. B examines the recurring relational theme, its emergence within the therapeutic relationship, associated defenses, and its connection to formative experiences. Psychoanalytic descriptions define transference as applying perceptions and expectations from earlier significant relationships to present relationships so those patterns can be examined in treatment.',
			'C' => 'Externalizing punishing authority, identifying exceptions, and constructing a preferred professional identity is narrative/solution-oriented.',
			'D' => 'Hierarchy, boundaries, and triangular patterns are family-systems concepts and do not directly use the authority expectation becoming active with the therapist.',
		),
	),
	'CTA-LMFT-CA-FB-058' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-DI-011',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Sexual desire remains strong, arguing against a desire disorder as the central dysfunction.',
			'B' => 'The problem is persistent for ten months, occurs during nearly all sexual activity, concerns obtaining or maintaining erection, causes marked distress, and is not better explained by medical, medication, substance, relationship, or another sexual-function problem. Erectile disorder is an established DSM sexual-dysfunction diagnosis.',
			'C' => 'Orgasm and ejaculation are described as intact.',
			'D' => 'The stem explicitly removes medication and substance exposure as the better explanation.',
		),
	),
	'CTA-LMFT-CA-FB-059' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-LE6-005-R1',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. The overlap is foreseeable and difficult to avoid, but it is not automatically disqualifying. Proactive role and confidentiality planning plus monitoring of clinical judgment is the strongest response.',
			'B' => 'Using administrative channels to prevent normal teacher-parent contact may be impractical and unnecessary. The therapist should manage the overlap rather than assume all contact must be eliminated.',
			'C' => 'Delegating school contact may reduce exposure, but it unnecessarily burdens the therapist\'s family and does not replace a direct boundary plan with the client.',
			'D' => 'Documentation and later monitoring are useful, but waiting until a conflict develops misses the opportunity to establish confidentiality and role expectations before the foreseeable overlap begins.',
		),
	),
	'CTA-LMFT-CA-FB-060' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-CE-036',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The client\'s family support, community connection, advocacy, rest, and withdrawal may each function differently. Evaluating how these responses affect functioning while also identifying continuing burden and vulnerability captures both resilience and the ongoing cost of coping with discrimination.',
			'B' => 'Exhaustion and other symptoms warrant assessment, but focusing primarily on whether coping resources are becoming insufficient risks treating resilience as absent whenever substantial distress remains.',
			'C' => 'Family and community support are important protective factors, but resilience is broader than the availability of interpersonal resources.',
			'D' => 'Advocacy may provide meaning while also contributing to depletion, but it represents only one component of the client\'s overall coping and resilience system.',
		),
	),
	'CTA-LMFT-CA-FB-061' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-CE-027',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'focuses too strongly on which sibling recruits others.',
			'B' => 'may provide useful intergenerational context but does not first establish the current sequence.',
			'C' => 'evaluates several individual communication variables but does not as directly map how the family interaction unfolds.',
			'D' => 'Third-party involvement repeatedly expands the sibling conflict. Reconstructing a specific episode allows the therapist to see how direct communication, recruitment of relatives, alliances, and escalation operate sequentially within the family interaction.',
		),
	),
	'CTA-LMFT-CA-FB-062' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-TX5E-004',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Catastrophizing may contribute to anxiety, but the client’s statement is more centrally organized around rigid demandingness and global self-rating.',
			'B' => 'Low frustration tolerance is a legitimate REBT target, but the stem does not primarily say that disappointment is unbearable; it says perfect performance is required for personal worth.',
			'C' => 'Best answer. The intervention directly disputes both the rigid “must” and the global negative self-rating, which are the clearest irrational beliefs expressed in the client’s statement.',
			'D' => 'Probability estimation may reduce overprediction, but REBT would more directly address the client’s evaluative demand and global worth judgment rather than whether criticism is likely.',
		),
	),
	'CTA-LMFT-CA-FB-063' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-LE6-003',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The disclosure restriction is overbroad. A therapist may receive unsolicited collateral information; the lack of authorization limits what the therapist can disclose back to the parent.',
			'B' => 'Whether a particular concern has been discussed in therapy is itself protected treatment information and should not be disclosed without authority.',
			'C' => 'A general treatment-status reassurance still communicates protected information about the client\'s treatment.',
			'D' => 'Best answer. Authority to provide information to the therapist is different from authority to receive information from the therapist. The therapist can receive clinically useful collateral information while preserving the client\'s confidentiality and managing the contact transparently in treatment.',
		),
	),
	'CTA-LMFT-CA-FB-064' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-TX5F-003-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. The client wants to retain the current job and needs disability-specific assistance with workplace functioning and possible accommodations, which is the direct focus of vocational rehabilitation services.',
			'B' => 'A general employment center is useful for job seeking, but the client is not asking to leave the current position and needs disability-related job-retention support rather than a new-job search.',
			'C' => 'Career-development services may help with future occupational planning, but they do not directly address the immediate need to adapt current work demands after acquisition of a disability.',
			'D' => 'Benefits counseling may be useful if work changes affect financial supports, but the client’s stated problem is maintaining employment through workplace adjustments rather than understanding benefit eligibility.',
		),
	),
	'CTA-LMFT-CA-FB-065' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-LE6-006-R1',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Reducing the therapist\'s community authority can be useful, but excluding faith-community experiences from therapy merely to keep the roles separate may unnecessarily restrict clinically relevant material.',
			'B' => 'The client\'s preferences matter, but the therapist cannot shift primary responsibility for managing the therapist\'s power and professional boundaries onto the client.',
			'C' => 'Minimizing contact and considering referral are possible safeguards, but the shared community is unavoidable and treatment is beneficial. Avoidance is less targeted than directly reducing the therapist\'s nonclinical power and managing the overlap.',
			'D' => 'Best answer. The therapist should address the power differential, reduce direct control where feasible, establish public-contact boundaries, and monitor how the unavoidable overlap affects judgment and treatment.',
		),
	),
	'CTA-LMFT-CA-FB-066' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-CE-041-R1',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The child has meaningful concerns spanning developmental, medical, educational, and behavioral domains, and a single-discipline evaluation has not clarified how those concerns interact. Coordinated multidisciplinary assessment allows those domains to be evaluated and interpreted together.',
			'B' => 'Neuropsychological assessment may be an important component, but beginning serially with one specialty assumes cognition or development should lead the assessment despite evidence of several concurrent domains.',
			'C' => 'School-based assessment would address an important part of the presentation but would similarly make the educational domain the starting point for a problem that clearly extends beyond school.',
			'D' => 'Requiring the therapist first to identify one “primary” source of impairment defeats the purpose of multidisciplinary assessment when the unresolved problem is precisely the interaction among several domains.',
		),
	),
	'CTA-LMFT-CA-FB-067' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-CE-007',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The client is visibly losing track of questions during the session. Directly assessing attention, concentration, orientation, and short-term recall characterizes the current cognitive MSE finding before determining its cause.',
			'B' => 'Sleep disturbance is an important potential contributor but should not be assumed to explain the observed cognitive difficulty before current cognition is assessed.',
			'C' => 'Mood, anxiety, dissociation, and stress may produce cognitive complaints, but this option shifts prematurely toward possible explanations.',
			'D' => 'Collateral examples can establish external functional impact, but they should supplement rather than replace direct assessment of the impairment being observed in session.',
		),
	),
	'CTA-LMFT-CA-FB-068' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-CR-015-R1',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'Community support is useful, but beginning exposure-oriented trauma preparation this early still places trauma processing ahead of the practical stability and trust-building needed in the resettlement context.',
			'B' => 'The presentation combines trauma exposure with language barriers, institutional mistrust, transportation difficulty, and unstable resources. Initial care should establish safety and practical stability, provide meaningful language access, build trust, and pace trauma work according to readiness.',
			'C' => 'Engagement with community systems may help address resettlement needs, but the response gives systems participation priority over the client\'s immediate trust and stabilization needs.',
			'D' => 'A complete trauma hierarchy is not required before support can begin and may make intensive trauma disclosure the organizing focus too early.',
		),
	),
	'CTA-LMFT-CA-FB-069' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-CP-014',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The client’s panic symptoms have decreased, but the client continues to avoid independent exposure, relies on therapist reassurance, and cannot consistently use treatment skills without prompting. The remaining goals should therefore focus on independent practice and generalization before termination readiness is reconsidered.',
			'B' => 'A gradual step-down can be appropriate when gains are stable enough to test at lower treatment frequency. Here, the central treatment behavior has not yet generalized independently, making step-down premature.',
			'C' => 'Continuing weekly sessions unchanged may preserve the reassurance dependence already interfering with independent progress. The treatment plan needs modification rather than more time in the same structure.',
			'D' => 'Providing relapse and exposure guidance does not compensate for ending treatment before the client can reliably perform the core treatment tasks independently.',
		),
	),
	'CTA-LMFT-CA-FB-070' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-TX5D-002-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Restoring routine can help after retirement, but activity scheduling alone does not address the client’s culturally organized provider identity and family-role conflict.',
			'B' => 'Grief and identity work are relevant, but they do not directly change the family meaning of giving versus receiving support.',
			'C' => 'Volunteer or mentoring roles can preserve contribution, yet they may simply relocate the provider role without renegotiating the client’s difficulty receiving support from family.',
			'D' => 'Correct. The intervention preserves the value of contribution while broadening how it is expressed and directly renegotiating family roles around both giving and receiving.',
		),
	),
	'CTA-LMFT-CA-FB-071' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-CR-012-R1',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'Identification and housing needs are important, but requiring a fuller trafficking history before additional referrals still makes access to services contingent on disclosure, which is inconsistent with the survivor-centered crisis priority.',
			'B' => 'Trust building is important, but delaying specialized outside resources may prolong unmet housing, identification, safety, or advocacy needs.',
			'C' => 'The client needs immediate safety and basic-needs assistance, specialized survivor resources, and control over the pace of disclosure. Access to help should not depend on telling the full story.',
			'D' => 'Family reconnection should never be presumed safe or preferable for a trafficking survivor without assessment of the client\'s circumstances and wishes.',
		),
	),
	'CTA-LMFT-CA-FB-072' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-TX5E-002-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Tracking underlying emotion fits experiential work, but it leaves the corrective exchange largely intact rather than changing the incongruent communication occurring in the room.',
			'B' => 'Role reversal may deepen awareness of each person’s experience, but it is less direct than transforming the live communication pattern while it is happening.',
			'C' => 'Family sculpting is an experiential technique and could externalize the pattern, but the target interaction is already present in the session and can be addressed more immediately.',
			'D' => 'Best answer. The therapist uses the live exchange to stop perfectionistic correction and facilitate more direct expression of vulnerable feelings, needs, and desired connection.',
		),
	),
	'CTA-LMFT-CA-FB-073' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-CR-013-R2',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'The adolescent experienced a frightening caregiver-related crisis and now shows trauma-related arousal, guilt, and avoidance. Developmentally appropriate stabilization should address safety and self-blame, use the reliable caregiver as support, restore routines, and monitor functioning.',
			'B' => 'Caregiver and school support are useful, but detailed retelling is not a prerequisite for early stabilization after witnessing a caregiver overdose and may exceed the adolescent\'s current readiness.',
			'C' => 'Supporting independence can be useful later, but it should not become the primary frame for trauma-related fear immediately after witnessing a caregiver overdose.',
			'D' => 'The parent\'s recovery matters to the family context, but focusing primarily on the parent underresponds to the adolescent\'s own guilt, fear, and disruption.',
		),
	),
	'CTA-LMFT-CA-FB-074' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-LE6-007-R1',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Restoring policies and structure is useful, but the response emphasizes procedural correction more than examining the rescue identification that is driving the selective treatment.',
			'B' => 'Self-disclosure is not the primary method for managing countertransference and may shift the burden of the therapist\'s reaction onto the client.',
			'C' => 'Best answer. The therapist has identified a countertransference pattern that is already affecting boundaries and selective attention. Consultation, recognition of the rescue response, and restoration of consistent limits directly address the risk.',
			'D' => 'Objective goals and outcome review may support treatment decisions, but they do not directly address the rescue identification or the altered boundaries already occurring.',
		),
	),
	'CTA-LMFT-CA-FB-075' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-CE-010',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Motivation and illness beliefs may influence adherence, but this option interprets the behavior before accurately characterizing it.',
			'B' => 'The therapist must first understand what the client is actually doing with the prescribed treatment, what barriers exist, and how symptoms and functioning vary in relation to adherence.',
			'C' => 'Coordination with the medical provider can be useful, but the therapist should first obtain the client\'s own adherence history and functional context.',
			'D' => 'Cost, access, routines, and practical obstacles are plausible barriers, but this option focuses on possible causes before establishing the actual adherence pattern and its effects.',
		),
	),
);
