<?php
/**
 * ADMIN ONLY — LMFT California Clinical Form B answer key items 1–25 (PROMPT 19).
 * Secured answer + rationale mapping. Never exposed to learners.
 *
 * @package CTA_LMS
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'CTA-LMFT-CA-FB-001' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-CP-006-R2',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Continuous referrals and a repeating eight-week modular curriculum make rolling admission appropriate. A preserves the necessary clinical safeguards by requiring eligibility screening, orientation for each entrant, a reliable curriculum, and stable participation rules.',
			'B' => 'Closed cohorts could work for a sequential curriculum, but this curriculum repeats and was designed to accept continuous referrals. Delaying eligible participants until the next cohort creates an unnecessary access barrier.',
			'C' => 'Open drop-in attendance and participant-selected topics would reduce continuity, group cohesion, orientation, and faithful delivery of the intended adjustment and self-management curriculum.',
			'D' => 'Including both routine and crisis-level members creates an unsafe and clinically incoherent mix. Replacing the modular design with an entirely needs-driven process also departs from the stated program structure.',
		),
	),
	'CTA-LMFT-CA-FB-002' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-CE-004',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The client expects the therapist to make a major personal decision. The therapist should clarify the professional role and help the client examine values, concerns, and desired outcomes while keeping ownership of the decision with the client.',
			'B' => 'Decisional balance is a legitimate technique and may be useful later, but beginning with the technique does not first correct the client\'s expectation that the therapist will make the decision.',
			'C' => 'Relationship history may provide important information, but gathering additional evidence about the marriage does not address the role misunderstanding at the center of the client\'s request.',
			'D' => 'Urgency, coercion, and safety are important if indicated. The vignette does not establish those as the primary issue, so this option changes the assessment priority.',
		),
	),
	'CTA-LMFT-CA-FB-003' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-LE6-008',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Shared decision-making is client-centered, but the stem identifies a problem in the therapist\'s own values and prior steering. Comparing strategies does not directly manage that interference.',
			'B' => 'Best answer. The therapist should recognize that personal values are shaping recommendations, return treatment to the client\'s goals, obtain an outside perspective when needed, and monitor later recommendations for neutrality.',
			'C' => 'Allowing the client to reject advice does not correct the therapist\'s continued preference for harsher consequences or the repeated steering described in the stem.',
			'D' => 'Referral may become necessary if the therapist cannot practice neutrally, but the first response is to address the therapist\'s own value interference rather than transfer the client automatically.',
		),
	),
	'CTA-LMFT-CA-FB-004' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-DI-005-R1',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The client is preoccupied with a perceived appearance defect that others do not observe, engages in repetitive mirror checking, comparison, reassurance seeking, and camouflage, and experiences substantial distress and functional impairment. That is the characteristic body-dysmorphic pattern within the obsessive-compulsive-related family.',
			'B' => 'General OCD is less specific because the obsession and repetitive behaviors are organized specifically around perceived physical appearance.',
			'C' => 'The repetitive appearance-focused behaviors and retained recognition that the belief may be exaggerated make the OCD-related formulation more appropriate than a primary delusional disorder.',
			'D' => 'The concern is not about body weight or fatness and is not embedded in a restrictive eating syndrome.',
		),
	),
	'CTA-LMFT-CA-FB-005' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-TX5D-007-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Rehearsal can support a client who has decided to disclose, but this option assumes disclosure is the preferred next step before the client has completed an individualized risk-benefit and timing decision.',
			'B' => 'Strengthening support is useful, but directing the client to delay disclosure substitutes the therapist’s judgment for the client’s autonomy when there is no acute safety condition requiring that recommendation.',
			'C' => 'Best answer. The intervention affirms identity while helping the client evaluate goals, anticipated responses, supports, and timing so the disclosure decision remains individualized and autonomous.',
			'D' => 'Exploring family influence and strengthening self-acceptance may help, but postponing the decision until the client is less reactive may imply that disclosure requires a particular emotional state rather than a values- and context-based choice.',
		),
	),
	'CTA-LMFT-CA-FB-006' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-TX5E-008-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Interpretation may eventually be useful, but self psychology prioritizes empathic understanding of the selfobject injury before moving quickly to a defensive explanation of idealization.',
			'B' => 'Best answer. The limit has disrupted an idealizing selfobject experience and the client reports loss of cohesion, so empathic rupture work should first understand the injury and help restore a more cohesive sense of self.',
			'C' => 'Identifying selfobject functions can inform longer-term treatment, but immediately redirecting those functions to other relationships risks bypassing the rupture that just occurred with the therapist.',
			'D' => 'Validation and consistent limits are appropriate, but emphasizing reduced reliance and independent coping can miss the self-psychological task of understanding and repairing the selfobject disruption.',
		),
	),
	'CTA-LMFT-CA-FB-007' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-CP-008',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Identifying automatic appraisals, examining evidence, and testing balanced alternatives is standard CBT. It does not as directly address demandingness and global self-rating.',
			'B' => 'Exploring early criticism, evaluative transference, and shame-related defenses is psychodynamic.',
			'C' => 'Empathic acceptance and nondirective values clarification are humanistic/client-centered. The option does not directly challenge the rigid beliefs maintaining the problem.',
			'D' => 'The client’s statements contain two especially characteristic REBT processes: demandingness—“I must never disappoint anyone”—and global self-rating—“failure proves I am worthless.” D directly identifies and disputes those beliefs and replaces them with flexible preferences and unconditional acceptance. REBT sources identify disputation, rigid “must” demands, global evaluation, flexible preferences, and unconditional self-acceptance as central constructs.',
		),
	),
	'CTA-LMFT-CA-FB-008' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-LE6-015-R2',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'The authorization permits attendance and session-compliance reporting, not a progress summary. Probation referral status does not independently expand the disclosure scope.',
			'B' => 'Best answer. The therapist should provide only the information covered by the client\'s authorization and withhold diagnosis, symptoms, and treatment content unless another valid legal basis is established.',
			'C' => 'A blanket refusal ignores the client\'s existing authorization for attendance and compliance reporting.',
			'D' => 'The therapist does not need a broader authorization to provide information already authorized. Withholding permitted attendance information while waiting for expansion is unnecessarily restrictive.',
		),
	),
	'CTA-LMFT-CA-FB-009' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-CR-002-R3',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'Meals, shelter, outreach, and case management may be necessary, but they still assume enough independent organization to use those supports safely.',
			'B' => 'Medication-focused stabilization and supervised community support may be part of treatment, but the current inability to manage food, shelter, orientation, and self-care requires a staffed setting now.',
			'C' => 'Severe disorganization is preventing reliable basic self-care and safe functioning. A staffed crisis setting can provide same-day assessment, observation, psychiatric stabilization, and direct support for basic needs.',
			'D' => 'Temporary housing plus consultation does not provide sufficient immediate containment for the degree of disorganization and loss of self-care capacity established.',
		),
	),
	'CTA-LMFT-CA-FB-010' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-CP-017-R3',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'A respectful closure message, referrals, and documentation are useful, but this pathway moves to closure without making the stronger continuity-oriented outreach and final-session offer warranted by abrupt disengagement and expressed dissatisfaction.',
			'B' => 'Several outreach attempts may become intrusive or coercive when there is no known acute safety concern. Keeping the case open until the client responds also creates an indefinite administrative status dependent on participation the client has not requested.',
			'C' => 'One feedback-focused message and an offer of consultation are appropriate, but requiring the client to confirm the decision before closure makes the ending dependent on a response that may never come.',
			'D' => 'Reasonable, respectful outreach gives the client an opportunity to discuss dissatisfaction, complete a final session, and receive continuity information. Documenting those efforts and closing after no response balances nonabandonment with respect for the client’s choice not to reengage.',
		),
	),
	'CTA-LMFT-CA-FB-011' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-TX5D-005-R2',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Study structure may improve task completion, but it does not directly reverse the avoidance cycle around class attendance and contact with the instructor.',
			'B' => 'Peer support can improve mastery, but making return to class contingent on feeling more competent risks maintaining academic avoidance.',
			'C' => 'Cognitive preparation can reduce anticipatory anxiety, but rehearsal alone does not create a graded behavioral return to the avoided academic setting.',
			'D' => 'Correct. A graded return directly interrupts the avoidance cycle and reconnects the student with the class and instructor while the academic backlog is addressed.',
		),
	),
	'CTA-LMFT-CA-FB-012' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-TX5E-009-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. The client explicitly wants to clarify meaning in the face of limited time, making exploration of values, choice, and how to live authentically within present limits the most responsive existential intervention.',
			'B' => 'Responsibility and choice are important existential themes, but a retrospective accounting of past decisions risks shifting toward judgment rather than the client’s stated wish to determine what matters now.',
			'C' => 'Mortality and finitude are directly relevant and this intervention is highly plausible, but the client has already acknowledged death and is asking how to orient the remaining life around meaning.',
			'D' => 'A legacy activity may eventually become meaningful, but prescribing a concrete project before the client identifies personally chosen meaning could substitute the therapist’s structure for the client’s existential exploration.',
		),
	),
	'CTA-LMFT-CA-FB-013' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-CE-013',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Breakup distress could contribute to use, but beginning with grief and mood risks reducing substance use to a coping response before its independent pattern is assessed.',
			'B' => 'Tolerance, withdrawal, craving, and impaired control are relevant, but this option underemphasizes the chronology and functional decline emphasized in the vignette.',
			'C' => 'Substance history and family context may eventually inform formulation but are less immediately useful than assessing the current change in use and functioning.',
			'D' => 'The presentation involves escalating cannabis use after a breakup together with occupational and social decline. Mapping use amount and frequency, timing, efforts to reduce use, and functional consequences directly evaluates that pattern.',
		),
	),
	'CTA-LMFT-CA-FB-014' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-CE-034',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Symptom duration and functioning are relevant but conventional bereavement comparisons may fit poorly when the status of the loved one remains unresolved.',
			'B' => 'Lack of recognition and support is important, but it represents only one aspect of the client\'s experience.',
			'C' => 'The family member\'s disappearance creates an ambiguous loss with limited social recognition. Evaluating the meaning of the loss, social recognition, cultural context, support, and current functioning best captures the client\'s grief experience.',
			'D' => 'Previous unresolved losses and spiritual beliefs may provide useful historical context but are less directly responsive to the current ambiguous loss and its present effects.',
		),
	),
	'CTA-LMFT-CA-FB-015' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-DI-008-R3',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'A schizophrenia-spectrum interpretation would require evidence beyond a culturally recognized perceptual experience confined to a ritual context; the added interpretive wording does not supply a broader psychotic syndrome.',
			'B' => 'No delusional syndrome is established; the experience is limited to a recognized spiritual ritual and does not produce a broader psychotic presentation.',
			'C' => 'The perceptual experience is culturally sanctioned, occurs only in the ritual context, and is not accompanied by distress, disorganization, or impaired functioning, so a primary psychotic diagnosis is not supported.',
			'D' => 'The stem does not describe detachment, amnesia, identity disruption, or another dissociative syndrome; the religious context alone does not make the experience dissociative.',
		),
	),
	'CTA-LMFT-CA-FB-016' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-CP-013',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The client intellectualizes unresolved grief, shifts away from immediate feeling, and has difficulty noticing physical responses. A focuses on present-moment contact, experiential awareness of bodily and emotional signals, and integration of unfinished grief. Gestalt therapy emphasizes contact, conscious awareness, experimentation, present experience, body awareness, and unfinished business.',
			'B' => 'Developmental loss patterns, transference, avoidance, and unconscious conflict are psychodynamic.',
			'C' => 'Identifying appraisals, evaluating evidence, and using activity scheduling is CBT.',
			'D' => 'Separating grief from identity and developing an alternative story of continuing bonds is narrative.',
		),
	),
	'CTA-LMFT-CA-FB-017' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-TX5C-001',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. Pacing addresses the illness- or injury-related stressor directly, while renegotiating roles helps the couple adapt relational expectations to the client’s current and more predictable functional limits.',
			'B' => 'Relaxation and temporary assistance may help during flares, but this keeps the household responding reactively to the boom-and-bust cycle rather than changing the overexertion pattern that contributes to it.',
			'C' => 'Grief work may be appropriate, but delaying role adaptation leaves a current functional and relational problem untreated even though medical rehabilitation is already established.',
			'D' => 'Couple problem-solving is useful, but psychotherapy can address behavioral pacing and its relational consequences while coordinating with rehabilitation rather than treating pacing as outside the therapeutic domain.',
		),
	),
	'CTA-LMFT-CA-FB-018' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-CE-005-R1',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Areas of agreement with court concerns may be clinically useful, but making those concerns the starting framework risks allowing the referral source to define the client\'s therapy.',
			'B' => 'Reporting boundaries must be clear, but deciding whether therapy should focus primarily on court concerns prematurely privileges the mandate over the client\'s clinical needs.',
			'C' => 'Court-mandated participation establishes an external condition, not necessarily the client\'s therapeutic goal. C distinguishes the referral requirement from the client\'s perspective and explores whether meaningful treatment goals can exist within a mandated context.',
			'D' => 'Practical, parenting, or relationship goals may ultimately emerge, but offering categories of goals before adequately exploring the client\'s own perspective can subtly impose treatment content.',
		),
	),
	'CTA-LMFT-CA-FB-019' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-TX5A-001-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. The adolescent already experiences the aunt’s reliable routines as caring. Using those established practices as the attachment base and adding a repair process that fits the family’s style is culturally responsive and clinically targeted.',
			'B' => 'Exploring which expressions of closeness feel authentic can increase mutual understanding, but it is less direct than using the caregiving rituals that already function as attachment signals and addressing withdrawal after conflict.',
			'C' => 'A verbal-affection routine may be well intended, but it risks privileging verbal reassurance over the family’s existing culturally meaningful caregiving behaviors.',
			'D' => 'Individual work on caregiver disruption may help the adolescent process change, but the stem already identifies a safe caregiver relationship that can be strengthened directly through dyadic treatment.',
		),
	),
	'CTA-LMFT-CA-FB-020' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-CE-017',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Individual mood and health may influence adjustment but do not sufficiently capture the couple\'s shared transition.',
			'B' => 'Retirement has altered several major life-cycle dimensions at once—roles, routines, identity, intimacy, social connection, and expectations. Evaluating those changes directly addresses the developmental transition described.',
			'C' => 'Financial effects of retirement may be significant, but the vignette identifies a broader reorganization than economics alone.',
			'D' => 'Earlier couple patterns provide useful history but should not be presumed to explain difficulties that emerged during a major new developmental stage.',
		),
	),
	'CTA-LMFT-CA-FB-021' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-CP-007',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Hierarchy, boundaries, coalitions, and structural enactments constitute a structural family therapy plan.',
			'B' => 'Multigenerational patterns and differentiation are Bowen-family-systems concepts.',
			'C' => 'The family discusses the loss intellectually, avoids immediate emotion, and wants greater closeness while remaining controlled and distant in sessions. C targets the here-and-now experience through emotional contact, enactment, authenticity, and congruent expression. Experiential family therapy, including Satir’s work, emphasizes present experience, human authenticity, and congruent communication.',
			'D' => 'Identifying a maintaining sequence and prescribing structured conversations is strategic therapy.',
		),
	),
	'CTA-LMFT-CA-FB-022' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-LE6-004',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. Attendance and client status are protected treatment information. The spouse\'s statement that treatment is occurring does not create authority for the therapist to confirm it.',
			'B' => 'Appointment dates disclose treatment participation and are not made permissible merely by withholding diagnosis or session content.',
			'C' => 'Confirming that the person is an active client is itself a disclosure of protected treatment information.',
			'D' => 'Seeking authorization could be appropriate if there is a genuine treatment reason for communication, but an unsolicited spouse request does not require the therapist to involve the client or create a new disclosure process. The therapist can simply preserve confidentiality.',
		),
	),
	'CTA-LMFT-CA-FB-023' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-CE-026',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'compares occupational and friendship behavior usefully but does not establish the pattern across the client’s broader social history.',
			'B' => 'relies too heavily on one recent rupture.',
			'C' => 'The discrepancy between adequate occupational relationships and repeated friendship problems makes a broader social-history review necessary. Looking across relationships for recurring interaction patterns, ruptures, repair attempts, and periods of connection best evaluates the client’s social functioning.',
			'D' => 'moves toward explaining the pattern through individual vulnerabilities before adequately establishing the relational pattern itself.',
		),
	),
	'CTA-LMFT-CA-FB-024' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-TX5F-005-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Comparing data is useful, but retaining different definitions and reinforcement approaches across settings preserves the inconsistency that is limiting progress.',
			'B' => 'Best answer. Standardizing the target-behavior definition and reinforcement approach across home, school, and treatment directly addresses the cross-setting inconsistency.',
			'C' => 'Sharing observations and revising only the therapy plan leaves the parent and teacher using the same inconsistent approaches that contributed to uneven progress.',
			'D' => 'Applying the therapist\'s plan everywhere might increase consistency, but it is less collaborative and does not require the team to develop a shared operational definition and coordinated approach.',
		),
	),
	'CTA-LMFT-CA-FB-025' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-TX5F-002-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Meal delivery addresses one identified barrier but does not coordinate the transportation and caregiver-strain needs that are also affecting the household.',
			'B' => 'Accessible transportation addresses appointment access but leaves the meal-preparation and caregiver-burden concerns uncoordinated.',
			'C' => 'Best answer. A care coordinator is suited to a client with several simultaneous aging-in-place barriers because the service can organize needs and connect the household to multiple programs.',
			'D' => 'Respite directly addresses caregiver strain but does not integrate the client’s transportation and meal needs into a broader support plan.',
		),
	),
);
