<?php
/**
 * ADMIN ONLY — LMFT California Clinical Form A answer key items 76–100 (PROMPT 16).
 * Secured answer + rationale mapping. Never exposed to learners.
 *
 * @package CTA_LMS
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'CTA-LMFT-CA-FA-076' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-CE-016',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Communication and social skills are particularly relevant, but this option narrows the developmental review before establishing whether other developmental domains are also involved.',
			'B' => 'The concern appears differently across language environments and settings. Reviewing developmental history across multiple domains while accounting for language exposure and environmental demands is the strongest way to determine whether the observed differences reflect developmental concerns, contextual variation, or both.',
			'C' => 'Preschool observations are important, but privileging the school environment does not adequately incorporate the substantially different home presentation.',
			'D' => 'Early milestones, hearing, and language exposure are useful historical information, but this option gives less attention to current functioning across developmental domains and settings.',
		),
	),
	'CTA-LMFT-CA-FA-077' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-DI-010-R2',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'The client has substantial physical symptoms together with persistent, excessive health-related thoughts and behaviors that consume significant time and disrupt functioning. Somatic symptom disorder can coexist with a genuine medical condition.',
			'B' => 'Illness anxiety disorder is more characteristic when physical symptoms are absent or minimal. Here, chronic abdominal pain is a substantial part of the presentation.',
			'C' => 'The anxiety is concentrated on physical symptoms and health rather than distributed across multiple unrelated domains as expected in generalized anxiety disorder.',
			'D' => 'Factitious disorder requires intentional falsification or production of illness behavior. The stem provides no evidence of deliberate fabrication.',
		),
	),
	'CTA-LMFT-CA-FA-078' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-LE6-012',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. The therapist should avoid publicly confirming the treatment relationship, reduce the identifying exposure if the platform permits, and address confidentiality and social-media boundaries privately with the client.',
			'B' => 'Removing the comment may reduce exposure, but instructing the client about future posts is more controlling than necessary and places greater emphasis on regulating the client\'s public behavior than on a collaborative boundary plan.',
			'C' => 'Not replying protects against public confirmation, but leaving an identifying comment visible without taking a reasonable step to reduce exposure is less protective than the keyed response.',
			'D' => 'Even a neutral public reply can create additional association between therapist and client. The stronger response avoids public engagement with the identifying comment.',
		),
	),
	'CTA-LMFT-CA-FA-079' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-TX5C-009-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Providing feedback with permission is consistent with motivational interviewing, but the client is already expressing both sustain talk and concerns about drinking, making direct exploration of the ambivalence more immediately responsive.',
			'B' => 'Importance and confidence rulers can evoke change talk, but moving to ratings is less direct than first reflecting the ambivalence the client has just expressed and inviting further self-generated exploration.',
			'C' => 'Best answer. A double-sided reflection acknowledges both the perceived benefits and costs of drinking, while the follow-up question evokes the client’s own motivations without arguing for change or prematurely moving into planning.',
			'D' => 'Supporting a client-selected goal is appropriate once the client is ready for planning, but the stem indicates active ambivalence and no clear commitment to change yet.',
		),
	),
	'CTA-LMFT-CA-FA-080' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-TX5E-008-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Exploring early caregiving expectations may deepen understanding, but the immediate treatment target is the client\'s protective withdrawal when closeness is offered.',
			'B' => 'Direct disclosure and reassurance-seeking may increase connection, but it can leave the client\'s attachment-based withdrawal strategy unchanged and may strengthen dependence on reassurance.',
			'C' => 'Best answer. The intervention identifies withdrawal as protective, examines how it functions during bids for closeness, and practices a tolerable reciprocal response rather than repeating avoidance.',
			'D' => 'Physiological awareness and grounding can support regulation, but they do not directly address the attachment expectation that emotional investment will lead to disappointment.',
		),
	),
	'CTA-LMFT-CA-FA-081' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-CP-003',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The client has attended, understood the treatment model, and completed assigned practices during an adequate trial. When engagement and implementation are present but the target symptoms and impairment remain unchanged, the therapist should reconsider whether the formulation and selected intervention are addressing the actual maintaining mechanism.',
			'B' => 'Increasing exposure dose or assignment intensity would be appropriate if insufficient implementation were established. The stem instead states that the client completed the practices during an adequate trial, so simply providing more of the same may repeat an ineffective approach.',
			'C' => 'Diagnostic or medication consultation may be useful as one component of reassessment, but the option leaves the current psychotherapy target unchanged despite evidence that it has not produced meaningful improvement.',
			'D' => 'Alliance and treatment preferences should be monitored, but the stem provides no direct evidence that an alliance rupture explains the lack of progress. Moving immediately into supportive therapy changes the approach before the formulation failure has been examined.',
		),
	),
	'CTA-LMFT-CA-FA-082' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-DI-017-R3',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'A job change is present, but the couple identifies the affair-related relationship rupture—not occupational stress—as the primary reason for treatment.',
			'B' => 'The affair-related rupture, mistrust, repeated conflict, and uncertainty about the relationship are the explicit treatment focus, while no individual mental disorder is supported.',
			'C' => 'The vignette does not identify a parent-child relational problem as the primary clinical concern.',
			'D' => 'Financial strain is present but secondary; the couple identifies the intimate-partner rupture as the central reason for care.',
		),
	),
	'CTA-LMFT-CA-FA-083' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-CP-012',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Externalizing morning chaos and developing an alternative family story is narrative planning.',
			'B' => 'Analyzing antecedents and consequences and establishing contingencies is behavioral/CBT-oriented planning. It is plausible but does not use the successful exceptions central to the specification.',
			'C' => 'Prescribing a sequence change and revising the directive based on the family’s response is strategic therapy.',
			'D' => 'The family already reports several successful mornings. D develops a preferred future, examines those exceptions, uses scaling, and converts previously successful behavior into a small repeatable next step. Official SFBTA materials emphasize client-defined preferred futures, exceptions, existing competencies and resources, scaling, and small solution-building changes.',
		),
	),
	'CTA-LMFT-CA-FA-084' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-DI-004',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Generalized anxiety disorder involves a broader persistent worry pattern rather than recurrent unexpected panic attacks as the central syndrome.',
			'B' => 'Social anxiety is organized around scrutiny, embarrassment, or rejection in social/performance settings.',
			'C' => 'The avoidance described is fear of panic-related bodily sensations during exercise rather than the broader situational pattern necessary to make agoraphobia the better diagnosis.',
			'D' => 'The attacks are recurrent and unexpected, and they are followed by persistent concern and behavioral avoidance related to another attack. That organization distinguishes panic disorder from anxiety tied primarily to social scrutiny or broad everyday worry.',
		),
	),
	'CTA-LMFT-CA-FA-085' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-CE-003-R1',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The adolescent\'s internal experience is highly relevant, but beginning primarily from that perspective risks giving one source priority when the discrepancy itself needs evaluation.',
			'B' => 'The adolescent, parents, and school provide differing accounts. Those differences are assessment information. Comparing specific examples, timing, setting, and consequences across sources allows the therapist to understand the presenting concern before choosing among competing explanations.',
			'C' => 'Family-maintenance factors may contribute to school refusal, but this option selects a family explanation before the broader cross-informant pattern has been clarified.',
			'D' => 'School records and observations could strengthen the evaluation, but collecting additional school information does not replace comparing the already conflicting perspectives of the adolescent and parents.',
		),
	),
	'CTA-LMFT-CA-FA-086' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-CE-007-R2',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Depression is a plausible explanation, but this option moves from an observed MSE change to a diagnostic hypothesis too early.',
			'B' => 'Medical, medication, substance, or sleep factors could contribute, but they are possible explanations for the finding rather than the first task of describing the current mental status.',
			'C' => 'Collateral information could help establish functional change, but the therapist should first assess the directly observable mental-status findings.',
			'D' => 'The therapist is directly observing changes in appearance and psychomotor activity. The immediate MSE task is to characterize those observable findings and determine how they differ from baseline before explaining their cause.',
		),
	),
	'CTA-LMFT-CA-FA-087' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-TX5A-007-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'This is collaborative and consent-aware, but it treats the problem mainly as a frequency-negotiation issue and does not directly interrupt the pressure-withdraw cycle driven by outside expectations.',
			'B' => 'Postpartum fatigue and body-image concerns are relevant, but moving the work primarily into one partner’s individual experience misses the couple-level interaction that is maintaining disconnection.',
			'C' => 'Best answer. The intervention directly targets the pressure-withdraw pattern, corrects the externally imposed “normal” timeline, and broadens intimacy so closeness is not equated with pressured sexual performance.',
			'D' => 'Sensate-attention work can reduce performance pressure, but it does not as directly address the couple’s meaning-making around rejection and the outside expectations that are driving the current cycle.',
		),
	),
	'CTA-LMFT-CA-FA-088' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-TX5E-006-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Externalizing the dominant story and identifying resistance are valid narrative interventions, but the stem already contains a concrete exception that can be developed more fully.',
			'B' => 'Best answer. The leadership event is a clear unique outcome. Building a richer preferred-identity narrative from the adolescent\'s choices and qualities thickens an alternative story that competes with the long-standing troublemaker identity.',
			'C' => 'Deconstructing school labels can reduce the power of the dominant discourse, but it remains centered on the imposed story rather than expanding the new leadership exception already present.',
			'D' => 'A therapeutic letter can reinforce preferred-story development, but documenting the new story is less useful than first developing the unique outcome in greater depth.',
		),
	),
	'CTA-LMFT-CA-FA-089' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-CR-015',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Normalizing early reactions and monitoring may be useful, but this response underaddresses the family\'s concrete disruption in housing, routines, school continuity, rest, and daily functioning.',
			'B' => 'Trauma-symptom assessment can contribute later, but diagnostic clarification should not take priority over immediate stabilization and restoration of basic functioning after displacement.',
			'C' => 'The family is physically safe but lacks ordinary routines and stability. Addressing resources and coping needs, restoring predictable routines, and strengthening natural supports directly supports early recovery.',
			'D' => 'Housing resources and coping support are appropriate, but introducing structured trauma work as an early next step may move ahead of basic security, routine restoration, and readiness.',
		),
	),
	'CTA-LMFT-CA-FA-090' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-CP-016',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'A planned ending should include a defined timeline, consolidation of treatment gains, recognition of warning signs, maintenance strategies, and clear information about reentry or additional care. A includes all of those elements without unnecessarily extending treatment.',
			'B' => 'Two summary sessions may be adequate in some circumstances, but this option compresses termination into a brief review and leaves future care primarily to an invitation to return if symptoms recur. It does not establish as complete a maintenance and reentry plan.',
			'C' => 'An open-ended taper provides no clear endpoint and makes termination dependent on recurrence risk becoming minimal. Some future vulnerability may remain even after treatment has been appropriately completed.',
			'D' => 'The client has already met the agreed goals and accepted the ending. Adding a new growth phase creates further treatment without a clearly established clinical need.',
		),
	),
	'CTA-LMFT-CA-FA-091' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-CE-040',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Medical causes can sometimes contribute to mood or behavioral changes, but the vignette does not provide physical findings that make a general medical evaluation the most directly indicated referral.',
			'B' => 'Psychological testing can answer particular diagnostic or personality questions but is not the most appropriate first specialty evaluation for the episodic mood pattern described.',
			'C' => 'The therapist does not need to establish the definitive diagnosis independently before making an appropriate psychiatric referral.',
			'D' => 'The client reports distinct episodes involving markedly reduced need for sleep, increased activity, unusual confidence, impulsive spending, and depression. A psychiatric evaluation is the additional assessment most directly suited to clarifying this episodic mood presentation and possible need for psychiatric treatment.',
		),
	),
	'CTA-LMFT-CA-FA-092' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-DI-008',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Panic may contain feelings of unreality, but the stem does not establish recurrent panic attacks as the organizing syndrome.',
			'B' => 'The client experiences recurrent detachment from self and surroundings while maintaining awareness that the altered experience is subjective rather than literally real. APA includes depersonalization/derealization among the major dissociative disorders and describes dissociation as involving disruptions in perception and sense of self.',
			'C' => 'Preserved reality testing and the absence of psychotic disorganization weigh against a schizophrenia-spectrum formulation.',
			'D' => 'No distinct identity states or corresponding identity disruption are described.',
		),
	),
	'CTA-LMFT-CA-FA-093' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-CP-001-R2',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Pausing and engaging in planned connection activities may reduce some conflict, but this plan does not directly require the couple to return to and repair the interrupted interaction. It could reduce argument frequency without changing the pursue–withdraw process.',
			'B' => 'The formulation identifies a reciprocal pursue–withdraw cycle rather than a problem located in either partner alone. The immediate goal should therefore help the couple interrupt escalation and successfully return to the conversation. The longer-term plan also needs to represent both partners’ priorities: increased connection and legitimate space for emotional regulation. B accomplishes both while providing observable indicators of repair and responsiveness.',
			'C' => 'Trigger awareness and vulnerable discussion can become useful later, but the couple has not yet demonstrated reliable de-escalation and repair. Moving first toward deeper disclosure may exceed the current treatment stage.',
			'D' => 'Needs-sharing and engagement periods are relevant, but the plan does not protect the withdrawing partner’s stated need for respectful space as clearly as B. It also focuses more on identifying the pattern than on completing successful repairs.',
		),
	),
	'CTA-LMFT-CA-FA-094' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-CE-038',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'A broad distress measure could provide useful information but is less directly matched to the anxiety construct the therapist specifically wants to monitor.',
			'B' => 'Daily self-monitoring can help identify fluctuations and triggers, but a therapist-created log is not equivalent to using a standardized instrument for comparable symptom measurement.',
			'C' => 'The therapist wants structured information about anxiety that can be compared over time. A validated anxiety measure directly matches that assessment purpose while remaining one source of information interpreted alongside interview findings and functioning.',
			'D' => 'Functional measurement may supplement the evaluation, but it measures a different construct and cannot substitute for targeted assessment of anxiety symptoms.',
		),
	),
	'CTA-LMFT-CA-FA-095' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-TX5F-002-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Food assistance is relevant to the client’s financial strain, but the stem states that food is available for the next several days and the urgent threat is the utility shutoff.',
			'B' => 'Employment services could improve income over time, but they cannot address the immediate loss of electricity scheduled for tomorrow.',
			'C' => 'Housing-stability services may help with longer-term financial planning, but the most immediate barrier is the pending utility shutoff.',
			'D' => 'Best answer. The referral matches the most urgent practical barrier and can address the imminent shutoff while also determining whether continued energy assistance is available.',
		),
	),
	'CTA-LMFT-CA-FA-096' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-CE-025',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'prematurely frames reduced social activity through depression.',
			'B' => 'evaluates relationship quality but is too narrow to characterize the broader change in social functioning.',
			'C' => 'The clinically important feature is the change from the client’s prior social functioning after relocation. Comparing pre-relocation and current connection, desired involvement, available support, and barriers to participation directly evaluates whether the client is experiencing meaningful social isolation or simply choosing more solitude.',
			'D' => 'appropriately considers environmental access but emphasizes opportunities for connection before establishing the client’s actual social pattern and desired level of involvement.',
		),
	),
	'CTA-LMFT-CA-FA-097' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-TX5D-008-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Increasing contact with affirming relatives can reduce exposure to harm, but the client specifically wants to preserve the parental relationship if it can be made safer.',
			'B' => 'Best answer. The client’s stated goal is continued family connection with self-protection. Clear visit-specific boundaries, practiced responses, and predetermined limits directly support both parts of that goal.',
			'C' => 'Processing grief and clarifying desired closeness are appropriate, but the client has already identified a wish to maintain contact and needs a concrete strategy for protecting boundaries during visits.',
			'D' => 'Mapping supportive and harmful relationships is affirming and may guide broader family choices, but it is less direct than establishing and practicing boundaries for the parental visits the client wants to continue.',
		),
	),
	'CTA-LMFT-CA-FA-098' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-LE6-007-R1',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'A structured grief protocol and clearer boundaries may be useful, and documenting consultation is appropriate, but this pathway moves too quickly toward a treatment protocol rather than first using consultation to examine how the therapist\'s own grief and overidentification are shaping clinical judgment.',
			'B' => 'Best answer. The therapist has identified a countertransference pattern affecting boundaries and treatment decisions. Consultation focused on the overidentification, consistent limits, and continued observation directly addresses the problem while preserving care.',
			'C' => 'A clinically purposeful self-disclosure can sometimes be appropriate, but disclosure is not the primary method for managing the therapist\'s countertransference and may shift focus away from the client.',
			'D' => 'Consultation about frequency, structure, or referral may become necessary if the therapist cannot correct the problem, but those changes are secondary to examining and managing the overidentification already shaping treatment.',
		),
	),
	'CTA-LMFT-CA-FA-099' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-CP-004',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Inviting reactions to the formulation is helpful, but the option starts by explaining the therapist’s view and delays process change for several sessions. That may reinforce the perception that the therapist is defending the existing alignment.',
			'B' => 'An individual conversation may yield useful feedback, but meeting separately with the already quieter partner could deepen the sense of triangulation or secrecy. The option also returns to the existing conjoint process without clearly repairing it.',
			'C' => 'The partner’s increasing silence and missed sessions follow a perception that the therapist accepts the other partner’s account. These are credible indicators of an alliance rupture. C addresses the rupture with both members of the treatment unit, includes examination of the therapist’s contribution, and uses their feedback to revise the conjoint process.',
			'D' => 'Equal speaking time and routine feedback may improve structure, but they do not sufficiently examine the meaning of the perceived alignment or the therapist’s contribution. Waiting for continued attendance problems also delays repair.',
		),
	),
	'CTA-LMFT-CA-FA-100' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-TX5E-002-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. Structural family therapy uses live enactment to expose and alter the hierarchy in the room. Coaching the parents to state the limit together strengthens the parental subsystem while the grandmother experiences the new boundary.',
			'B' => 'Hierarchy mapping and redirection are structurally appropriate, but they are less powerful than working directly with the disagreement that is already occurring in session.',
			'C' => 'Joining the grandmother and strengthening the parents are plausible structural moves, but negotiating the content of the gaming rule is less central than changing the hierarchy around who sets the rule.',
			'D' => 'Structured turn-taking may improve order, but it is more procedural and less directly focused on restructuring the live parental-grandparent hierarchy.',
		),
	),
);
