<?php
/**
 * ADMIN ONLY — LMFT California Clinical Form B answer key items 76–100 (PROMPT 22).
 * Secured answer + rationale mapping. Never exposed to learners.
 *
 * @package CTA_LMS
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'CTA-LMFT-CA-FB-076' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-CP-002',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Child and caregiver symptoms are measured, but the school setting is represented mainly through therapist observation rather than direct teacher or classroom-functioning information.',
			'B' => 'Attendance, nurse visits, assignments, classroom behavior, and teacher reports provide strong school data but underrepresent home symptoms and caregiver accommodation.',
			'C' => 'The anxiety presents differently across home and school and involves symptoms, attendance, classroom functioning, and caregiver accommodation. C integrates direct reports from the child, caregiver, and teacher with observable indicators from both settings.',
			'D' => 'Family accommodation, parent distress, and school-refusal behavior are relevant, but the plan omits direct child and teacher symptom reports and relies partly on a therapist confidence rating.',
		),
	),
	'CTA-LMFT-CA-FB-077' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-LE6-011',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Client willingness to accept privacy risk does not eliminate the therapist\'s professional responsibility to manage confidentiality and appropriateness in telehealth. Avoiding names does not make an audible sensitive discussion adequately private.',
			'B' => 'Shifting to less sensitive material may reduce immediate exposure, but the client is still in an environment where therapy can be overheard. The therapist should first address whether the setting is appropriate for substantive treatment.',
			'C' => 'Headphones and additional distance may reduce exposure, but they do not establish adequate privacy for a highly sensitive discussion. Documenting the client\'s choice also does not remove the therapist\'s professional responsibility to address the setting.',
			'D' => 'Best answer. Telehealth does not eliminate confidentiality and professional-practice responsibilities. The therapist should address the privacy problem before substantive discussion and either improve the setting or reschedule as clinically appropriate.',
		),
	),
	'CTA-LMFT-CA-FB-078' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-TX5A-002-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Separating decision domains respects both traditions but institutionalizes different expectations instead of helping the parents co-parent consistently.',
			'B' => 'Correct. The task is to integrate culturally grounded parenting values into a coordinated response rather than privileging one cultural model or ignoring the differences.',
			'C' => 'Choosing one guiding principle creates consistency but can flatten meaningful differences and prematurely privilege one framework.',
			'D' => 'A united presentation may reduce overt conflict in front of the adolescent, but it does not resolve the incompatible expectations driving the pattern.',
		),
	),
	'CTA-LMFT-CA-FB-079' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-TX5D-003',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Reinforcing calm behavior is useful, but a delayed end-of-day plan does not directly change the immediate sequence in which aggression is followed by extensive attention and access to another preferred activity.',
			'B' => 'Best answer. The intervention uses an available developmentally appropriate replacement behavior and changes the caregiver contingency that currently follows aggression, while preserving clear caregiver structure and support.',
			'C' => 'Calming and validation may reduce arousal, but restarting a preferred activity after aggression risks maintaining the behavior by allowing aggression to continue producing access to something desirable.',
			'D' => 'Brief separation and repair address the aftermath of aggression, but this does not teach the available replacement request or change the consequence pattern that currently follows aggression.',
		),
	),
	'CTA-LMFT-CA-FB-080' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-DI-013-R1',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The client has recurrent weekly binges for longer than three months, loss of control, marked distress, multiple associated features, and no regular compensatory behavior. APA distinguishes binge-eating disorder from bulimia specifically by the absence of regular vomiting, fasting, excessive exercise, or similar compensation.',
			'B' => 'Bulimia requires recurrent compensatory behavior following binges.',
			'C' => 'The stem does not establish the low-weight restrictive syndrome required for anorexia nervosa.',
			'D' => 'The full binge-eating disorder pattern is established, so an other-specified category is unnecessary.',
		),
	),
	'CTA-LMFT-CA-FB-081' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-DI-006-R2',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'The panic-like episodes occur in response to trauma reminders rather than unexpectedly, and they occur within a broader trauma-related syndrome.',
			'B' => 'The home invasion is followed by intrusion, trauma-linked avoidance, persistent negative safety beliefs, detachment, hypervigilance, sleep disturbance, and impairment for three months, supporting posttraumatic stress disorder.',
			'C' => 'The anxiety is organized around a discrete traumatic exposure rather than broad excessive worry across multiple domains.',
			'D' => 'A situational phobia would not account for the intrusive memories, negative trauma-related beliefs, emotional detachment, and hyperarousal.',
		),
	),
	'CTA-LMFT-CA-FB-082' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-CP-016',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Discussing anger and missed sessions while maintaining the timeline is reasonable, but the plan does not sufficiently connect the behavior to the adolescent’s history of disrupted relationships.',
			'B' => 'The adolescent’s anger, missed sessions, and testing of the therapist’s availability occur in the context of repeated placement disruptions. The response should connect the current reaction to that developmental history, maintain a predictable ending, and appropriately involve the supportive caregiver.',
			'C' => 'A time-limited extension might sometimes support developmentally appropriate termination work, but this option makes ending dependent on the adolescent accepting termination. That can create an uncertain or indefinite endpoint.',
			'D' => 'Continued absences require attention, but arranging transfer treats the behavior primarily as disengagement or noncompliance. The therapist should first understand it as a possible response to another anticipated relational disruption.',
		),
	),
	'CTA-LMFT-CA-FB-083' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-CE-021-R1',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The family is simultaneously managing relocation, a new job, school transition, and weekday separation. Mapping how those stressors interact with routines, support, symptoms, and family functioning directly evaluates the cumulative psychosocial burden.',
			'B' => 'Job demands and individual coping are relevant but privilege the client\'s occupational adjustment over the wider family transition.',
			'C' => 'School adjustment and spousal separation are important, but attempting to identify which change produces the greatest strain unnecessarily reduces an interacting set of stressors to one primary cause.',
			'D' => 'Prior transition history and supports can contextualize the presentation, but the immediate assessment needs to characterize the current cluster of stressors and their effects.',
		),
	),
	'CTA-LMFT-CA-FB-084' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-CE-022',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Personal beliefs are important but cannot be meaningfully separated from community relationships when the community itself is central to the current conflict.',
			'B' => 'The client\'s religious community is simultaneously a source of support and conflict. Exploring beliefs, practices, community relationships, support, areas of tension, and their meaning for the client\'s decision captures both functions without presuming that religion is either beneficial or harmful.',
			'C' => 'Family and community pressure and functional effects deserve assessment, but this option emphasizes the conflict side more than the supportive role described.',
			'D' => 'Previous faith transitions and alternative communities may eventually provide useful context, but this response broadens beyond the immediate religious/spiritual factors influencing the current decision.',
		),
	),
	'CTA-LMFT-CA-FB-085' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-CP-004-R2',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The concern is acknowledged and the presentation of the goal is modified, but independence remains the controlling therapeutic aim. That does not fully examine whether the original goal reflects the client’s values or context.',
			'B' => 'The client identifies a specific cultural and relational mismatch in the treatment goal, followed by reduced openness and missed sessions. Repair requires the therapist to consider that the goal itself—not merely its wording—may be misattuned, understand the client’s meaning and family obligations, and revise goals and methods accordingly.',
			'C' => 'Transfer may become appropriate when repair is unsuccessful or the client prefers it, but moving there immediately bypasses an opportunity to address the therapist’s contribution and repair the alliance.',
			'D' => 'Family participation could be useful if the client desires it, but the current goals remain unchanged. Adding relatives does not by itself correct the identified cultural misattunement.',
		),
	),
	'CTA-LMFT-CA-FB-086' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-CR-007',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Substance-use treatment for the caregiver may be necessary, but it does not replace the mandated child-protection response triggered by the repeated overnight neglect.',
			'B' => 'Gathering additional facts before deciding whether to report imposes a higher evidentiary threshold than reasonable suspicion and delays the required protective response.',
			'C' => 'A family safety agreement may support immediate supervision, but it cannot substitute for the required child-protection report.',
			'D' => 'The children should remain safely supervised, and the repeated overnight neglect should be reported based on reasonable suspicion without waiting for injury or definitive proof.',
		),
	),
	'CTA-LMFT-CA-FB-087' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-TX5E-001',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Recording the sequence can clarify the maintaining pattern, but the pattern is already evident and the next strategic step should change it rather than continue observing it.',
			'B' => 'Best answer. A strategic directive that keeps both parents from changing the limit or rescuing the child directly interrupts the rescue-escalation-parental-disagreement sequence maintaining the bedtime problem.',
			'C' => 'A prescribed protest period is a legitimate strategic technique, but it does not directly target the parental rescue and disagreement that are reinforcing the current sequence.',
			'D' => 'Reframing may shift how the parents understand the protest, but observation alone does not alter the interaction that repeatedly sustains the symptom.',
		),
	),
	'CTA-LMFT-CA-FB-088' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-TX5F-001-R3',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'An open support group can reduce isolation, but broad membership and flexible attendance provide less continuity for repeated interpersonal feedback and cohesion around the client’s treatment need.',
			'B' => 'Best answer. The client is ready to benefit from group referral, and stable membership plus here-and-now interpersonal feedback directly matches the need to practice and revise recurring relationship responses.',
			'C' => 'Psychoeducation may reinforce coping knowledge, but the client has already improved symptom management and now needs sustained interpersonal interaction rather than primarily didactic content.',
			'D' => 'A skills group offers useful practice, but scripted exchanges with little process discussion are less suited to examining misread feedback and the client’s recurring reactions in relationships.',
		),
	),
	'CTA-LMFT-CA-FB-089' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-CP-015',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Processing the ending is appropriate, but waiting until the final appointment to provide referrals leaves too little time to address access barriers or create an effective transition.',
			'B' => 'Continuing current goals through session twelve may provide useful treatment, but initiating transfer only after the program has ended creates an avoidable interruption in care.',
			'C' => 'The agency ending is known in advance, and the client has both meaningful gains and unresolved needs. The remaining sessions should therefore be used to consolidate progress, identify what remains unfinished, and establish continuity before the final visit.',
			'D' => 'Beginning longer-term goals that cannot be completed within the remaining sessions does not fit the known service limit. Continuity planning should begin because the needs are already known, not only if additional goals later remain unfinished.',
		),
	),
	'CTA-LMFT-CA-FB-090' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-CE-024-R1',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Selective disclosure occurs within a context of family dependence, anticipated rejection, supportive peers, minority stress, and practical safety considerations. Evaluating those factors together avoids treating concealment itself as inherently pathological.',
			'B' => 'Internalized stigma is one possible contributor, but this option risks interpreting concealment primarily as an intrapsychic problem before accounting for realistic consequences of disclosure.',
			'C' => 'Affirming peer support is protective but does not erase family dependence or the potential costs of disclosure.',
			'D' => 'Housing and financial independence may be relevant practical concerns, but this option begins moving toward changing the current arrangement rather than first evaluating the meaning and effects of selective disclosure.',
		),
	),
	'CTA-LMFT-CA-FB-091' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-CE-015-R2',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Psychosocial stress, sleep, and earlier mood history are important but do not most directly clarify the association between stimulant exposure and the current episodic symptoms.',
			'B' => 'This option characterizes stimulant use well but gives less attention to whether the mood phenomena occur outside substance exposure.',
			'C' => 'The key unresolved issue is whether mood symptoms track stimulant exposure or also persist independently. Mapping symptoms across use, withdrawal, and nonuse directly addresses that temporal relationship.',
			'D' => 'Independent mood episodes and family history are relevant differential information, but this option relies heavily on historical factors instead of first establishing the present use/nonuse chronology.',
		),
	),
	'CTA-LMFT-CA-FB-092' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-LE6-012-R1',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'Client preference, privacy limits, and urgent-routing instructions are relevant, but this pathway still permits clinical questions through social-media direct messaging before the therapist has adequately determined whether that platform is appropriate for clinical communication.',
			'B' => 'Client initiation does not eliminate the therapist\'s responsibility for the communication channel, and documenting exchanges does not by itself make the platform appropriate.',
			'C' => 'Best answer. The therapist should evaluate privacy, security, response expectations, boundaries, and record implications and then define which channel is appropriate for clinical communication and what role social-media messaging will have.',
			'D' => 'A practice can decide not to use social-media messaging, but an automatic ban is not the only defensible response. The controlling task is responsible management of the communication method.',
		),
	),
	'CTA-LMFT-CA-FB-093' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-LE6-010-R1',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. Representing a certification that the therapist does not hold is a qualification misrepresentation. The therapist should correct the public representation and ensure the client is making treatment decisions based on accurate qualifications.',
			'B' => 'Applying for the credential later does not make the current representation accurate. The misrepresentation should not remain public while the therapist seeks the qualification.',
			'C' => 'Changing the language prospectively is necessary, but the client specifically relied on the false credential. The therapist should directly correct that misunderstanding rather than only describing workshop experience.',
			'D' => 'This thoroughly corrects the public advertising problem, but it does not directly correct the known new client\'s understanding of the therapist\'s actual qualifications after the client expressly relied on the false credential.',
		),
	),
	'CTA-LMFT-CA-FB-094' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-CP-018-R4',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'Warning signs, crisis contacts, referrals, and documentation are useful, but this pathway leaves the client principally responsible for securing continuing care despite known vulnerability and an externally imposed ending.',
			'B' => 'The recent crisis has stabilized, so emergency disposition is not indicated. However, ongoing treatment needs and relapse vulnerability make a purely administrative ending insufficient. A time-limited bridge, relapse and safety review, and active transfer coordination provide an appropriate transition before coverage ends.',
			'C' => 'Seeking authorization may be appropriate, but waiting for the payer’s decision before beginning transfer planning risks a gap if authorization is denied or delayed. Both processes can proceed concurrently.',
			'D' => 'Urgent psychiatric reassessment is not supported when the crisis is stable and no acute danger exists. Requiring relapse risk to resolve fully before termination is also unrealistic and may produce indefinite care.',
		),
	),
	'CTA-LMFT-CA-FB-095' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-TX5E-010-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Moment-to-moment reflection is compatible with a client-centered stance, but directing attention toward several named internal processes adds more therapist structure than is necessary here.',
			'B' => 'Empathic reassurance may be caring, but telling the client how to understand the tears risks replacing the client’s own experience with the therapist’s evaluation.',
			'C' => 'Best answer. Genuine presence, accurate reflection, and allowing the emotion to unfold without pressure are most consistent with a client-centered response to shame and loneliness.',
			'D' => 'Following the client’s preference supports autonomy, but moving quickly into selecting a therapist response can shift attention away from the client’s immediate emotional experience.',
		),
	),
	'CTA-LMFT-CA-FB-096' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-CR-008',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'A direct boundary-setting conversation may increase exposure or retaliation when technology is already being used to monitor and control the client.',
			'B' => 'Account security is useful, but password changes and follow-up alone do not address hidden tracking, physical location exposure, retaliation risk, or the broader coercive pattern.',
			'C' => 'Private safety assessment, technology-aware planning, and specialized abuse resources directly address both digital and physical dimensions of the coercive control.',
			'D' => 'Mediated communication is not an appropriate default when technology is being used to monitor, locate, threaten, and control the client.',
		),
	),
	'CTA-LMFT-CA-FB-097' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-CE-001',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Beginning with the child is plausible because the referral concerns the child\'s behavior, but it presumes that the identified symptom-holder should be the initial unit.',
			'B' => 'The child\'s symptoms occur within visibly significant caregiver interaction. Joint initial assessment provides information about both the child\'s presentation and the relational system before the therapist commits to an individual, parent-focused, or family treatment unit.',
			'C' => 'Caregiver conflict may be important, but beginning with parents alone makes the opposite premature assumption—that parenting dynamics are the principal treatment target.',
			'D' => 'Separate interviews can produce useful perspectives, but the vignette specifically provides meaningful live interactional data that would be lost if joint assessment were deferred.',
		),
	),
	'CTA-LMFT-CA-FB-098' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-CE-028',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The client reports the same withdrawal response across several close relationships. Comparing what precedes withdrawal, how closeness is interpreted, and what follows the distancing directly evaluates whether a recurring interpersonal pattern exists.',
			'B' => 'gives the current partner’s behavior disproportionate explanatory weight.',
			'C' => 'may eventually illuminate formative influences but assumes earlier relationships are the primary explanation before the present pattern is clarified.',
			'D' => 'prematurely reframes the repeated behavior as evidence of an individual symptom or trait pattern.',
		),
	),
	'CTA-LMFT-CA-FB-099' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-DI-016-R1',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Social anxiety emerged later after peer rejection and cannot explain the early-development social-communication and restricted/repetitive pattern.',
			'B' => 'The repaired stem establishes all three social-communication areas—reciprocity, nonverbal communication, and relationship development—plus restricted interests and rigid routines, with onset in early childhood and occurrence across settings. CDC\'s DSM-based criteria require deficits in all three social-communication domains plus at least two restricted/repetitive behavior categories, developmental onset, and clinically significant impairment.',
			'C' => 'ADHD does not account for the complete developmental social-communication pattern and restricted interests/routines.',
			'D' => 'A personality-disorder formulation does not adequately explain symptoms clearly present from early childhood and meeting the neurodevelopmental pattern.',
		),
	),
	'CTA-LMFT-CA-FB-100' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-DI-015',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Major depressive disorder would be more strongly supported by a syndrome occurring independently of the alcohol exposure.',
			'B' => 'Persistent depressive disorder requires a chronic depressive course rather than repeated substance-linked episodes.',
			'C' => 'Adjustment disorder does not explain the recurring intoxication/withdrawal-linked symptom pattern.',
			'D' => 'The depressive syndrome reliably appears during heavy alcohol use or withdrawal and resolves during sustained abstinence, with no independent depressive episode before the substance pattern or during prolonged nonuse. That chronology makes a substance-induced depressive formulation the best fit rather than an independent depressive disorder. DSM-5-TR remains the current diagnostic standard and includes substance/medication-induced diagnostic categories.',
		),
	),
);
