<?php
/**
 * ADMIN ONLY — LMFT California Clinical Form A answer key items 51–75 (PROMPT 15).
 * Secured answer + rationale mapping. Never exposed to learners.
 *
 * @package CTA_LMS
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'CTA-LMFT-CA-FA-051' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-DI-001',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The client currently meets the pattern for a major depressive episode and has a distinct prior period of elevated mood, decreased need for sleep, increased activity/talkativeness, impulsive spending, and observable change from baseline without the marked impairment, psychosis, or hospitalization characteristic of mania. That combination supports bipolar II.',
			'B' => 'Major depressive disorder does not account for the established hypomanic episode.',
			'C' => 'ADHD is developmentally persistent rather than characterized by a discrete five-day elevation from baseline.',
			'D' => 'Cyclothymic disorder involves chronic subthreshold mood fluctuation rather than established major depressive and hypomanic episodes.',
		),
	),
	'CTA-LMFT-CA-FA-052' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-TX5D-005-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. The father is pressing for immediate closeness while the daughter withdraws. Following her approach and withdrawal cues allows reunification to proceed at a developmentally tolerable pace while coaching the father toward lower-pressure bids.',
			'B' => 'An age-appropriate explanation of incarceration may eventually be useful, but the immediate treatment problem is pressure for closeness during visits, not lack of information.',
			'C' => 'Enjoyable activities can support familiarity, but increasing contact does not address the father’s tendency to push past the daughter’s relational cues.',
			'D' => 'Father-only guilt work may be valuable, but the central difficulty is occurring in the father-daughter interaction and requires paced dyadic intervention.',
		),
	),
	'CTA-LMFT-CA-FA-053' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-DI-016-R1',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Trauma may have temporarily worsened concentration, but the attentional syndrome was well documented long before the traumatic event.',
			'B' => 'Anxiety can impair concentration but does not explain the childhood-onset, persistent cross-setting pattern.',
			'C' => 'A specific learning disorder would be organized around persistent difficulty acquiring academic skills rather than this broad pattern of inattention and executive dysfunction.',
			'D' => 'The final stem establishes multiple inattentive symptoms, childhood onset before age 12, occurrence across home and school and later work/home settings, and current impairment. CDC\'s current adult ADHD guidance emphasizes childhood onset, and DSM-based diagnostic guidance also requires multiple settings and functional interference.',
		),
	),
	'CTA-LMFT-CA-FA-054' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-CE-017',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Individual mood and stress symptoms could contribute, but starting there would shift the assessment away from a clearly identified systemic transition.',
			'B' => 'Longstanding relationship patterns may become relevant, but the vignette specifically notes that substantial difficulties were not reported before parenthood.',
			'C' => 'Infant demands and practical strain are highly plausible contributors, but this option represents only part of the broader developmental transition.',
			'D' => 'The difficulties emerged after entry into parenthood and involve roles, expectations, support, intimacy, and caregiving. Evaluating those changes directly addresses the family life-cycle transition described.',
		),
	),
	'CTA-LMFT-CA-FA-055' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-CE-008',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Orientation, attention, and memory assess cognition but do not most directly characterize the disorganized flow of thought described.',
			'B' => 'Unusual beliefs and perceptual experiences concern thought content and perception. The vignette primarily signals a problem with thought process.',
			'C' => 'Abrupt topic shifts and failure to return consistently to the original question concern thought organization and goal direction. Assessing coherence, associations, and maintenance of goal direction directly evaluates the observed finding.',
			'D' => 'Mood and affect are separate MSE domains and do not most directly explain the observed topic shifting.',
		),
	),
	'CTA-LMFT-CA-FA-056' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-LE6-014',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Exporting remaining records and documenting the migration are useful, but the option does not clearly establish that required record integrity and the new system\'s protections have been verified before the old system is closed.',
			'B' => 'Maintaining an old-vendor archive may be part of a secure transition, but relying on the old vendor does not resolve whether the new system preserves the complete required record and integrity information.',
			'C' => 'A read-only export may protect availability, but it does not necessarily preserve the electronic integrity and change-history protections that prompted the migration concern in the stem.',
			'D' => 'Best answer. The therapist should complete and document the migration, preserve required record integrity and confidentiality protections, and deactivate the old system only after the new system has been verified.',
		),
	),
	'CTA-LMFT-CA-FA-057' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-CP-014',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Boundaries, subsystem leadership, and alliances are structural-family concepts.',
			'B' => 'The pursue–withdraw pattern is organized by underlying fears of rejection and failure. B identifies the negative interactional cycle, accesses the attachment-related emotional experience beneath the partners’ positions, and shapes more responsive bonding exchanges. EFT is attachment- and emotion-based and explicitly focuses on transforming negative relational cycles and increasing accessibility and responsiveness.',
			'C' => 'Identifying and testing conflict-related thoughts and practicing balanced communication is CBT-oriented planning.',
			'D' => 'Externalizing the cycle and constructing an alternative relationship story is narrative planning.',
		),
	),
	'CTA-LMFT-CA-FA-058' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-CR-008',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Recommending temporary separation may be appropriate in some circumstances, but directing that choice can disregard the client\'s autonomy and may not fit the client\'s immediate safety needs.',
			'B' => 'The pattern of financial restriction, isolation, monitoring, threats involving the children, and blocked exits indicates escalating coercive control. Private danger assessment and practical safety planning that fit the client\'s priorities directly address the crisis.',
			'C' => 'Defining conditions for conjoint work is premature while coercive control and current danger remain unresolved.',
			'D' => 'Trusted supports and close follow-up are useful, but they are insufficient without first assessing the controlling behavior, escalation, and present danger.',
		),
	),
	'CTA-LMFT-CA-FA-059' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-CE-032-R1',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'concentrates on the coparenting subsystem.',
			'B' => 'emphasizes the children’s adjustment.',
			'C' => 'focuses primarily on the grandparents’ role. Each could be clinically appropriate, but the vignette signals reorganization across the broader family system rather than one subsystem alone.',
			'D' => 'Divorce has reorganized several parts of the primary support system simultaneously. Evaluating caregiving roles, household membership, extended-family involvement, alliances, decision-making, and support directly captures that systemwide restructuring.',
		),
	),
	'CTA-LMFT-CA-FA-060' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-LE6-004',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Continuing conjoint therapy while compartmentalizing material information that directly affects the treatment goals can make the conjoint work clinically untenable and conflicts with the treatment policy described in the stem.',
			'B' => 'The treatment policy does not independently authorize the therapist to disclose one partner\'s confidential information to the other. California confidentiality law requires authorization or another legal basis for disclosure.',
			'C' => 'Pausing or ending conjoint work can become necessary if the secrecy makes treatment untenable, but automatic termination solely because the partner will not authorize therapist disclosure skips the clinically appropriate effort to work with the partner toward disclosure.',
			'D' => 'Best answer. The therapist can return to the agreed treatment expectations, assess safety, help the disclosing partner plan the partner\'s own disclosure, and reassess whether conjoint treatment can continue if the impasse remains—without treating the policy as independent legal authority for therapist disclosure.',
		),
	),
	'CTA-LMFT-CA-FA-061' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-CR-010-R1',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'Four days after the event, the client is distressed but safe and able to meet basic needs. Early crisis care should emphasize stabilization, practical coping, support, and restoration of manageable functioning rather than intensive trauma processing or emergency-level care.',
			'B' => 'Grounding, coping, and close follow-up are useful, but the response leaves the practical return-to-function problem less directly addressed than the keyed pathway.',
			'C' => 'Readiness and trusted support matter, but moving toward narrative work this early gives event processing more priority than the immediate stabilization, practical support, and restoration of functioning indicated four days after the violence.',
			'D' => 'Same-day crisis consultation is more intensive than the current risk and functioning information supports.',
		),
	),
	'CTA-LMFT-CA-FA-062' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-CE-001-R2',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'These are appropriate individual-assessment domains, but the option narrows the evaluation toward the identified client\'s panic before adequately evaluating the relational component already present.',
			'B' => 'The therapist has evidence that panic symptoms and relationship processes may both be clinically relevant, but not enough information to decide that the treatment unit should automatically be individual or conjoint. Clarifying both people\'s perspectives, relational effects, and goals provides the information necessary to select the initial treatment unit.',
			'C' => 'It appropriately examines the couple process but similarly gives relational maintenance mechanisms priority before the therapist has determined whether conjoint treatment should be the initial unit.',
			'D' => 'Confidentiality and prior-treatment information may matter, and separate interviews could eventually be useful, but those procedures do not first answer the central question of how the presenting problem is organized across the client and relationship.',
		),
	),
	'CTA-LMFT-CA-FA-063' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-LE6-010',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Consultation does not itself make the therapist competent to perform a specialized protocol for which the therapist has not been trained. Beginning first and learning during treatment places competence after service delivery.',
			'B' => 'Best answer. California distinguishes legal scope from competence established through education, training, or experience. The therapist should establish competence before providing the specialized protocol and maintain an appropriate interim plan.',
			'C' => 'Client consent to a training gap does not substitute for professional competence. Consultation and outcome monitoring are safeguards, not replacements for adequate preparation.',
			'D' => 'Familiar treatment may be appropriate temporarily, but simply continuing it while monitoring progress does not resolve the identified competence gap when the specialized service is clinically relevant and training or consultation is available.',
		),
	),
	'CTA-LMFT-CA-FA-064' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-TX5E-009-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Staying with bodily experience is Gestalt-consistent and may deepen awareness, but the client has already noticed the tension. A more active experiment can now make the embodied perfectionistic pattern more vivid and available for exploration.',
			'B' => 'Two-chair work is a legitimate Gestalt experiment, but the stem presents a live bodily process rather than a clearly differentiated internal dialogue that requires chair work.',
			'C' => 'Sentence completion can increase awareness of unfinished meanings and fears, but it does not use the immediately observable jaw and posture pattern as directly as an embodied experiment.',
			'D' => 'Best answer. Deliberately exaggerating the posture and statement creates a present-moment Gestalt experiment that heightens awareness of how the perfectionistic demand is organized in the client’s body and experience.',
		),
	),
	'CTA-LMFT-CA-FA-065' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-CR-005-R1',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'Same-day psychiatric evaluation and supervised transition are more restrictive than the established acute-risk state requires. Updating supports does not change the fact that the client retains the ability to maintain safety with structured outpatient management.',
			'B' => 'The client has clinically important death thoughts but retains protective factors and independent safety capacity. Structured outpatient safety planning, means-safety review, closer follow-up, and repeated reassessment appropriately intensify care without unnecessary emergency transfer.',
			'C' => 'Leaving treatment unchanged underresponds to current suicidal ideation; the presence of passive death wishes warrants an active risk-management response even without high acute risk.',
			'D' => 'Continuous informal monitoring shifts the safety burden to a support person and unnecessarily postpones the client\'s own structured safety planning.',
		),
	),
	'CTA-LMFT-CA-FA-066' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-CP-015',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'This plan creates a predetermined three-month extension and new preventive goals despite the absence of a clear continuing treatment need. Monitoring relapse is appropriate, but it does not by itself justify continued weekly therapy.',
			'B' => 'Monthly maintenance is less intensive than weekly treatment, but the endpoint remains open until the client personally requests termination. That structure may preserve the same reassurance dependence that needs to be addressed.',
			'C' => 'The client’s symptoms have remained remitted, functioning has returned, treatment skills are being used independently, and no additional goals have been identified. Those facts support readiness for termination. A planned step-down also allows the therapist to explore the client’s reliance on weekly reassurance and verify that gains remain stable as contact becomes less frequent.',
			'D' => 'This option similarly creates a fixed six-month extension and makes reduction of termination-related distress a condition for reconsidering the ending. A client does not need to feel entirely comfortable with termination before treatment can conclude appropriately.',
		),
	),
	'CTA-LMFT-CA-FA-067' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-CP-005-R2',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Broad goals are unlikely to be completed within six visits, and waiting until the final appointment to assess continuing-care needs creates an avoidable risk of disrupted treatment.',
			'B' => 'The client can benefit from focused work during the authorized visits even though all needs will not be resolved. The therapist should clarify the limit from the beginning, establish achievable client-centered goals, and address longer-term access before the final session.',
			'C' => 'The employer’s concerns may provide referral context but should not automatically become the client’s primary treatment goals. Reserving continuity planning for the final appointment is also too late.',
			'D' => 'Outside referral may ultimately be necessary, but limiting the six visits to stabilization and transfer underuses treatment that could provide meaningful focused benefit now.',
		),
	),
	'CTA-LMFT-CA-FA-068' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-CR-001-R3',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'The client has severe alcohol-withdrawal features with disorientation, hallucinations, marked autonomic activation, and tremor. The immediate priority is supervised emergency medical transfer rather than a lower-intensity or delayed disposition pathway.',
			'B' => 'Specialty withdrawal treatment may ultimately be appropriate, but waiting for acceptance and non-emergency transfer is less direct than emergency medical transport when complicated withdrawal is already present.',
			'C' => 'A psychiatric destination gives primary psychosis too much priority and risks delaying the medical management required by a dangerous withdrawal syndrome.',
			'D' => 'Medical consultation can be useful in less clearly unstable presentations, but obtaining consultation before disposition delays transfer when the medical-risk level is already established.',
		),
	),
	'CTA-LMFT-CA-FA-069' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-DI-012',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Bipolar II requires distinct hypomanic episodes. The mood shifts here are brief, reactive to interpersonal events, and embedded in a persistent relational/personality pattern.',
			'B' => 'The presentation is longstanding and cross-situational and includes unstable relationships, unstable self-image, abandonment sensitivity, affective instability, chronic emptiness, and impulsivity. APA characterizes personality disorders as long-term patterns and describes BPD specifically in terms of unstable relationships, self-image, intense affect, abandonment fears, emptiness, and impulsive behavior.',
			'C' => 'Trauma-related pathology could coexist, but the stem does not establish a trauma syndrome that better explains the pervasive personality pattern.',
			'D' => 'Dependent personality disorder is more strongly organized around difficulty making decisions, needing others to assume responsibility, and fear of functioning independently; it does not adequately explain the instability described here.',
		),
	),
	'CTA-LMFT-CA-FA-070' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-TX5A-003',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Assertive responses and online-safety choices may reduce ongoing peer stress, but they do not directly address the client’s growing avoidance of in-person social situations and fear of negative evaluation.',
			'B' => 'Reducing comparison-heavy social-media use may help, but avoidance of real-world peer contact is already maintaining the client’s social anxiety and needs direct behavioral treatment.',
			'C' => 'Best answer. The intervention integrates the relevant social-pressure and social-media context with graded exposure to the avoided interpersonal situations, directly targeting the cycle that is maintaining social anxiety and isolation.',
			'D' => 'Processing rejection and strengthening self-compassion can be useful, but postponing direct practice risks reinforcing avoidance when the client already wants more connection and can engage in gradual exposure.',
		),
	),
	'CTA-LMFT-CA-FA-071' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-CE-013',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The client explicitly reports that prior treatment conflicted with important family or cultural beliefs. The therapist should understand what felt incompatible and how that experience now shapes expectations about treatment.',
			'B' => 'Current values and desired adaptations are useful to explore, but this option moves toward modifying treatment before fully understanding the previous experience.',
			'C' => 'Reviewing the entire prior therapy history can be useful, but it is less focused on the specific cultural conflict the client identified as influencing current hesitation.',
			'D' => 'Family attitudes and prior disclosure may have affected participation, but the vignette identifies incompatibility within treatment itself as the central concern.',
		),
	),
	'CTA-LMFT-CA-FA-072' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-CE-022',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Caregiving burden is substantial but represents only one of several concurrent stressors.',
			'B' => 'Relationship loss may account for some distress, but making it the dominant frame would prematurely isolate one stressor.',
			'C' => 'Relocation can disrupt support and functioning, but it likewise cannot be assumed to be the principal factor.',
			'D' => 'The client is experiencing several major life changes simultaneously. Mapping caregiving, relocation, and relationship loss against changes in symptoms, support, and functioning evaluates their cumulative and interacting psychosocial effects.',
		),
	),
	'CTA-LMFT-CA-FA-073' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-TX5C-007-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Correct. The client’s rigid self-appraisal and refusal of help are maintaining caregiver burden and self-neglect. Reframing the belief while adding respite directly targets both appraisal and coping.',
			'B' => 'A schedule can distribute tasks, but framing success around completing planned care can reinforce the client’s performance-based caregiving standard rather than modify it.',
			'C' => 'Anticipatory grief is relevant, but grief processing alone does not address the immediate maladaptive appraisal, refusal of help, and self-care erosion.',
			'D' => 'Restoring sleep and medical care is important, but keeping primary responsibility unchanged leaves the burden and refusal of assistance largely intact.',
		),
	),
	'CTA-LMFT-CA-FA-074' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-LE6-013',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The therapist may offer to review records with the client, but access should not be conditioned on completing a therapeutic review merely because accurate notes may be upsetting.',
			'B' => 'A summary can sometimes be useful, but it does not automatically replace a client\'s request for the underlying record when the statutory access process applies.',
			'C' => 'Best answer. The stem expressly states that the therapist does not identify the substantial-risk condition required for the special mental-health-record restriction procedure. Discomfort alone is not a sufficient basis to withhold or condition access.',
			'D' => 'The substantial-risk process can involve another licensed professional in specified circumstances, but the stem states that the therapist has not identified the required level of risk. A second review should not be invented as a prerequisite.',
		),
	),
	'CTA-LMFT-CA-FA-075' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-TX5F-003-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Neuropsychology may clarify cognitive contributors after a stroke, but the treatment barrier described is persistent expressive-language difficulty during couple communication rather than a primarily cognitive problem.',
			'B' => 'Occupational therapy can improve functional routines and adaptive participation after stroke, but it is not the most direct service for aphasia-related word retrieval and supported conversation.',
			'C' => 'Best answer. Speech-language pathology directly addresses aphasia and can teach language-rehabilitation and supported-conversation strategies that help the client communicate more effectively with the partner during treatment.',
			'D' => 'Rehabilitation psychology may help with adjustment, frustration, and disability-related coping, but it would not directly remediate the expressive-language barrier interfering with couple-session participation.',
		),
	),
);
