<?php
/**
 * ADMIN ONLY — LMFT California Clinical Form B answer key items 26–50 (PROMPT 20).
 * Secured answer + rationale mapping. Never exposed to learners.
 *
 * @package CTA_LMS
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'CTA-LMFT-CA-FB-026' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-DI-009-R2',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'The hallucination and delusional belief occur only during severe major depressive episodes and resolve fully when the mood episodes remit, which supports major depressive disorder with psychotic features.',
			'B' => 'Schizoaffective disorder requires a different temporal relationship between psychosis and mood disturbance; the stem explicitly states there has never been psychosis outside a mood episode.',
			'C' => 'The psychosis is episodic and completely mood-bound rather than part of a persistent primary schizophrenia syndrome.',
			'D' => 'The psychotic symptoms are consistently embedded within major depressive episodes rather than occurring as independent brief psychotic episodes.',
		),
	),
	'CTA-LMFT-CA-FB-027' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-CE-035-R1',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The client reports recurrent aggression associated with alcohol use but denies current intent or weapon access. The therapist should evaluate the aggression pattern, relationship to substance use, prior episodes and consequences, triggers, and whether present circumstances indicate a change in danger.',
			'B' => 'This thoroughly evaluates the alcohol-use pattern and whether aggression occurs only during intoxication, but the controlling task is broader evaluation of aggression rather than substance use alone.',
			'C' => 'Impulsivity, anger regulation, and behavior across settings are useful variables but do not adequately incorporate the role of alcohol or clarify current danger.',
			'D' => 'Legal and relational consequences and treatment history provide helpful context, but they are less direct than evaluating the aggressive behavior itself, its relationship to alcohol, and its present risk relevance.',
		),
	),
	'CTA-LMFT-CA-FB-028' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-CE-020-R1',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Individual symptoms and prior family conflict are useful information, but this option shifts the emphasis toward whether psychological or relational problems existed independently of the financial change.',
			'B' => 'Reduced income has affected basic-needs access, childcare, work demands, and family conflict. Assessing those socioeconomic changes together with support and functioning directly evaluates the stressor described.',
			'C' => 'Employment history and budgeting may become relevant, but the choice moves toward occupational and financial problem-solving rather than evaluating the current socioeconomic impact.',
			'D' => 'Communication and division of labor matter, but this option risks reversing the apparent direction of the problem by asking whether relationship dysfunction is driving financial stress.',
		),
	),
	'CTA-LMFT-CA-FB-029' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-TX5C-006',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Sleep and exercise support recovery, but the adult children are used only for household help, leaving the client’s continuous direct-care burden largely unchanged.',
			'B' => 'A coping plan may reduce distress, but it does not make use of the available family support or restore a meaningful activity that the client has already lost.',
			'C' => 'Delegating household tasks can help, but keeping the client in primary direct-care responsibility does not create true respite from the caregiving role.',
			'D' => 'Best answer. The pattern indicates caregiver depletion in the context of available support. A predictable respite shift directly reduces burden and protects recovery activity rather than relying only on coping around the same workload.',
		),
	),
	'CTA-LMFT-CA-FB-030' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-CP-009',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Each partner asks the therapist to determine which account is objectively correct. A instead treats both accounts as locally meaningful, uses collaborative inquiry, and co-constructs goals without privileging one perspective. Collaborative therapy is a postmodern, social-constructionist approach that emphasizes language, multiple contextual meanings, collaboration, and a less hierarchical stance toward knowledge.',
			'B' => 'Externalizing conflict, identifying unique outcomes, and developing an alternative relationship story is specifically narrative.',
			'C' => 'Preferred futures, exceptions, competencies, and small observable changes are specifically solution-focused.',
			'D' => 'A therapist-generated systemic formulation may be clinically useful, but it reestablishes the therapist as the primary authority whose interpretation organizes treatment.',
		),
	),
	'CTA-LMFT-CA-FB-031' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-CR-006-R2',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'Emergency protective action overstates the established acuity because the client has no near-term plan, preparation, acquired means, recent violence, or unwillingness to avoid the property.',
			'B' => 'The destructive ideation warrants active risk assessment and a concrete avoidance/safety plan, but the absence of preparation or near-term intent supports close outpatient management rather than emergency escalation.',
			'C' => 'Psychiatric consultation and support monitoring may become appropriate, but the current facts do not establish near-term planning or preparation. This pathway is more intensive than needed when active outpatient danger-management can address the ideation while monitoring for escalation.',
			'D' => 'Routine follow-up with coping work underresponds to expressed property-damage ideation even though imminence is not established. Active safety planning and close monitoring are indicated now rather than waiting for the threat to become more specific.',
		),
	),
	'CTA-LMFT-CA-FB-032' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-DI-004',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Panic symptoms occur only within scrutiny situations rather than unexpectedly.',
			'B' => 'The fear is negative evaluation, not difficulty escaping or obtaining help.',
			'C' => 'The anxiety consistently arises in situations involving possible scrutiny or negative evaluation—meetings, social events, eating around unfamiliar people, and dating—and avoidance is organized around that fear. APA describes social anxiety disorder in terms of intense fear of being judged, embarrassed, or rejected in social or performance situations.',
			'D' => 'The worry is situation-specific rather than broadly distributed across daily life.',
		),
	),
	'CTA-LMFT-CA-FB-033' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-CR-009-R2',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'The client is acutely distressed after learning of violent harm to a family member and is struggling with work, travel, communication, and family responsibilities. Immediate practical assistance and support mobilization directly address the current crisis without overpathologizing it.',
			'B' => 'Coping support, trusted supports, and work planning are useful, but this pathway gives travel readiness and coping more emphasis than the immediate family-logistics disruption that is organizing the crisis after learning of the violent event.',
			'C' => 'Grounding and organizing information can help, but this option underemphasizes the immediate logistical and family-functioning demands driving the crisis.',
			'D' => 'An urgent crisis consultation is more intensive than the established risk state requires because no imminent psychiatric danger is present.',
		),
	),
	'CTA-LMFT-CA-FB-034' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-CE-002',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Clarifying limits and pace respects autonomy, but focusing first on making therapy merely tolerable sets a lower and less collaborative engagement target than exploring the person\'s own perspective and possible usefulness.',
			'B' => 'Shared goals may eventually be important, but comparing motivation and establishing a common target is premature before the skeptical partner feels meaningfully included.',
			'C' => 'Exploring prior failed efforts is relevant, but it presumes that skepticism is based primarily on previous attempts rather than first understanding how the partner presently views the problem.',
			'D' => 'The skeptical partner does not need to be persuaded before participating meaningfully. Acknowledging the skepticism, eliciting that person\'s own view of the relationship concern, and asking what might make the meeting useful directly supports engagement.',
		),
	),
	'CTA-LMFT-CA-FB-035' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-CE-009',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Pain severity and activity limitation matter, but this option does not adequately evaluate the relational and household changes already described.',
			'B' => 'Mood and anxiety may contribute to the presentation, but beginning there risks psychologizing the effects of the medical condition.',
			'C' => 'Partner responses and family changes are relevant but represent only the relational side of a presentation that also includes physical and individual functioning.',
			'D' => 'The chronic pain condition has changed multiple aspects of functioning—sleep, activity, intimacy, and household roles. Evaluating those domains together addresses the physical condition\'s broader individual and family effects.',
		),
	),
	'CTA-LMFT-CA-FB-036' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-DI-001-R1',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Bipolar II requires full hypomanic and major depressive episodes, which the stem explicitly does not establish.',
			'B' => 'The client has more than three years of alternating hypomanic-type and depressive symptoms that never meet full episode criteria, are present at least half the time, and do not disappear for prolonged intervals. That chronic subthreshold pattern supports cyclothymia rather than bipolar II.',
			'C' => 'Persistent depressive disorder does not account for the recurring hypomanic-type symptom periods.',
			'D' => 'An other-specified bipolar formulation is less appropriate when the specific cyclothymic pattern is established.',
		),
	),
	'CTA-LMFT-CA-FB-037' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-TX5E-005-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Externalizing a problem is compatible with postmodern practice, but the stem most clearly highlights a socially produced standard whose authority and meaning can be examined collaboratively.',
			'B' => 'Exception-finding can open preferred possibilities, but it does not as directly investigate the social discourse shaping the client’s belief about what a good mother must be.',
			'C' => 'Best answer. Postmodern treatment can deconstruct dominant discourse, examine whose knowledge is privileged, and collaborate with the client to construct local meanings that fit lived relationships and values.',
			'D' => 'Exploring multiple community meanings is useful and resists a single universal standard, but it is less direct than examining the power of the specific good-mother discourse and constructing an alternative local meaning.',
		),
	),
	'CTA-LMFT-CA-FB-038' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-LE6-009-R2',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'Workflow protections and repeated review may improve organization, but retaining the same workload fails to address the practice conditions already producing repeated continuity and recordkeeping failures.',
			'B' => 'Notifying clients and prioritizing higher-risk documentation may reduce some immediate strain, but it leaves the underlying overbooking and performance failures substantially intact.',
			'C' => 'Best answer. The therapist has identified a practice-capacity problem that is already affecting continuity and recordkeeping. Reducing capacity to a manageable level and correcting outstanding work directly protects clients while performance stabilizes.',
			'D' => 'Administrative support and chart audits may improve workflow, but retaining the existing caseload does not correct the workload conditions already producing repeated continuity and recordkeeping failures.',
		),
	),
	'CTA-LMFT-CA-FB-039' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-TX5D-006-R1',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Comparing racialized workplace stress with sexuality-related family stress acknowledges multiple identities, but it treats them as parallel rather than examining how identities and roles interact within each context.',
			'B' => 'Best answer. Intersectional treatment examines how race, gender, sexuality, and role demands combine across settings and then links that analysis to coping and boundary decisions that fit the client’s priorities.',
			'C' => 'Identifying the most salient identity in each setting can be useful, but it risks separating identities that the client experiences simultaneously.',
			'D' => 'Validating discrimination and creating setting-specific strategies are appropriate, but separating the contexts does not directly examine the interaction among the client’s identities and role demands.',
		),
	),
	'CTA-LMFT-CA-FB-040' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-LE6-013-R1',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Not everything physically stored in a chart is necessarily part of the requesting patient\'s record for access purposes. California law excludes certain confidential collateral information provided by someone other than the patient or another health care provider.',
			'B' => 'Best answer. HSC §123105(d) excludes qualifying confidential third-party collateral information from the requesting patient\'s patient records and permits that material to be removed before inspection or copying.',
			'C' => 'The statute does not make release depend on later permission from the collateral source. The therapist must determine whether the material falls within the statutory exclusion.',
			'D' => 'A treatment summary is not automatically a substitute for a requested record. The therapist can remove qualifying collateral material and provide the remainder under the normal access process.',
		),
	),
	'CTA-LMFT-CA-FB-041' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-CP-011',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Testing criticism-related appraisals and constructing balanced beliefs is CBT.',
			'B' => 'Target hierarchies, behavioral chains, and regulation and interpersonal skills are DBT.',
			'C' => 'The client’s self-worth collapses after minor criticism and depends heavily on recognition and reassurance from others. C targets unstable self-cohesion through empathic attunement, examination of disruptions in needed interpersonal affirmation, and development of a more cohesive and regulated self-experience. Research on Kohut’s self psychology links mirroring, idealization, and twinship selfobject needs with self-cohesion, affect regulation, and interpersonal functioning.',
			'D' => 'This is the strongest distractor. Exploring idealized and devalued representations and integrating conflicting views is object-relations planning. It would be stronger if the central formulation emphasized splitting and integration of internal representations. The stem’s dominant feature is collapse of self-worth following failures of recognition, making self-cohesion and selfobject regulation the more direct plan.',
		),
	),
	'CTA-LMFT-CA-FB-042' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-CR-010',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Guilt-focused coping may be clinically useful, but it is too narrow for a crisis involving bias-motivated violence, identity-related threat, community disconnection, fear, and functional disruption.',
			'B' => 'Graded reentry can be helpful later, but emphasizing transportation exposure now may disregard readiness and the client\'s current safety and identity-related concerns.',
			'C' => 'The severity and discriminatory nature of the assault do not by themselves establish imminent danger or inability to function safely that would justify urgent psychiatric disposition.',
			'D' => 'The crisis includes fear, guilt, disrupted public functioning, community disconnection, and identity-related threat. Identity-aware trauma stabilization and culturally relevant community support address that full context without forcing premature exposure.',
		),
	),
	'CTA-LMFT-CA-FB-043' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-CE-039',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Psychiatric evaluation could eventually be useful, but it does not directly address the unexplained physical changes accompanying the psychological symptoms.',
			'B' => 'New anxiety and concentration changes occur alongside unexplained weight change, tremulousness, and episodes of rapid heartbeat that have not been medically evaluated. Medical evaluation is the additional assessment most directly indicated by the unresolved physical findings.',
			'C' => 'A concentration complaint alone does not make specialized neurocognitive testing the most appropriate referral when new systemic physical symptoms are also present.',
			'D' => 'Psychological and medical assessment do not need to occur in a rigid sequence. There is no clinical reason to exhaust psychosocial explanations before obtaining indicated medical evaluation.',
		),
	),
	'CTA-LMFT-CA-FB-044' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-TX5C-002',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Accountability can support practice, but simply repeating the same sequence does not address the couple’s specific report that the plan becomes too complex during escalation.',
			'B' => 'Journaling may reveal triggers, but the couple already identifies a usability problem and still wants a concrete interruption strategy; replacing the plan delays work on that barrier.',
			'C' => 'Rehearsal can improve fluency, but practicing the same full sequence does not correct the complexity that is interfering with use during real conflict.',
			'D' => 'Best answer. The therapist identifies the point of nonadherence, simplifies the intervention to fit the couple’s actual capacity during conflict, and rehearses the revised plan in a relevant context.',
		),
	),
	'CTA-LMFT-CA-FB-045' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'B-TX5C-003',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. The couple wants reconnection without overwhelming the client. A low-demand shared activity matches current energy while helping both partners interpret withdrawal as a depression-related change rather than relational rejection.',
			'B' => 'Independent behavioral activation can help depression, but beginning only with solitary activity does not directly address the couple’s shared concern about connection and the spouse’s interpretation of withdrawal.',
			'C' => 'A reflective check-in may improve communication, but it asks for verbal processing during the same low-energy periods that are already difficult and does not provide a concrete reconnection activity.',
			'D' => 'Reviewing premorbid relationship patterns can clarify history, but the stem already identifies low energy during a depressive episode as the reason for the current withdrawal.',
		),
	),
	'CTA-LMFT-CA-FB-046' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'B-CE-031',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'risks identifying a child as the source of a systemic problem.',
			'B' => 'focuses primarily on the remarried couple subsystem.',
			'C' => 'narrows the issue to discipline differences. Each may eventually contribute to formulation, but none adequately evaluates the blended-family organization described.',
			'D' => 'Blended-family concerns around loyalty, authority, and household roles require evaluation of prior relationships and losses, household transitions, current authority patterns, and family interactions. This provides the broadest relevant picture of the primary support system without presuming where the problem resides.',
		),
	),
	'CTA-LMFT-CA-FB-047' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-LE6-002-R1',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Participant paperwork and a limited-purpose explanation may be useful, but the option risks making paperwork the controlling step rather than clarifying the spouse\'s exact role and the boundaries of the individual therapy.',
			'B' => 'The spouse can sometimes be included as support, but the role and confidentiality expectations should be clarified before the session begins rather than only as issues arise during the meeting.',
			'C' => 'Best answer. The client remains the individual-therapy client. The therapist should clarify that role, the spouse\'s limited support purpose, and the relevant confidentiality and record expectations before participation.',
			'D' => 'A separate pre-session meeting can create additional expectations and collateral information that are not necessary to accomplish the client\'s stated goal of one supportive session.',
		),
	),
	'CTA-LMFT-CA-FB-048' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'B-CE-029',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'concentrates mainly on the physical component.',
			'B' => 'focuses on anxiety and avoidance.',
			'C' => 'Sexual pain, health changes, anticipatory anxiety, avoidance, partner responses, and relationship distress are occurring together. Clarifying how these variables relate provides a multidimensional evaluation without prematurely deciding whether the difficulty is primarily medical, psychological, or relational.',
			'D' => 'focuses on the relationship response. All are plausible assessment pathways, but each isolates one portion of a presentation that the stem indicates is interacting across domains.',
		),
	),
	'CTA-LMFT-CA-FB-049' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-CR-011-R2',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'Specialized medical-forensic care does not require the therapist to make police reporting the first condition of access, and tying care to reporting can undermine informed choice.',
			'B' => 'Showering or changing clothes can affect particular evidence-collection procedures but does not make specialized medical, advocacy, or forensic care pointless. The therapist should connect the client with qualified services that can explain the remaining options.',
			'C' => 'Documenting questions can support continuity, but detailed event review is not required before connecting the survivor with specialized services that can explain what medical-forensic options remain after showering or changing clothes.',
			'D' => 'Grounding may be helpful, but delaying discussion or referral can unnecessarily reduce access to time-sensitive medical, advocacy, or forensic options.',
		),
	),
	'CTA-LMFT-CA-FB-050' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'B-TX5A-003',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Reducing self-focused anxiety can help social functioning, but the stem identifies specific observable conversational-skill deficits that require direct teaching and practice.',
			'B' => 'Best answer. Behavioral rehearsal, feedback, and planned real-world practice directly target the turn-taking, question-asking, and cue-reading skills that are interfering with relationship formation.',
			'C' => 'Interest-based groups may provide opportunities for connection, but exposure to more conversations without explicit skills training may reproduce the same interaction problems.',
			'D' => 'Cognitive work may reduce negative self-appraisal and reviewing interactions can increase awareness, but the client also needs direct rehearsal and feedback on specific interpersonal behaviors.',
		),
	),
);
