<?php
/**
 * ADMIN ONLY — LMFT California Clinical Form A answer key items 26–50 (PROMPT 14).
 * Secured answer + rationale mapping. Never exposed to learners.
 *
 * @package CTA_LMS
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'CTA-LMFT-CA-FA-026' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-CE-009',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Depressive symptoms are clinically relevant, but this choice treats depression as the explanatory frame before the mood-affect discrepancy itself has been assessed.',
			'B' => 'The important finding is the discrepancy between the client\'s verbal report and observed affect. The therapist should characterize mood, affective range, reactivity, and whether the discrepancy persists across topics before interpreting it.',
			'C' => 'Recent stressors may help contextualize the tearfulness but do not first clarify the observed MSE discrepancy.',
			'D' => 'Suicide assessment may be indicated when supported by additional risk information, but tearfulness and constricted affect alone do not make crisis-risk assessment the controlling operation here.',
		),
	),
	'CTA-LMFT-CA-FA-027' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-CR-011-R1',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'Explaining a forensic examination as an option is appropriate, but strongly steering the client toward it substitutes the therapist\'s preference for informed choice.',
			'B' => 'Police involvement may be one available option, but recommending it as the preferred next step is unnecessarily directive when the client is explicitly asking to understand choices.',
			'C' => 'The therapist should assess immediate safety and medical needs, explain available medical and advocacy options in understandable terms, and support the client\'s informed decisions without coercion or unnecessary direction.',
			'D' => 'Stabilization is important, but delaying discussion of medical-forensic or advocacy options can reduce access to time-sensitive care and information.',
		),
	),
	'CTA-LMFT-CA-FA-028' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-CE-030',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'appropriately evaluates physical contributors but underrepresents relational and developmental meaning.',
			'B' => 'focuses on the couple relationship but underrepresents health and lifespan factors.',
			'C' => 'appropriately addresses lifespan history and expectations but omits important current physical and relational variables.',
			'D' => 'The couple’s intimacy change occurs alongside health changes and differing beliefs about sexuality in later life. Evaluating health, medication, lifespan sexual functioning, expectations, relational dynamics, and meaning captures the multidimensional nature of the concern.',
		),
	),
	'CTA-LMFT-CA-FA-029' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-LE6-002',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. Adding a recurring adult participant can change client/participant roles, treatment purpose, confidentiality expectations, and record implications. Those expectations should be established before substantive participation begins.',
			'B' => 'Reviewing expectations at the first meeting is useful, but this option does not clearly establish the sister\'s client or participant role and informed agreement before deciding whether she belongs in the ongoing treatment structure.',
			'C' => 'A separate individual meeting can create additional privacy and record expectations before the therapist has established how the sister fits within the existing family treatment.',
			'D' => 'Documenting a proposed role is not enough if the therapist begins regular participation and waits several sessions before finalizing the agreement. The role and expectations should be settled first.',
		),
	),
	'CTA-LMFT-CA-FA-030' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-TX5A-008',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Immediate joint authority may increase consistency, but it moves the stepfather too quickly into a full parenting role despite the adolescent’s loyalty conflict and the very new remarriage.',
			'B' => 'Keeping the mother in the primary discipline role while the stepfather builds connection is helpful, but it does not describe how the stepfather’s role can develop as the new family stabilizes.',
			'C' => 'Negotiating household authority can clarify roles, but treating the role primarily as an agreement may move faster than the trust and loyalty process requires.',
			'D' => 'Best answer. Loyalty conflicts are common in stepfamily formation. Protecting existing bonds while allowing the stepfather’s authority to expand gradually addresses both developmental timing and role clarity.',
		),
	),
	'CTA-LMFT-CA-FA-031' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-TX5C-001',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Testing feared social judgment may be useful if social anxiety is primary, but the client explicitly wants help adjusting to illness-related identity and unpredictable physical functioning.',
			'B' => 'Grief and coping work are relevant, but this option does not reconnect the client with a valued social role using practical accommodations.',
			'C' => 'Best answer. The response integrates illness-related identity adjustment with reengagement in a valued activity and uses accommodations for fatigue and balance limitations.',
			'D' => 'Practical pacing and accommodations may improve participation, but they underaddress the client’s stated identity loss and uncertainty about being socially present with a changed body.',
		),
	),
	'CTA-LMFT-CA-FA-032' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-CP-002-R2',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Panic intensity and frequency are relevant, but medication use, sleep, and general distress do not directly measure whether the client is independently commuting or participating fully at work.',
			'B' => 'Work attendance and commute confidence are useful, but confidence and therapist ratings are indirect indicators. The plan does not adequately measure whether the client remains in the feared setting rather than escaping.',
			'C' => 'This is a strong distractor because it measures commuting, avoidance, reassurance, work attendance, and practice completion. It is not best because treatment-assignment completion is not equivalent to the client’s actual symptom change or ability to tolerate the feared transit situation through completion.',
			'D' => 'The stated goals and formulation involve four distinct outcomes: the severity of panic symptoms, independent completion of the commute, the ability to remain in feared transit situations without escaping, and full workplace participation. D measures all four directly.',
		),
	),
	'CTA-LMFT-CA-FA-033' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-CP-017',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'This response validates the client’s grief and preserves predictability, but it treats the timeline as essentially fixed and does not fully use the relational meaning of the client’s abandonment response.',
			'B' => 'A temporary extension may occasionally be justified, but this option makes resumption of termination dependent on abandonment fears substantially decreasing. That can reinforce the idea that treatment may end only when the client no longer experiences difficult feelings about it.',
			'C' => 'Addressing the reaction during closure is appropriate, but offering referral for further relational work may unnecessarily transfer termination material that can still be addressed within the current treatment. The response also emphasizes why treatment is not indicated rather than examining the client’s experience of the ending.',
			'D' => 'The client’s grief and perception of abandonment are clinically meaningful and should be explored within the current therapeutic relationship. D does that while preserving appropriate boundaries and the established goals of treatment. It also allows the timeline to be modified when there is a defined clinical reason rather than merely because the client is distressed by ending.',
		),
	),
	'CTA-LMFT-CA-FA-034' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-CE-006',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Reviewing examples can help clarify what occurred, but trying to determine how the previous therapist actually behaved shifts the focus toward adjudicating the former therapy rather than understanding its effect on this client.',
			'B' => 'Identifying helpful aspects of prior treatment can be useful, but it does not directly address the rupture that the client spontaneously identified as important.',
			'C' => 'The prior experience matters because it may affect present trust, expectations, and participation. C explores the client\'s experience and how that experience may influence the current therapeutic relationship.',
			'D' => 'Explaining how therapists manage competing perspectives may be reassuring, but psychoeducation before fully understanding the client\'s experience risks responding to the concern rather than assessing it.',
		),
	),
	'CTA-LMFT-CA-FA-035' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-DI-007-R4',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'Major depressive disorder would require a pervasive depressive syndrome rather than symptoms that remain organized around the identifiable demotion; adding broad impairment language does not supply that missing syndrome pattern.',
			'B' => 'The worry remains centered on the demotion and its consequences rather than extending broadly across multiple unrelated life domains.',
			'C' => 'A job demotion does not establish the qualifying traumatic exposure required for posttraumatic stress disorder, and the broader PTSD symptom organization is not present.',
			'D' => 'The symptoms began after an identifiable stressor, include both anxiety and depressive features, cause impairment, and remain organized around the demotion without meeting a more specific competing syndrome.',
		),
	),
	'CTA-LMFT-CA-FA-036' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-TX5D-003',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Best answer. The pattern improves when expectations and follow-through are predictable. A small set of observable targets plus one consistent caregiver response directly addresses the environmental and interpersonal contingencies maintaining the oppositional behavior.',
			'B' => 'Collaborative problem solving may improve engagement, but using it mainly after arguments does not correct the inconsistent caregiver follow-through that is already identified as a major maintaining factor.',
			'C' => 'Emotion coaching may reduce escalation, but pausing consequences and processing the conflict later leaves the central problem of inconsistent structure and contingency management insufficiently addressed.',
			'D' => 'Natural consequences can support autonomy, but the stem indicates that consistent, developmentally appropriate structure improves behavior. Reducing caregiver involvement would remove a useful treatment mechanism.',
		),
	),
	'CTA-LMFT-CA-FA-037' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-CR-006-R1',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Urgent psychiatric evaluation and weapon securing are active safety steps, but they may not adequately protect the identified target when a near-term plan, weapon access, and preparatory behavior are already established.',
			'B' => 'Further targeted-violence assessment may add information, but it unnecessarily delays protective action because the decisive risk facts are already present.',
			'C' => 'A no-contact plan and same-day crisis follow-up rely too heavily on voluntary outpatient containment for a presentation with established near-term targeted danger.',
			'D' => 'The identified target, near-term plan, weapon access, and preparatory behavior support immediate protective and emergency intervention rather than further outpatient containment.',
		),
	),
	'CTA-LMFT-CA-FA-038' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-CE-011',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'A psychiatric history could become relevant, but this option privileges a depressive formulation before the temporal relationship has been established.',
			'B' => 'Medication effects are plausible, but focusing primarily on them assumes the treatment adjustment is the key causal factor.',
			'C' => 'Focused medical information may eventually strengthen the evaluation, but the therapist should first organize the symptom chronology already available.',
			'D' => 'The central unresolved issue is chronology. Mapping the medical change and medication adjustment against physical, emotional, cognitive, and functional changes allows the therapist to evaluate competing explanations without prematurely selecting one.',
		),
	),
	'CTA-LMFT-CA-FA-039' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-DI-015',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Schizophrenia would not be the best diagnosis when psychosis repeatedly disappears outside the substance-exposure periods.',
			'B' => 'Brief psychotic disorder does not explain the repeated exposure-linked pattern.',
			'C' => 'The psychotic symptoms repeatedly emerge during or shortly after heavy methamphetamine exposure, resolve fully during sustained abstinence, and have never occurred independently. The temporal relationship therefore supports a substance-induced formulation over a primary psychotic or mood disorder. APA recognizes that substances and medications can produce psychosis, while DSM-5-TR separately classifies substance-related and psychotic conditions.',
			'D' => 'No independent manic syndrome accompanies the psychosis.',
		),
	),
	'CTA-LMFT-CA-FA-040' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-CP-011',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Reviewing evidence and replacing global failure conclusions with balanced beliefs is CBT.',
			'B' => 'Preferred-future questions, exceptions, and strengths represent solution-focused planning. That approach could build change but does not directly address the dominant identity story.',
			'C' => 'The couple has adopted a dominant problem-saturated identity story in which infertility means that they are “broken” and relationally unsuccessful. C separates the couple from that story, examines its effects, identifies experiences that contradict it, and develops an alternative relationship identity. Narrative practice explicitly connects externalizing conversations, unique outcomes, and development of alternative or re-authored storylines.',
			'D' => 'Clarifying boundaries and alliances is structural family therapy. The stem does not identify a structural organization problem as the primary mechanism.',
		),
	),
	'CTA-LMFT-CA-FA-041' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-CE-033',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Trauma history can be clinically relevant, but requesting detailed historical information before determining what currently affects functioning can collect unnecessary material and place excessive emphasis on the past event itself.',
			'B' => 'The client has disclosed past interpersonal trauma in the context of current difficulty with emotional closeness. The therapist should determine whether trauma-related symptoms, triggers, and relational effects are relevant to the present problem while respecting the client\'s control over the pace and depth of disclosure.',
			'C' => 'Current intimacy patterns warrant assessment, but the client has already introduced potentially relevant trauma information. Excluding it unless relationship-focused treatment fails would prematurely narrow the evaluation.',
			'D' => 'Mood, anxiety, dissociation, sleep, and substance use may contribute to the presentation, but searching first for an alternative symptom explanation underweights the trauma-related information already provided.',
		),
	),
	'CTA-LMFT-CA-FA-042' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-CP-018-R3',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'A repair trial could be offered as one possible option, but specifying a two-session trial gives continued treatment preferred status. The client should not have to decline a therapist-designed repair phase before the decision to leave is fully respected.',
			'B' => 'The therapist should understand the client’s dissatisfaction, review the unfinished goals, explain reasonable alternatives and foreseeable consequences, and then respect the client’s informed decision. This balances clinical responsibility with the client’s authority to stop treatment.',
			'C' => 'Transfer can be appropriate, but moving directly toward another therapist before reviewing the client\'s alternatives and foreseeable effects of ending bypasses the informed decision-making step that should precede a transfer decision.',
			'D' => 'This response respects the request to terminate and offers future resources, but it moves too quickly to closure. It does not adequately review treatment alternatives or the likely effects of ending with important goals unfinished.',
		),
	),
	'CTA-LMFT-CA-FA-043' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-CE-031',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'uses a useful systemic tool but gives historical mapping priority over integrating present functioning.',
			'B' => 'thoroughly assesses current conflict but does not adequately address the multigenerational component.',
			'C' => 'The family explicitly connects current conflict with recurring patterns across generations. Evaluating significant relationships, historical disruptions, current alliances, and how earlier patterns appear in present interactions directly addresses both the family history and current support-system dynamics.',
			'D' => 'captures differing family perspectives but is less direct in examining how historical and current patterns relate.',
		),
	),
	'CTA-LMFT-CA-FA-044' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-CR-009-R2',
		'area'                      => 'Area 3: Managing Crisis Situations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'CONTROLLED SUCCESSOR',
		'rationales'                => array(
			'A' => 'Coping support is useful, but waiting for further escalation underresponds to an already developing external threat involving unwanted workplace appearances and surveillance-like knowledge of the client\'s schedule.',
			'B' => 'A direct boundary message may not be safe or appropriate in an escalating harassment pattern and places unnecessary emphasis on communicating with the person creating the threat.',
			'C' => 'Privacy precautions and general victim services are reasonable, but the risk is specifically organized around the workplace and warrants a more targeted safety response.',
			'D' => 'The repeated threatening contact, unwanted workplace appearances, and knowledge of the client\'s movements call for active threat assessment, workplace-focused safety coordination, and specialized harassment or stalking resources before physical assault occurs.',
		),
	),
	'CTA-LMFT-CA-FA-045' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-TX5B-002',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Calibration',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'This option adds collaboration and control, but it still keeps detailed trauma narration as the primary method despite evidence that the current level of memory work is destabilizing treatment participation.',
			'B' => 'Present-focused regulation and jointly defined readiness markers are reasonable, but this approach steps away from the client’s stated wish to continue trauma work when a more titrated approach is available.',
			'C' => 'Best answer. The client explicitly wants continued trauma work with more control. Collaborative pacing, stronger stabilization, and small doses of memory work directly address post-session dysregulation without abandoning the treatment goal.',
			'D' => 'Cognitive work and grounding may be helpful adjuncts, but the stem does not identify distorted beliefs as the main barrier; the immediate problem is loss of control over pacing and activation.',
		),
	),
	'CTA-LMFT-CA-FA-046' => array(
		'correct_option'            => 'b',
		'item_id'                   => 'A-TX5B-004',
		'area'                      => 'Area 5: Treatment',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Assertive communication may improve disagreements, but the client’s target is recognizing and interrupting escalation earlier, before the verbal outburst occurs.',
			'B' => 'Best answer. The client already notices a sequence of physiologic and cognitive cues. Identifying the earliest cue and applying the existing pause-and-return plan at that point targets the mechanism closest to escalation.',
			'C' => 'Paced breathing may reduce arousal, but it is a more general regulation strategy and does not use the client’s established pause-and-return plan as directly.',
			'D' => 'Reappraising perceived disrespect can reduce anger in some situations, but the stem emphasizes a reliable escalation sequence and early body cues rather than a clearly established cognitive distortion.',
		),
	),
	'CTA-LMFT-CA-FA-047' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-LE6-005',
		'area'                      => 'Area 6: Managing Legal and Ethical Obligations',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'This is a thoughtful partial plan, but it centers on greetings and repeated event review rather than fully addressing the therapist\'s ongoing community role and the associated power dimension.',
			'B' => 'Client preference is important, but the therapist retains responsibility for professional boundaries and cannot make the client solely responsible for managing the overlap.',
			'C' => 'Separating roles and considering referral are useful safeguards, but this response remains more reactive and avoidant than establishing a comprehensive plan for an unavoidable overlap.',
			'D' => 'Best answer. A nonsexual community overlap is not automatically disqualifying. The strongest response proactively addresses acknowledgment, confidentiality, role boundaries, power, and possible effects on clinical judgment.',
		),
	),
	'CTA-LMFT-CA-FA-048' => array(
		'correct_option'            => 'd',
		'item_id'                   => 'A-DI-011-R1',
		'area'                      => 'Area 2: Developing a Diagnostic Impression',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Conduct disorder involves a broader persistent pattern of violating others\' rights or societal norms and is generally identified earlier developmentally.',
			'B' => 'Antisocial personality disorder requires a pervasive long-term pattern substantially broader than episodic impulsive anger outbursts.',
			'C' => 'No manic episode or episodic bipolar pattern is established.',
			'D' => 'The corrected stem establishes recurrent aggressive outbursts averaging two to three times weekly for four months, disproportionate to minor provocation, impulsive rather than premeditated, noninstrumental, and associated with significant work and relationship impairment. Those features align directly with the IED pattern described by APA.',
		),
	),
	'CTA-LMFT-CA-FA-049' => array(
		'correct_option'            => 'a',
		'item_id'                   => 'A-CP-009',
		'area'                      => 'Area 4: Case Conceptualization and Planning',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'The case formulation explicitly identifies a maintenance cycle: bodily arousal is interpreted catastrophically, leading to escape, reassurance seeking, and avoidance. A targets each component through cognitive evaluation, behavioral testing, and interoceptive and situational exposure. Beck Institute’s anxiety-training materials identify cognitive formulation, evaluation of anxious beliefs, behavioral experiments, and interoceptive and in-vivo exposure as corresponding CBT strategies.',
			'B' => 'Exploring separation meanings, defenses, and expectations within the therapeutic relationship is psychodynamic planning. It does not directly address the panic-specific cognition–arousal–avoidance cycle.',
			'C' => 'Changing family reassurance may remove one source of reinforcement and could support treatment. It is not the best overall plan because it omits direct work with catastrophic interpretation, physiological sensations, and situational avoidance.',
			'D' => 'Clarifying personal meaning and supporting self-directed engagement is humanistic-experiential. It does not provide the structured cognitive and exposure-based plan indicated by the formulation.',
		),
	),
	'CTA-LMFT-CA-FA-050' => array(
		'correct_option'            => 'c',
		'item_id'                   => 'A-CE-015-R1',
		'area'                      => 'Area 1: Clinical Evaluation',
		'core_calibration_status'   => 'Core',
		'source_status'             => 'EXACT/FROZEN SOURCE',
		'rationales'                => array(
			'A' => 'Frequency and financial losses are relevant, but intermittent gambling can still be clinically significant; amount and frequency alone do not capture impaired control.',
			'B' => 'Emotional triggers may help explain why gambling occurs, but they do not directly assess the central pattern already described.',
			'C' => 'The client has strong urges, unsuccessful efforts to stop, concealment, debt, and relationship consequences. Those features directly characterize impaired control and clinically meaningful effects of gambling.',
			'D' => 'Family history, treatment history, and readiness for change may inform subsequent care but do not best establish the current gambling pattern.',
		),
	),
);
