<?php
/**
 * Official California Law & Ethics (CTA-CE-001) final examination.
 *
 * Generated from:
 * - CTA_CaliforniaLawEthics_Final_Exam_Learner_REVISED_v2.1.docx
 * - CTA_California_Law_Ethics_Final_Exam_Detailed_Rationales_v2.1.docx
 *
 * @package CTA_LMS
 */

/**
 * @return array[] */
return array(
	array(
		'question_text' => 'What is the primary difference between scope of practice and scope of competence?',
		'option_a' => 'Scope of practice is determined by law, while scope of competence is determined by the clinician\'s training, education, and skill',
		'option_b' => 'Scope of practice applies only in private practice, while scope of competence applies only in agencies',
		'option_c' => 'Scope of competence is established by insurance companies',
		'option_d' => 'Scope of practice refers only to ethics',
		'correct_option' => 'a',
		'explanation' => 'Why A is correct: The course separates legal authority from individual readiness. Scope of practice concerns what a license or registration legally permits. Scope of competence concerns whether this clinician has sufficient education, training, experience, supervision, consultation, and skill to provide the service safely.\n\nWhy B is incorrect: Both concepts apply across practice settings. Private practice and agency employment may create different procedures, but the distinction between legal scope and personal competence remains relevant in either setting.\n\nWhy C is incorrect: An insurer may impose coverage or credentialing requirements, but it does not establish a clinician\'s professional competence. Competence is evaluated through the clinician\'s preparation, experience, support, and ability to practice safely.\n\nWhy D is incorrect: Scope of practice is a legal and regulatory concept, not merely an ethical one. Ethical standards may reinforce the duty to remain competent, but they do not replace the legal scope established for the profession.\n\nCTA Clinical Takeaway: Ask two separate questions: Is the service legally within my professional scope, and am I personally prepared to provide it competently?\n\nSource Alignment: Module 1; course Objective 1.',
	),
	array(
		'question_text' => 'A therapist is asked to begin treating a population they have never worked with before. What is the most appropriate first step?',
		'option_a' => 'Begin treatment immediately and seek training later',
		'option_b' => 'Ask the client whether they are comfortable with the therapist\'s lack of experience',
		'option_c' => 'Evaluate whether the therapist possesses the education, training, supervision, and competence necessary to provide services',
		'option_d' => 'Automatically refer the client elsewhere',
		'correct_option' => 'c',
		'explanation' => 'Why A is incorrect: Beginning first and attempting to become competent later places the client at avoidable risk. The course emphasizes evaluating fit and preparation before accepting or continuing a service that may exceed current competence.\n\nWhy B is incorrect: Client preference matters, but a client\'s willingness does not establish professional competence or remove the clinician\'s responsibility to assess training, experience, consultation, and safety.\n\nWhy C is correct: The first step is a structured competence assessment. The clinician should consider education, training, supervised experience, consultation access, population needs, treatment complexity, setting support, and whether the service can be provided safely.\n\nWhy D is incorrect: Referral may ultimately be appropriate, but automatic referral is premature. The clinician may be able to proceed after consultation, supervision, additional training, co-treatment, or another proportionate support.\n\nCTA Clinical Takeaway: Do not assume competence and do not assume referral. Assess first, then choose the safest proportionate response.\n\nSource Alignment: Module 1; course Objective 1.',
	),
	array(
		'question_text' => 'Which statement best reflects informed consent?',
		'option_a' => 'It is completed once during intake and never revisited',
		'option_b' => 'It is primarily a billing requirement',
		'option_c' => 'It is an ongoing process of communication, clarification, and agreement',
		'option_d' => 'It applies only to high-risk clients',
		'correct_option' => 'c',
		'explanation' => 'Why A is incorrect: A signed intake form does not end informed consent. Consent should be revisited when services, risks, fees, technology, communication methods, treatment units, or other important conditions change.\n\nWhy B is incorrect: Fees are one part of informed consent, but the process is broader. It includes the nature of services, risks, benefits, alternatives, confidentiality, policies, boundaries, and opportunities for questions.\n\nWhy C is correct: The course teaches informed consent as an ongoing professional conversation. The clinician explains relevant information, checks understanding, clarifies expectations, responds to changes, and documents the process.\n\nWhy D is incorrect: Informed consent applies to routine and high-risk care. The amount and detail may vary with the service and circumstances, but it is not limited to clients presenting with elevated risk.\n\nCTA Clinical Takeaway: A form records consent; communication creates and maintains informed consent.\n\nSource Alignment: Module 2; course Objective 2.',
	),
	array(
		'question_text' => 'Which of the following should generally be included in informed consent?',
		'option_a' => 'Nature of treatment, risks, benefits, alternatives, fees, and limits of confidentiality',
		'option_b' => 'Personal opinions about previous clients',
		'option_c' => 'A complete list of all treatment techniques the therapist knows',
		'option_d' => 'Future diagnoses that may develop',
		'correct_option' => 'a',
		'explanation' => 'Why A is correct: These elements help the client understand the service, make a voluntary decision, anticipate financial and privacy issues, and recognize the circumstances in which confidentiality may be limited.\n\nWhy B is incorrect: Personal opinions or information about previous clients are irrelevant to the current client\'s decision and may create confidentiality and professionalism concerns.\n\nWhy C is incorrect: The clinician should explain the proposed service and relevant methods, not provide an exhaustive inventory of every technique learned. Excess information can obscure what the client actually needs to understand.\n\nWhy D is incorrect: Clinicians should discuss current assessment findings and uncertainty appropriately, but they cannot predict every future diagnosis. Informed consent should be accurate and relevant rather than speculative.\n\nCTA Clinical Takeaway: Give the client the information reasonably needed to understand the service and decide whether to participate.\n\nSource Alignment: Module 2; course Objective 2.',
	),
	array(
		'question_text' => 'A therapist sets texting boundaries and emergency instructions. This is best viewed as:',
		'option_a' => 'A violation of confidentiality',
		'option_b' => 'A clear communication boundary that establishes expectations',
		'option_c' => 'A guarantee of crisis coverage',
		'option_d' => 'An unethical restriction of client access',
		'correct_option' => 'b',
		'explanation' => 'Why A is incorrect: Explaining how texting will be used is a privacy and boundary safeguard. The therapist should also describe security limits, documentation practices, and appropriate alternatives for sensitive or urgent communication.\n\nWhy B is correct: Clear texting and emergency policies establish what the channel is for, typical response times, what is not monitored continuously, and what the client should do during an urgent situation.\n\nWhy C is incorrect: Emergency instructions clarify limits; they do not guarantee continuous crisis availability. A responsible policy avoids creating the impression that a therapist monitors messages at all times.\n\nWhy D is incorrect: Reasonable communication boundaries protect both client welfare and the treatment relationship. They are not unethical when they are disclosed clearly and paired with appropriate emergency and access information.\n\nCTA Clinical Takeaway: Digital access should be clear and realistic, not unlimited or implied.\n\nSource Alignment: Module 2; course Objective 2.',
	),
	array(
		'question_text' => 'What best defines confidentiality?',
		'option_a' => 'A client\'s right to refuse testimony in court',
		'option_b' => 'A therapist\'s duty to protect private information obtained in treatment',
		'option_c' => 'A parent\'s automatic right to all information',
		'option_d' => 'A rule that applies only to written records',
		'correct_option' => 'b',
		'explanation' => 'Why A is incorrect: This describes psychotherapist-patient privilege more closely than confidentiality. Privilege concerns protection of therapy communications in legal proceedings.\n\nWhy B is correct: The course defines confidentiality as the clinician\'s broad legal and ethical duty to protect information obtained through the professional relationship and disclose it only with valid authority.\n\nWhy C is incorrect: A parent does not automatically receive every piece of treatment information in every circumstance. Consent authority, confidentiality, minor self-consent, safety, and record-access rights must be analyzed separately.\n\nWhy D is incorrect: Confidentiality applies to spoken information, electronic communications, billing information, records, observations, and other identifiable information—not only written notes.\n\nCTA Clinical Takeaway: Confidentiality is the broad duty to protect information; privilege is a distinct legal protection in proceedings.\n\nSource Alignment: Final Module 3 content; course Objective 3.',
	),
	array(
		'question_text' => 'Who generally holds privilege in psychotherapy?',
		'option_a' => 'The therapist',
		'option_b' => 'The court',
		'option_c' => 'The client',
		'option_d' => 'The insurance company',
		'correct_option' => 'c',
		'explanation' => 'Why A is incorrect: The therapist protects confidential information and may assert privilege on the client\'s behalf in appropriate circumstances, but the therapist is not generally the privilege holder.\n\nWhy B is incorrect: A court may decide disputes about privilege, waiver, or an exception, but the court does not generally own the privilege.\n\nWhy C is correct: Within the course framework, psychotherapist-patient privilege generally belongs to the client or patient. That is why a therapist should identify the privilege holder and evaluate authorization, waiver, and exceptions before disclosing in legal proceedings.\n\nWhy D is incorrect: An insurer may receive limited information for authorized purposes, but it does not generally hold the client\'s psychotherapist-patient privilege.\n\nCTA Clinical Takeaway: Before responding to legal process, identify whose right is being protected and who has authority to waive or assert it.\n\nSource Alignment: Final Module 3 content; course Objective 3.',
	),
	array(
		'question_text' => 'A therapist receives a subpoena requesting client records. What is the most appropriate initial response?',
		'option_a' => 'Send the records immediately',
		'option_b' => 'Clarify legal requirements, client authorization, and privilege issues before responding',
		'option_c' => 'Ignore the subpoena',
		'option_d' => 'Send a brief summary instead',
		'correct_option' => 'b',
		'explanation' => 'Why A is incorrect: A subpoena begins a review process; it does not automatically eliminate confidentiality or privilege or authorize production of an entire record.\n\nWhy B is correct: The therapist should identify the document, preserve records, note the deadline, review authorization and privilege, communicate with the client when appropriate, obtain qualified consultation, and respond only within lawful scope.\n\nWhy C is incorrect: Legal process requires prompt attention. Protecting privilege does not mean ignoring deadlines or failing to respond through the appropriate process.\n\nWhy D is incorrect: A summary is still a disclosure. The therapist should not substitute a summary for records without determining whether any disclosure is authorized, required, clinically appropriate, and properly limited.\n\nCTA Clinical Takeaway: Do not automatically disclose and do not ignore. Review, consult, protect, and respond appropriately.\n\nSource Alignment: Final Module 3 content; course Objective 3.',
	),
	array(
		'question_text' => 'Which situation most clearly represents a legally recognized exception to confidentiality?',
		'option_a' => 'A therapist believes disclosure may improve treatment',
		'option_b' => 'A parent requests information about an adult child',
		'option_c' => 'A client becomes upset during session',
		'option_d' => 'A reportable abuse situation meets legal reporting requirements',
		'correct_option' => 'd',
		'explanation' => 'Why A is incorrect: A clinician\'s belief that disclosure might be helpful does not by itself create legal authority. The clinician still needs authorization or another recognized legal basis.\n\nWhy B is incorrect: A parent\'s relationship to an adult client does not automatically authorize disclosure. The clinician must evaluate the adult client\'s authorization and any applicable legal exception.\n\nWhy C is incorrect: Emotional upset is clinically important, but it does not by itself create a confidentiality exception.\n\nWhy D is correct: When the facts meet the legal threshold for a mandated report, the reporting duty creates a recognized exception to the ordinary confidentiality rule. The clinician should report to the legally designated recipient, limit unnecessary disclosure, document, and continue clinical follow-up.\n\nCTA Clinical Takeaway: Disclosure requires authority. A legal reporting threshold—not pressure, preference, or discomfort—creates the duty.\n\nSource Alignment: Final Module 3 and Module 4 reporting content; course Objectives 3 and 4.',
	),
	array(
		'question_text' => 'When working with a minor, what is often the first legal question a therapist should clarify?',
		'option_a' => 'Whether the minor likes therapy',
		'option_b' => 'Whether the parent is cooperative',
		'option_c' => 'Who has legal authority to consent to treatment',
		'option_d' => 'Which parent attends appointments most often',
		'correct_option' => 'c',
		'explanation' => 'Why A is incorrect: The minor\'s engagement and preferences matter clinically, but they do not answer the initial legal question of who may authorize treatment.\n\nWhy B is incorrect: Cooperation affects treatment logistics and alliance, but a cooperative parent may still lack sole authority to consent.\n\nWhy C is correct: Before routine treatment begins, the therapist should determine whether a parent, guardian, minor-consent statute, or other legally recognized authority permits treatment and whether any court order limits decision-making.\n\nWhy D is incorrect: Attendance does not establish legal authority. The parent who calls, pays, or attends most often is not automatically the person authorized to consent.\n\nCTA Clinical Takeaway: Verify legal authority before relying on family roles, confidence, payment, or attendance.\n\nSource Alignment: Module 4; course Objective 4.',
	),
	array(
		'question_text' => 'Which statement about custody is most accurate?',
		'option_a' => 'Physical custody always determines treatment consent',
		'option_b' => 'Legal custody is typically the primary factor in treatment decision-making authority',
		'option_c' => 'Therapists should assume both parents always have equal authority',
		'option_d' => 'Custody status rarely affects treatment decisions',
		'correct_option' => 'b',
		'explanation' => 'Why A is incorrect: Physical custody concerns where the child lives or spends time; it does not always determine authority for health or mental-health decisions.\n\nWhy B is correct: The course teaches that legal custody is typically central to treatment decision-making authority. The clinician should review the actual current custody order and any provisions affecting consent rather than relying on labels alone.\n\nWhy C is incorrect: Parents may have joint, sole, limited, or differently allocated authority. Assuming equal authority can conflict with the operative order.\n\nWhy D is incorrect: Custody can directly affect consent, parent communication, access questions, and the therapist\'s role in high-conflict situations.\n\nCTA Clinical Takeaway: Use the current legal documents, not assumptions about family structure or physical custody.\n\nSource Alignment: Module 4; course Objective 4.',
	),
	array(
		'question_text' => 'A self-referred minor presents for therapy without a parent. What should the clinician do first?',
		'option_a' => 'Begin treatment immediately',
		'option_b' => 'Refuse treatment automatically',
		'option_c' => 'Determine whether the minor qualifies to consent under applicable California law',
		'option_d' => 'Contact the school before proceeding',
		'correct_option' => 'c',
		'explanation' => 'Why A is incorrect: Starting immediately without evaluating consent authority may create an avoidable legal and clinical problem.\n\nWhy B is incorrect: Automatic refusal is also premature. California law may allow a qualifying minor to consent under specified circumstances.\n\nWhy C is correct: The clinician should assess whether the applicable minor-consent pathway covers the minor, the service, and the circumstances, and should address maturity, parent involvement, documentation, confidentiality, and safety as taught in the course.\n\nWhy D is incorrect: A school cannot determine the clinician\'s legal authority to provide private treatment. Contacting the school also creates separate authorization and confidentiality issues.\n\nCTA Clinical Takeaway: A self-referred minor requires a structured legal assessment, not automatic acceptance or automatic rejection.\n\nSource Alignment: Module 4; course Objective 4.',
	),
	array(
		'question_text' => 'What is the primary goal during a crisis situation?',
		'option_a' => 'Complete a diagnosis',
		'option_b' => 'Preserve rapport',
		'option_c' => 'Review long-term treatment goals',
		'option_d' => 'Ensure safety',
		'correct_option' => 'd',
		'explanation' => 'Why A is incorrect: Diagnostic clarification may matter, but it should not delay assessment and intervention when immediate safety is uncertain.\n\nWhy B is incorrect: Rapport supports honest disclosure and collaboration, but preserving rapport cannot take priority over necessary protective action.\n\nWhy C is incorrect: Long-term goals are secondary during an acute crisis. The clinician first addresses current danger, stabilization, level of care, and follow-up.\n\nWhy D is correct: The immediate priority is safety. The clinician assesses the crisis, clarifies risk, uses proportionate protective interventions, consults as needed, and documents the reasoning and plan.\n\nCTA Clinical Takeaway: In a crisis, address immediate safety before returning to broader treatment goals.\n\nSource Alignment: Module 5; course Objective 5.',
	),
	array(
		'question_text' => 'Which combination of factors is particularly important when assessing suicide risk?',
		'option_a' => 'Insurance status, education level, diagnosis, and employment',
		'option_b' => 'Relationship status, hobbies, and treatment history',
		'option_c' => 'Intent, plan, means, and timeline',
		'option_d' => 'Intelligence, appearance, insight, and motivation',
		'correct_option' => 'c',
		'explanation' => 'Why A is incorrect: These contextual factors may affect access or formulation, but they do not replace direct assessment of suicidal thinking and near-term capability.\n\nWhy B is incorrect: Relationships, interests, and treatment history may contribute to risk or protection, but this option omits the direct questions needed to clarify possible action.\n\nWhy C is correct: Intent, plan, access to means, and anticipated timeline are central direct-assessment areas. The course also teaches considering past behavior, escalation, risk factors, protective factors, willingness to accept help, and the overall clinical formulation.\n\nWhy D is incorrect: Mental-status observations may be relevant, but they are not a substitute for direct inquiry about suicidal intent, planning, means, and timing.\n\nCTA Clinical Takeaway: Ask directly about the dimensions that clarify whether thoughts may become action.\n\nSource Alignment: Module 5; course Objective 5.',
	),
	array(
		'question_text' => 'What is the primary legal principle associated with Tarasoff?',
		'option_a' => 'Therapists must always warn family members first',
		'option_b' => 'Therapists must hospitalize every client expressing anger',
		'option_c' => 'Therapists may have a duty to protect when a patient has communicated a serious threat of physical violence against a reasonably identifiable victim or victims',
		'option_d' => 'Therapists must release records whenever danger is discussed',
		'correct_option' => 'c',
		'explanation' => 'Why A is incorrect: The course does not teach a universal rule requiring family members to be warned first. Protective actions depend on the applicable legal framework, the facts, and the person or agency that must be contacted.\n\nWhy B is incorrect: Anger alone does not automatically establish a serious threat or require hospitalization. The clinician assesses seriousness, specificity, credibility, victim identifiability, access, context, and level of care.\n\nWhy C is correct: Within the course framework, California’s duty-to-protect statute is triggered only in the limited circumstance in which the patient has communicated to the psychotherapist a serious threat of physical violence against a reasonably identifiable victim or victims. The precise response depends on current California law and the facts.\n\nWhy D is incorrect: Discussion of danger does not automatically authorize release of the entire record. Protective disclosure and record production are distinct legal questions, and disclosure should be limited to valid authority and purpose.\n\nCTA Clinical Takeaway: Assess the threat and the legal trigger; do not convert every angry statement into automatic warning, hospitalization, or record release.\n\nSource Alignment: Module 5; course Objective 5. Verified against Civil Code section 43.92 on July 27, 2026.',
	),
	array(
		'question_text' => 'A client states they think about hurting a former supervisor. What should the therapist do first?',
		'option_a' => 'Notify the supervisor immediately',
		'option_b' => 'Contact law enforcement',
		'option_c' => 'Continue assessing the seriousness, specificity, and credibility of the threat',
		'option_d' => 'Terminate treatment',
		'correct_option' => 'c',
		'explanation' => 'Why A is incorrect: Immediate warning may be required after the legal and clinical threshold is established, but the statement alone does not provide enough information to determine the appropriate protective action.\n\nWhy B is incorrect: Law-enforcement contact may be part of a protective response, but it is premature before clarifying the threat unless the available facts already indicate an immediate emergency.\n\nWhy C is correct: The therapist should assess what was said, target identifiability, intent, plan, means, access, preparation, timeframe, history, escalation, credibility, protective factors, and immediate safety. Assessment then informs consultation and proportionate action.\n\nWhy D is incorrect: Termination does not assess or manage the threat and could disrupt care during a high-risk period.\n\nCTA Clinical Takeaway: Assessment comes before selecting the protective response, unless the existing facts already require immediate emergency action.\n\nSource Alignment: Module 5; course Objective 5.',
	),
	array(
		'question_text' => 'Which documentation practice is strongest following a crisis intervention?',
		'option_a' => 'Document the assessment, actions taken, rationale for decisions, and follow-up plan',
		'option_b' => 'Note only that the client was stable',
		'option_c' => 'Wait several days before documenting',
		'option_d' => 'Keep documentation minimal to reduce liability',
		'correct_option' => 'a',
		'explanation' => 'Why A is correct: Strong crisis documentation shows what the client reported, what the clinician assessed, relevant risk and protective factors, consultation, actions, response, level-of-care reasoning, safety planning, handoff, and follow-up.\n\nWhy B is incorrect: \'Stable\' is a conclusion without supporting assessment. It does not show how risk was evaluated or why the selected plan was reasonable.\n\nWhy C is incorrect: Delayed documentation increases the chance of omissions and weakens continuity. Crisis-related records should be completed promptly and accurately.\n\nWhy D is incorrect: Intentionally sparse documentation does not reduce risk. It removes the reasoning needed for continuity, accountability, and review.\n\nCTA Clinical Takeaway: Document the bridge from facts to assessment, decision, action, and follow-up.\n\nSource Alignment: Modules 5 and 6; course Objective 5.',
	),
	array(
		'question_text' => 'Which statement best reflects a client\'s access rights regarding records?',
		'option_a' => 'Clients never have a right to inspect records',
		'option_b' => 'Only attorneys may request records',
		'option_c' => 'Therapists should generally deny access to avoid risk',
		'option_d' => 'Clients generally have rights to inspect or obtain records, subject to legal limitations',
		'correct_option' => 'd',
		'explanation' => 'Why A is incorrect: The course teaches that clients generally have access rights. Those rights may be affected by specific legal limitations, procedures, representatives, or other circumstances.\n\nWhy B is incorrect: A client\'s access does not depend on having an attorney. Attorneys may submit requests in some matters, but they are not the only people who may lawfully request records.\n\nWhy C is incorrect: Routine denial is not a risk-management strategy. The clinician should verify the requester, identify the governing law, track deadlines, evaluate any lawful limitation, communicate appropriately, and document the response.\n\nWhy D is correct: The course presents client access as the general rule, subject to applicable legal limits and procedures. The clinician should distinguish client access from third-party requests, subpoenas, authorizations, and privilege issues.\n\nCTA Clinical Takeaway: Start from the client\'s general access rights, then evaluate the specific lawful procedure and any supported limitation.\n\nSource Alignment: Module 6; course Objective 6. Current statutory verification remains part of the separate prepublication review.',
	),
	array(
		'question_text' => 'What is one significant consequence of poor documentation?',
		'option_a' => 'It automatically results in Board discipline',
		'option_b' => 'It weakens clinical continuity and legal defensibility',
		'option_c' => 'It eliminates confidentiality protections',
		'option_d' => 'It extends treatment duration',
		'correct_option' => 'b',
		'explanation' => 'Why A is incorrect: Poor documentation can contribute to professional risk, but discipline is not automatic and depends on the facts, pattern, applicable requirements, and adjudicative process.\n\nWhy B is correct: Incomplete or vague notes make it harder for the clinician or another provider to understand assessment, interventions, risk, consultation, decisions, and follow-up. They also weaken the record supporting professional reasoning.\n\nWhy C is incorrect: Documentation quality does not erase confidentiality obligations. The record remains protected even when it is incomplete or poorly written.\n\nWhy D is incorrect: Poor documentation may create inefficiency, but it does not necessarily lengthen treatment. The more direct consequences are impaired continuity, accountability, and defensibility.\n\nCTA Clinical Takeaway: A strong note supports care first and also shows the reasoning behind professional decisions.\n\nSource Alignment: Module 6; course Objective 6.',
	),
	array(
		'question_text' => 'A therapist receives a Board complaint. What is generally the most appropriate initial response?',
		'option_a' => 'Alter documentation to improve clarity',
		'option_b' => 'Ignore the complaint unless a hearing is scheduled',
		'option_c' => 'Read the notice carefully, preserve documentation, and seek consultation as needed',
		'option_d' => 'Contact the complainant directly and demand withdrawal',
		'correct_option' => 'c',
		'explanation' => 'Why A is incorrect: Records must not be altered, backdated, rewritten, or disguised after a complaint or investigation begins. Any legitimate later entry must follow an accurate amendment or late-entry process.\n\nWhy B is incorrect: Board correspondence may contain deadlines and required actions. Ignoring it can compound the problem.\n\nWhy C is correct: The clinician should identify what is requested and by when, preserve records, notify the malpractice carrier when appropriate, obtain qualified licensing or legal consultation, and respond professionally through the required process.\n\nWhy D is incorrect: Directly pressuring the complainant may be retaliatory, coercive, counterproductive, or confidentiality-breaching. The complaint should be handled through formal channels.\n\nCTA Clinical Takeaway: Preserve, understand, consult, and respond—never alter, ignore, or retaliate.\n\nSource Alignment: Module 6; course Objective 6.',
	),
	array(
		'question_text' => 'Which statement best reflects the CTA Crisis Framework taught in this course?',
		'option_a' => 'Act quickly before additional information is gathered',
		'option_b' => 'Pause, assess, clarify, consult, protect, and document',
		'option_c' => 'Warn first and assess later',
		'option_d' => 'Refer all crisis situations to emergency services',
		'correct_option' => 'b',
		'explanation' => 'Why A is incorrect: Urgent action may sometimes be necessary, but the framework rejects impulsive action without gathering the information needed to understand the risk and legal duty.\n\nWhy B is correct: The sequence structures clinical judgment: pause, assess risk, clarify facts and authority, consult when needed, take protective action proportionate to the situation, and document the reasoning and follow-up.\n\nWhy C is incorrect: Warning before assessment can lead to unnecessary disclosure or the wrong intervention. Assessment and clarification identify whether a protective duty is triggered and what response fits.\n\nWhy D is incorrect: Crisis situations vary. Some require emergency services; others may be managed through safety planning, increased contact, consultation, support involvement, voluntary evaluation, or another proportionate response.\n\nCTA Clinical Takeaway: Use a consistent process so urgency does not become impulsivity.\n\nSource Alignment: Module 5 and course capstone framework; course Objective 5.',
	),
	array(
		'question_text' => 'Which statement best reflects ethical advertising for mental health professionals?',
		'option_a' => 'Guaranteed results in five sessions',
		'option_b' => 'California\'s best therapist',
		'option_c' => '100% success rate with anxiety treatment',
		'option_d' => 'Services are provided consistent with professional standards and individual client needs',
		'correct_option' => 'd',
		'explanation' => 'Why A is incorrect: A guaranteed outcome overstates what therapy can promise and does not account for individual needs, circumstances, participation, diagnosis, risk, or treatment response.\n\nWhy B is incorrect: An unsupported superlative is difficult to substantiate and may mislead consumers about comparative quality.\n\nWhy C is incorrect: A universal success-rate claim is not credible and creates an unrealistic expectation of outcome.\n\nWhy D is correct: This statement is restrained, accurate, and consistent with individualized care. Ethical advertising should accurately identify the clinician and services and avoid misleading, unverifiable, or guaranteed claims.\n\nCTA Clinical Takeaway: Describe qualifications and services accurately; do not promise outcomes or use unsupported superiority claims.\n\nSource Alignment: Module 6; course Objective 6. Current advertising requirements remain part of the separate prepublication legal review.',
	),
	array(
		'question_text' => 'What is a professional will?',
		'option_a' => 'A document used to terminate treatment',
		'option_b' => 'A plan addressing client records and professional responsibilities if a therapist dies or becomes incapacitated',
		'option_c' => 'A mandatory BBS reporting form',
		'option_d' => 'A billing document required by insurance companies',
		'correct_option' => 'b',
		'explanation' => 'Why A is incorrect: A professional will may support client notification and transition after death or incapacity, but it is not simply a routine termination document.\n\nWhy B is correct: The course uses professional will planning to address client notification, urgent cases, referrals, record custody, technology access, business obligations, and continuity when the clinician cannot personally manage the practice.\n\nWhy C is incorrect: The course does not identify a professional will as a mandatory BBS reporting form.\n\nWhy D is incorrect: It is a continuity and records plan, not an insurer billing document.\n\nCTA Clinical Takeaway: Plan before incapacity so clients, records, and professional obligations can be handled responsibly.\n\nSource Alignment: Module 6 syllabus content and Practice Protection Toolkit; course Objective 6.',
	),
	array(
		'question_text' => 'After reviewing the Cole-Zakarian disciplinary case, what was the primary lesson emphasized in the course?',
		'option_a' => 'Most Board actions result from one catastrophic mistake',
		'option_b' => 'Documentation is more important than client care',
		'option_c' => 'Multiple small professional failures can accumulate into significant disciplinary consequences',
		'option_d' => 'Board investigations are unavoidable',
		'correct_option' => 'c',
		'explanation' => 'Why A is incorrect: The course explicitly avoids reducing discipline to one catastrophic event. The case was used to examine how concerns across records, billing, advertising, license status, communication, termination, and cooperation can form a pattern.\n\nWhy B is incorrect: Documentation supports client care; it does not outrank it. The lesson is that clinical and administrative responsibilities work together to protect clients and professional accountability.\n\nWhy C is correct: The corrected course teaching is that multiple professional concerns may combine into a pattern that results in serious discipline. Small failures become more significant when they repeat, interact, or remain uncorrected.\n\nWhy D is incorrect: Investigations are not inevitable. Preventive systems, timely response, accurate records, consultation, and professional follow-through can reduce risk and support an appropriate response if a complaint occurs.\n\nCTA Clinical Takeaway: Look for patterns early. Repeated small breakdowns can create a larger professional problem.\n\nSource Alignment: Module 6 corrected script; course Objective 6. Final case-source verification remains part of the separate prepublication review.',
	),
	array(
		'question_text' => 'Which statement best reflects the central theme of this California Law & Ethics course?',
		'option_a' => 'Memorize every law and regulation governing practice',
		'option_b' => 'Avoid difficult clinical situations whenever possible',
		'option_c' => 'Apply thoughtful clinical judgment supported by law, ethics, documentation, and consultation',
		'option_d' => 'Focus primarily on avoiding Board complaints',
		'correct_option' => 'c',
		'explanation' => 'Why A is incorrect: Clinicians must use current authority, but the course does not frame competent practice as memorizing every rule. It teaches how to identify the controlling issue and source and then apply them thoughtfully.\n\nWhy B is incorrect: Ethical practice does not mean avoiding complexity. It means assessing fit, using consultation and supervision, taking proportionate action, and referring when the client\'s needs exceed the clinician\'s role or competence.\n\nWhy C is correct: This option captures the course\'s unifying method: gather information, identify legal and ethical authority, assess clinical risk and fit, consult when appropriate, act proportionately, and document the reasoning.\n\nWhy D is incorrect: Complaint prevention is one possible benefit of sound practice, but the primary purpose is client welfare, professional accountability, and reliable clinical decision-making.\n\nCTA Clinical Takeaway: The goal is disciplined professional reasoning—not fear, avoidance, or memorization alone.\n\nSource Alignment: Course capstone; all six course objectives.',
	),
);
