<?php
/**
 * LMFT California Clinical — Comprehensive Simulation Form B items 76–100 (PROMPT 10).
 * Learner-facing stems and choices only. Answer keys deferred to admin merge.
 *
 * @package CTA_LMS
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-076',
		'question_text'  => 'A child’s anxiety appears differently at home and school and includes school refusal, somatic complaints, caregiver accommodation, and reduced classroom participation. Which outcome-measurement plan is BEST?',
		'option_a'       => 'Combine child/caregiver symptom ratings; record sleep plus session behavior; review therapist observations across treatment.',
		'option_b'       => 'Combine attendance plus nurse-visit data; record assignment completion plus classroom behavior; review detailed teacher reports across treatment.',
		'option_c'       => 'Combine child/caregiver/teacher symptom reports; record attendance plus classroom participation; review caregiver accommodation over time.',
		'option_d'       => 'Combine caregiver accommodation plus parent distress; record morning departures plus refusal episodes; review therapist-rated confidence consistently over time.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-077',
		'question_text'  => 'During a scheduled telehealth session, an adult client joins from a shared workplace break room. Coworkers are walking through the room and can hear portions of the conversation. The client says, "It\'s fine, I don\'t care if they hear," and wants to begin discussing a highly sensitive family issue. What should the therapist do?',
		'option_a'       => 'Continue the session because the client knowingly accepts the privacy risk, avoid names and identifying details, use headphones, lower the therapist\'s voice, and document the client\'s preference to proceed in the shared space.',
		'option_b'       => 'Shift to nonsensitive content, document the privacy and confidentiality concern, and make a plan for a more private telehealth setting next time.',
		'option_c'       => 'With headphones in place and more distance from coworkers, continue the discussion and document the client\'s choice to proceed despite the privacy risk.',
		'option_d'       => 'Address the privacy problem before substantive discussion, help the client move to a private setting or reschedule if needed, and document the telehealth decision.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-078',
		'question_text'  => 'Parents from different cultural backgrounds are co-parenting a 14-year-old. One parent views increasing independence as a sign of maturity and respect; the other expects important decisions to remain family-based. Neither approach is unsafe, but the parents debate these expectations in front of the adolescent, who now seeks permission from whichever parent is more likely to agree. Which intervention should the therapist use?',
		'option_a'       => 'Define separate decision areas in which each parent’s cultural expectations guide the adolescent, coordinating when domains overlap.',
		'option_b'       => 'Identify the priorities behind each approach and build a coordinated response that preserves meaningful parts of both traditions during recurring family decisions.',
		'option_c'       => 'Use a family-values exercise to select one guiding principle for independence and apply it consistently across major decisions.',
		'option_d'       => 'Coach the parents to present a united response to the adolescent while privately maintaining their different cultural expectations.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-079',
		'question_text'  => 'An 8-year-old frequently yells and hits a younger sibling when a preferred game ends. The caregiver responds with lengthy lectures, then usually allows the child to choose another preferred activity to settle down. The child can use a brief “one more minute” request when prompted before becoming upset. Which intervention should the therapist use?',
		'option_a'       => 'Use a behavior chart for calm sibling play, give a reward at the end of the day, and discuss aggressive episodes during the evening routine.',
		'option_b'       => 'Prompt the replacement request before transitions, reinforce using it, and follow aggression with one brief, predictable loss of the current privilege.',
		'option_c'       => 'Teach a calming routine after aggression, validate frustration, and restart the activity once the child settles enough to talk.',
		'option_d'       => 'Ignore verbal protests, separate the siblings briefly after aggression, and coach a repair once both children are calm.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-080',
		'question_text'  => 'For four months, a client has experienced binge-eating episodes at least weekly. During episodes, the client consumes unusually large amounts rapidly, feels unable to stop, often eats when not physically hungry, eats alone because of embarrassment, and afterward feels disgusted and very guilty. The episodes cause marked distress. The client does not regularly vomit, fast, misuse medication, or exercise to compensate. Which diagnosis is MOST supported?',
		'option_a'       => 'Binge-eating disorder',
		'option_b'       => 'Bulimia nervosa',
		'option_c'       => 'Anorexia nervosa, binge-eating/purging type',
		'option_d'       => 'Other specified feeding or eating disorder',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-081',
		'question_text'  => 'Three months after surviving a home invasion, a client has abrupt episodes of racing heart and shortness of breath when hearing footsteps outside at night. The client also experiences intrusive memories, avoids being home alone after dark, believes the home is persistently unsafe, feels emotionally detached from others, remains hypervigilant, and has significant sleep disturbance. The symptoms interfere with daily functioning, and similar attacks do not occur unexpectedly in unrelated situations. Which diagnosis is MOST supported?',
		'option_a'       => 'Panic disorder',
		'option_b'       => 'Posttraumatic stress disorder',
		'option_c'       => 'Generalized anxiety disorder',
		'option_d'       => 'Specific phobia, situational type',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-082',
		'question_text'  => 'An adolescent with a history of repeated placement disruptions responds to planned termination with anger, missed sessions, and repeated testing of whether the therapist will remain available. A supportive caregiver participates in treatment. What should the therapist do NEXT?',
		'option_a'       => 'Address the ending directly; discuss anger plus missed sessions; keep the original timeline with caregiver support.',
		'option_b'       => 'Address the ending clearly; link reactions to past disruptions; keep a predictable timeline with caregiver support.',
		'option_c'       => 'Address the ending developmentally; process reactions to prior disruptions; extend the timeline until the adolescent accepts termination with caregiver support.',
		'option_d'       => 'Address the ending developmentally; review disengagement reactions plus attendance; arrange transfer with caregiver support if absences continue.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-083',
		'question_text'  => 'A client recently relocated for a new job. The client\'s adolescent started at a new school, while the spouse remains in the former city during the workweek until a transfer becomes available. The client reports poor sleep, irritability, disrupted routines, and increasing family tension. Which assessment is BEST?',
		'option_a'       => 'Map the timing and combined effects of relocation, new employment, school transition, and weekday separation on routines, support, symptoms, and family functioning.',
		'option_b'       => 'Assess the client\'s new job demands, sleep, and individual coping before examining how the family\'s relocation and separation schedule are affecting the household.',
		'option_c'       => 'Explore the adolescent\'s school adjustment, the spouse\'s weekday absence, and family communication to determine which change is producing the greatest strain.',
		'option_d'       => 'Review the family\'s prior adjustment to major transitions, current conflict patterns, and available supports before deciding whether the present changes are clinically significant.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-084',
		'question_text'  => 'A client is considering a major life decision. The client\'s religious community provides substantial social support but also teaches beliefs that contribute to the client\'s conflict about the decision. What should the therapist assess NEXT?',
		'option_a'       => 'Assess personal beliefs, values, decision-making principles, and whether the client’s own spiritual views differ from the community’s expectations.',
		'option_b'       => 'Explore beliefs, practices, community relationships, sources of support, areas of conflict, and their meaning for the client’s current decision.',
		'option_c'       => 'Assess family and community pressure, feared consequences, social support, and whether disagreement with religious guidance is impairing current functioning.',
		'option_d'       => 'Explore alternative communities, secular supports, prior faith transitions, family reactions, social consequences, practical constraints, and how earlier value conflicts were handled.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-085',
		'question_text'  => 'A client says the therapist’s emphasis on individual independence disregards important family and cultural obligations. The client has become less open and has begun missing sessions. What should the therapist do NEXT?',
		'option_a'       => 'Acknowledge the concern; adapt how independence is discussed; retain independence as the primary goal while monitoring openness and attendance.',
		'option_b'       => 'Acknowledge possible mismatch; explore the client’s meaning and family roles; revise goals and methods within the relevant cultural context.',
		'option_c'       => 'Acknowledge the concern; explore transfer choices and therapeutic fit; offer brief bridge sessions if the client requests another therapist.',
		'option_d'       => 'Acknowledge the concern; invite family participation if desired; retain the current goals while monitoring attendance and depth of disclosure.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-086',
		'question_text'  => 'A therapist learns that two young children have repeatedly been left alone overnight while their primary caregiver was intoxicated. A sober relative currently has the children and they are physically safe. The caregiver tells the therapist the arrangement “won\'t happen again” and asks for an opportunity to address the substance problem privately. What should the therapist do NEXT?',
		'option_a'       => 'Keep the children with the sober relative, arrange immediate substance-use treatment for the caregiver, and monitor whether supervision improves before reporting.',
		'option_b'       => 'Clarify how frequently the children were left alone, whether injury occurred, and whether the caregiver appreciated the risk before deciding whether a report is warranted.',
		'option_c'       => 'Develop a formal family safety plan with the sober relative and make a child-protection report only if the intoxicated caregiver violates that agreement.',
		'option_d'       => 'Ensure the children remain safely supervised and make the required child-protection report based on reasonable suspicion without waiting for injury or definitive proof.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-087',
		'question_text'  => 'Parents of a 7-year-old report that bedtime has become a two-hour struggle. The child protests, one parent threatens consequences, the other parent rescues the child and stays in the bedroom, and the child escalates until the parents disagree with each other. The pattern repeats nightly. The therapist is using a strategic family therapy approach. Which intervention should the therapist use?',
		'option_a'       => 'Assign the parents to record the bedtime sequence, including what each adult does immediately before the child’s protest intensifies.',
		'option_b'       => 'Give both parents a single bedtime directive in which neither adult changes the limit or stays in the room to rescue the child when protest escalates throughout the bedtime routine.',
		'option_c'       => 'Prescribe a brief scheduled protest period before the normal bedtime routine and instruct the parents to end the period at the agreed time.',
		'option_d'       => 'Reframe the protest as a way of organizing parental involvement and have the parents observe when their disagreement strengthens the bedtime struggle.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-088',
		'question_text'  => 'A 28-year-old client in individual therapy has improved substantially in managing social anxiety symptoms but continues to withdraw during conversations, overexplain when uncertain, and interpret neutral feedback as rejection. The client wants live practice with peers, can tolerate direct feedback, and has no acute instability. The therapist is considering a group referral. Which group is the best fit for this treatment need?',
		'option_a'       => 'An open drop-in support group for adults with life stressors that emphasizes mutual encouragement and flexible attendance.',
		'option_b'       => 'A closed interpersonal-process group for adults with similar relationship difficulties that uses direct here-and-now feedback and stable membership.',
		'option_c'       => 'A large psychoeducation group for anxiety that teaches coping concepts through lectures, structured worksheets, and limited interaction among members.',
		'option_d'       => 'A short-term skills group for social confidence that practices scripted conversations in rotating pairs with minimal process discussion.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-089',
		'question_text'  => 'A twelve-session agency program will end as scheduled. The client has made meaningful progress but continues to have treatment needs that cannot be completed within the remaining sessions. Which plan is BEST?',
		'option_a'       => 'Use remaining sessions to process the ending; review gains plus treatment reactions; provide referrals plus reentry information at the final appointment.',
		'option_b'       => 'Continue current goals through session twelve; summarize progress plus unfinished needs; initiate transfer after the program ends.',
		'option_c'       => 'Plan remaining sessions for closure; identify unfinished needs plus priorities; arrange continuity before the final visit now.',
		'option_d'       => 'Introduce achievable long-term goals; use progress data to prioritize them; seek continuation only if goals remain unfinished.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-090',
		'question_text'  => 'A bisexual client is open with supportive friends but conceals sexual orientation from family members because the client expects rejection and currently depends on the family for housing. The client reports mixed relief and distress about selective disclosure. What should the therapist assess NEXT?',
		'option_a'       => 'Explore disclosure goals, family dependence, housing safety, peer support, minority stress, and the effects of selective disclosure on the client\'s current functioning.',
		'option_b'       => 'Explore internalized stigma, anxiety about rejection, family attitudes, prior disclosure experiences, and whether concealment itself is increasing the client\'s distress.',
		'option_c'       => 'Explore peer support, identity affirmation, community belonging, coping resources, and whether those supports reduce the impact of family nonacceptance.',
		'option_d'       => 'Explore alternative housing, financial independence, family conflict history, practical consequences of disclosure, and the client\'s readiness to change the current arrangement.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-091',
		'question_text'  => 'A client reports periods of stimulant use that overlap with episodes of irritability, increased energy, and reduced sleep. The client also remembers having some mood symptoms during periods of nonuse. What should the therapist do NEXT during the clinical evaluation?',
		'option_a'       => 'Map mood symptoms to psychosocial stressors, sleep changes, relationship conflict, prior treatment periods, and whether similar episodes occurred before stimulant use began.',
		'option_b'       => 'Map stimulant dose and frequency, intoxication and withdrawal periods, sleep disruption, work impairment, and behavioral changes associated with heavier use.',
		'option_c'       => 'Map mood symptoms across stimulant use, withdrawal, and nonuse, noting whether episodes persist independently of stimulant exposure.',
		'option_d'       => 'Map prior mood episodes, family psychiatric history, medication exposure, longer abstinent periods, and evidence of mood changes occurring independently of stimulant use.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-092',
		'question_text'  => 'A client asks the therapist to use social-media direct messages for routine therapy communication because the client finds the platform easier than the practice\'s usual communication channels. The client understands that the platform is not controlled by the therapist. What is the therapist\'s BEST response?',
		'option_a'       => 'Use direct messages for scheduling, brief clinical questions, and urgent-routing instructions; document the client’s preference, privacy limits, and restrictions on highly sensitive content.',
		'option_b'       => 'Use direct messages only when initiated by the client, keep responses brief, document clinically relevant exchanges in the record, and review response-time expectations and privacy limits.',
		'option_c'       => 'Review the platform\'s privacy and security limits together with response expectations, boundary risks, and record obligations; then establish the appropriate clinical channel and define whether social-media messaging will be used.',
		'option_d'       => 'Disable direct messaging for clients, document the practice\'s communication policy, require the designated secure channel for clinical contact, and explain how urgent and routine messages should be handled through the clinically appropriate practice channel.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-093',
		'question_text'  => 'A group practice website advertises an LMFT as a "certified trauma specialist" even though the therapist has completed several trauma workshops but has never earned the certification named on the website. The therapist discovers the description after a new client says that credential was the reason for choosing the therapist. What should the therapist do?',
		'option_a'       => 'Correct the inaccurate credential representation promptly, clarify the therapist\'s actual qualifications and training with the client, including the scope of completed trauma workshops, address the client\'s reliance on the claim, and determine whether the client still wants to continue treatment based on accurate information.',
		'option_b'       => 'Keep the description temporarily while the therapist applies for the certification, tell the client that the therapist has substantial trauma training, document that clarification, and remove the claim if certification is not obtained.',
		'option_c'       => 'Ask the practice to replace "certified" with "trauma-focused," explain the therapist\'s workshop training and current competence to the client, document the discussion, and continue treatment if the client chooses to remain.',
		'option_d'       => 'Remove the specialty description from current and future professional advertising materials, notify the practice manager of the error, review every public listing for the same claim, correct any repeated credential language, verify the corrections, document the advertising remediation before the next session, and schedule a broader practice review of credential language across all clinician profiles.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-094',
		'question_text'  => 'Insurance coverage ends unexpectedly. The client’s recent depressive crisis has stabilized, and no acute danger is present, but relapse vulnerability and ongoing treatment needs remain. Which plan is MOST appropriate?',
		'option_a'       => 'Review relapse warning signs, crisis contacts, and referrals before coverage ends, then ask the client to arrange follow-up independently and document the referral information provided.',
		'option_b'       => 'Create a brief bridge plan, review relapse and safety needs, and coordinate transfer before the coverage period ends.',
		'option_c'       => 'Seek temporary authorization to continue treatment and postpone transfer planning until the payer decides whether additional visits are approved.',
		'option_d'       => 'Arrange higher-level psychiatric reassessment and continue treatment until relapse risk has fully resolved before ending care.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-095',
		'question_text'  => 'During a session, a client begins to cry while describing loneliness and immediately says, “This is ridiculous. I hate that I’m being so weak in front of you.” The client looks away and tries to stop the tears. The therapist is using a client-centered approach. Which response should the therapist make?',
		'option_a'       => 'Reflect the client’s judgment of the tears and invite attention to how loneliness, shame, and self-criticism are experienced in the moment.',
		'option_b'       => 'Offer empathic reassurance about the tears and ask what makes emotional expression feel unacceptable within the therapy relationship.',
		'option_c'       => 'Stay genuinely present with the loneliness and shame, reflect the client’s experience, and allow the tears to unfold without directing change.',
		'option_d'       => 'Ask what kind of therapist response would feel most helpful and follow the client’s preference for silence, reflection, or continued exploration.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-096',
		'question_text'  => 'A client trying to end a relationship discovers that the partner secretly installed location-tracking software, accesses private online accounts, threatens to distribute intimate photographs, and repeatedly appears at locations the client has not disclosed. What should the therapist do NEXT?',
		'option_a'       => 'Assess current safety privately, review technology risks, and support a direct boundary-setting conversation with a trusted person nearby.',
		'option_b'       => 'Assess current safety privately, review technology risks, and strengthen account security with victim-support follow-up.',
		'option_c'       => 'Assess current safety privately, review technology risks, and develop a technology-aware safety plan with specialized abuse services.',
		'option_d'       => 'Assess current safety privately, review technology risks, and explore mediated communication with trusted support if the client prefers contact.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-097',
		'question_text'  => 'Parents bring their 10-year-old to therapy because of escalating behavior problems. During the intake, the parents disagree sharply about discipline, frequently interrupt one another, and describe the child\'s behavior differently. The child\'s behavior also changes noticeably while the parents argue. What should the therapist do FIRST when determining the treatment unit?',
		'option_a'       => 'Begin with individual child assessment, adding caregiver sessions if symptoms appear linked to parenting or family conflict.',
		'option_b'       => 'Begin with joint child-caregiver assessment of symptoms and interaction, then select the treatment unit from those findings.',
		'option_c'       => 'Begin with caregiver sessions to assess discipline differences and conflict, then decide whether direct child participation is needed.',
		'option_d'       => 'Begin with separate child and caregiver interviews to clarify perspectives, then choose individual, parent-focused, or family treatment.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-098',
		'question_text'  => 'A client reports that several romantic partners have complained that the client becomes distant whenever they request greater emotional closeness. The client says, “I just need space when people start expecting too much.” What should the therapist assess NEXT?',
		'option_a'       => 'Compare several close relationships for what precedes withdrawal, how requests for closeness are interpreted, and what typically follows the distancing across relationships.',
		'option_b'       => 'Assess the current partner’s requests, conflict style, expectations for intimacy, and whether the client’s withdrawal is proportionate to relationship pressure.',
		'option_c'       => 'Review childhood caregiver relationships, prior losses, attachment experiences, and whether distancing from closeness appears connected with earlier relational patterns.',
		'option_d'       => 'Assess social anxiety, avoidant traits, emotion regulation, and fear of dependence to determine whether a stable individual pattern explains the behavior.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-099',
		'question_text'  => 'A 23-year-old has, since early childhood, had difficulty with reciprocal conversation, integrating eye contact and gestures with speech, and adjusting behavior to develop and maintain age-appropriate relationships. Caregiver history also describes highly restricted interests, rigid routines, and marked distress when routines changed. These patterns have occurred across settings. Fear of negative evaluation emerged only during adolescence after repeated peer rejection. Which diagnosis is MOST supported?',
		'option_a'       => 'Social anxiety disorder',
		'option_b'       => 'Autism spectrum disorder',
		'option_c'       => 'Attention-deficit/hyperactivity disorder',
		'option_d'       => 'Schizoid personality disorder',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-100',
		'question_text'  => 'A client has repeated periods of depressed mood, anhedonia, fatigue, and sleep disturbance during episodes of heavy alcohol use and withdrawal. The depressive syndrome resolves during sustained periods without alcohol exposure. There is no history of an independent depressive episode before the alcohol pattern or during extended abstinence. Which diagnosis is MOST supported?',
		'option_a'       => 'Major depressive disorder',
		'option_b'       => 'Persistent depressive disorder',
		'option_c'       => 'Adjustment disorder with depressed mood',
		'option_d'       => 'Substance/medication-induced depressive disorder',
		'correct_option' => 'x',
		'explanation'    => '',
	),
);
