<?php
/**
 * LMFT California Clinical — Comprehensive Simulation Form A items 1–25 (PROMPT 01).
 * Learner-facing stems and choices only. Answer keys deferred to admin merge.
 *
 * @package CTA_LMS
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-001',
		'question_text'  => 'A transgender man reports for ten months a marked incongruence between his experienced gender and sex characteristics, intense distress about his chest and menstrual characteristics, and a persistent desire to be rid of those characteristics. The distress remains significant in affirming environments and interferes with work and social functioning. Which diagnosis is MOST supported?',
		'option_a'       => 'Gender dysphoria',
		'option_b'       => 'Adjustment disorder',
		'option_c'       => 'Major depressive disorder',
		'option_d'       => 'Body dysmorphic disorder',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-002',
		'question_text'  => 'A client lost a job two months ago and reports understandable distress about finances. The client has maintained a daily routine, continues exercising, remains connected with friends and family, and has begun exploring new employment options. Which assessment would be MOST useful?',
		'option_a'       => 'Assess current distress, sleep, concentration, financial worry, and whether symptoms are beginning to impair work-seeking or self-care.',
		'option_b'       => 'Assess social support, frequency of contact, practical assistance, and whether relationships remain available when the client needs help.',
		'option_c'       => 'Assess coping behaviors, job-search activity, exercise, daily structure, and whether routines are sustaining or depleting the client’s functioning.',
		'option_d'       => 'Assess how routines, support, problem-solving, and personal strengths are helping maintain functioning while identifying areas that remain vulnerable over time.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-003',
		'question_text'  => 'A couple requests therapy for “communication problems.” One partner describes repeated arguments about spending, while the other says the more important problem is feeling emotionally disconnected even when the couple is not arguing. What should the therapist do NEXT?',
		'option_a'       => 'Ask each partner for a recent interaction, what it meant, and what change would make therapy useful.',
		'option_b'       => 'Ask each partner about conflict frequency, escalation patterns, and which disagreements feel most damaging to the relationship.',
		'option_c'       => 'Ask each partner about family-of-origin communication, learned conflict roles, and similarities between past and current interactions.',
		'option_d'       => 'Ask each partner about current stress, mood, and coping to determine how individual factors affect communication.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-004',
		'question_text'  => 'An 8-year-old witnessed serious violence at school two weeks ago. Since then, the child has nightmares, asks repeatedly whether school is safe, becomes distressed when separated from a caregiver, and has difficulty returning to normal bedtime and school routines. The caregiver is calm and supportive. Which response is BEST?',
		'option_a'       => 'Use age-appropriate coping support, involve the caregiver in planning, and coordinate gradual school reentry while monitoring symptoms.',
		'option_b'       => 'Use age-appropriate reassurance and coping, involve the caregiver in support, and restore predictable routines while monitoring symptoms closely.',
		'option_c'       => 'Use structured therapeutic play and coping, involve the caregiver in support, and coordinate school planning around trauma reminders during recovery.',
		'option_d'       => 'Use clear behavioral expectations and coping, involve the caregiver in support, and restore school routines while monitoring regression.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-005',
		'question_text'  => 'A 32-year-old client has had almost no direct contact with the father for three years after repeated family conflict. The client still receives frequent updates through a sibling, asks the sibling to pass messages back to the father, and becomes highly anxious whenever direct contact is considered. The therapist is using a multigenerational family systems approach. Which intervention should the therapist use?',
		'option_a'       => 'Map recurring cutoff and triangulation patterns, identify when anxiety pulls the sibling into communication, and coach the client to observe that process.',
		'option_b'       => 'Coach the client to rehearse an I-position in session, practice regulating anxiety, and prepare for direct contact with the father.',
		'option_c'       => 'Map the sibling-mediated communication pattern, coach observation of family-system reactions, clarify how cutoff is maintained across relationships, and compare what changes when messages no longer pass through the sibling.',
		'option_d'       => 'Coach the client to state an I-position directly to the father, maintain self-definition during the exchange, and end the sibling’s intermediary role in their relationship.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-006',
		'question_text'  => 'A client with chronic pain is receiving psychotherapy from the LMFT while also seeing a psychiatrist and a pain specialist. Current releases permit care coordination. The psychiatrist has encouraged greater behavioral activation, while the pain specialist recently advised reducing activity during a flare. The client is confused by the apparently conflicting recommendations and has stopped following either plan. Which coordination step should the therapist take?',
		'option_a'       => 'Coordinate with the psychiatrist and pain specialist separately, compare their explanations, review how each applies to the current flare, and plan an activity approach for the client from both recommendations.',
		'option_b'       => 'Coordinate with the psychiatrist and pain specialist by obtaining written activity parameters, then select the recommendation that best fits the client’s current flare.',
		'option_c'       => 'Send both providers a shared case summary and integrate their separate written recommendations into psychotherapy.',
		'option_d'       => 'Convene both providers for a joint reconciliation of the activity recommendations and a shared set of treatment parameters.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-007',
		'question_text'  => 'An older adult reports gradually worsening difficulty managing finances and keeping track of complex appointments. Family members describe a similar decline, while a recent general medical evaluation did not identify an acute explanation. Which referral is MOST appropriate?',
		'option_a'       => 'Refer for psychiatric evaluation to determine whether an emerging mood or psychotic disorder is contributing to the cognitive complaints.',
		'option_b'       => 'Refer for specialized psychological or neurocognitive testing to clarify the pattern, severity, and functional significance of the client’s cognitive difficulties.',
		'option_c'       => 'Repeat brief cognitive screening over several sessions and refer only if the scores show continued decline across time.',
		'option_d'       => 'Refer back to primary care for another general medical evaluation before considering specialized cognitive or psychological testing.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-008',
		'question_text'  => 'A clinic is designing a ten-week closed psychotherapy group for current caregivers of relatives with moderate-to-advanced dementia. Participants must be stable enough for outpatient group treatment; acute grief or crisis needs are handled separately. The goals are to reduce isolation, strengthen coping, practice communication and boundary strategies, and build practical caregiving skills. Which group framework is MOST appropriate?',
		'option_a'       => 'Use an open monthly support group for varied progressive-illness caregivers; offer rotating topics and peer discussion; repeat orientation for new members.',
		'option_b'       => 'Use a closed ten-week dementia-caregiver education group; provide fixed lessons and home practice; screen for caregiving status and overall clinical readiness.',
		'option_c'       => 'Use a closed ten-week grief group for current and bereaved caregivers; provide emotional processing and peer support; screen for general stability.',
		'option_d'       => 'Use a closed ten-week therapy group; combine peer support with practical skills; screen current dementia caregivers for clinical fit and stability.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-009',
		'question_text'  => 'During couples therapy, one partner repeatedly presses for immediate discussion whenever conflict occurs. The other becomes quieter, gives shorter responses, and eventually leaves the room. The first partner then follows and increases efforts to obtain a response. What should the therapist assess NEXT?',
		'option_a'       => 'Determine which partner usually initiates conflict, what topics trigger arguments, and whether one person’s behavior reliably predicts escalation.',
		'option_b'       => 'Explore childhood relationship models, attachment expectations, prior partners, conflict responses, repair patterns, and whether similar dynamics appeared in earlier relationships.',
		'option_c'       => 'Assess each partner’s emotion regulation, conflict tolerance, communication skills, and whether individual vulnerabilities contribute to the recurring relationship pattern over time.',
		'option_d'       => 'Track a recent disagreement step by step, including each partner’s response, interpretation, escalation, and effect on the other partner.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-010',
		'question_text'  => 'An 11-year-old with ADHD is medically stable and receives medication management from a pediatrician. Homework often turns into a 90-minute conflict: the parent gives repeated verbal reminders, the child becomes frustrated and leaves the table, and both end the evening angry. Which intervention should the therapist use?',
		'option_a'       => 'Divide assignments into child-chosen order, use a timer for sustained work, and provide one parent prompt when attention drifts.',
		'option_b'       => 'Move homework to a low-distraction space, set one work interval, and have the parent give feedback at the end of the interval.',
		'option_c'       => 'Break homework into short work intervals with a visible sequence, and have the parent use one neutral cue instead of repeated reminders.',
		'option_d'       => 'Use a point system for completed assignments, let the child record each finished task, and provide reinforcement after the homework period.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-011',
		'question_text'  => 'Acute danger has been stabilized, but a client continues to experience recurrent self-injury urges, rapid emotional escalation, impulsive behavior, and treatment-interfering absences. Which treatment plan is MOST consistent with dialectical behavior therapy?',
		'option_a'       => 'Sequence trauma memories during exposure, teach grounding strategies, and track symptoms to regulate processing intensity.',
		'option_b'       => 'Rank priority behaviors, analyze chains leading to self-injury/absence, and teach regulation plus crisis-survival skills.',
		'option_c'       => 'Identify rigid demands/global self-ratings, dispute them directly, and rehearse flexible beliefs during emotional activation.',
		'option_d'       => 'Explore relational expectations/unconscious conflict, examine the therapy relationship, and interpret the function of self-injury.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-012',
		'question_text'  => 'A client has a history of psychiatric hospitalization, several medication changes, and multiple periods of outpatient therapy. The client now reports symptoms similar to those experienced several years ago. Which information would be MOST useful for understanding the mental-health history?',
		'option_a'       => 'Organize prior diagnoses, hospital admissions, treating clinicians, medications, and levels of care to compare earlier treatment periods.',
		'option_b'       => 'Reconstruct symptom onset, severity, treatment changes, response, remission or relapse, and functional change across the prior episodes.',
		'option_c'       => 'Review hospitalization triggers, discharge plans, post-discharge adherence, support availability, and whether baseline functioning returned afterward.',
		'option_d'       => 'Review medication trials, side effects, adherence, reasons for stopping, and which symptoms improved or persisted during each treatment period.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-013',
		'question_text'  => 'A 79-year-old client who depends on an adult caregiver arrives with untreated medical needs and reports frequently going without food and prescribed medication. The client also states that the caregiver has been withdrawing money from the client\'s account for personal purchases. The client says, “Please don\'t tell anyone until I can prove exactly what happened.” What should the therapist do FIRST?',
		'option_a'       => 'Address immediate safety and health needs, obtain corroborating financial and medical records, and report if additional evidence supports abuse or neglect.',
		'option_b'       => 'Address immediate safety and health needs, clarify the concerns directly with the caregiver, and report if the explanation does not resolve the suspicion.',
		'option_c'       => 'Address immediate safety and health needs, make the required protective report promptly based on reasonable suspicion, and coordinate appropriate client support.',
		'option_d'       => 'Address immediate safety and health needs, arrange alternative care and practical resources, and allow the client to decide whether authorities are contacted.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-014',
		'question_text'  => 'A client states an intention to die tonight, describes a specific suicide plan, has immediate access to the intended means, has already made preparations, and says, “I don\'t think I can stop myself once I leave here.” What should the therapist do FIRST?',
		'option_a'       => 'Maintain direct observation, initiate secure psychiatric transfer, and hand off the current suicide-risk findings directly to receiving staff.',
		'option_b'       => 'Maintain direct observation, have a support person remove the identified means, and transport the client to same-day psychiatric urgent care.',
		'option_c'       => 'Maintain direct observation, obtain emergency psychiatric consultation, and decide disposition after a fuller suicide-risk assessment.',
		'option_d'       => 'Maintain direct observation, complete crisis safety planning, and discharge with continuous support to next-day psychiatric care.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-015',
		'question_text'  => 'A therapist has been providing conjoint therapy to a married couple whose stated treatment purpose is reconciliation. One partner privately asks the therapist to stop couple sessions and continue seeing only that partner for individual therapy. The therapist has not yet discussed this proposed change with the other partner. What should the therapist do FIRST?',
		'option_a'       => 'In a meeting with the requesting partner, explore treatment goals, client-role concerns, and privacy issues before discussing any treatment change with both partners.',
		'option_b'       => 'Pause conjoint treatment and meet separately with both partners to review client roles, informed consent, confidentiality expectations, records concerns, and whether either treatment structure remains clinically workable.',
		'option_c'       => 'With both partners, review treatment purpose, client roles, privacy expectations, records implications, future communication expectations, and the informed agreement governing the proposed treatment structure.',
		'option_d'       => 'Close conjoint treatment, review client-role and privacy implications with both partners, and consider later individual treatment only after a planned transition.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-016',
		'question_text'  => 'A client communicates online with dozens of people each week but reports, “When something actually goes wrong, I don’t know who I could call.” The client denies feeling socially isolated because “I talk to people constantly.” Which assessment is MOST appropriate?',
		'option_a'       => 'Count regular online and in-person contacts, frequency of interaction, network size, and whether the client has enough social opportunities each week.',
		'option_b'       => 'Assess which relationships provide emotional support, practical help, reciprocity, dependable contact, and connection when the client experiences stress.',
		'option_c'       => 'Assess loneliness, social anxiety, avoidance, comfort with in-person contact, and whether online interaction substitutes for relationships the client actually wants.',
		'option_d'       => 'Identify the client’s closest relationships, perceived intimacy, shared history, and whether those connections remain available when practical or emotional help is needed.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-017',
		'question_text'  => 'In the fourth session of an interpersonal therapy group, two members disagree about one member repeatedly interrupting the other. Their voices rise slightly, but neither becomes threatening, and the group remains physically and emotionally safe. Several other members become quiet and look away. Which intervention should the group therapist use next?',
		'option_a'       => 'Invite the group to restate the disagreement as specific requests, use the exchange to identify what helps participation remain workable, and observe members’ responses.',
		'option_b'       => 'Invite the group to examine the conflict as it unfolds, process its effect on participation, and connect the current interaction to the group’s relational work.',
		'option_c'       => 'Invite the two members to connect their reactions to prior interpersonal patterns and ask the group what similar patterns they recognize.',
		'option_d'       => 'Invite the group to repair the current tension, practice one shared strategy for disagreement, and generate additional responses for future sessions.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-018',
		'question_text'  => 'A client spends hours reviewing routine work before sending it to colleagues. The client predicts, “If I do not check everything several times, I will miss something obvious and everyone will think I am incompetent.” Repeated checking reduces anxiety briefly but is causing missed deadlines. The therapist is using CBT. Which intervention most directly tests the maintaining belief and behavior?',
		'option_a'       => 'Test the feared mistake prediction while eliminating repeated checking during one planned work task.',
		'option_b'       => 'Record automatic thoughts before work tasks and generate balanced alternatives after each episode of repeated checking.',
		'option_c'       => 'Create a graded hierarchy of increasingly difficult work tasks and practice each level while keeping checking available initially.',
		'option_d'       => 'Review evidence for and against being incompetent and use coping statements whenever uncertainty triggers the urge to check.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-019',
		'question_text'  => 'Six weeks after giving birth, a client reports that for the past four weeks she has experienced depressed mood nearly every day, marked loss of interest, feelings of worthlessness, impaired concentration, psychomotor slowing, decreased appetite, and insomnia even when the infant is asleep. The symptoms substantially interfere with functioning. There is no history of mania or hypomania. Which diagnosis is MOST supported?',
		'option_a'       => 'Adjustment disorder with depressed mood',
		'option_b'       => 'Major depressive disorder',
		'option_c'       => 'Persistent depressive disorder',
		'option_d'       => 'Bipolar II disorder',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-020',
		'question_text'  => 'A therapist strongly believes an adult client should leave a long-term relationship after repeated infidelity. The client has clearly stated that the current treatment goal is to decide what kind of relationship the client wants, not to be persuaded toward separation. The therapist notices becoming increasingly directive about ending the relationship. What should the therapist do?',
		'option_a'       => 'Use a neutral decisional-balance exercise, document the client\'s clinical treatment goals, compare staying and leaving, and keep recommendations limited to concerns the client identifies as relevant.',
		'option_b'       => 'Discuss the value conflict openly, document the client\'s clinical treatment goals, and offer referral while continuing care long enough to assess whether the therapist can remain neutral.',
		'option_c'       => 'Identify the therapist\'s value interference and return treatment to the client\'s stated goals, using consultation as needed for clinically neutral recommendations, document the treatment direction, and monitor whether later guidance remains aligned with the client\'s values.',
		'option_d'       => 'Explore safety, trust, and relationship consequences under the client\'s clinical treatment goals, document the preferred direction, and avoid recommending either staying or leaving unless new concerns arise.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-021',
		'question_text'  => 'For eight months, a 24-year-old has shown progressive social withdrawal, loss of motivation, and substantial decline in work functioning. During the most recent two months, the client has also experienced voices commenting on behavior, fixed persecutory beliefs, and disorganized speech. There have been no sustained major mood episodes, and substance and medical evaluation do not explain the disturbance. Which diagnosis is MOST supported?',
		'option_a'       => 'Schizoaffective disorder, depressive type',
		'option_b'       => 'Major depressive disorder with psychotic features',
		'option_c'       => 'Schizophrenia',
		'option_d'       => 'Schizophreniform disorder',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-022',
		'question_text'  => 'A graduate student seeks therapy for chronic procrastination. Most weeks, assignments are delayed until the deadline. The client reports one recent week when all work was completed early after studying at the library with a friend and dividing tasks into short blocks. The client says, “I don’t know why that week was different.” The therapist is using a solution-oriented approach. Which intervention should the therapist use next?',
		'option_a'       => 'Examine the successful week in detail, identify what the client did differently, and choose one element to repeat before the next session.',
		'option_b'       => 'Use the miracle question to describe a day with manageable procrastination, then identify one observable sign that the preferred future has begun.',
		'option_c'       => 'Use coping questions to identify what has kept deadlines from being missed entirely, then build on one existing strength during the next assignment.',
		'option_d'       => 'Offer a compliment for the early completion and use a scaling question to identify the next realistic increase in follow-through.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-023',
		'question_text'  => 'A client attends therapy after an employer suggested using the company\'s employee-assistance program. During the first meeting, the client gives brief answers and says, “HR thinks I have an anger problem. I don\'t know why I\'m here.” Which response would BEST support initial therapeutic engagement?',
		'option_a'       => 'Review the EAP purpose, confidentiality limits, and reporting expectations, then ask how the client understands the employer’s concern.',
		'option_b'       => 'Acknowledge the client’s reluctance, ask what feels inaccurate about the referral, and clarify what the client does not want from therapy.',
		'option_c'       => 'Acknowledge the referral and skepticism, invite the client’s view of the concern, and identify any personally useful outcome from meeting.',
		'option_d'       => 'Clarify that participation can be explored without accepting the employer’s view, then ask whether the client prefers discussing the incident or current stress first.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-024',
		'question_text'  => 'A client with chronic anxiety repeatedly texts a partner for reassurance whenever the partner is away. The client feels brief relief after each response, but the partner has become increasingly irritated and says the constant checking is straining the relationship. The client wants to change the pattern. Which intervention should the therapist use?',
		'option_a'       => 'Set one daily check-in and have the partner limit reassurance to that agreed time.',
		'option_b'       => 'Explore separation fears and have the partner validate distress without repeatedly confirming that everything is okay.',
		'option_c'       => 'Practice tolerating uncertainty by briefly delaying reassurance-seeking during separations while the partner responds consistently without repeated confirmation.',
		'option_d'       => 'Track anxious predictions and partner responses for one week to identify the situations that most strongly trigger checking.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-025',
		'question_text'  => 'A 16-year-old\'s close friend died suddenly. The adolescent reports guilt about not answering the friend\'s final text message, poor sleep, difficulty attending school, and feeling "numb." The adolescent denies current suicidal intent or plan. A supportive caregiver is available. What should the therapist prioritize?',
		'option_a'       => 'Assess grief plus suicide risk, involve the caregiver in support, and establish a structured school-attendance plan.',
		'option_b'       => 'Assess grief plus suicide risk, involve the caregiver in support, and arrange an urgent crisis evaluation because of guilt.',
		'option_c'       => 'Assess grief plus suicide risk, involve the caregiver in support, and use structured retelling to address guilt.',
		'option_d'       => 'Assess grief plus suicide risk, involve caregiver support, and provide age-appropriate grief care with functional restoration.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
);
