<?php
/**
 * LMFT California Clinical — Comprehensive Simulation Form A items 26–50 (PROMPT 02).
 * Learner-facing stems and choices only. Answer keys deferred to admin merge.
 *
 * @package CTA_LMS
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-026',
		'question_text'  => 'A client repeatedly states, “I’m fine and not particularly upset,” while speaking quietly, appearing tearful, and showing a constricted range of affect. What should the therapist do NEXT?',
		'option_a'       => 'Assess depressive symptoms, functioning, recent change, and whether the presentation resembles past mood episodes.',
		'option_b'       => 'Clarify the client’s reported mood, observed affect, reactivity, and whether the discrepancy changes across topics.',
		'option_c'       => 'Explore recent losses, conflict, stressors, and emotional contexts associated with the client’s visible tearfulness.',
		'option_d'       => 'Assess suicidal thoughts, hopelessness, impulsivity, available supports, and whether risk indicators exceed the client’s report.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-027',
		'question_text'  => 'An adult client discloses a sexual assault that occurred two days ago. The client is medically stable during the session, feels overwhelmed, and says, “I don\'t know if I want an exam or to report it. I just want to understand my options.” What should the therapist do NEXT?',
		'option_a'       => 'Assess immediate safety and medical needs, explain care and advocacy options, and recommend prompt forensic examination while making clear that it remains optional.',
		'option_b'       => 'Assess immediate safety and medical needs, explain reporting and advocacy options, and recommend police contact while making clear the client may decline.',
		'option_c'       => 'Assess immediate safety and medical needs, explain available care and advocacy options, and preserve informed client choice about next steps without directing the decision.',
		'option_d'       => 'Assess immediate safety and medical needs, provide stabilization and support, and invite the client to defer medical-forensic choices until the next appointment.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-028',
		'question_text'  => 'An older couple reports that sexual intimacy has changed substantially during the past year. Both partners have experienced health changes, and they disagree about what sexual closeness “should look like at our age.” Which assessment is BEST?',
		'option_a'       => 'Assess health changes, medications, pain, energy, sleep, and whether physical limitations have altered sexual activity or comfort.',
		'option_b'       => 'Assess relationship satisfaction, initiation patterns, closeness, conflict, and whether intimacy concerns occur during relational tension.',
		'option_c'       => 'Review lifespan sexual history, prior changes with aging, cultural expectations, and how each partner’s beliefs about sexuality influence current distress.',
		'option_d'       => 'Explore health, medications, expectations, sexual functioning across the lifespan, relationship dynamics, and the meaning each partner gives the change.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-029',
		'question_text'  => 'A therapist is providing ongoing family therapy to a mother and her two adult children. The family agrees that the mother\'s adult sister should begin attending regularly because she is directly involved in the conflict being treated. The sister has never participated in therapy. What should the therapist do BEFORE beginning substantive work with her in the sessions?',
		'option_a'       => 'Before substantive participation, clarify whether the sister is a client or other participant, review the treatment purpose and confidentiality expectations with everyone involved, and obtain informed agreement about her role.',
		'option_b'       => 'Invite the sister to the next family session, review the existing treatment purpose and confidentiality expectations at the start, and decide afterward whether ongoing participation is appropriate.',
		'option_c'       => 'Meet with the sister alone before the family session, review the treatment purpose and confidentiality expectations, gather her perspective, and decide what information may later enter family work.',
		'option_d'       => 'Add the sister as a regular participant, review the family\'s treatment purpose and confidentiality expectations, document the proposed client role and consent expectations, and revise the agreement after observing sessions.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-030',
		'question_text'  => 'A remarried couple has been living together with the mother’s 13-year-old son for four months. The stepfather is eager to function as a parent and often corrects the adolescent’s behavior. The adolescent responds, “You are not my dad,” and later tells the mother that accepting the stepfather feels disloyal to the biological father. Which intervention should the therapist use next?',
		'option_a'       => 'Clarify household rules with both adults, plan one consistent response to limit challenges, and reinforce the mother and stepfather’s shared expectations.',
		'option_b'       => 'Validate loyalty concerns, protect the mother’s primary discipline role, and build the stepfather’s connection through shared activities and low-conflict contact.',
		'option_c'       => 'Discuss loyalty concerns with the family, clarify the stepfather’s current role, and negotiate a specific agreement about household authority.',
		'option_d'       => 'Normalize loyalty conflicts, protect existing parent-child bonds, and expand the stepfather’s authority gradually as trust and role clarity develop.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-031',
		'question_text'  => 'A client recently diagnosed with multiple sclerosis has stopped attending a weekly music group because fatigue and visible balance problems feel embarrassing. The client says, “I am still me, but I do not know how to be around people when my body is unpredictable.” Medical care is established and the client wants psychotherapy to focus on adjustment. Which intervention should the therapist use?',
		'option_a'       => 'Explore social judgment fears, plan brief returns to the music group, and compare feared reactions with actual responses during those visits.',
		'option_b'       => 'Explore illness-related grief and practice coping responses for social situations where physical changes feel especially visible.',
		'option_c'       => 'Explore illness-related identity and valued roles, select needed accommodations, and plan a paced return to the music group with selected accommodations.',
		'option_d'       => 'Review fatigue and balance patterns, select practical accommodations, and plan attendance during periods when the client has greater physical capacity.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-032',
		'question_text'  => 'A client receiving treatment for panic-related avoidance wants to commute independently and return to full workplace participation. The formulation identifies both panic symptoms and escape from feared transit situations as barriers to those goals. Which outcome-measurement plan BEST matches the treatment goals and formulation?',
		'option_a'       => 'Track panic intensity and attack frequency; record medication reliance and sleep disruption; review overall distress at scheduled intervals.',
		'option_b'       => 'Track work attendance and commuting confidence; record coping-skill use and therapist ratings; review distress during attempted travel weekly.',
		'option_c'       => 'Track full-commute completion and avoided routes; record reassurance requests and work attendance; review completion of planned travel practices.',
		'option_d'       => 'Track panic symptoms and independent commute completion; record time in feared transit situations; review full-workday attendance each week.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-033',
		'question_text'  => 'A long-term client reacts to a planned ending with grief and repeatedly states that the therapist is “abandoning” the client. The client has made meaningful progress, and no new clinical need supports indefinite treatment. What should the therapist do NEXT?',
		'option_a'       => 'Maintain the agreed termination timeline; validate grief plus ending distress; review support/reentry options during remaining sessions.',
		'option_b'       => 'Extend treatment temporarily; process abandonment fears plus relational themes; resume termination after distress substantially decreases.',
		'option_c'       => 'Address the reaction during closure; offer referrals for further relational work; reinforce that continued treatment is not indicated.',
		'option_d'       => 'Explore the ending’s relational meaning; maintain appropriate boundaries plus goals; alter timing only for a defined clinical purpose.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-034',
		'question_text'  => 'During an intake, a client reports that previous couples therapy ended because the client felt the therapist consistently “took my partner\'s side.” Which response would make the BEST clinical use of this information?',
		'option_a'       => 'Review examples from prior therapy, what was discussed, and how the client interpreted the therapist’s responses during those sessions.',
		'option_b'       => 'Review what was helpful before the rupture, unfinished goals, and which prior methods the client would want repeated now.',
		'option_c'       => 'Explore what felt one-sided and how that experience affected trust and willingness to raise similar concerns now.',
		'option_d'       => 'Explain how conjoint therapists manage competing perspectives and ask how the client wants future alliance concerns addressed.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-035',
		'question_text'  => 'Two months after an unexpected job demotion, a client reports tearfulness, increased worry about work, difficulty sleeping, and reduced concentration. The symptoms interfere with work and the client\'s relationship. The client continues to enjoy usual activities, does not report pervasive worthlessness or depressed mood across contexts, and the worry remains centered on the demotion and its consequences. No qualifying traumatic event occurred. Which diagnosis is MOST supported?',
		'option_a'       => 'Major depressive disorder because the symptoms reflect a pervasive depressive syndrome, broad impairment, and a course independent of the demotion.',
		'option_b'       => 'Generalized anxiety disorder because the worry extends across multiple domains beyond occupational stress.',
		'option_c'       => 'Posttraumatic stress disorder because the demotion functions as a qualifying traumatic event.',
		'option_d'       => 'Adjustment disorder with mixed anxiety and depressed mood because the symptoms remain tied to the demotion.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-036',
		'question_text'  => 'A 14-year-old repeatedly refuses household responsibilities and argues when limits are set. One caregiver usually follows through with an agreed consequence, while another often changes the consequence after a prolonged argument. The adolescent is much more likely to comply when expectations are brief and follow-through is predictable. Which intervention should the therapist use?',
		'option_a'       => 'Choose two observable target behaviors, set one shared caregiver response for each, and reinforce follow-through consistently across the week.',
		'option_b'       => 'Use collaborative problem solving after arguments, invite the teen to propose alternatives, and revise expectations when both sides agree.',
		'option_c'       => 'Teach caregivers emotion coaching during refusals, pause consequences until everyone is calm, and process the conflict later in family sessions.',
		'option_d'       => 'Increase the teen’s independence by allowing natural consequences for missed responsibilities, while caregivers monitor only behavior that affects safety.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-037',
		'question_text'  => 'A client angrily discusses a former coworker and identifies the person by name. The client says there will be a confrontation within the next day, describes what the client intends to do, has ready access to a weapon, and has recently begun driving past the former coworker\'s workplace. Which action is MOST appropriate?',
		'option_a'       => 'Maintain direct observation, arrange emergency psychiatric evaluation, and have a reliable support person secure the weapon.',
		'option_b'       => 'Maintain direct observation, complete a focused targeted-violence assessment, and decide on external action after clarifying prior violence.',
		'option_c'       => 'Maintain direct observation, create a strict no-contact plan, and transfer the client to same-day crisis follow-up.',
		'option_d'       => 'Maintain direct observation, initiate an emergency protective response, and transfer the known risk facts directly to responders.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-038',
		'question_text'  => 'A client reports new problems with sleep, energy, and concentration beginning shortly after a significant physical-health change and a medication adjustment. The client has no previous history of similar symptoms. Which assessment approach is BEST?',
		'option_a'       => 'Review depressive symptoms, prior mood episodes, family history, impairment, and whether the pattern resembles earlier psychiatric episodes.',
		'option_b'       => 'Review medication side effects, adherence, prescriber instructions, physical symptoms, and whether changes followed treatment adjustment.',
		'option_c'       => 'Obtain focused medical information about the health change, current treatment, relevant findings, and provider observations of symptom timing.',
		'option_d'       => 'Map the timing of medical and medication changes against physical, emotional, and cognitive symptoms and resulting functional effects.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-039',
		'question_text'  => 'A client has had several episodes of paranoia and auditory hallucinations during periods of heavy methamphetamine use. Each episode begins during or soon after heavy use and resolves completely after sustained abstinence. There is no history of psychosis during drug-free periods and no independent manic or major depressive episode associated with the psychosis. Which diagnosis is MOST supported?',
		'option_a'       => 'Schizophrenia',
		'option_b'       => 'Brief psychotic disorder',
		'option_c'       => 'Stimulant-induced psychotic disorder',
		'option_d'       => 'Bipolar I disorder with psychotic features',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-040',
		'question_text'  => 'Infertility-related stress has led a couple to describe themselves as “broken” and their relationship as a failure, despite evidence of persistence, mutual care, and shared values. Which treatment plan is MOST consistent with narrative therapy?',
		'option_a'       => 'Revise global failure appraisals, examine contradictory evidence, and test balanced beliefs through shared behavioral activities.',
		'option_b'       => 'Describe the preferred relationship future, identify exception-based patterns, and construct observable changes from demonstrated strengths.',
		'option_c'       => 'Externalize the shared problem story, identify unique outcomes, and develop an alternative relationship identity collaboratively.',
		'option_d'       => 'Clarify couple boundaries, identify stress-based alliances, and change interactions that maintain relational distress within therapy.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-041',
		'question_text'  => 'An adult begins therapy for difficulty maintaining emotional closeness in romantic relationships. During the third session, the client discloses a history of interpersonal trauma and says, “I’ve never really thought about whether that has anything to do with my relationships now.” What should the therapist do NEXT?',
		'option_a'       => 'Assess the trauma history, type and duration of exposure, developmental timing, prior disclosure, and whether the client received support after the events.',
		'option_b'       => 'Assess current trauma-related symptoms, triggers, relationship effects, functioning, and the client’s preferred pace for discussing the earlier experiences.',
		'option_c'       => 'Assess current intimacy patterns, expectations, communication, and whether relationship problems occur independently of trauma reminders.',
		'option_d'       => 'Assess mood, anxiety, dissociation, sleep, substance use, and whether another symptom pattern better accounts for the client’s current relationship difficulties.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-042',
		'question_text'  => 'A client states an intention to stop treatment because of dissatisfaction with its direction. Important goals remain incomplete, but no acute safety concern is present. What should the therapist do NEXT?',
		'option_a'       => 'Discuss the client’s dissatisfaction and unfinished goals, propose a two-session repair trial, and respect the client’s informed choice to leave if the trial is declined.',
		'option_b'       => 'Discuss the client’s dissatisfaction and unfinished goals, review reasonable alternatives and foreseeable effects of ending, and respect the client’s informed decision to leave.',
		'option_c'       => 'Discuss dissatisfaction and unfinished goals, coordinate transfer, and respect the client’s informed choice once transfer begins.',
		'option_d'       => 'Discuss the client’s dissatisfaction and unfinished goals, honor the client’s informed request to end, and provide referrals and reentry information after termination.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-043',
		'question_text'  => 'A family reports intense conflict that several members describe as “the same fight our parents used to have.” Different relatives frequently form temporary alliances during disagreements. What should the therapist assess NEXT?',
		'option_a'       => 'Construct a multigenerational map emphasizing prior conflicts, alliances, cutoffs, losses, and whether similar patterns appeared in earlier generations.',
		'option_b'       => 'Assess the current conflict sequence, communication style, problem-solving, emotional intensity, and which family members become involved during escalation.',
		'option_c'       => 'Evaluate significant family relationships, past disruptions, recurring patterns, current alliances, and how those dynamics appear in the present conflict across generations.',
		'option_d'       => 'Interview family members separately about family history, current concerns, perceived alliances, and areas where their descriptions of recurring patterns differ.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-044',
		'question_text'  => 'A client reports that a former coworker who was terminated after a serious workplace conflict has sent increasingly threatening messages, appeared twice in the employee parking area after being told not to return, and recently sent a photograph of the client\'s car with a message showing knowledge of the client\'s work schedule. The client is frightened but has not been physically assaulted. What should the therapist do NEXT?',
		'option_a'       => 'Assess the threatening contact and workplace impact, strengthen coping during work hours, and review personal safety steps if the contact escalates.',
		'option_b'       => 'Assess the threatening contact and workplace impact, support a direct written boundary, and document any response with the client’s supervisor.',
		'option_c'       => 'Assess the threatening contact and workplace impact, review privacy and technology precautions, and connect the client with general victim-support resources.',
		'option_d'       => 'Assess the threatening contact and workplace impact, coordinate a workplace safety plan, and connect the client with specialized harassment resources.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-045',
		'question_text'  => 'A client with a history of childhood sexual abuse wants to work on trauma memories. After two sessions of detailed narration, the client reports hours of panic and nightmares afterward and skipped the next appointment because, “I knew I would be pushed back into it.” The client says, “I want to continue, but I need more control over the pace.” Which intervention should the therapist use next?',
		'option_a'       => 'Agree collaboratively on an individualized shorter narration segment, use client-controlled stop signals, practice grounding after each segment, review activation, and maintain detailed memory work as the primary method.',
		'option_b'       => 'Use several sessions of present-focused regulation and relationship safety, with jointly defined readiness markers for adding trauma-memory work.',
		'option_c'       => 'Reestablish client-controlled pacing, strengthen stabilization skills, and use small, collaboratively selected trauma-memory doses with explicit review of post-session activation.',
		'option_d'       => 'Use trauma-focused cognitive work on expectations of being overwhelmed, pair it with client-chosen grounding, and add memory work as confidence increases.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-046',
		'question_text'  => 'A client reports repeated verbal outbursts during arguments with a partner. The client notices a racing heart and clenched fists shortly before yelling, then leaves the room only after the argument has escalated. There has been no physical assault, and the couple has agreed on a safety plan. The client wants to stop the outbursts earlier. Which intervention should the therapist use?',
		'option_a'       => 'Review the anger sequence, rehearse an assertive request for the recurring disagreement, and establish a cue for the partner to signal rising tension.',
		'option_b'       => 'Review the anger sequence, identify the earliest body or thought cue, and apply the existing pause-and-return response before the argument escalates further.',
		'option_c'       => 'Review the anger sequence, practice paced breathing at early arousal, and use the skill during a planned discussion with the partner.',
		'option_d'       => 'Review the anger sequence, examine interpretations of disrespect, rehearse alternative interpretations using a recent disagreement, and compare which interpretation is associated with less escalation.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-047',
		'question_text'  => 'A therapist and an ongoing client are members of the same small cultural association. They will regularly see one another at community events, and there is no realistic way for either person to avoid the organization. The therapy has been effective and neither person wants to end it. What is the therapist\'s BEST course of action?',
		'option_a'       => 'Set a detailed public-contact plan for brief greetings, confidentiality, therapy boundaries, power concerns, and clinical-judgment review after community events.',
		'option_b'       => 'Ask the client how public contact should be handled, document the preference, review role boundaries, privacy, power concerns, and effects on clinical judgment.',
		'option_c'       => 'Keep therapy and organizational roles separate, avoid decisions involving the client when possible, document confidentiality, power, boundary, and clinical-judgment concerns, and consider referral if problems develop.',
		'option_d'       => 'Establish expectations for public acknowledgment, confidentiality, role boundaries, and power concerns, while attending to effects on clinical judgment.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-048',
		'question_text'  => 'For four months, a 29-year-old has averaged two to three aggressive outbursts each week involving shouting, threats, pushing, or striking objects without causing injury or property damage. The reactions are grossly disproportionate to minor provocations, occur impulsively rather than deliberately, and are not used to achieve a practical objective. The pattern has caused significant relationship and work problems. There is no manic episode, substance explanation, or pervasive pattern of violating others\' rights. Which diagnosis is MOST supported?',
		'option_a'       => 'Conduct disorder',
		'option_b'       => 'Antisocial personality disorder',
		'option_c'       => 'Bipolar I disorder',
		'option_d'       => 'Intermittent explosive disorder',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-049',
		'question_text'  => 'A client’s panic is maintained by catastrophic interpretations of bodily sensations, escape from feared settings, repeated reassurance seeking, and avoidance of activities that increase heart rate. Which treatment plan is MOST consistent with cognitive behavioral therapy?',
		'option_a'       => 'Map the panic-avoidance sequence, evaluate threat beliefs, and use interoceptive plus situational exposure exercises consistently.',
		'option_b'       => 'Map separation meanings, examine defensive avoidance carefully, and interpret relational expectations within the therapy relationship.',
		'option_c'       => 'Map family reassurance patterns, change reinforcing responses, and support independent approach behavior across feared situations.',
		'option_d'       => 'Map lived panic meaning, deepen phenomenological awareness gradually, and support self-directed engagement with feared situations.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-050',
		'question_text'  => 'A client gambles only several times each month but reports strong urges, repeated unsuccessful efforts to stop, hiding losses from a spouse, and growing household debt. Which assessment approach is BEST?',
		'option_a'       => 'Quantify gambling frequency, amount wagered, losses, debt, borrowing, and access to funds during periods of active gambling.',
		'option_b'       => 'Assess mood triggers, excitement seeking, escape motives, stress level, and whether substance use commonly occurs around gambling episodes.',
		'option_c'       => 'Assess urges, unsuccessful efforts to stop, preoccupation, concealment, financial consequences, and relationship effects across the gambling pattern.',
		'option_d'       => 'Review family history, prior consequences, previous treatment, partner concerns, and the client’s readiness to change.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
);
