<?php
/**
 * LMFT California Clinical — Comprehensive Simulation Form B items 51–75 (PROMPT 09).
 * Learner-facing stems and choices only. Answer keys deferred to admin merge.
 *
 * @package CTA_LMS
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-051',
		'question_text'  => 'Since early adulthood, a client has shown a pervasive pattern of perfectionism, preoccupation with rules and schedules, reluctance to delegate unless others follow the client\'s exact methods, excessive devotion to work, and marked inflexibility. The client considers these standards appropriate and does not report intrusive unwanted thoughts or rituals performed to reduce anxiety. Which diagnosis is MOST supported?',
		'option_a'       => 'Obsessive-compulsive disorder',
		'option_b'       => 'Generalized anxiety disorder',
		'option_c'       => 'Autism spectrum disorder',
		'option_d'       => 'Obsessive-compulsive personality disorder',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-052',
		'question_text'  => 'Six months after witnessing a serious automobile collision, a client reports occasional intrusive images when hearing screeching tires and has largely stopped driving after dark. The client is functioning adequately in most other areas and denies current danger. What should the therapist assess NEXT?',
		'option_a'       => 'Assess driving confidence, transportation limits, accident details, and whether avoidance of nighttime driving was present before the witnessed collision.',
		'option_b'       => 'Assess panic symptoms, sleep disruption, substance use, and family anxiety history to determine whether the current reactions reflect a broader anxiety pattern.',
		'option_c'       => 'Explore the client\'s understanding of the collision, current coping, available support, and whether reduced driving has caused occupational or relationship problems.',
		'option_d'       => 'Assess intrusive recollections, physiological reactivity, avoidance, changes in mood or beliefs, and the functional impact of reminders related to the collision.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-053',
		'question_text'  => 'During an intake, a client speaks much more rapidly than expected but remains coherent and responds directly to questions. Which additional information would BEST help the therapist interpret this observation?',
		'option_a'       => 'Assess orientation, attention, recent memory, concentration, and whether cognitive inefficiency could be contributing to the unusually rapid speech.',
		'option_b'       => 'Assess speech pressure and interruptibility, thought organization, psychomotor activity, and observed activation during the interview.',
		'option_c'       => 'Assess unusual beliefs, suspiciousness, perceptual disturbances, thought content, and whether psychotic features accompany the change in speech rate.',
		'option_d'       => 'Assess reported mood, observed affect, physiological arousal, subjective anxiety, and whether emotional activation is associated with the rapid speech.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-054',
		'question_text'  => 'At a major midlife transition, a client feels disconnected from personal values and asks the therapist to decide which career and relationship choices are “correct.” Which treatment plan is MOST consistent with a humanistic-existential/client-centered approach?',
		'option_a'       => 'Compare current options with a decisional matrix, estimate long-term consequences, and choose the least regrettable path.',
		'option_b'       => 'Explore unconscious conflict, examine authority transference, and connect formative relationships to the current longing for direction.',
		'option_c'       => 'Describe the preferred future, scale confidence in choice, and build a small step from prior decisiveness.',
		'option_d'       => 'Offer empathic congruent presence, clarify the client’s personal meaning, and support self-directed choice without prescribing answers.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-055',
		'question_text'  => 'A client in couple therapy frequently raises their voice and slams doors when the partner questions household spending. After several recent episodes, the client says those questions instantly feel like, “You think I’m useless,” and describes a surge of shame just before becoming angry. There have been no threats or physical violence. Which intervention would most directly reduce the aggressive pattern?',
		'option_a'       => 'Teach a time-out procedure and rehearse leaving the interaction before anger escalates.',
		'option_b'       => 'Set predictable consequences for verbal aggression and review whether consequences reduce later escalation.',
		'option_c'       => 'Identify shame-based threat interpretations before escalation and rehearse alternative responses before returning to conflict.',
		'option_d'       => 'Coach the partner to phrase questions differently and practice communication that reduces defensiveness during recurring disagreements.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-056',
		'question_text'  => 'A client has been abstinent from methamphetamine for seven months and is preparing to attend a three-day family reunion in the hometown where the client previously used with several friends. Current cravings are mild, outpatient treatment is stable, and the client wants to attend without jeopardizing recovery. Which intervention should the therapist use?',
		'option_a'       => 'Practice urge surfing, identify one supportive relative, and reassess cravings each evening during the reunion.',
		'option_b'       => 'Limit attendance to daytime events, avoid locations linked to past use, and ask a relative to stay nearby during unstructured periods.',
		'option_c'       => 'Identify high-risk cues, rehearse responses to offers to use, and set an exit-and-transport plan if relapse risk rises.',
		'option_d'       => 'Review the client’s reasons for recovery, strengthen a sober identity plan for the reunion, and schedule a therapy session immediately after returning.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-057',
		'question_text'  => 'A client repeatedly experiences conflict with supervisors and begins responding to the therapist as though disagreement will lead to punishment or humiliation. Which treatment plan is MOST consistent with a general psychodynamic approach?',
		'option_a'       => 'Teach assertive responses, test punishment predictions in workplace experiments, and revise inflexible beliefs about authority.',
		'option_b'       => 'Trace recurring authority themes, examine within the therapeutic relationship, and connect defenses with formative experiences.',
		'option_c'       => 'Externalize punishing authority, identify exceptions across work relationships, and develop a preferred future professional identity.',
		'option_d'       => 'Clarify hierarchy/boundaries with authority figures, reduce triangular patterns, and support more immediate relational contact.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-058',
		'question_text'  => 'A man reports that for ten months he has had recurrent difficulty obtaining or maintaining an erection during nearly all sexual activity, including both partnered and solitary activity. Sexual interest remains strong, orgasm and ejaculation are otherwise intact, and the problem causes marked distress. Medical evaluation, medications, and substance use do not account for the problem. Which diagnosis is MOST supported?',
		'option_a'       => 'Male hypoactive sexual desire disorder',
		'option_b'       => 'Erectile disorder',
		'option_c'       => 'Delayed ejaculation',
		'option_d'       => 'Substance/medication-induced sexual dysfunction',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-059',
		'question_text'  => 'A therapist discovers that an established psychotherapy client is the therapist\'s child\'s teacher at the only practical local school. The therapist expects occasional parent-teacher contact during the school year, but therapy has been productive and there is no current impairment in clinical judgment. What should the therapist do?',
		'option_a'       => 'Discuss foreseeable school contact, set confidentiality and role boundaries, and monitor whether the overlap affects clinical judgment.',
		'option_b'       => 'Ask the client to route school communication through the principal, document the confidentiality boundary, and keep therapy separate from teacher-parent interactions whenever possible.',
		'option_c'       => 'Have another family member attend school meetings, document the therapy-role boundary, and monitor whether reduced contact better protects client confidentiality and clinical judgment.',
		'option_d'       => 'Continue treatment under existing boundaries, document the school overlap, review confidentiality and client-role concerns if conflict develops, and monitor any effect on judgment.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-060',
		'question_text'  => 'A client experiencing repeated discrimination reports relying on family, a supportive community group, and advocacy work. These resources provide connection and meaning, although the client also reports exhaustion and periods of withdrawing from others. Which assessment is MOST appropriate?',
		'option_a'       => 'Evaluate how family support, community connection, advocacy, rest, and withdrawal affect functioning while also identifying ongoing burden and vulnerability.',
		'option_b'       => 'Assess exhaustion, sleep, concentration, irritability, and whether the client’s coping resources are becoming insufficient for the current level of stress.',
		'option_c'       => 'Assess family and community support, frequency of contact, practical assistance, belonging, and whether those resources remain available during periods of exhaustion.',
		'option_d'       => 'Assess advocacy activity, discrimination exposure, recovery time, role demands, and whether activism is increasing meaning, depletion, or both over time.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-061',
		'question_text'  => 'Two adult siblings repeatedly involve other family members in their disagreements. Each reports calling relatives “just so someone understands what really happened,” after which the conflict typically spreads through the family. What should the therapist assess NEXT?',
		'option_a'       => 'Determine which sibling most often recruits relatives, what support that person seeks, and whether third-party involvement consistently increases or reduces conflict.',
		'option_b'       => 'Review family history of alliances, conflict avoidance, roles, and whether relatives used similar third-party communication.',
		'option_c'       => 'Assess each sibling’s communication style, emotional reactivity, fairness beliefs, repair attempts, direct-contact patterns, and willingness to address disagreements together.',
		'option_d'       => 'Reconstruct a recent conflict, tracing direct communication, third-party involvement, shifting alliances, escalation, and how each response affected the next.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-062',
		'question_text'  => 'After receiving one critical comment from a supervisor, a client says, “I must never disappoint someone in authority. If I do, it proves I am incompetent and worthless.” The client becomes intensely anxious before supervision meetings. The therapist is using REBT. Which intervention most directly targets the central irrational belief?',
		'option_a'       => 'Dispute the belief that the supervisor’s disappointment would be catastrophic and identify evidence that the outcome is survivable.',
		'option_b'       => 'Challenge the belief that making mistakes is intolerable and develop a more flexible statement about handling discomfort.',
		'option_c'       => 'Dispute the demand to perform perfectly and the global conclusion that one disappointing outcome makes the client worthless.',
		'option_d'       => 'Examine the probability that the supervisor will be disappointed and replace certainty about failure with a more realistic estimate.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-063',
		'question_text'  => 'The parent of an adult psychotherapy client calls the therapist and provides detailed information about the client\'s recent behavior. Before ending the call, the parent asks, "Has my child told you about this, and what are you doing about it?" The client has not authorized disclosure to the parent. What is the therapist\'s BEST response?',
		'option_a'       => 'Explain that client confidentiality and treatment privacy prohibit both receiving and disclosing collateral information without client authorization, then end the conversation and document the contact.',
		'option_b'       => 'Accept the parent\'s information, then confirm whether the concern has already been discussed in treatment while withholding session content and diagnosis.',
		'option_c'       => 'Accept the information and offer a general treatment-status reassurance without describing the client\'s diagnosis, goals, or specific session content.',
		'option_d'       => 'Accept clinically useful information without disclosing client treatment information back, document the collateral contact, discuss it with the client, and clarify how future parent communication should be handled.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-064',
		'question_text'  => 'A client with a recently acquired physical disability wants to keep a current job but is having difficulty performing several tasks in the same way as before. The client says, “I don’t want to quit. I need help figuring out what changes at work might let me stay employed.” Which referral best matches the client’s stated need?',
		'option_a'       => 'Refer the client to a vocational rehabilitation service that specializes in disability-related job retention, workplace functioning, and accommodation planning.',
		'option_b'       => 'Refer the client to a general employment center that offers job listings, interview preparation, and assistance applying for positions with other employers.',
		'option_c'       => 'Refer the client to a career-development program that helps workers identify transferable skills, compare occupations, and plan for longer-term advancement.',
		'option_d'       => 'Refer the client to a benefits-counseling service that explains how changes in earnings or work status may affect disability-related financial supports.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-065',
		'question_text'  => 'A therapist and an ongoing client attend the same small faith community. The therapist also holds a visible volunteer leadership role there, and the client sometimes attends activities led by the therapist. Neither person can reasonably leave the community, and therapy is currently beneficial. What is the therapist\'s BEST course of action?',
		'option_a'       => 'Discuss confidentiality and power concerns, transfer client-related activities to another leader, keep faith-community experiences outside therapy, and monitor clinical judgment while the shared setting continues.',
		'option_b'       => 'Discuss confidentiality and power concerns, let the client choose community activities, set boundaries around those choices, and monitor clinical judgment while the shared faith setting continues.',
		'option_c'       => 'Discuss confidentiality and power concerns, minimize direct community contact, set public boundaries, and monitor clinical judgment while considering referral if discomfort increases.',
		'option_d'       => 'Discuss privacy and power concerns, reduce direct control over the client when feasible, set clear public-contact boundaries, and monitor decisions as the shared setting continues over time.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-066',
		'question_text'  => 'A child presents with delayed developmental skills, a chronic medical condition, persistent classroom difficulties, and behavioral concerns across several settings. Assessment by the therapist alone has not clarified how these concerns relate. Which next step is BEST?',
		'option_a'       => 'Coordinate developmental, medical, educational, and behavioral evaluations from the outset because several domains are concurrently implicated and need to be interpreted together.',
		'option_b'       => 'Start neuropsychological testing, then integrate pediatric and school findings if the results indicate cognitive or developmental deficits that need further clarification.',
		'option_c'       => 'Start school-based psychoeducational assessment, then add medical and developmental consultation if the educational findings do not adequately explain the child\'s difficulties.',
		'option_d'       => 'Complete family-system and behavioral assessment first, then refer to the specialty that best matches whichever area emerges as the primary source of impairment.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-067',
		'question_text'  => 'A client reports worsening memory after several weeks of severe sleep disruption. During the session, the client repeatedly loses track of questions and asks the therapist to repeat information. Which assessment should the therapist conduct NEXT?',
		'option_a'       => 'Directly assess attention, concentration, orientation, and short-term recall, then compare findings with reported baseline functioning.',
		'option_b'       => 'Characterize sleep duration, sleep quality, daytime fatigue, medication or substance use, and timing of the cognitive complaints.',
		'option_c'       => 'Screen mood, anxiety, dissociation, stress load, and subjective cognitive concerns to identify possible emotional contributors.',
		'option_d'       => 'Obtain collateral examples of memory lapses, missed obligations, safety errors, and recent changes in daily functioning.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-068',
		'question_text'  => 'A recently resettled refugee survived war, displacement, and torture. The client reports hypervigilance, poor sleep, difficulty trusting institutions, limited English proficiency, and unstable access to transportation and community resources. The client is not currently in imminent danger. Which approach is BEST initially?',
		'option_a'       => 'Assess immediate safety and resettlement needs, provide culturally responsive language-accessible support, begin trauma preparation with paced exposure after initial trust, and identify initial community supports.',
		'option_b'       => 'Assess immediate safety and resettlement needs, provide culturally responsive language-accessible support, and build trust before pacing trauma work to readiness.',
		'option_c'       => 'Assess immediate safety and resettlement needs, provide culturally responsive language-accessible support, and encourage gradual engagement with needed community systems.',
		'option_d'       => 'Assess immediate safety and resettlement needs, provide culturally responsive language-accessible support, and organize trauma assessment around the most severe exposures first.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-069',
		'question_text'  => 'A client’s panic symptoms have decreased substantially. However, the client still avoids independent exposure practice, seeks therapist reassurance before entering feared situations, and rarely applies treatment skills without prompting. Which plan is MOST appropriate?',
		'option_a'       => 'Revise goals toward independent exposure practice; reduce reassurance reliance; reassess termination after gains generalize across settings.',
		'option_b'       => 'Start a gradual step-down schedule; monitor exposure practice plus reassurance use; return to weekly care if avoidance increases.',
		'option_c'       => 'Continue weekly sessions unchanged; reinforce skill practice plus family support; allow independence to develop before termination.',
		'option_d'       => 'Begin termination planning now; provide relapse/exposure guidance; shift remaining practice to self-directed follow-through after discharge.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-070',
		'question_text'  => 'A 64-year-old client retired six months ago after 38 years as the family’s primary wage earner. The client immigrated to the United States as a young adult and says that, in the family and cultural community, being a dependable provider has always defined adulthood. The pension covers basic expenses, but the client feels useless, criticizes the spouse’s spending, and rejects adult children’s invitations because “I should still be helping them, not the other way around.” Which intervention should the therapist use to facilitate adjustment to retirement?',
		'option_a'       => 'Build a weekly routine that includes social, community, and family contribution roles consistent with the client’s values.',
		'option_b'       => 'Process grief over career loss and identify nonwork roles that preserve a sense of contribution within the family.',
		'option_c'       => 'Develop volunteer or mentoring roles that support contribution while the client accepts selected practical help from family.',
		'option_d'       => 'Reframe contribution within the client’s cultural framework and renegotiate family roles to include both giving and receiving.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-071',
		'question_text'  => 'An adult has recently left a trafficking situation. The client fears retaliation, does not have stable housing or identification documents, distrusts unfamiliar helpers, and says, “I\'m not ready to tell the whole story.” No immediate medical emergency is identified. What should the therapist prioritize?',
		'option_a'       => 'Assess immediate safety and basic needs, connect specialized survivor resources, request a fuller trafficking history before additional referrals, and document current identification and housing needs.',
		'option_b'       => 'Assess immediate safety and basic needs, connect specialized survivor resources, and delay outside coordination until therapeutic trust becomes stronger.',
		'option_c'       => 'Assess immediate safety and basic needs, connect specialized survivor resources, and proceed without making services contingent on fuller disclosure.',
		'option_d'       => 'Assess immediate safety and basic needs, connect specialized survivor resources, and prioritize reconnecting with family before unfamiliar services.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-072',
		'question_text'  => 'In family therapy, a parent repeatedly corrects the 15-year-old’s wording whenever the adolescent tries to describe feeling pressured at home. The adolescent then becomes quiet, while the parent says, “I am only trying to help you get it right.” Other family members become tense and stop speaking. The therapist is using an experiential family approach. Which intervention should the therapist use?',
		'option_a'       => 'Use emotion tracking and invite each family member to name the feelings beneath correction while the exchange continues in session.',
		'option_b'       => 'Use role reversal and ask the parent and adolescent to describe how repeated correction changes each person’s immediate experience.',
		'option_c'       => 'Use a family sculpt and invite each person to describe how the pattern shapes closeness, distance, and emotional expression.',
		'option_d'       => 'Use the live exchange to stop the correction and facilitate personal statements about fear, care, needs, and desired connection.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-073',
		'question_text'  => 'A 14-year-old witnessed a parent lose consciousness from an opioid overdose at home and saw emergency responders revive the parent. The adolescent now startles easily, sleeps poorly, avoids being alone with the parent, and says, “If I’d noticed sooner, this wouldn’t have happened.” The adolescent denies self-harm intent. A sober aunt who has been a reliable caregiver is available. What should the therapist prioritize?',
		'option_a'       => 'Assess current safety and self-blame, involve the safe caregiver in coping support, and restore predictable routines while monitoring functioning.',
		'option_b'       => 'Assess current safety and self-blame, involve the safe caregiver in coping support, begin detailed retelling of the overdose event, and coordinate school supports during recovery.',
		'option_c'       => 'Assess current safety and school functioning, involve the safe caregiver in coping support, and reinforce independence around trauma-related fears.',
		'option_d'       => 'Assess current safety and family stress, involve the safe caregiver in coping support, and focus first on monitoring the parent’s recovery.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-074',
		'question_text'  => 'A therapist is treating a young adult client who strongly reminds the therapist of the therapist\'s own adult child. The therapist notices an urge to rescue the client, has become unusually flexible about late cancellations, and gives the client more attention between sessions than other clients receive. What is the therapist\'s BEST next step?',
		'option_a'       => 'Use consultation to review cancellation and messaging boundaries, restore standard client policies, adopt a structured treatment agenda, document boundary decisions, and monitor selective attention.',
		'option_b'       => 'Use consultation to assess whether limited self-disclosure could benefit treatment and clarify its therapeutic purpose.',
		'option_c'       => 'Use consultation to identify the rescue response and restore consistent clinical limits while observing for selective treatment decisions.',
		'option_d'       => 'Use consultation to shift toward measurable treatment goals, objective outcome review, and more structured decision rules so clinical choices rely less on protective feelings.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-075',
		'question_text'  => 'A client with a longstanding medical condition reports taking prescribed treatment inconsistently and experiencing fluctuating physical and emotional functioning. Which response would BEST advance the clinical evaluation?',
		'option_a'       => 'Assess treatment motivation, illness beliefs, perceived benefits or side effects, and readiness to follow prescribed care more consistently.',
		'option_b'       => 'Clarify understanding of the regimen, actual adherence, barriers, symptom changes, and functional changes associated with adherence.',
		'option_c'       => 'Coordinate with the medical provider about recommendations, adherence concerns, health risks, and recent findings affecting psychological functioning.',
		'option_d'       => 'Review medication access, cost, family support, routines, competing demands, and practical obstacles interfering with adherence.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
);
