<?php
/**
 * LMFT California Clinical — Comprehensive Simulation Form A items 126–150 (PROMPT 06).
 * Learner-facing stems and choices only. Answer keys deferred to admin merge.
 *
 * @package CTA_LMS
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-126',
		'question_text'  => 'A client who previously maintained stable employment begins missing work and having repeated disagreements with coworkers after the employer reorganizes the department and substantially changes the client\'s responsibilities. Which assessment would be MOST useful?',
		'option_a'       => 'Assess mood, sleep, anxiety, concentration, and whether symptoms changed around the workplace reorganization.',
		'option_b'       => 'Review supervisor conflict, coworker interactions, communication problems, and whether interpersonal difficulties occur in other employment or relationship settings.',
		'option_c'       => 'Compare prior work functioning with changes in duties, expectations, attendance, performance, and stress since the department reorganized.',
		'option_d'       => 'Review career satisfaction, financial pressures, alternative employment options, and whether remaining in the current position is worsening overall functioning.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-127',
		'question_text'  => 'An adult client entered psychotherapy through an employee assistance program. The client\'s written authorization allows the therapist to tell the EAP only whether the client attended the authorized sessions and completed the referral. An employer representative contacts the therapist through the EAP and asks whether the client is emotionally ready to return to a high-pressure assignment. What is the therapist\'s BEST response?',
		'option_a'       => 'Provide the authorized attendance information plus a limited work-readiness opinion based on observed functioning, review the observed work factors, omit diagnosis and session details, explain the narrower purpose of the opinion, and document the rationale and disclosure to the EAP.',
		'option_b'       => 'Provide only the attendance and completion information already authorized by the client, explain that any work-readiness opinion requires separate authority, and document the exact disclosure scope to the EAP.',
		'option_c'       => 'Withhold all EAP information until the client decides whether to expand the authorization, explain the employer\'s request, review the client\'s decision before responding, and document the pending decision.',
		'option_d'       => 'Ask the client whether to authorize a work-readiness opinion, review the implications of taking that evaluative role, and respond after the client decides.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-128',
		'question_text'  => 'A 16-year-old has begun missing school after recurring morning stomachaches. One parent quickly allows the adolescent to stay home, while the other criticizes both of them for “giving in.” The parents then argue, the adolescent withdraws, and the next morning the same sequence repeats. The therapist is using a general systems approach. Which intervention should the therapist use?',
		'option_a'       => 'Map how each family member responds to school refusal and ask them to observe the sequence before changing it.',
		'option_b'       => 'Shift parental attention away from the adolescent and strengthen the couple relationship during discussions about school attendance.',
		'option_c'       => 'Interrupt the reciprocal school-refusal cycle by changing how parents respond when the adolescent begins avoiding school.',
		'option_d'       => 'Reframe the adolescent’s refusal as serving a family-stabilizing function and explore when that function becomes less necessary.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-129',
		'question_text'  => 'A client in treatment for panic symptoms agreed to complete brief interoceptive practice between sessions but tried it only once. The client says the exercise felt frightening, is unsure why it is necessary, and still wants therapy to help reduce panic. Which intervention should the therapist use next?',
		'option_a'       => 'Complete the interoceptive exercise in session, identify what made it frightening, and assign the same version with a coping plan.',
		'option_b'       => 'Review the client’s concerns and treatment rationale, then agree on a smaller interoceptive step the client is willing to repeat.',
		'option_c'       => 'Use a week of symptom monitoring to identify panic triggers, then choose an exposure target from the pattern.',
		'option_d'       => 'Provide additional education about the panic cycle, demonstrate the exercise again, and assign the original practice with written instructions.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-130',
		'question_text'  => 'An adolescent’s symptoms intensify when the adolescent is recruited into a cross-generational coalition during parental conflict. The parents have difficulty functioning as a coordinated leadership team, and boundaries between the parental and child subsystems are diffuse. Which treatment plan is MOST consistent with structural family therapy?',
		'option_a'       => 'Map family triangles, support differentiation under stress, and reduce reactive involvement across relationships over time.',
		'option_b'       => 'Map maintaining sequences, assign strategic directives, and revise interactional tasks according to observed family responses.',
		'option_c'       => 'Map current family role patterns, reinforce parental leadership, and delineate boundaries around the cross-generational alliance.',
		'option_d'       => 'Map emotional avoidance, deepen congruent expression through enactments, and increase interpersonal contact among family members.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-131',
		'question_text'  => 'A client experiences recurrent intrusive thoughts that household surfaces are contaminated. The thoughts are unwanted and distressing. The client washes repeatedly and spends approximately two hours each day cleaning to reduce anxiety, while recognizing that the feared contamination may be exaggerated. Which diagnosis is MOST supported?',
		'option_a'       => 'Generalized anxiety disorder',
		'option_b'       => 'Obsessive-compulsive personality disorder',
		'option_c'       => 'Obsessive-compulsive disorder',
		'option_d'       => 'Delusional disorder',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-132',
		'question_text'  => 'A parent has just received a serious medical diagnosis. Within two weeks, the family has lost its usual childcare arrangement, meals and school routines are inconsistent, both adults are sleeping poorly, and disagreements about responsibilities have increased. No family member is imminently unsafe. What should the therapist emphasize FIRST?',
		'option_a'       => 'Assess immediate family functioning and urgent routine disruptions, stabilize temporary roles, and mobilize practical supports for the near term.',
		'option_b'       => 'Assess family distress and communication, mobilize practical supports, and defer major role changes until emotional intensity decreases.',
		'option_c'       => 'Assess prior coping and family-role patterns, mobilize practical supports, and use historical strengths to guide current adaptation.',
		'option_d'       => 'Assess individual symptoms and coping, mobilize family supports, and coordinate psychiatric consultation for members with significant impairment.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-133',
		'question_text'  => 'A client with panic symptoms has begun leaving grocery stores as soon as dizziness or chest tightness appears and often calls a spouse from the parking lot for reassurance. Medical causes have been evaluated, and the client wants to remain in stores without relying on escape. Which intervention should the therapist use?',
		'option_a'       => 'Use graded store exposure with paced breathing and have the client remain through a planned interval while observing whether arousal settles over repeated visits.',
		'option_b'       => 'Use graded store exposure with cognitive reappraisal of dizziness and chest tightness while the client remains in the feared setting.',
		'option_c'       => 'Use graded store exposure during less crowded periods and extend visit duration as the client gains confidence across repetitions.',
		'option_d'       => 'Use graded store exposure through rising fear while reducing early exits and reassurance calls to the spouse.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-134',
		'question_text'  => 'A client’s spouse died unexpectedly three months ago. The client remains able to work and care for the children but becomes tearful during evening prayers and says relatives are urging the client to “move on.” In the client’s faith community, remembrance rituals and ongoing bonds with the deceased are considered important parts of mourning. Which intervention should the therapist use?',
		'option_a'       => 'Explore grief through the client’s faith tradition, support remembrance rituals, and help the client carry grief alongside daily responsibilities.',
		'option_b'       => 'Use grief-focused narrative reconstruction to revisit the death and identify emotionally unfinished material the client has not yet fully expressed.',
		'option_c'       => 'Help the client reorganize family responsibilities after the loss and use therapy mainly to support practical adaptation while spiritual remembrance rituals continue.',
		'option_d'       => 'Develop an individualized continuing-bond ritual with the children and establish responses to relatives who pressure premature emotional resolution.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-135',
		'question_text'  => 'A client with rapidly worsening psychiatric symptoms has eaten very little for several days, has stopped bathing, has been unable to obtain food independently, and cannot describe how basic needs will be met after leaving the office. The client denies current suicidal or homicidal intent. What is the BEST next action?',
		'option_a'       => 'Maintain observation, arrange same-day intensive outpatient stabilization, and add case-management and basic-needs support.',
		'option_b'       => 'Maintain observation, arrange same-day psychiatric medication evaluation, and provide supervised community support while stabilization begins.',
		'option_c'       => 'Maintain observation, arrange same-day supervised respite or housing, and provide daily crisis outreach with basic-needs assistance.',
		'option_d'       => 'Maintain observation, transfer to a staffed crisis setting, and obtain psychiatric assessment with basic-self-care stabilization.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-136',
		'question_text'  => 'A client reports several episodes of yelling and damaging household objects during arguments over the past year. The client denies threatening or physically assaulting anyone and denies any current intent to harm another person. What should the therapist do NEXT?',
		'option_a'       => 'Clarify the frequency, triggers, escalation, consequences, relationship effects, and whether current intent or access indicates any change in danger at present.',
		'option_b'       => 'Assess impulsivity, anger tolerance, emotion regulation, remorse, and whether property destruction occurs in contexts other than interpersonal arguments.',
		'option_c'       => 'Assess substance use, sleep, mood changes, stress, and whether the outbursts reliably occur during intoxication or periods of psychological deterioration.',
		'option_d'       => 'Review legal history, family responses, prior aggression, treatment history, and whether consequences have altered the client’s behavior over time.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-137',
		'question_text'  => 'A veteran seeks couples therapy for emotional distance and frequent conflict after returning from a lengthy deployment. The veteran says military service “has nothing to do with this” and prefers to focus only on the partner\'s complaints. What should the therapist do NEXT?',
		'option_a'       => 'Assess trauma symptoms, sleep, avoidance, and whether deployment experiences contribute to current relationship difficulties.',
		'option_b'       => 'Explore military service, deployment experiences, reintegration, military culture, and changes in family and relationship functioning after return.',
		'option_c'       => 'Assess current couple conflict, emotional distance, communication patterns, intimacy, support, and whether similar difficulties existed before deployment.',
		'option_d'       => 'Obtain the partner’s observations of post-deployment changes, family-role shifts, conflict patterns, and situations that seem to increase disconnection.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-138',
		'question_text'  => 'A couple with a 4-month-old first child reports escalating arguments about chores, nighttime care, and lack of couple time. Before the baby they divided responsibilities evenly, but both say the old “50/50” rule no longer fits their schedules or energy. Neither reports a longstanding relationship problem. Which intervention should the therapist use?',
		'option_a'       => 'Use a weekly planning meeting to restore the prior 50/50 division of infant care and household tasks and review whether both partners can sustain that arrangement.',
		'option_b'       => 'Use a weekly meeting to plan responsibilities by current capacity and protect recurring time for couple connection.',
		'option_c'       => 'Use a weekly planning meeting to clarify shared parenting values and create a new agreement for nighttime care, chores, and couple time.',
		'option_d'       => 'Use a weekly planning meeting to plan alternating recovery periods, recruit outside help for high-burden tasks, and review whether fatigue-related conflict changes.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-139',
		'question_text'  => 'A client reports superficial cutting several times during the past month after intense interpersonal conflict. The client consistently denies wanting to die, denies a suicide plan or preparatory behavior, has no medically serious injury, identifies the situations that trigger cutting, and can use supportive contacts when urges increase. Which intervention is MOST appropriate now?',
		'option_a'       => 'Reassess suicide risk directly, arrange a same-day crisis evaluation, and involve a support person in transfer.',
		'option_b'       => 'Reassess suicide risk directly, keep the routine outpatient frequency, and use identified supports if urges intensify.',
		'option_c'       => 'Reassess suicide risk directly, revise the self-harm safety plan, and increase near-term outpatient follow-up for now.',
		'option_d'       => 'Reassess suicide risk directly, restrict access to self-harm tools, and postpone coping work until urges decrease.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-140',
		'question_text'  => 'A 15-year-old adopted at age 8 after several caregiver changes is in therapy with the adoptive mother. When the mother sets a limit, the adolescent says, “You’ll get tired of me too,” pulls away, and then repeatedly messages friends for reassurance. The mother responds by avoiding the conflict for the rest of the day. Which intervention should the therapist use to improve attachment stability and relational functioning?',
		'option_a'       => 'Use attachment-focused family work to strengthen supportive peer contact after conflict and return the adolescent to the family discussion with a clear plan.',
		'option_b'       => 'Use attachment-focused family work to pair limits with reassurance, reduce the mother’s disengagement, and review what happens when rejection fears appear.',
		'option_c'       => 'Use attachment-focused individual work to process caregiver losses and identify how rejection expectations shape the adolescent’s current reactions.',
		'option_d'       => 'Use attachment-focused conjoint work to set predictable limits and establish a reliable reconnection process after conflict between mother and adolescent.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-141',
		'question_text'  => 'A service member returned from a nine-month deployment two months ago. The couple expected reunion to feel easy, but they now argue about parenting routines, household decisions, and how much time the service member spends alone. Both say they want to reconnect and neither reports current violence or acute danger. Which intervention should the therapist use?',
		'option_a'       => 'Use reintegration work to explore deployment-related emotional distance, identify reactions that interfere with family contact, and compare how those reactions appear at home.',
		'option_b'       => 'Use reintegration work to plan current parenting and household roles and protect routines for alone time and couple reconnection.',
		'option_c'       => 'Use reintegration work to practice communication around one recurring disagreement and establish a shared method for household decisions.',
		'option_d'       => 'Use reintegration work to compare predeployment and current roles, clarify family values, and translate those values into household priorities.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-142',
		'question_text'  => 'A family seeking therapy has received an eviction notice after a major reduction in household income. Family members report increased arguments, disrupted sleep, and difficulty concentrating at work and school. Which assessment approach is BEST?',
		'option_a'       => 'Assess anxiety, depressive symptoms, sleep, school or work impairment, and how each family member is responding emotionally to possible eviction.',
		'option_b'       => 'Assess family conflict, division of responsibilities, financial decision-making, communication, and whether relational strain is interfering with practical problem-solving.',
		'option_c'       => 'Assess housing stability, income loss, access to necessities, available supports, and effects of these stressors on individual and family functioning over time.',
		'option_d'       => 'Assess immediate resource needs, housing options, financial assistance, transportation, and whether practical barriers are limiting the family’s available choices.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-143',
		'question_text'  => 'A family includes two parents, a 15-year-old, and the maternal grandparents, who recently moved into the home. The grandparents frequently reverse the parents’ limits, the parents argue with the grandparents about discipline, and the adolescent has begun seeking whichever adult is most likely to say yes. Which intervention should the therapist use?',
		'option_a'       => 'Define separate decision domains for parents and grandparents and practice how the adults will handle discipline, routines, and privileges within those domains.',
		'option_b'       => 'Restore parental leadership through private adult resolution of rule disagreements before consistent limits are presented to the adolescent.',
		'option_c'       => 'Create household rules and consequences for all adults to apply when the adolescent violates a limit.',
		'option_d'       => 'Create a four-adult consultation process for discipline decisions and practice reaching consensus before any limit is presented to the adolescent.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-144',
		'question_text'  => 'A transgender young adult reports strong acceptance from friends and coworkers but ongoing rejection from several relatives. The client says functioning varies considerably depending on which social environment the client is in. What should the therapist assess NEXT?',
		'option_a'       => 'Assess identity development, acceptance and rejection across settings, available supports, minority stress, and corresponding changes in functioning.',
		'option_b'       => 'Assess family rejection, dependence on relatives, housing stability, conflict patterns, safety concerns, and whether family interactions account for most current distress.',
		'option_c'       => 'Assess social or medical transition experiences, body-related concerns, healthcare support, and whether transition-related changes correspond with current functioning.',
		'option_d'       => 'Assess peer and workplace affirmation, community connection, coping resources, and whether supportive environments sufficiently buffer stress occurring within the family.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-145',
		'question_text'  => 'A client under prolonged stress frequently seeks support from trusted friends but also spends entire weekends avoiding responsibilities by sleeping and watching television. The client says both strategies “help me get through it.” What should the therapist assess NEXT?',
		'option_a'       => 'Classify each coping response by whether it is approach-based or avoidance-based, then compare how often each strategy is used during stress.',
		'option_b'       => 'Evaluate what each coping strategy accomplishes, its short- and longer-term effects, and whether it supports functioning or extends avoidance.',
		'option_c'       => 'Assess immediate relief, emotional intensity before and after coping, perceived control, and whether the client experiences each strategy as helpful.',
		'option_d'       => 'Review support quality, weekend routines, unfinished responsibilities, sleep, and whether demands influence coping choices.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-146',
		'question_text'  => 'A 42-year-old manager begins short-term therapy through an employee assistance program after a promotion. The EAP authorization and limits of information sharing are already documented. The client reports avoiding difficult conversations, doing subordinates’ tasks rather than delegating, working late, then becoming resentful and less productive. Which intervention should the therapist use to improve workplace functioning?',
		'option_a'       => 'Use stress-inoculation and boundary-setting to reduce late work and prepare for difficult meetings with subordinates.',
		'option_b'       => 'Challenge beliefs that competent managers should complete tasks themselves and test those beliefs with one planned delegation.',
		'option_c'       => 'Rehearse assertive delegation in role-play and prepare coping responses for the stress that follows difficult workplace conversations.',
		'option_d'       => 'Create a workload-prioritization plan with EAP resources and set limits on after-hours work while keeping the current communication approach.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-147',
		'question_text'  => 'A 20-year-old college student immigrated with the parents at age 10. The student reports repeated microaggressions at school and says the parents expect problems to be handled privately because “family matters stay in the family.” The student values family loyalty but also wants more independence and feels “too American at home and too foreign at school.” The parents agree to family sessions. Which intervention should the therapist use?',
		'option_a'       => 'Integrate discrimination and acculturation differences into family work while negotiating independence and family-loyalty expectations around shared priorities.',
		'option_b'       => 'Use the family’s migration story to identify traditions that support the student, then build coping plans for school microaggressions around those strengths.',
		'option_c'       => 'Validate bicultural strain and practice responses to microaggressions while helping the student define how much independence is desired in specific situations.',
		'option_d'       => 'Facilitate a family discussion of cultural priorities and create respectful rules for handling disagreements about privacy, school stress, and independence.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-148',
		'question_text'  => 'A client describes functioning well during a previous period of treatment, but a prior treatment summary indicates substantial impairment during the same period. The discrepancy affects the therapist’s understanding of the current presentation. What should the therapist do NEXT?',
		'option_a'       => 'With the client’s authorization, review the prior record or consult the former provider about the specific discrepancy in functioning.',
		'option_b'       => 'Treat the prior record as the more reliable source because it documents functioning closer to the period being evaluated than the client’s current recollection.',
		'option_c'       => 'Rely on the client’s current account unless the discrepancy changes the diagnosis or creates an immediate safety concern.',
		'option_d'       => 'Seek a family member’s account of the earlier period before contacting the former provider or reviewing treatment records.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-149',
		'question_text'  => 'A client with schizophrenia remains engaged in outpatient psychiatric care and reports occasional noncommand voices at night. Family members become alarmed and repeatedly ask whether the voices are getting worse; the client then retreats to a bedroom and stops interacting. There is no current safety concern. Which intervention should the therapist use?',
		'option_a'       => 'Teach grounding for voices, ask what helps, and have family members stop repeated questions when the client is stable and safe.',
		'option_b'       => 'Develop a coping plan for residual voices and coach family members to respond calmly without repeated checking that increases withdrawal.',
		'option_c'       => 'Focus family sessions on communication skills and leave management of psychotic symptoms entirely to the psychiatric provider.',
		'option_d'       => 'Help the client challenge the voice content and ask family members to provide reality-based reassurance whenever symptoms increase.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-150',
		'question_text'  => 'Parents of a 9-year-old with sensory and transition difficulties disagree sharply about discipline. One parent relies on highly structured routines; the other often changes expectations to prevent meltdowns. Both parents are exhausted, argue about each other’s approach, and the child increasingly seeks a different answer from each parent. Which intervention should the therapist use to improve the parenting relationship?',
		'option_a'       => 'Map recurring parenting conflicts and have each parent practice consistent responses within separate household domains.',
		'option_b'       => 'Identify stress-driven differences and establish shared responses for recurring parenting challenges that predictably trigger conflict.',
		'option_c'       => 'Develop a joint behavior plan around the child’s sensory triggers and use the same consequence sequence across both parents.',
		'option_d'       => 'Practice conflict-management skills between the parents while allowing each parent to keep an individualized discipline approach.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
);
