<?php
/**
 * LMFT California Clinical — Comprehensive Simulation Form A items 76–100 (PROMPT 04).
 * Learner-facing stems and choices only. Answer keys deferred to admin merge.
 *
 * @package CTA_LMS
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-076',
		'question_text'  => 'A 4-year-old who speaks one language primarily at home and English at preschool is referred because teachers report limited peer interaction and difficulty following classroom directions. The parents report age-appropriate conversation and play with relatives at home. What should the therapist do NEXT?',
		'option_a'       => 'Compare receptive and expressive language, peer interaction, classroom directions, and differences between home and preschool performance.',
		'option_b'       => 'Review developmental history across communication, social, motor, and adaptive domains while comparing both language contexts and settings for this child.',
		'option_c'       => 'Review preschool peer behavior, classroom demands, teacher supports, and whether difficulties change during familiar versus unfamiliar activities.',
		'option_d'       => 'Review early milestones, hearing history, bilingual exposure, family developmental history, and changes in communication across the past year.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-077',
		'question_text'  => 'A client has experienced chronic abdominal pain for more than a year. Medical evaluation has identified a gastrointestinal condition that can account for some of the pain. For at least eight months, the client has spent several hours each day checking symptoms, repeatedly seeking additional medical opinions, and worrying that minor changes signal serious deterioration. The preoccupation has substantially disrupted work and relationships. Which diagnosis is MOST supported?',
		'option_a'       => 'Somatic symptom disorder',
		'option_b'       => 'Illness anxiety disorder',
		'option_c'       => 'Generalized anxiety disorder',
		'option_d'       => 'Factitious disorder',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-078',
		'question_text'  => 'A current client posts a public comment on the therapist\'s professional social-media page saying, "You have helped me more than any therapist ever has." The comment could reveal the client\'s treatment relationship to people who know the client. What is the therapist\'s BEST response?',
		'option_a'       => 'Do not reply publicly; hide the comment if possible, document the privacy concern, and review social-media boundaries with the client privately.',
		'option_b'       => 'Hide the public comment, message the client about the confidentiality and boundary concern, document the interaction, review whether removal reduces exposure, explain the public-contact risk, and ask that future posts avoid identifying the therapy relationship.',
		'option_c'       => 'Leave the comment unanswered, document the confidentiality and privacy concern, and review with the client whether public identification fits the client\'s understanding of online treatment boundaries.',
		'option_d'       => 'Post a neutral response that avoids confirming treatment, document the confidentiality issue, and review with the client how public comments can affect privacy and future therapy boundaries.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-079',
		'question_text'  => 'A client discussing alcohol use says, “I hate being tired and missing things after I drink, but it is how I relax with my friends. I know there are costs, and I am still not sure I want to change.” The therapist is using motivational interviewing and has not asked the client to commit to a change plan. Which response should the therapist use next?',
		'option_a'       => 'Ask permission to share personalized feedback about the drinking pattern, then invite the client to describe what feels relevant.',
		'option_b'       => 'Use importance and confidence rulers, then ask why the ratings are not lower so the client articulates personally meaningful reasons favoring change.',
		'option_c'       => 'Reflect both sides of the ambivalence and ask what concerns the client most about continuing versus changing so personal motivations emerge.',
		'option_d'       => 'Summarize the client’s change language, ask which goal feels acceptable now, and support an individually selected, immediately achievable next step.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-080',
		'question_text'  => 'A client wants closer friendships but repeatedly pulls away when others become emotionally available. After a close friend recently invited the client to share more openly, the client ignored messages for several days and later said, “If I let people matter, they can disappoint me.” The therapist is using an attachment-informed approach. Which intervention should the therapist use?',
		'option_a'       => 'Explore early caregiving expectations and use a current friendship example to identify when bids for closeness trigger withdrawal.',
		'option_b'       => 'Help the client describe the fear of disappointment to the friend and practice a brief request for reassurance after an emotionally important exchange.',
		'option_c'       => 'Identify withdrawal as a protective attachment strategy, explore how it functions during bids for closeness, and practice a tolerable reciprocal response when the friend reaches out.',
		'option_d'       => 'Notice physiological activation during relational bids and practice grounding while the client chooses how much emotional contact to sustain.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-081',
		'question_text'  => 'A client has attended consistently, completed CBT practices as assigned, and demonstrated understanding of the treatment model. After an adequate trial, worry, avoidance, and occupational impairment remain essentially unchanged. What should the therapist do NEXT?',
		'option_a'       => 'Review formulation plus longitudinal progress data; compare interventions with the maintenance cycle; revise the therapeutic target when indicated.',
		'option_b'       => 'Review assignment quality plus exposure dose; compare practice with the plan; intensify the intervention for another trial.',
		'option_c'       => 'Review diagnostic plus medication factors; compare symptoms around consultation; maintain the current psychotherapy target meanwhile.',
		'option_d'       => 'Review alliance quality plus treatment preferences; compare engagement across recent sessions; shift carefully toward supportive therapy before revisiting the formulation.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-082',
		'question_text'  => 'A couple seeks therapy primarily because disclosure of an affair has produced severe mistrust, repeated arguments, and uncertainty about whether the relationship can continue. One partner recently changed jobs and the household is also under some financial strain, but both identify the relationship rupture as the reason for treatment. Neither partner meets criteria for an individual mental disorder. Which condition is MOST appropriate as the primary focus of clinical attention?',
		'option_a'       => 'Occupational problem related to work-role stress and job changes.',
		'option_b'       => 'Relationship distress with spouse or intimate partner following affair disclosure.',
		'option_c'       => 'Parent-child relational problem involving family conflict and caregiving strain.',
		'option_d'       => 'Housing or economic problem involving financial strain, housing instability, and resource limitations.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-083',
		'question_text'  => 'A family reports frequent chaotic mornings but can identify several recent days when routines worked, conflict remained low, and everyone left on time. Which treatment plan is MOST consistent with a solution-oriented approach?',
		'option_a'       => 'Externalize morning chaos, map its effects on family identity, and re-author cooperation through unique successful outcomes.',
		'option_b'       => 'Analyze triggers before late departures, set behavioral contingencies, and track daily morning-task success across one week.',
		'option_c'       => 'Prescribe a planned sequence change, observe the family response, and revise the directive according to demonstrated effects.',
		'option_d'       => 'Outline the preferred morning, examine exceptions through scaling, and build a single repeatable strategy from prior success.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-084',
		'question_text'  => 'During the past two months, a client has experienced six abrupt episodes of intense fear with palpitations, trembling, shortness of breath, and fear of losing control. Several attacks occurred when the client was relaxed and no specific trigger was present. The client now worries persistently about another attack and avoids exercise because increased heart rate feels frightening. Which diagnosis is MOST supported?',
		'option_a'       => 'Generalized anxiety disorder',
		'option_b'       => 'Social anxiety disorder',
		'option_c'       => 'Agoraphobia',
		'option_d'       => 'Panic disorder',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-085',
		'question_text'  => 'A 15-year-old has stopped attending school regularly. The parents describe the adolescent as “defiant and lazy,” while the adolescent reports becoming intensely uncomfortable around classmates and says the parents “don\'t understand what happens at school.” What should the therapist do NEXT?',
		'option_a'       => 'Explore school triggers, internal reactions, avoidance, and peer experiences primarily from the adolescent’s perspective before comparing family reports.',
		'option_b'       => 'Compare concrete examples, timing, setting, and consequences reported by the adolescent, parents, and school before selecting among competing explanations.',
		'option_c'       => 'Review parent responses, family conflict, attendance consequences, and home routines to determine whether family interactions are maintaining the refusal.',
		'option_d'       => 'Obtain attendance records, teacher observations, academic changes, and peer information before deciding how much weight to give the family’s differing accounts.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-086',
		'question_text'  => 'A 38-year-old client reports that “everything is basically fine,” but arrives in noticeably soiled clothing and moves much more slowly than during an intake completed six months earlier. The client’s spouse has recently expressed concern about declining self-care. Which information should the therapist clarify NEXT as part of the mental-status evaluation?',
		'option_a'       => 'Assess depressive symptoms, vegetative changes, prior mood episodes, current impairment, and whether the presentation resembles earlier periods of depression.',
		'option_b'       => 'Assess recent medication or substance changes, medical symptoms, fatigue, sleep disruption, and whether physical factors could account for the observed slowing.',
		'option_c'       => 'Obtain focused collateral information about self-care, activity level, daily routines, occupational functioning, and how recently the change became noticeable.',
		'option_d'       => 'Directly assess appearance, psychomotor activity, speech, attention, and change from baseline before interpreting the mental-status findings.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-087',
		'question_text'  => 'Four months after the birth of their first child, one partner reports fatigue, body changes, and little interest in sex. The other partner has heard friends and social-media posts say that couples should have “returned to normal” by now, interprets decreased initiation as rejection, and presses for more sexual contact. The first partner withdraws, and both report feeling less emotionally close. Which intervention should the therapist use?',
		'option_a'       => 'Clarify each partner’s preferred frequency and build a mutually agreed intimacy plan that includes clear signals for initiation, decline, and requests for nonsexual closeness.',
		'option_b'       => 'Explore postpartum body-image and fatigue with the lower-desire partner, then identify conditions that make sexual contact feel more possible.',
		'option_c'       => 'Map the pressure-withdraw cycle, challenge outside “normal” timelines, and negotiate several forms of closeness that either partner can initiate without obligation.',
		'option_d'       => 'Use sensate-attention exercises that remove intercourse as the goal and help the couple identify types of contact that feel connecting now.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-088',
		'question_text'  => 'A 15-year-old in therapy has been described at school for years as “the troublemaker.” In session, the adolescent mentions that last week two peers were arguing, and the client helped one calm down and return to class. A teacher later said, “You showed real leadership today.” The client shrugs and calls it a fluke. The therapist is using narrative therapy. Which intervention should the therapist use next?',
		'option_a'       => 'Externalize the “troublemaker” story, map its effects, and identify when the adolescent has resisted it and how it shapes school relationships.',
		'option_b'       => 'Use the leadership event to construct a richer preferred-identity narrative by tracing the adolescent’s choices, intentions, and personal qualities that made the event possible.',
		'option_c'       => 'Deconstruct the school labels, compare who reinforces them and whose interests they serve, and identify descriptions that fit the adolescent’s preferred identity.',
		'option_d'       => 'Develop a therapeutic letter that contrasts the “troublemaker” story with the leadership event and identifies language for the adolescent’s preferred identity.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-089',
		'question_text'  => 'A family was displaced by a wildfire one week ago. Everyone is physically safe and staying temporarily with relatives, but the children are out of school, routines are disrupted, the parents are irritable and exhausted, and family members repeatedly check emergency alerts despite the immediate danger having passed. Which intervention is BEST?',
		'option_a'       => 'Normalize common early reactions and coping needs, strengthen natural supports, and monitor family routines as immediate danger recedes.',
		'option_b'       => 'Assess trauma symptoms and coping needs, coordinate school support, and monitor family routines before deciding on further treatment.',
		'option_c'       => 'Address immediate resource and coping needs, restore predictable family routines, and strengthen natural supports while monitoring early recovery.',
		'option_d'       => 'Coordinate housing resources and coping support, restore family routines, and introduce structured trauma work after immediate logistics stabilize.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-090',
		'question_text'  => 'A client has met the agreed treatment goals, maintained the gains outside therapy, and agrees that treatment should end. Which termination plan is BEST?',
		'option_a'       => 'Set a shared ending timeline; review gains plus warning signs; document maintenance plus reentry options.',
		'option_b'       => 'Use two final sessions for summary; review coping resources plus warning signs; invite return if symptoms recur.',
		'option_c'       => 'Begin an open-ended taper; review stability at wider intervals; end when recurrence risk becomes minimal.',
		'option_d'       => 'Add a brief growth phase; set new goals plus progress measures; reconsider termination after another treatment cycle.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-091',
		'question_text'  => 'A client describes distinct periods of markedly increased activity, very little need for sleep, unusual confidence, and impulsive spending alternating with periods of significant depression. The client is not currently in acute danger. Which additional evaluation is MOST appropriate?',
		'option_a'       => 'Refer for a medical evaluation to determine whether a physical condition could account for the episodic changes in mood and activity.',
		'option_b'       => 'Refer for psychological testing to clarify personality structure and determine whether the impulsive behavior reflects a stable pattern.',
		'option_c'       => 'Continue outpatient assessment until the therapist can determine whether the symptoms meet criteria for a specific mood disorder.',
		'option_d'       => 'Refer for psychiatric evaluation because the episodic mood, sleep, and behavioral changes warrant specialized psychiatric assessment.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-092',
		'question_text'  => 'For six months, a client has recurrent episodes during severe stress in which the client feels detached from the body and describes the environment as “dreamlike and unreal.” During the episodes, the client states, “I know the world hasn\'t actually changed—it just feels unreal.” Medical and substance evaluations have not identified another explanation, and the episodes cause significant distress. Which diagnosis is MOST supported?',
		'option_a'       => 'Panic disorder',
		'option_b'       => 'Depersonalization/derealization disorder',
		'option_c'       => 'Schizophrenia spectrum disorder',
		'option_d'       => 'Dissociative identity disorder',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-093',
		'question_text'  => 'A couple has identified a recurring pursue–withdraw cycle. Both partners want fewer escalated arguments; one also wants more emotional closeness, while the other wants respectful space during conflict. Which goal structure is MOST appropriate for the current stage of treatment?',
		'option_a'       => 'Set a pause goal for four of five conflicts; schedule two weekly connection activities; track argument frequency and repair quality.',
		'option_b'       => 'Set a pause-and-return goal for four of five conflicts; schedule connection and space routines; track successful repair and responsiveness together.',
		'option_c'       => 'Set a trigger-awareness goal for four of five conflicts; schedule two weekly vulnerability talks; track insight and emotional disclosure regularly.',
		'option_d'       => 'Set a needs-sharing goal for four of five conflicts; schedule brief engagement periods; track pursuit and withdrawal during disagreements carefully.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-094',
		'question_text'  => 'A client reports anxiety that varies considerably from week to week and has difficulty describing whether overall symptoms are improving. The therapist wants additional information that can be compared over time. Which approach is MOST appropriate?',
		'option_a'       => 'Use a broad personality inventory to determine whether anxiety reflects a stable trait pattern rather than a recent change.',
		'option_b'       => 'Repeat the clinical interview at several visits and defer standardized measurement until the symptom pattern becomes more consistent across time.',
		'option_c'       => 'Administer a brief validated anxiety measure to establish a baseline and interpret the score alongside clinical interview and functioning data.',
		'option_d'       => 'Administer several symptom measures at the same visit and use agreement across scores to estimate the client’s current anxiety severity.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-095',
		'question_text'  => 'A client reports that a reduction in work hours has made it difficult to cover basic expenses. The client has food for the next several days through a neighborhood pantry, but shows the therapist a utility shutoff notice scheduled for tomorrow and says the loss of electricity would make it difficult to remain in the apartment. Which referral should the therapist prioritize?',
		'option_a'       => 'Refer the client to a food-assistance agency that can address recurring grocery needs while the reduction in work hours continues.',
		'option_b'       => 'Refer the client to an employment-services agency that can address income recovery through job-search, résumé, and placement assistance.',
		'option_c'       => 'Refer the client to a housing-stability agency that can address budgeting and longer-term risks to maintaining the apartment.',
		'option_d'       => 'Refer the client to an emergency energy-assistance agency that can prevent tomorrow’s shutoff and provide continued utility assistance if eligible.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-096',
		'question_text'  => 'A client moved to a new city six months ago and now spends most evenings alone. Before relocating, the client had several close friendships and participated regularly in community activities. The client says, “Maybe I’m just becoming someone who prefers being alone.” What should the therapist assess NEXT?',
		'option_a'       => 'Assess mood, motivation, pleasure, sleep, and whether reduced participation reflects depression.',
		'option_b'       => 'Review the client’s closest current relationships, frequency of contact, reciprocity, and whether at least one dependable person remains available during stress.',
		'option_c'       => 'Compare pre-relocation and current social functioning, desired connection, support access, and barriers to participation.',
		'option_d'       => 'Assess opportunities for community involvement, work relationships, neighborhood familiarity, and whether limited access rather than preference is restricting social contact.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-097',
		'question_text'  => 'A transgender adult wants to maintain a relationship with the parents but leaves family visits exhausted. The parents sometimes use the client’s correct name yet continue asking invasive questions and invite a relative who makes demeaning comments. The client says, “I do not want to cut them off. I want a relationship if I can protect myself.” Which intervention best fits the client’s stated goal?',
		'option_a'       => 'Collaboratively identify relatives who consistently affirm the client, compare the emotional cost of different family contacts, and design a contact pattern that increases time with safer relationships.',
		'option_b'       => 'Define visit-specific boundaries, practice concise responses to invasive or demeaning comments, and decide in advance how the client will limit contact if those boundaries are crossed.',
		'option_c'       => 'Collaboratively process grief and ambivalence about parental acceptance while clarifying what degree of closeness remains consistent with the client’s wellbeing.',
		'option_d'       => 'Collaboratively map affirming and harmful interactions across family members and decide which relationships to deepen, limit, or approach under conditions the client chooses.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-098',
		'question_text'  => 'A therapist whose parent died recently is treating a client with a similar loss. The therapist notices unusually strong identification with the client, repeatedly extends sessions, and feels an urge to steer the client toward the therapist\'s own preferred way of grieving. What should the therapist do NEXT?',
		'option_a'       => 'Use consultation to select a structured clinical grief protocol, reinforce treatment boundaries, monitor whether the therapist can follow the plan without extending sessions or directing the client\'s grieving, and document the consultation conclusions.',
		'option_b'       => 'Use consultation focused on the overidentification, consistent clinical boundaries, and continued observation of whether personal grief is shaping treatment decisions.',
		'option_c'       => 'Use consultation to assess whether limited self-disclosure could benefit treatment, disclosing only with a clear clinical purpose.',
		'option_d'       => 'Use consultation to assess whether reduced session frequency, stricter treatment structure, or referral is needed if the therapist\'s reactions persist despite clearer boundaries.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-099',
		'question_text'  => 'In conjoint treatment, one partner has become increasingly quiet and has begun missing sessions after perceiving that the therapist repeatedly accepts the other partner’s explanation of the problem. What should the therapist do NEXT?',
		'option_a'       => 'Name the concern plus current formulation; invite both partners’ reactions openly; continue the existing process for three additional sessions.',
		'option_b'       => 'Meet with the quieter partner; invite feedback about perceived imbalance; resume conjoint work using the existing process.',
		'option_c'       => 'Name the possible rupture with both partners; examine the therapist’s contribution; revise the conjoint process using their feedback.',
		'option_d'       => 'Structure equal speaking time for both partners; gather feedback after each session; revise the process only if attendance remains inconsistent.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-100',
		'question_text'  => 'A grandmother lives with her adult daughter, son-in-law, and 14-year-old grandchild. During family sessions, the parents try to set a limit on late-night gaming, but the grandmother immediately tells the adolescent that the rule is too strict. The mother then looks to the grandmother for approval, the father becomes quiet, and the adolescent appeals directly to the grandmother. The therapist is using structural family therapy. Which intervention should the therapist use next?',
		'option_a'       => 'Use a live enactment of the disagreement and coach the parents to state the limit together while the grandmother observes the new hierarchy.',
		'option_b'       => 'Use hierarchy mapping to coach the adolescent to bring limit questions to the parents, strengthen their shared response, and position the grandmother in a supporting role.',
		'option_c'       => 'Join the grandmother’s concern, coach the parents to negotiate the gaming limit, strengthen the parental subsystem, and clarify how the grandmother can support the decision.',
		'option_d'       => 'Use structured turn-taking to direct the adults to present the parental decision and coach the grandmother to respond after that decision is clear.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
);
