<?php
/**
 * LMFT California Clinical — Comprehensive Simulation Form A items 101–125 (PROMPT 05).
 * Learner-facing stems and choices only. Answer keys deferred to admin merge.
 *
 * @package CTA_LMS
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-101',
		'question_text'  => 'A client\'s alcohol use has increased over the past year. The client has missed work, argues more frequently with a partner after drinking, and has unsuccessfully attempted to reduce use. Which assessment is MOST appropriate?',
		'option_a'       => 'Map changes in alcohol use, impaired control, attempts to cut down, and work and relationship consequences over the past year.',
		'option_b'       => 'Assess quantity, frequency, tolerance, withdrawal, morning use, and whether increasing amounts are needed for the same effect.',
		'option_c'       => 'Explore mood triggers, recent stressors, coping motives, relationship conflict, and whether use increases during emotional distress.',
		'option_d'       => 'Review partner concerns, workplace consequences, family history, prior treatment, and the client’s previous attempts to change drinking.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-102',
		'question_text'  => 'A client whose parent recently died reports participating in mourning practices that several relatives criticize as “dwelling on the loss.” The client continues working but has withdrawn from some social activities and feels increasingly misunderstood by family members. What should the therapist assess NEXT?',
		'option_a'       => 'Compare grief intensity, duration, sleep, appetite, and functioning with common bereavement patterns to identify whether the response is unusually severe.',
		'option_b'       => 'Assess family criticism, conflict, available support, cultural expectations, and whether relatives’ reactions are worsening the client’s social withdrawal.',
		'option_c'       => 'Explore the meaning of the loss, cultural grieving practices, support, functional changes, and areas of conflict with family expectations.',
		'option_d'       => 'Review prior losses, coping responses, spiritual beliefs, rituals, and whether the current grief resembles or differs from earlier bereavement experiences.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-103',
		'question_text'  => 'A 41-year-old client presents with depression. After a recent antidepressant dose increase, the client became unusually energetic and slept less for several days. Further history reveals that four years earlier—before taking psychiatric medication—the client had an eight-day period of expansive mood, markedly reduced need for sleep, grandiosity, pressured speech, and impulsive business decisions that caused serious occupational impairment. Which diagnosis is MOST supported by the longitudinal history?',
		'option_a'       => 'Substance/medication-induced bipolar and related disorder',
		'option_b'       => 'Major depressive disorder with mixed features',
		'option_c'       => 'Bipolar I disorder',
		'option_d'       => 'Cyclothymic disorder',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-104',
		'question_text'  => 'Three months after one partner disclosed an emotional affair, the couple wants to repair the relationship. The injured partner repeatedly asks for details and checks the other partner’s phone. The other partner becomes defensive and shuts down, which increases suspicion and leads to more questioning. Which intervention should the therapist use next?',
		'option_a'       => 'Set temporary transparency agreements and review whether predictable access to information reduces suspicion and repeated reassurance seeking.',
		'option_b'       => 'Explore dissatisfaction that preceded the affair and delay focused trust conversations until both partners understand the contributing relationship factors.',
		'option_c'       => 'Limit repeated discussion of the affair and emphasize current positive interactions so the couple can reduce conflict and rebuild connection.',
		'option_d'       => 'Structure focused repair conversations that address unanswered trust concerns while interrupting the accusation-withdrawal pattern that keeps the injury active.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-105',
		'question_text'  => 'A 16-year-old client with improving anxiety says a parent still checks every assignment, contacts teachers before the teen can do so, and answers questions for the teen during appointments. The teen wants more independence but worries about making mistakes. There is no current safety concern. Which intervention should the therapist use?',
		'option_a'       => 'Have the teen take over school communication immediately and ask the parent to stop monitoring assignments unless the teen requests help.',
		'option_b'       => 'Keep the current level of parent involvement while the teen practices anxiety-management skills, then reduce support after confidence improves.',
		'option_c'       => 'Explore the parent’s fears about the teen becoming independent and postpone behavioral changes until both understand the source of the overinvolvement.',
		'option_d'       => 'Create graded independence tasks, define when the parent will step back, and review mistakes as practice rather than reasons to resume control over time.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-106',
		'question_text'  => 'An established client begins sending lengthy descriptions of trauma memories and relationship conflicts to the therapist\'s personal mobile number between sessions. The therapist previously used that number only for scheduling and has not established expectations for clinical messaging. What should the therapist do FIRST?',
		'option_a'       => 'Address the communication pattern, move clinical exchanges to an appropriate treatment channel, and establish clear response expectations after checking any immediate needs in the messages.',
		'option_b'       => 'Move the messages into the clinical record, continue responding briefly from the same number, and tell the client that detailed clinical work should occur during scheduled sessions.',
		'option_c'       => 'Ask the client to stop sending clinical material to the personal number, provide a secure messaging option, and explain that the therapist will read future messages only during business hours.',
		'option_d'       => 'Block clinical messages on the personal number, direct the client to use the emergency resources listed in the treatment agreement, and revisit between-session communication at the next appointment.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-107',
		'question_text'  => 'A client attends through an employee-assistance referral and states, “I don\'t think I need therapy. I just need proof that I showed up.” The client denies having any personal treatment goals. Which action should the therapist take FIRST?',
		'option_a'       => 'Clarify the employer’s concerns, the client’s agreement or disagreement, and whether work functioning is a meaningful therapy focus.',
		'option_b'       => 'Clarify documentation requirements, confidentiality limits, the client’s expectations, and whether sessions should focus mainly on referral concerns.',
		'option_c'       => 'Clarify participation consequences, the client’s reservations, practical concerns, and whether a short-term goal feels worth addressing now.',
		'option_d'       => 'Clarify referral requirements, the client’s perspective, and whether a personally meaningful goal can coexist with mandated attendance.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-108',
		'question_text'  => 'A client reports a substantial decrease in sexual desire during the past four months. During the same period, the client started a new medication and the couple began having more frequent relationship conflict. Which assessment should the therapist conduct NEXT?',
		'option_a'       => 'Clarify the timing of desire changes relative to medication, health, relationship tension, sexual experiences, and the client’s level of distress over time.',
		'option_b'       => 'Assess medication effects, other physical symptoms, sleep, energy, and whether desire changed before or after the recent treatment adjustment.',
		'option_c'       => 'Assess relationship satisfaction, conflict frequency, emotional closeness, sexual communication, and whether desire changes track periods of greater couple tension.',
		'option_d'       => 'Review prior sexual functioning, expectations about desire, cultural or relational meaning, and whether similar changes have occurred during earlier stressful periods.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-109',
		'question_text'  => 'A client had to leave an apartment unexpectedly after a major plumbing failure made it temporarily uninhabitable. During the past two weeks, the client has been staying with friends while searching for housing and reports muscle tension, irritability, difficulty sleeping, and trouble concentrating. There is no injury, trauma reexperiencing, or acute safety concern. Which intervention should the therapist use?',
		'option_a'       => 'Use stress-management treatment to restore sleep and activity routines and practice brief relaxation during predictable periods of displacement stress.',
		'option_b'       => 'Use acceptance-based treatment to reduce reactivity to housing uncertainty, plan regular social contact, and maintain flexible routines during displacement stress.',
		'option_c'       => 'Use problem-solving treatment to plan housing tasks, schedule administrative breaks, and organize daily search demands during displacement stress.',
		'option_d'       => 'Use behavioral activation to increase social support and restorative activities and review which routines improve functioning during displacement stress.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-110',
		'question_text'  => 'An adult daughter repeatedly mediates conflict between her parents and then becomes similarly overinvolved in disagreements within her own partnership. The pattern has persisted across generations and intensifies when family anxiety rises. Which treatment plan is MOST consistent with multigenerational family-systems theory?',
		'option_a'       => 'Map generational boundaries, strengthen parental leadership, and reduce interactions placing the daughter between familial subsystems.',
		'option_b'       => 'Identify the mediating sequence, prescribe tasks that interrupt it, and track whether conflict decreases consistently.',
		'option_c'       => 'Access attachment fears, shape responsive partner interactions, and reduce recurring withdrawal within the daughter’s partnership.',
		'option_d'       => 'Map interlocking triangles, increase differentiation amidst family stress, and reduce reactive overfunctioning through direct contact.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-111',
		'question_text'  => 'A 17-year-old client is in therapy for longstanding body dissatisfaction. Over the past month, the client has begun skipping lunch several days a week, weighing themself repeatedly, and spending hours viewing fitness-content accounts. A recent medical visit found no acute instability, and a specialized eating-disorder consultation is already scheduled. Which intervention should the therapist use now to address the client’s body-image treatment goal?',
		'option_a'       => 'Identify body features the client values and replace harsh appearance statements with balanced descriptions during daily self-observation.',
		'option_b'       => 'Map how appearance-focused media feeds restriction and build routines that broaden self-worth beyond body size and appearance comparisons.',
		'option_c'       => 'Set regular eating goals with the client and use weekly weight changes to evaluate body-image treatment progress.',
		'option_d'       => 'Explore family messages about appearance and delay behavior change until the client identifies the origin of body concerns.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-112',
		'question_text'  => 'A client with a chronic medical condition reports inconsistent adherence to treatment. Physical symptoms have worsened, family members have taken on additional caregiving responsibilities, and conflict has increased. What should the therapist clarify FIRST?',
		'option_a'       => 'Clarify the current medical regimen, adherence pattern, symptom change, daily functioning, and caregiving burden before interpreting family conflict.',
		'option_b'       => 'Clarify couple conflict, division of caregiving, illness beliefs, communication patterns, and whether relationship stress affects adherence.',
		'option_c'       => 'Clarify prior relationship functioning, caregiver stress, family roles, available support, and how conflict changed as symptoms worsened.',
		'option_d'       => 'Clarify medical history, treatment response, health literacy, access barriers, and beliefs about care before evaluating family effects.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-113',
		'question_text'  => 'A client has substantially restricted food intake for eight months and is now at significantly low body weight. The client has an intense fear of gaining weight, repeatedly checks body size, and continues restricting despite recommendations for weight restoration. Despite the low weight, the client describes the abdomen and thighs as “still too large” and reports that self-worth depends heavily on maintaining strict control over weight and shape. There are no recurrent binge or purging episodes. Which diagnosis is MOST supported?',
		'option_a'       => 'Avoidant/restrictive food intake disorder',
		'option_b'       => 'Bulimia nervosa',
		'option_c'       => 'Anorexia nervosa',
		'option_d'       => 'Body dysmorphic disorder',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-114',
		'question_text'  => 'An engaged couple plans to marry next year. They repeatedly argue about how much money should remain separate, how often extended family should be involved in decisions, and what each expects marriage to change. Both remain committed to the relationship but say these conversations quickly become unproductive. Which premarital intervention should the therapist use?',
		'option_a'       => 'Clarify expectations about money, family involvement, and decision-making, then rehearse a structured negotiation process for recurring differences.',
		'option_b'       => 'Explore family-of-origin beliefs about marriage and identify how inherited expectations shape each partner’s reactions during disagreements.',
		'option_c'       => 'Create a detailed household and financial plan first, then reassess commitment expectations after the couple has reduced practical uncertainty.',
		'option_d'       => 'Teach validation and reflective listening during conflict, then postpone major decisions until both partners can discuss differences with less escalation.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-115',
		'question_text'  => 'A therapist learns that an ongoing client has joined the same volunteer disaster-response committee on which the therapist coordinates team assignments. The client cannot reasonably switch committees, and the therapist will occasionally assign volunteers to tasks. Therapy has been effective. What is the therapist\'s BEST response?',
		'option_a'       => 'Keep both roles, arrange another coordinator for the client\'s assignments, document the client-role, privacy, confidentiality and power plan, and review treatment boundaries and clinical judgment if committee contact affects therapy.',
		'option_b'       => 'Discuss the overlapping roles, power and confidentiality risks, limit the therapist\'s committee authority over the client when feasible, set boundaries, and monitor clinical judgment.',
		'option_c'       => 'Review the dual-role, client-boundary, confidentiality, privacy and power concerns, document the client\'s preference about therapy, and use that preference when deciding whether the therapist keeps the coordinator role.',
		'option_d'       => 'Continue both roles, document the client-boundary, confidentiality, privacy and power plan, establish committee-only communication, and consider referral if clinical judgment concerns emerge.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-116',
		'question_text'  => 'A recently immigrated family faces possible forced separation. Family members have also experienced repeated discrimination, the parents are afraid to approach unfamiliar institutions, routines have deteriorated, and the children are becoming increasingly anxious. The family\'s preferred language is not English. Which intervention is MOST appropriate?',
		'option_a'       => 'Assess anxiety and family functioning, provide culturally responsive language-accessible support, and connect members with general mental-health resources.',
		'option_b'       => 'Assess practical needs and family functioning, provide culturally responsive language-accessible support, and clarify referral options without making legal predictions.',
		'option_c'       => 'Assess migration-separation history and family functioning, provide culturally responsive language-accessible support, and determine whether trauma-focused treatment is needed first.',
		'option_d'       => 'Assess discrimination and institutional mistrust, provide culturally responsive language-accessible support, and encourage use of trusted community services.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-117',
		'question_text'  => 'A client reports that friendships and romantic relationships frequently end after similar periods of escalating misunderstanding. The client says, “Eventually people always decide I’m too much.” Which assessment would BEST clarify the interpersonal pattern?',
		'option_a'       => 'Compare the most recent rupture with one earlier relationship, identifying similarities, differences, and whether the newest conflict is unusually severe.',
		'option_b'       => 'Assess personality features, emotion regulation, rejection sensitivity, interpersonal expectations, and whether stable traits may contribute to repeated relationship endings.',
		'option_c'       => 'Explore recurring sequences, expectations, communication patterns, repair attempts, and outcomes across several important friendships and romantic relationships.',
		'option_d'       => 'Review the client’s longest-lasting relationships, protective behaviors, successful repairs, and conditions under which closeness has been maintained over time.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-118',
		'question_text'  => 'A client who immigrated several years ago reports discriminatory comments at work and increasing conflict with relatives whose expectations differ from the client\'s evolving cultural values. Which assessment approach is BEST?',
		'option_a'       => 'Explore migration history, cultural identities, workplace discrimination, family expectations, acculturation experiences, available supports, and how these factors affect current functioning.',
		'option_b'       => 'Explore workplace power dynamics, coping responses, employment alternatives, social support at work, and whether distress changes outside the occupational setting.',
		'option_c'       => 'Explore family values, intergenerational expectations, acculturation differences, relationship history, and whether family conflict was present before the current workplace problems.',
		'option_d'       => 'Explore mood and anxiety symptoms, immigration stress, available supports, and whether family or workplace difficulties are producing greater functional impairment.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-119',
		'question_text'  => 'Seven weeks after surviving a violent assault, a client reports recurrent involuntary memories and nightmares, avoids the location and conversations about the assault, and says that nowhere is safe. The client has become detached from family, has lost interest in previously valued activities, remains hypervigilant, and has persistent sleep disturbance. The symptoms substantially interfere with work and relationships. Which diagnosis is MOST supported?',
		'option_a'       => 'Posttraumatic stress disorder',
		'option_b'       => 'Acute stress disorder',
		'option_c'       => 'Panic disorder',
		'option_d'       => 'Adjustment disorder with anxiety',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-120',
		'question_text'  => 'A client in DBT describes an episode in which a delayed reply from the partner led to thoughts of abandonment, mounting anger, repeated texting, and then blocking the partner. The next day, the client regretted the exchange. There is no current safety concern. Which intervention should the therapist use next?',
		'option_a'       => 'Review the diary card, rank repeated texting as the current target, and set a measurable reduction goal for the coming week.',
		'option_b'       => 'Practice paced breathing and wise-mind attention, then plan to use those skills whenever rejection thoughts begin during future conflicts.',
		'option_c'       => 'Validate the client’s sensitivity to rejection, complete a pros-and-cons exercise, and strengthen commitment to changing impulsive communication.',
		'option_d'       => 'Analyze the episode from prompting event through each link, then rehearse skills at points where the sequence could be interrupted.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-121',
		'question_text'  => 'An adult client is receiving individual psychotherapy. The client\'s mother pays the therapist directly for each session but is not a client and has no authorization to receive treatment information. The mother calls and asks whether therapy is helping and what the therapist thinks the client should do next. What is the therapist\'s BEST response?',
		'option_a'       => 'Explain that fee payment does not authorize disclosure of the client\'s treatment information, discuss what limited communication the client wants authorized, and document the client\'s decision.',
		'option_b'       => 'Tell the mother that attendance may be confirmed but confidential treatment content may not, then ask the client whether broader communication should be authorized.',
		'option_c'       => 'Give a general progress update that omits confidential session details and diagnosis, because the mother is paying for treatment.',
		'option_d'       => 'Tell the mother that no treatment information can be shared without client authorization and route future treatment questions through the client.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-122',
		'question_text'  => 'A therapist has been sleeping poorly for several weeks while caring for an ill family member. The therapist notices increasing difficulty concentrating in sessions, has forgotten two promised follow-up calls, and recently missed an important detail in a client\'s treatment history. What should the therapist do NEXT?',
		'option_a'       => 'Reduce high-complexity appointments, use written session checklists, and arrange administrative backup while keeping the overall clinical caseload unchanged and reviewing concentration each week.',
		'option_b'       => 'Shorten selected sessions, notify affected clients about reduced availability, and arrange follow-up coverage while monitoring concentration and missed tasks during the next several weeks.',
		'option_c'       => 'Move complex cases to earlier hours, delegate administrative work, and reduce same-day scheduling while monitoring whether the therapist can safely maintain the existing caseload.',
		'option_d'       => 'Reduce the workload to current safe capacity, arrange continuity for affected clients, and address the impairment before returning to the prior workload.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-123',
		'question_text'  => 'A client repeatedly tests partners’ commitment, expects abandonment, and interprets ordinary separations as evidence that close others will disappear. These patterns are linked to inconsistent early caregiving. Which treatment plan is MOST consistent with an attachment-informed psychodynamic approach?',
		'option_a'       => 'Explore recurring fears of loss, use consistent therapeutic contact, and build reflective capacity during separations.',
		'option_b'       => 'Identify feared outcomes, test them through planned separations, and gradually reduce reassurance using behavioral experiments.',
		'option_c'       => 'Rank self-harm and relationship-testing targets, analyze behavior chains, and consistently teach distress-tolerance plus interpersonal skills.',
		'option_d'       => 'Identify exceptions to loss concerns, assess confidence in closeness, and develop strategies from helpful separations.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-124',
		'question_text'  => 'In couples therapy after one partner lost a job, that partner has become quiet and avoids discussing finances. The other partner responds with criticism: “You don’t even seem to care what happens to us.” As the therapist slows the exchange, the critical partner identifies fear about losing the home, while the withdrawn partner describes shame about feeling like a failure. The therapist is using emotionally focused therapy. Which intervention should the therapist use next?',
		'option_a'       => 'Map the criticism-withdrawal cycle and reframe the recurring interaction as their shared attachment problem rather than either partner’s personal defect.',
		'option_b'       => 'Deepen each partner’s fear and shame, then facilitate direct expressions of those vulnerable emotions and attachment needs to the other partner.',
		'option_c'       => 'Heighten the critical partner’s anger and the withdrawn partner’s need for distance so both can express the positions that organize the recurring cycle.',
		'option_d'       => 'Validate both partners’ distress and ask each to identify one supportive response they can practice together when financial conversations become emotionally difficult.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FA-125',
		'question_text'  => 'A high-school student with a history of strong grades has experienced a substantial academic decline during the semester following a family relocation. The student says, “I just can\'t get myself organized here.” What should the therapist evaluate FIRST?',
		'option_a'       => 'Compare current and prior academic functioning, timing of the decline, school-transition demands, peer context, and organizational difficulties.',
		'option_b'       => 'Assess attention and executive history, earlier school performance, task completion, distractibility, and whether similar problems predated relocation.',
		'option_c'       => 'Assess mood, anxiety, sleep, social adjustment, family stress, and whether emotional changes began around the academic decline.',
		'option_d'       => 'Compare teacher reports, course demands, attendance, assignment completion, and performance across subjects since the student entered the new school.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
);
