<?php
/**
 * LMFT California Clinical — Comprehensive Simulation Form B items 101–125 (PROMPT 11).
 * Learner-facing stems and choices only. Answer keys deferred to admin merge.
 *
 * @package CTA_LMS
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-101',
		'question_text'  => 'A recently returned service member in couples therapy is quiet during conflict and says, “On deployment, staying contained and handling the task mattered. At home my partner thinks I do not care.” The partner says the silence feels rejecting. Both want to communicate better without treating the service member’s military experience as a defect. Which intervention should the therapist use?',
		'option_a'       => 'Validate how emotional containment served the deployment context, then build more flexible signals for engagement and reassurance at home.',
		'option_b'       => 'Teach direct emotion-labeling skills and ask the partner to reinforce each attempt at verbal disclosure during disagreements and repair conversations.',
		'option_c'       => 'Help the partner reduce demands for immediate discussion and give the service member more decompression time before returning to difficult conversations.',
		'option_d'       => 'Screen for trauma symptoms and shift to individual trauma treatment only if those symptoms become the main barrier.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-102',
		'question_text'  => 'A client describes recurring racial microaggressions at work and reports becoming increasingly vigilant after a recent highly publicized sociopolitical event. The client says, “Maybe I\'m just overreacting.” What should the therapist do NEXT?',
		'option_a'       => 'Explore discrimination, racial identity, sociopolitical context, coping, supports, and current functioning.',
		'option_b'       => 'Assess anxiety, vigilance, sleep, concentration, somatic arousal, and whether symptoms occur across settings without discrimination-related triggers.',
		'option_c'       => 'Review workplace incidents, organizational responses, power dynamics, support from colleagues, and whether occupational functioning has changed over time.',
		'option_d'       => 'Explore the recent public event, media exposure, prior experiences of discrimination, community reactions, and whether distress increased specifically after that event.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-103',
		'question_text'  => 'A client with a suicide attempt five years ago reports several recent episodes of superficial self-injury during periods of dissociation after interpersonal conflict. The client says the current behavior is intended to interrupt numbness, denies current suicidal intent, plan, or preparation, has no medically serious injury, and can identify supports and follow a safety plan. What should the therapist do NEXT?',
		'option_a'       => 'Reassess current suicide risk, arrange a same-day crisis evaluation, and involve the partner in transfer because of the documented remote attempt.',
		'option_b'       => 'Reassess current suicide risk, address the dissociation-linked self-injury pattern, and increase near-term outpatient follow-up this week.',
		'option_c'       => 'Reassess current suicide risk, begin trauma-focused stabilization, keep the usual session frequency while monitoring injuries, and review dissociation triggers during follow-up.',
		'option_d'       => 'Reassess current suicide risk, involve the partner in continuous monitoring, and postpone independent coping until the urges resolve.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-104',
		'question_text'  => 'An adult client reports episodes of binge eating several evenings each week after trying to eat as little as possible during the day. Afterward the client feels ashamed and responds by imposing even stricter food rules the next morning. Medical monitoring is established and there is no current instability. Which intervention should the therapist use?',
		'option_a'       => 'Use body-neutrality exercises, reduce appearance checking, and establish regular self-care routines unrelated to food while reviewing how body dissatisfaction changes across the week.',
		'option_b'       => 'Map rigid daytime restriction to evening binges and replace restrictive food rules with a more consistent eating pattern that interrupts the cycle.',
		'option_c'       => 'Use urge-surfing during binge impulses and have the client notice changes in urge intensity before making an eating decision.',
		'option_d'       => 'Explore family and cultural messages about food and weight, then use self-compassion after episodes to reduce shame.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-105',
		'question_text'  => 'A client\'s attorney, who is not providing health care to the client, requests a copy of the client\'s psychotherapy records. The attorney sends a signed and dated release that names the therapist and attorney and describes the records to be released, but the release contains no expiration date or expiration event. There is no subpoena, court order, or other legal basis for disclosure. What should the therapist do?',
		'option_a'       => 'Do not disclose under the defective authorization; document the deficiency, request a corrected authorization with the required expiration element, and release the client records only after valid authority is established.',
		'option_b'       => 'Honor the signed authorization, document the client-record request and named recipient, and disclose the specified records because the release clearly identifies the therapist, attorney, and information involved.',
		'option_c'       => 'Contact the client for verbal confirmation, document the written authorization, client confidentiality, record scope and current intent, and disclose the specified records because the release otherwise identifies the recipient and requested information.',
		'option_d'       => 'Provide a limited record summary, document the authorization and narrower disclosure, and treat the client\'s signed release as sufficient because fewer client records are being released than requested.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-106',
		'question_text'  => 'An adult client is receiving trauma-focused therapy after a serious motor-vehicle collision. While recounting part of the crash, the client becomes numb, says the room seems unreal, reports tingling in both hands, and loses track of what the therapist is saying. The client is not in immediate danger. Which intervention should the therapist use next?',
		'option_a'       => 'Label the numbness and tingling as trauma responses, use paced breathing, and structure the narrative into shorter segments while continuing.',
		'option_b'       => 'Reframe the physical sensations as conditioned fear, test catastrophic interpretations, and practice coping responses during the session.',
		'option_c'       => 'Shift to interoceptive exercises, coach regulation, and process the physical sensations as exposure targets.',
		'option_d'       => 'Orient the client to the present with grounding, then continue trauma work in smaller, tolerable segments.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-107',
		'question_text'  => 'A 15-year-old who identifies as nonbinary reports feeling comfortable with identity and body in an affirming school setting and denies distress about sex characteristics or a desire to change them. Two months ago, family members began openly rejecting the adolescent\'s identity. Since then, the adolescent has developed marked anxiety, sleep disturbance, difficulty concentrating, and significant impairment in functioning at home. The symptoms remain centered on the family rejection. Which diagnosis is MOST supported?',
		'option_a'       => 'Gender dysphoria involving persistent incongruence-related distress across supportive and rejecting settings.',
		'option_b'       => 'Generalized anxiety disorder involving broad worry across multiple unrelated life domains.',
		'option_c'       => 'Adjustment disorder with anxiety following the identifiable family-rejection stressor at home.',
		'option_d'       => 'Social anxiety disorder centered on scrutiny, embarrassment, and negative evaluation.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-108',
		'question_text'  => 'A roommate interrupted a suicide attempt earlier the same day. The original means is no longer available, but the client states that the intention to die remains and that another method will be found if the client leaves unsupervised. What should the therapist do FIRST?',
		'option_a'       => 'Maintain observation, arrange emergency psychiatric evaluation, and report the interrupted attempt with continuing intent.',
		'option_b'       => 'Maintain direct observation, remove remaining lethal means with the roommate, arrange same-day urgent psychiatric follow-up, and confirm a receiving appointment before transfer.',
		'option_c'       => 'Maintain direct observation, complete emergency suicide-risk consultation, and decide disposition after the client’s acute distress has meaningfully decreased.',
		'option_d'       => 'Maintain direct observation, arrange continuous roommate supervision, and schedule same-day psychiatric care with frequent check-ins.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-109',
		'question_text'  => 'A client arrives markedly sedated after taking a prescribed benzodiazepine together with an opioid pain medication and alcohol. The client repeatedly falls asleep while speaking, is difficult to awaken, and breathing appears slower than normal. What should the therapist do FIRST?',
		'option_a'       => 'Keep direct observation, activate EMS for immediate hospital transport, and monitor respiratory status until transfer occurs.',
		'option_b'       => 'Keep direct observation, contact the prescribing clinician for urgent guidance, arrange emergency-department transport with a responsible adult, and notify receiving staff of the combined depressant exposure.',
		'option_c'       => 'Keep direct observation, obtain poison-control or medical disposition guidance, and follow the recommended urgent transfer while monitoring alertness.',
		'option_d'       => 'Keep direct observation, arrange urgent same-day medical evaluation, and escalate transfer if alertness or breathing fails to improve.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-110',
		'question_text'  => 'An adult client with schizoaffective disorder is psychiatrically stable but continues to show blunted affect and slowed responses. A parent interprets this as “not trying,” and arguments about chores have increased. The client says, “I want my family to understand this is not laziness.” Which intervention should the therapist use?',
		'option_a'       => 'Help the client explain current needs and ask the parent to use less criticism on low-energy days.',
		'option_b'       => 'Ask the parent to notice times when the client joins in more and reinforce those efforts at home.',
		'option_c'       => 'Provide psychoeducation about persistent symptoms and set concrete household expectations consistent with current functioning.',
		'option_d'       => 'Use collaborative chore problem-solving without emphasizing symptoms so the family does not interpret every difficulty through the disorder.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-111',
		'question_text'  => 'A parent involved in a prolonged family-court matter reports increased anxiety, disrupted parenting routines, and growing distrust of professionals. The client repeatedly asks the therapist whether the court has treated the client fairly. What should the therapist do NEXT?',
		'option_a'       => 'Clarify the court timeline, disputed issues, attorney involvement, and whether the client’s account of unfair treatment matches available legal information.',
		'option_b'       => 'Assess anxiety severity, sleep, concentration, avoidance, and whether symptoms persist independently of court-related events or professional contacts.',
		'option_c'       => 'Assess how court involvement, parenting disruption, and perceived scrutiny affect current functioning and relationships.',
		'option_d'       => 'Review legal-resource needs, advocacy options, documentation concerns, and whether obtaining additional legal guidance would reduce the client’s current uncertainty.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-112',
		'question_text'  => 'A couple in a consensually nonmonogamous relationship is considering moving in together. One partner views cohabitation as a practical next step, while the other worries it could create an implicit primary-partner hierarchy and change responsibilities to other partners. Both want their relationship structure respected and want help deciding what living together would mean. Which intervention should the therapist use next?',
		'option_a'       => 'Explore how attachment histories shape each partner’s expectations for intimacy, independence, and commitment within their consensual nonmonogamous relationship.',
		'option_b'       => 'Revise agreements for privacy, scheduling, and reassurance with other partners before determining whether shared housing would support the relationship.',
		'option_c'       => 'Clarify each partner’s broader values for autonomy, equity, commitment, and belonging across the relationship network before making a housing decision.',
		'option_d'       => 'Help them agree on what living together will mean for rank, time, money, duties, privacy, and ties with other partners.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-113',
		'question_text'  => 'A client reports periods of low mood that fluctuate enough that neither the client nor therapist can tell whether overall symptoms are improving. The therapist wants a structured way to supplement the ongoing clinical evaluation. Which approach is BEST?',
		'option_a'       => 'Use a broad personality inventory now and again near discharge to determine whether stable traits account for changes in the client\'s mood.',
		'option_b'       => 'Use a validated depression measure at baseline and follow-up, interpreting score changes with interview findings, functioning, and the client\'s reported symptom course.',
		'option_c'       => 'Create a daily symptom checklist tailored to the client\'s concerns and use average weekly ratings as the primary indicator of improvement.',
		'option_d'       => 'Use a standardized functioning measure alone and infer improvement in mood from changes in work, social, and self-care performance.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-114',
		'question_text'  => 'A client’s mood scores have improved, but the client has not resumed work or valued activities, remains dependent on family reassurance, and rarely uses skills without prompting. What should the therapist do NEXT?',
		'option_a'       => 'Begin step-down after mood improvement; monitor work and activity recovery; restore weekly care if symptoms or impairment return.',
		'option_b'       => 'Continue treatment for four weeks; address practical barriers; monitor work, valued activity, reassurance use, and independent skill practice.',
		'option_c'       => 'Add another symptom-focused intervention; retain current functional goals; reassess work and activity after completing the next treatment trial.',
		'option_d'       => 'Revise goals toward independent activity and skill use; reduce family reassurance; evaluate functional progress before initiating any step-down.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-115',
		'question_text'  => 'A client with social anxiety mentally rehearses nearly every sentence before speaking to coworkers. The client believes, “If I do not script what I am going to say, I will sound foolish and they will pull away.” The rehearsal reduces uncertainty briefly but makes conversations stiff and self-focused. The therapist is using CBT. Which intervention most directly addresses the maintaining process?',
		'option_a'       => 'Before a coworker interaction, record the feared prediction, generate several alternative explanations, and compare each explanation with what actually happens during and after the conversation.',
		'option_b'       => 'Enter a brief conversation without scripting sentences, record the predicted rejection beforehand, and compare it with the coworker’s actual response.',
		'option_c'       => 'Complete a graded series of workplace conversations while gradually reducing preparation time, rating anxiety and self-focus before and after each interaction, and noting changes across trials.',
		'option_d'       => 'Shift attention to the coworker’s words and nonverbal cues during conversations, then record whether reduced self-monitoring changes the interaction.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-116',
		'question_text'  => 'For ten months, a client has been preoccupied with having a serious neurological disease. The client experiences only occasional mild headaches, but repeatedly checks coordination, searches symptoms online, requests reassurance, and remains highly anxious despite appropriate medical evaluations that have not identified serious disease. Which diagnosis is MOST supported?',
		'option_a'       => 'Somatic symptom disorder',
		'option_b'       => 'Generalized anxiety disorder',
		'option_c'       => 'Illness anxiety disorder',
		'option_d'       => 'Obsessive-compulsive disorder',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-117',
		'question_text'  => 'An adult client sustained a disabling spinal injury three weeks ago. The client is medically stable and beginning rehabilitation but now needs assistance with mobility, transportation, household tasks, and return-to-work planning. The client is frustrated by lost independence but denies suicidal intent and can participate in decisions. What should the therapist prioritize?',
		'option_a'       => 'Assess functional losses and emotional response, provide grief-focused support, identify practical assistance options, and add those resources after distress decreases.',
		'option_b'       => 'Assess functional barriers and mood symptoms, coordinate psychiatric support, and defer transportation or work adaptation until symptoms clinically stabilize.',
		'option_c'       => 'Assess functional barriers and family roles, coordinate household support, and use prior role patterns to guide current adaptation.',
		'option_d'       => 'Assess functional barriers and client priorities, coordinate rehabilitation-accessibility resources, and implement temporary adaptations in daily roles.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-118',
		'question_text'  => 'Following a violent assault, a client is unable to remember several important autobiographical details from the period surrounding the event, including how the client escaped and reached a friend\'s home. Witnesses confirm the client was awake and responsive during that time. There was no head injury, substance use, or neurological condition that explains the memory loss. Which diagnosis is MOST supported?',
		'option_a'       => 'Posttraumatic stress disorder',
		'option_b'       => 'Depersonalization/derealization disorder',
		'option_c'       => 'Mild neurocognitive disorder',
		'option_d'       => 'Dissociative amnesia',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-119',
		'question_text'  => 'A client with chronic musculoskeletal pain has been medically cleared for gradual activity but has become markedly deconditioned after months of avoiding movement. The client wants to resume routine walking and household tasks but becomes fatigued quickly and is unsure how to increase activity without overdoing it. Which adjunct referral best matches the current treatment need?',
		'option_a'       => 'Refer to physical therapy for progressive conditioning and restoration of functional movement.',
		'option_b'       => 'Refer to occupational therapy for pacing and routines supporting function across home, self-care, and work tasks.',
		'option_c'       => 'Refer to pain psychology for focused work on catastrophizing, movement fear, coping skills, and behavioral responses to persistent symptoms.',
		'option_d'       => 'Refer to a rehabilitation physician for medical reassessment of pain contributors, activity restrictions, medication options, and other physical treatment needs.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-120',
		'question_text'  => 'A client has received treatment for anxiety during several periods over the past decade. The client now presents with anxiety again but cannot remember whether earlier episodes began under similar circumstances. Which information should the therapist prioritize?',
		'option_a'       => 'Compare prior diagnoses, medication regimens, clinician impressions, treatment settings, and discharge summaries to identify the best historical formulation.',
		'option_b'       => 'Characterize current anxiety, then review only previous symptoms closely matching the present pattern to determine whether this is recurrence.',
		'option_c'       => 'Reconstruct each prior episode’s onset, context, symptom pattern, duration, treatment response, and functional impact before comparing it with current anxiety.',
		'option_d'       => 'Obtain records or collateral information from the most severe previous episode and use that period as the reference for current symptoms.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-121',
		'question_text'  => 'A school reports that an 8-year-old frequently leaves the seat, interrupts classmates, and fails to complete work. The caregiver reports that the child can spend long periods completing tasks at home and rarely appears restless. Which action should the therapist take NEXT?',
		'option_a'       => 'Compare teacher observations, task demands, classroom supports, and behavior during structured and unstructured school periods.',
		'option_b'       => 'Compare home routines, expectations, task completion, and behavior during activities that require sustained attention.',
		'option_c'       => 'Compare specific behaviors, task demands, supports, and consequences across settings before interpreting the home-school discrepancy.',
		'option_d'       => 'Compare sleep, stress, family routines, and academic workload with the timing of the school concerns.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-122',
		'question_text'  => 'A couple repeatedly argues about household responsibilities. One partner begins with criticism about chores, the other becomes defensive and lists everything already completed, and the first partner responds by escalating the criticism. Both agree the pattern is exhausting and want a better way to resolve the recurring disagreement. Which intervention should the therapist use?',
		'option_a'       => 'Create a shared task plan, define each partner’s responsibilities, and use weekly check-ins to identify where expectations, follow-through, and perceived fairness diverge.',
		'option_b'       => 'Explore family-of-origin meanings of fairness and use those differences to renegotiate how each partner defines an acceptable contribution.',
		'option_c'       => 'Practice de-escalation and time-out skills, then resume the same disagreement using agreed rules for turn-taking, requests, and responses when defensiveness returns.',
		'option_d'       => 'Identify the criticism-defensiveness escalation sequence and coach the couple through one current chore disagreement using a structured problem-solving exchange.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-123',
		'question_text'  => 'A family needs bilingual conjoint treatment for escalating parent–adolescent conflict. During assessment, a trial interpreter-assisted family session prevented direct interaction and caused clinically important relational meaning to be lost. The therapist is not sufficiently proficient in the family’s preferred language to provide the indicated treatment independently. The health plan has no in-network bilingual family therapist within a reasonable distance, but it accepts requests for network-gap exceptions. The family cannot pay privately. Which treatment plan is MOST appropriate?',
		'option_a'       => 'Continue brief interpreter-assisted family bridge sessions; consult about adapting the approach; reassess clinical fit while the family remains on in-network waitlists.',
		'option_b'       => 'Shift to individual treatment for the adolescent; address family effects through caregiver consultation; revisit bilingual family referral if symptoms persist later.',
		'option_c'       => 'Provide a time-limited stabilization bridge within competence; request a network-gap exception; coordinate suitable bilingual options and review access with the family.',
		'option_d'       => 'Give the family plan and community referrals; offer one transition session; close when the bridge period ends regardless of placement.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-124',
		'question_text'  => 'For six months, a client’s household has been under significant financial strain after the family income decreased. Basic needs are currently being met, but the client reports constant mental rehearsal of expenses, jaw tension, headaches, irritability, and staying awake late to recheck the budget. Medical causes for the headaches have been ruled out. Which intervention should the therapist use?',
		'option_a'       => 'Explore the meaning the client attaches to financial security, connect the current worry to earlier experiences of scarcity, and delay behavioral changes until those themes are clearer.',
		'option_b'       => 'Schedule a limited daily problem-solving period for finances, add a brief relaxation practice afterward, and reestablish a consistent bedtime routine.',
		'option_c'       => 'Encourage the client to reduce all discretionary activities, review the budget whenever worry rises, and use distraction only after the numbers have been checked.',
		'option_d'       => 'Focus on challenging catastrophic predictions about money, postpone practical budgeting discussions in therapy, and increase cognitive restructuring when physical tension appears.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-125',
		'question_text'  => 'A separated couple has been attending conjoint therapy with the stated purpose of deciding whether to reconcile. Both now agree that reconciliation is no longer the goal and want to continue with the same therapist solely to improve co-parenting. What should the therapist do BEFORE continuing under the new purpose?',
		'option_a'       => 'Keep the current informed-consent agreement, document the co-parenting treatment purpose, and review privacy expectations with both partners before continuing conjoint work.',
		'option_b'       => 'Review the new treatment purpose, client roles, confidentiality expectations, and limits with both partners, and document their updated informed-consent understanding before continuing.',
		'option_c'       => 'Close the reconciliation treatment, complete a new informed-consent process, open a new co-parenting treatment episode, and document new client roles before any further conjoint session.',
		'option_d'       => 'Meet individually with each partner to review goals, privacy expectations, and client roles before deciding whether conjoint co-parenting treatment should continue.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
);
