<?php
/**
 * LMFT California Clinical — Comprehensive Simulation Form B items 126–150 (PROMPT 12).
 * Learner-facing stems and choices only. Answer keys deferred to admin merge.
 *
 * @package CTA_LMS
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-126',
		'question_text'  => 'Sixteen months after a spouse dies, a client reports that for the past six weeks there has been persistent depressed mood, pervasive inability to experience pleasure, insomnia, impaired concentration, and global worthlessness. The client misses the spouse but says the primary distress is “feeling like a failure as a person in every part of my life” rather than persistent yearning or preoccupation with the deceased. Which diagnosis is MOST supported?',
		'option_a'       => 'Prolonged grief disorder',
		'option_b'       => 'Adjustment disorder with depressed mood',
		'option_c'       => 'Persistent depressive disorder',
		'option_d'       => 'Major depressive disorder',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-127',
		'question_text'  => 'A client cannot clearly remember whether significant mood changes began before or after several medication adjustments. The client authorizes coordination with the prescribing clinician. What should the therapist do NEXT?',
		'option_a'       => 'Ask the client to reconstruct the medication timeline from memory before deciding whether outside information is necessary.',
		'option_b'       => 'Request the complete medical record so the therapist can independently reconstruct how each medication change corresponded with the client’s symptoms over time.',
		'option_c'       => 'With authorization, consult the prescriber or review focused records to clarify medication changes, timing, and observed symptom response.',
		'option_d'       => 'Defer interpretation of the symptom chronology to the prescriber because medication effects fall outside the therapist’s assessment role.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-128',
		'question_text'  => 'A client has repeatedly canceled the appointment immediately after sessions in which the client speaks openly about needing other people. After the latest cancellation, the client returns and says, “I figured you probably thought I was pathetic for needing so much.” The therapist is using a psychodynamic approach. Which intervention should the therapist use?',
		'option_a'       => 'Explore the cancellation as protection from vulnerability and the expectation of the therapist’s disappointment within the current therapeutic relationship.',
		'option_b'       => 'Trace dependency fears to early caregiving relationships and compare those experiences with the client’s current expectations before discussing the missed session.',
		'option_c'       => 'Invite free association to the word pathetic and follow emerging memories, fantasies, and affects without focusing first on the cancellation pattern.',
		'option_d'       => 'Support the client’s capacity to tolerate dependency feelings and postpone interpretation until the client can discuss vulnerable material without missing sessions.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-129',
		'question_text'  => 'A client whose father died in another country says the family values composure in public mourning and expects grief to be expressed mainly through private prayer and family rituals. The client feels sadness and longing but says, “My coworkers keep telling me I need to talk about it more. I am not sure that is how I grieve.” Which intervention should the therapist use?',
		'option_a'       => 'Invite more verbal grief work in session while the client keeps private family rites, and ask what each form gives or costs across time and settings.',
		'option_b'       => 'Compare public and private grieving styles and examine how each affects distress, connection, and functioning across the client’s different settings.',
		'option_c'       => 'Use imagery to facilitate an emotional farewell that supplements the family’s private mourning practices and gives the client another way to express longing.',
		'option_d'       => 'Ask how healthy mourning is understood within the family’s cultural traditions, then support the client’s personally chosen grieving process without requiring increased public emotional disclosure.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-130',
		'question_text'  => 'A client prescribed a sedating anti-anxiety medication reports increasingly taking extra doses beyond the prescribed schedule and occasionally obtaining additional pills from a relative. The client has missed several morning meetings after nighttime use but says, “I only take more when I really need it.” What should the therapist assess NEXT?',
		'option_a'       => 'Clarify dose and frequency, source of extra medication, attempts to limit use, co-use with sedatives, and effects on daily functioning.',
		'option_b'       => 'Clarify anxiety severity, prescriber instructions, medication benefit, and whether symptoms reliably intensify before each additional dose is taken.',
		'option_c'       => 'Review sedation, memory changes, sleep, and work impairment, then determine whether adverse medication effects account for the client’s current concerns.',
		'option_d'       => 'Compare current use with prior prescription periods, family history of addiction, attitudes toward medication misuse, and reasons the client considers the pattern acceptable.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-131',
		'question_text'  => 'A client with alcohol-use problems has attended weekly individual therapy and peer support for three months. Despite a written relapse-prevention plan, the client has returned to heavy drinking on four weekends, missed work twice, and had escalating conflict with a spouse. The client denies withdrawal symptoms, suicidal intent, or current intoxication; housing and medical status are stable. Which treatment adjustment should the therapist recommend?',
		'option_a'       => 'Continue weekly outpatient therapy and refine relapse triggers while monitoring whether drinking episodes decrease over the next month.',
		'option_b'       => 'Increase sessions to twice weekly and add daily self-monitoring before considering a different treatment level.',
		'option_c'       => 'Refer to an intensive outpatient program and coordinate relapse-prevention goals across the program and ongoing therapy.',
		'option_d'       => 'Pause substance-focused work and shift to couple sessions to address relationship conflict before changing the current treatment intensity.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-132',
		'question_text'  => 'A client with a chronic health condition has gradually stopped attending social activities that were previously important. The client says some withdrawal is necessary because of fatigue but also reports feeling increasingly disconnected from friends. What should the therapist assess NEXT?',
		'option_a'       => 'Assess depressive symptoms, loss of interest, sleep, energy, and whether reduced participation exceeds what the health condition alone would explain.',
		'option_b'       => 'Compare social functioning before and after the health changes, including lost activities, support access, participation barriers, and isolation.',
		'option_c'       => 'Assess medical limitations, fatigue patterns, treatment burden, transportation, and whether practical restrictions account for most changes in social participation.',
		'option_d'       => 'Review the client’s strongest relationships, contact, practical assistance, and whether support remains available despite reduced activity.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-133',
		'question_text'  => 'An adolescent wants less family conflict, the parents want greater rule compliance, and the school referral emphasizes attendance. Which initial goal hierarchy is MOST appropriate?',
		'option_a'       => 'Prioritize attendance plus family problem solving; set measurable steps with adolescent/parent input; review progress through a shared hierarchy.',
		'option_b'       => 'Prioritize attendance plus rule compliance; set steps with parent/school input; add adolescent concerns after four weeks.',
		'option_c'       => 'Prioritize conflict reduction plus autonomy; set measurable steps with adolescent input; add attendance after the adolescent endorses it.',
		'option_d'       => 'Prioritize all referral/family goals equally; set measurable steps with each participating stakeholder; review each goal without a shared hierarchy during treatment.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-134',
		'question_text'  => 'A client states that recent self-injury is intended to stop overwhelming emotional pain rather than cause death. The most recent injury has already received appropriate medical treatment. Since then, the urges have intensified; the client reports being unable to interrupt the behavior once it begins and has no dependable person available to help maintain safety after the session. What should the therapist do NEXT?',
		'option_a'       => 'Maintain observation, arrange urgent intensive outpatient contact, restrict access to the methods used for self-injury, and verify same-day support availability.',
		'option_b'       => 'Maintain observation, treat the episode as suicidal behavior, and use emergency psychiatric disposition regardless of the stated nonsuicidal function.',
		'option_c'       => 'Maintain observation, obtain same-day psychiatric crisis consultation, and discharge with an intensive support-based safety plan.',
		'option_d'       => 'Maintain observation, arrange same-day higher-level evaluation, and communicate the client’s inability to maintain safety independently.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-135',
		'question_text'  => 'The parents of a 7-year-old expect the child to calm down alone after frustrating events and view requests for help as “babyish.” The child instead escalates, throws school materials, and then becomes embarrassed. The parents ask how much emotional support is appropriate at this age. Which intervention should the therapist use?',
		'option_a'       => 'Explain age-appropriate co-regulation and teach a parent-guided calming routine that can be faded as the child’s skills improve.',
		'option_b'       => 'Teach an independent calming sequence and have the parents praise successful use while limiting help during outbursts.',
		'option_c'       => 'Help the parents set firmer limits on throwing materials and add consistent consequences before introducing additional emotion-regulation support.',
		'option_d'       => 'Explore the parents’ childhood emotion rules and decide which expectations they want to change.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-136',
		'question_text'  => 'A client seeks therapy after a promotion placed the client in a supervisory role over former peers. The client reports substantial stress related to role conflict, workplace expectations, and strained relationships with coworkers. Functioning remains stable at home, housing and finances are secure, and the client is not enrolled in an educational program. Symptoms do not support an anxiety, depressive, or other mental disorder. Which condition is MOST appropriate as the primary focus of clinical attention?',
		'option_a'       => 'Occupational problem',
		'option_b'       => 'Relationship distress with spouse or intimate partner',
		'option_c'       => 'Educational problem',
		'option_d'       => 'Housing or economic problem',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-137',
		'question_text'  => 'Six months after their parents separated, two siblings move between households on different schedules. Handoffs are tense, family traditions have largely stopped, and both children say they feel as though the family “disappears” whenever they leave one home. The parents want to support the children’s relationships through the transition. Which intervention should the therapist use?',
		'option_a'       => 'Hold separate parent-child sessions to process loss, help each child develop a narrative for moving between homes, and create coping routines for each transition day.',
		'option_b'       => 'Create distinct rituals within each household so each home develops its own predictable sense of family continuity.',
		'option_c'       => 'Build brief handoff rituals and regular cross-home contact while helping the family name how relationships are changing through the separation.',
		'option_d'       => 'Coordinate one shared weekly planning conversation so the parents reduce handoff tension and present schedules consistently to the children.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-138',
		'question_text'  => 'A family has recently reunited after several years of migration-related separation. The adolescent had been living with relatives and now struggles with changed parental roles, school disengagement, language and cultural adjustment, and anger toward the parents. The family is distressed but not imminently unsafe. What should the therapist prioritize?',
		'option_a'       => 'Assess reunification stress and family functioning, provide culturally responsive language-accessible support, connect the adolescent with individual coping resources, and coordinate school support.',
		'option_b'       => 'Assess reunification stress and family functioning, provide culturally responsive language-accessible support, and connect the family with structured household-role resources.',
		'option_c'       => 'Assess reunification stress and family functioning, provide culturally responsive language-accessible support, and connect the family with community communication resources.',
		'option_d'       => 'Assess reunification stress and family functioning, provide culturally responsive language-accessible support, and connect the family with trauma-processing resources before changing routines.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-139',
		'question_text'  => 'A client reports that the family strongly stigmatizes mental-health treatment. During previous therapy, the client concealed appointments from relatives and stopped attending when family members became suspicious. Which issue should the therapist explore NEXT?',
		'option_a'       => 'Explore family stigma’s effects on disclosure, treatment attendance, available support, and current expectations.',
		'option_b'       => 'Assess family beliefs about therapy, the client’s agreement with those beliefs, anticipated consequences of discovery, and current privacy concerns.',
		'option_c'       => 'Review what prior therapy helped, what was difficult, why attendance stopped, and what the client wants handled differently now.',
		'option_d'       => 'Explore secrecy burden, current privacy needs, support outside family, and strategies previously used to protect treatment confidentiality.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-140',
		'question_text'  => 'A college student who previously earned strong grades is now failing two courses. The decline has occurred during a semester involving a heavier course load, a new medical problem, and substantial relationship stress. What should the therapist evaluate NEXT?',
		'option_a'       => 'Assess study habits, time management, sleep, course difficulty, and whether heavier workload exceeds prior coping strategies now.',
		'option_b'       => 'Assess depression, anxiety, concentration, motivation, and whether emotional symptoms preceded or followed the current academic decline.',
		'option_c'       => 'Review instructor feedback, assignment completion, attendance, examination performance, and whether difficulties are consistent across courses and academic tasks.',
		'option_d'       => 'Compare current with prior academic functioning and assess changes in workload, health, relationship stress, and learning conditions this semester.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-141',
		'question_text'  => 'For more than three years, a client has felt depressed on most days and reports chronically low energy, low self-esteem, poor concentration, and hopelessness. The client cannot recall being symptom-free for more than several weeks at a time. There has never been a manic or hypomanic episode or a distinct period of substantially more severe depressive symptoms. Which diagnosis is MOST supported?',
		'option_a'       => 'Persistent depressive disorder',
		'option_b'       => 'Major depressive disorder, recurrent',
		'option_c'       => 'Cyclothymic disorder',
		'option_d'       => 'Adjustment disorder with depressed mood',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-142',
		'question_text'  => 'A 9-year-old with autism becomes distressed when family plans change unexpectedly. One parent usually cancels the activity to prevent a meltdown, while the other insists the child continue without preparation. The disagreement between the parents now creates tension before most family outings. Which intervention should the therapist use?',
		'option_a'       => 'Use visual previews and consistent transition cues, practice small planned changes, and coach both parents to use the same response before, during, and after those changes.',
		'option_b'       => 'Keep routines highly predictable for several weeks, have both parents follow the same schedule, and introduce changes only after outings produce minimal distress.',
		'option_c'       => 'Validate distress, offer two acceptable choices during unexpected changes, and let the child choose which option to continue with during the activity.',
		'option_d'       => 'Create a reward plan for completing changed routines, preview the reward before outings, and review successful transitions to strengthen flexibility.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-143',
		'question_text'  => 'A client has become the primary caregiver for an aging parent and reports escalating conflict with siblings about decisions, finances, and division of caregiving responsibilities. Which assessment is MOST appropriate?',
		'option_a'       => 'Assess the client\'s caregiver burden, the parent\'s medical needs, division of labor, available respite, and whether the current arrangement is sustainable.',
		'option_b'       => 'Review historical sibling relationships, current caregiving roles, decision-making patterns, resource sharing, and the support each person contributes to the parent\'s care.',
		'option_c'       => 'Review recent sibling conflicts, beliefs about fairness, financial disagreements, communication patterns, and each sibling\'s view of caregiving responsibility.',
		'option_d'       => 'Clarify legal decision authority, financial responsibilities, each sibling\'s caregiving capacity, the parent\'s preferences, and the practical needs of the current care plan.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-144',
		'question_text'  => 'A client reports that previous therapy had been helpful until the therapist unexpectedly closed the practice. The client says, “I didn\'t even get to say goodbye. Now I keep wondering whether this will suddenly end too.” What should the current therapist do FIRST with this information?',
		'option_a'       => 'Review attendance agreements, planned absences, communication procedures, and termination policies so the client understands continuity expectations.',
		'option_b'       => 'Explore what was helpful in former therapy, what remained unfinished, and which elements the client would want repeated.',
		'option_c'       => 'Explore whether other abrupt losses produced similar reactions and whether the prior ending fits a broader separation pattern.',
		'option_d'       => 'Explore how the abrupt ending affected trust, expectations about continuity, and willingness to discuss future endings.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-145',
		'question_text'  => 'A client describes a romantic partner as “the most caring person I’ve ever met” when the partner is attentive. After the partner forgot to call one evening, the client said, “I finally saw who they really are—selfish and completely uncaring,” and considered ending the relationship. The therapist is using an object relations approach. Which intervention should the therapist use?',
		'option_a'       => 'Explore whether anger toward the partner reflects feelings first experienced with an inconsistent caregiver and identify similarities across relationships.',
		'option_b'       => 'Examine how the client experiences the therapist after minor disappointments and connect those reactions with shifts in the partner’s perceived character.',
		'option_c'       => 'Help the client mourn the idealized image of the partner and develop more realistic expectations about what dependable adult relationships can provide.',
		'option_d'       => 'Help the client hold caring and disappointing aspects of the partner together, tolerating ambivalence without shifting between idealization and devaluation.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-146',
		'question_text'  => 'A couple reports a persistent difference in sexual desire. Neither partner reports a recent medical change, and both describe the relationship as generally satisfying outside disagreements about frequency and initiation. What should the therapist assess NEXT?',
		'option_a'       => 'Assess the lower-desire partner’s mood, medications, health, stress, sleep, relationship satisfaction, and whether individual factors account for the discrepancy.',
		'option_b'       => 'Explore each partner’s desired frequency, meaning of sex, expectations, initiation patterns, emotional responses, and degree of relationship distress.',
		'option_c'       => 'Review relationship satisfaction, conflict, closeness, and whether desire discrepancy appears during relational disconnection.',
		'option_d'       => 'Review sexual history, prior desire differences, cultural expectations, developmental changes, and whether the current discrepancy is new or longstanding.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-147',
		'question_text'  => 'A client who survived violence from a former partner has no current contact with that person and reports no present safety threat. In therapy, the client quickly agrees with nearly every suggestion but later says the suggestion did not feel right and often does not follow through. The client explains, “I learned it was safer to say yes.” Which intervention should the therapist use next?',
		'option_a'       => 'Name the learned agreement response as protective, then practice one low-stakes difference of preference with the therapist.',
		'option_b'       => 'Use client-led agenda setting and practice choosing among several acceptable session directions when preferences are uncertain.',
		'option_c'       => 'Explore situations outside therapy where agreement appears, then map the cues that precede compliance and the consequences that follow.',
		'option_d'       => 'Use grounding before decisions, offer several acceptable choices, and practice rating comfort before selecting the next treatment step.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-148',
		'question_text'  => 'A middle-school student has persistent difficulty completing classroom assignments and organizing school materials. Teachers also describe disruptive behavior during complex academic tasks, while caregivers report substantially fewer problems at home. Which additional assessment is MOST appropriate?',
		'option_a'       => 'Refer for outpatient psychological testing to determine whether the student has a learning, attention, or emotional disorder that could explain the school difficulties.',
		'option_b'       => 'Refer to the pediatrician first to rule out medical contributors before requesting any educational or behavioral assessment.',
		'option_c'       => 'Continue family assessment to determine whether differences between home and school reflect inconsistent expectations across settings.',
		'option_d'       => 'Refer for school-based evaluation to assess educational and behavioral functioning within the setting where the difficulties are occurring.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-149',
		'question_text'  => 'A 7-year-old follows routines independently at home but appears overwhelmed by multistep classroom tasks and requires substantially more assistance at school than peers. Caregivers and teachers disagree about whether the child is developmentally delayed. What should the therapist do NEXT?',
		'option_a'       => 'Compare the child’s chronological age with classroom expectations, task difficulty, teacher supports, and whether school demands exceed age-typical abilities.',
		'option_b'       => 'Review caregiver observations, home routines, independent tasks, family expectations, and whether difficulties become apparent during more complex activities at home.',
		'option_c'       => 'Review developmental history across domains and compare task demands, supports, and performance in both home and school settings.',
		'option_d'       => 'Compare teacher reports, classroom behavior, academic performance, and whether difficulties vary across school activities.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-150',
		'question_text'  => 'A client who survived sexual assault is in a safe, supportive relationship and wants more physical closeness with the partner. Certain kinds of touch still trigger freezing and sudden withdrawal. The client does not want to avoid intimacy indefinitely and asks for a way to move gradually while remaining in control. Which intervention should the therapist use?',
		'option_a'       => 'Use a consent-based ladder of closeness and rehearse brief signals to slow, stop, or reconnect during each mutually chosen step of touch.',
		'option_b'       => 'Plan nonsexual affection with explicit opt-in choices, rehearse brief consent signals for each contact, and use a shared comfort scale before and after each type of touch.',
		'option_c'       => 'Explore the client’s meanings around intimacy triggers and coach the partner to respond with validation rather than reassurance or problem-solving.',
		'option_d'       => 'Strengthen emotional closeness through shared routines and add mutually chosen forms of touch that the client already experiences as safe.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
);
