<?php
/**
 * LMFT California Clinical — Comprehensive Simulation Form B items 26–50 (PROMPT 08).
 * Learner-facing stems and choices only. Answer keys deferred to admin merge.
 *
 * @package CTA_LMS
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-026',
		'question_text'  => 'A client has had two severe major depressive episodes. During each episode, the client heard an accusatory voice and developed a fixed belief that the client had caused terrible events in the community. Both the hallucination and delusional belief resolved completely when the depressive episode remitted. There has never been psychosis outside a mood episode. Which diagnosis is MOST supported?',
		'option_a'       => 'Major depressive disorder with psychotic features occurring during severe depressive episodes.',
		'option_b'       => 'Schizoaffective disorder, depressive type, with psychosis linked primarily to mood episodes throughout.',
		'option_c'       => 'Schizophrenia with prominent depressive symptoms occurring during active psychotic episodes.',
		'option_d'       => 'Brief psychotic disorder recurring specifically during periods of severe depression.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-027',
		'question_text'  => 'A client reports two physical fights at bars during the past year and increasingly hostile verbal arguments when drinking. The client denies any current threat, intent to harm anyone, or access to a weapon. What should the therapist assess NEXT?',
		'option_a'       => 'Assess alcohol use, escalation of aggression, prior fights, consequences, triggers, and whether current intent or access changes present danger.',
		'option_b'       => 'Assess alcohol quantity, frequency, tolerance, withdrawal, and whether aggressive episodes occur only during intoxication or also when sober.',
		'option_c'       => 'Assess impulsivity across settings, anger triggers, ability to stop escalation, remorse afterward, and whether similar behavior occurs outside interpersonal conflict.',
		'option_d'       => 'Review legal consequences, relationship losses, family responses, prior treatment, and the client\'s explanation for why the fights and verbal aggression have occurred.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-028',
		'question_text'  => 'A couple with two children seeks therapy after one partner\'s work hours are sharply reduced. The other partner takes a second job, childcare becomes inconsistent, the family cuts spending on basic necessities, and arguments about money and household responsibilities increase. Which assessment is MOST appropriate?',
		'option_a'       => 'Assess each adult\'s mood, sleep, parenting stress, and whether the current family conflict was present before the household income decreased.',
		'option_b'       => 'Assess changes in household income, basic-needs access, childcare stability, work demands, family conflict, and available supports across the recent period.',
		'option_c'       => 'Review both adults\' employment histories, job satisfaction, budgeting practices, and plans for increasing income before evaluating the family\'s relational functioning.',
		'option_d'       => 'Assess communication, division of labor, coparenting, and conflict around spending to determine whether relationship problems are driving the family\'s financial distress.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-029',
		'question_text'  => 'A client provides most of the daily care for a spouse recovering from a stroke. Over the last month the client has stopped attending a weekly exercise class, sleeps poorly, and becomes irritable with adult children who repeatedly offer to take over a regular evening of care. The spouse’s rehabilitation plan is stable. Which intervention should the therapist use?',
		'option_a'       => 'Set a nightly wind-down routine, schedule brief exercise on two days when adult children help with household tasks, and review the effect on sleep and irritability.',
		'option_b'       => 'Create a caregiver coping plan centered on sleep hygiene, irritability cues, and brief restorative activities during the day.',
		'option_c'       => 'Ask the adult children to take over selected household tasks while the client keeps primary responsibility for the spouse’s direct care.',
		'option_d'       => 'Establish a predictable weekly respite shift with the adult children and use that protected time to restore one meaningful recovery activity.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-030',
		'question_text'  => 'A couple presents with sharply different explanations of the relationship problem, and each wants the therapist to determine whose account is correct. Which treatment plan is MOST consistent with a general postmodern approach?',
		'option_a'       => 'Consider each account as meaningful, employ collaborative inquiry, and develop shared goals without privileging perspectives.',
		'option_b'       => 'Externalize conflict from the couple, identify unique outcomes, and develop an alternative relationship story collaboratively.',
		'option_c'       => 'Describe the preferred future, identify exceptions to conflict, and create observable changes from demonstrated competencies.',
		'option_d'       => 'Offer systemic interactional formulation, identify the maintaining sequence, and coordinate goals around that recurring pattern.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-031',
		'question_text'  => 'A client angrily fantasizes about damaging a landlord’s property but has made no preparations, has not acquired tools or accelerants, does not describe a near-term plan, has no recent violent behavior, and is willing to avoid the property. What should the therapist do NEXT?',
		'option_a'       => 'Assess intent and preparation, initiate an emergency protective response, and communicate the property-damage threat to responders.',
		'option_b'       => 'Assess intent and preparation, develop a property-avoidance safety plan, and arrange close follow-up because imminence is not established.',
		'option_c'       => 'Assess intent and preparation, obtain urgent psychiatric consultation, ask a support person to monitor access to the property, and review any recent attempts to approach the site.',
		'option_d'       => 'Assess intent and preparation, use anger-coping strategies, and continue routine follow-up unless threat specificity increases.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-032',
		'question_text'  => 'For ten months, a client has experienced intense fear when speaking in meetings, eating in front of unfamiliar people, attending parties, or going on dates. The client fears appearing foolish or visibly anxious and avoids these situations whenever possible. Panic symptoms occur only when the client expects social scrutiny. Which diagnosis is MOST supported?',
		'option_a'       => 'Panic disorder',
		'option_b'       => 'Agoraphobia',
		'option_c'       => 'Social anxiety disorder',
		'option_d'       => 'Generalized anxiety disorder',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-033',
		'question_text'  => 'The client has just learned that a close family member was seriously injured in a mass-violence incident in another state. The client was not present and is physically safe, but is overwhelmed, cannot concentrate on work or travel arrangements, and is struggling to organize immediate family responsibilities. No imminent psychiatric danger is established. What should the therapist prioritize?',
		'option_a'       => 'Assess immediate functioning and acute stress, provide practical support for immediate family logistics, and mobilize available supports.',
		'option_b'       => 'Assess immediate functioning and acute stress, provide coping support, mobilize trusted supports before the client makes travel decisions, and outline near-term work-coverage needs.',
		'option_c'       => 'Assess immediate functioning and acute stress, provide grounding support, and involve trusted family supports while organizing available family information.',
		'option_d'       => 'Assess immediate functioning and acute stress, provide practical support, and involve trusted supports during an urgent crisis consultation.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-034',
		'question_text'  => 'During an initial couples session, one partner says, “I\'m here because my spouse insisted. I don\'t think talking to a therapist is going to change anything.” Which response should the therapist make FIRST?',
		'option_a'       => 'Acknowledge the skepticism, clarify the pace and limits of conjoint work, and ask what would make participation tolerable.',
		'option_b'       => 'Ask both partners what change they want, compare their motivation, and identify one concern they could address together.',
		'option_c'       => 'Explore what the skeptical partner has already tried, what seemed unhelpful, and what might make therapy feel different.',
		'option_d'       => 'Acknowledge the skepticism, invite the partner’s view of the relationship concern, and ask what would make the meeting useful.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-035',
		'question_text'  => 'A client receiving treatment for chronic pain reports reduced activity, disrupted sleep, less sexual intimacy, and major changes in household responsibilities. Which assessment approach is BEST?',
		'option_a'       => 'Map pain severity, timing, treatment changes, activity limits, and sleep disruption to establish daily functional change.',
		'option_b'       => 'Assess mood, anxiety, avoidance, coping responses, and whether distress predicts changes in pain behavior.',
		'option_c'       => 'Assess partner responses, caregiving changes, conflict, sexual changes, and available support since pain became limiting.',
		'option_d'       => 'Evaluate effects of pain and treatment changes on sleep, activity, intimacy, household roles, and family functioning.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-036',
		'question_text'  => 'For more than three years, a 30-year-old client has experienced numerous periods of increased energy, talkativeness, sociability, and reduced sleep, alternating with periods of low mood, fatigue, and self-doubt. Neither the elevated nor depressed periods has ever met full criteria for a hypomanic, manic, or major depressive episode. Symptoms have been present at least half the time, with no symptom-free period longer than two months. Which diagnosis is MOST supported?',
		'option_a'       => 'Bipolar II disorder',
		'option_b'       => 'Cyclothymic disorder',
		'option_c'       => 'Persistent depressive disorder',
		'option_d'       => 'Other specified bipolar and related disorder',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-037',
		'question_text'  => 'A parent of two young children says, “A good mother should never need time away from her kids.” The client describes family, social-media, and community messages that equate constant availability with devotion. The client feels exhausted and resentful but worries that wanting rest means being selfish. The therapist is using a postmodern approach. Which intervention should the therapist use?',
		'option_a'       => 'Externalize maternal perfection and map how the problem influences the client’s routines, relationships, guilt, and available choices.',
		'option_b'       => 'Invite the client to identify exceptions to the dominant motherhood standard and describe times caregiving has felt more flexible and sustainable.',
		'option_c'       => 'Collaboratively examine where the good-mother standard comes from, whose interests it serves, and develop locally meaningful definitions of caregiving for this family.',
		'option_d'       => 'Explore how different communities define devoted parenting and ask the client which descriptions fit the life and relationships she values.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-038',
		'question_text'  => 'A therapist\'s practice has been overbooked for several months. The therapist is now routinely starting sessions late, has missed multiple follow-up tasks, and has growing documentation gaps. The therapist recognizes that these problems are affecting continuity of care. What is the therapist\'s BEST next step?',
		'option_a'       => 'Add protected documentation blocks at the end of each day, use automated reminders for follow-up tasks, retain the existing caseload, and review whether the workflow changes correct the problems over the next month and again at quarter end.',
		'option_b'       => 'Notify clients that the practice is experiencing scheduling delays, shorten the most complex appointments temporarily, and prioritize documentation for higher-risk cases first.',
		'option_c'       => 'Reduce the workload to a manageable level, correct outstanding continuity and recordkeeping problems, and change the practice conditions that are producing repeated performance failures.',
		'option_d'       => 'Hire administrative support, retain the caseload, and use chart audits to determine whether performance returns to an acceptable level.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-039',
		'question_text'  => 'A 34-year-old Black bisexual woman in a management role reports that coworkers often describe her as “intimidating” when she is assertive, while some relatives make dismissive comments about her same-sex relationship. She says the pressures feel different across settings and she is unsure how to respond without losing important parts of herself. Which intervention should the therapist use?',
		'option_a'       => 'Examine how racialized workplace stereotypes shape assertiveness and compare that process with sexuality-related family stress, noting where expectations about gender and professional role also affect each setting.',
		'option_b'       => 'Examine how race, gender, sexuality, and management-role expectations intersect across settings, then develop responses that fit those combined pressures.',
		'option_c'       => 'Explore which identity-related pressure feels most salient in each setting and identify coping responses that protect the client’s sense of self while preserving important relationships and work goals.',
		'option_d'       => 'Validate discrimination in work and family contexts and develop separate setting-specific strategies for the demands the client faces in each environment.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-040',
		'question_text'  => 'An adult client requests a copy of the client\'s psychotherapy record. The file contains several pages of information that the client\'s sibling gave the therapist in confidence, without the client present, and the sibling specifically asked that the information not be shared with the client. What should the therapist do?',
		'option_a'       => 'Provide the complete record because information stored and relied on in the client\'s chart should be treated as part of the client\'s record once it has influenced treatment decisions.',
		'option_b'       => 'Identify and remove the confidential collateral information excluded from the client\'s patient record for access purposes, document the separation of that material, and provide the remainder through the applicable record-access process.',
		'option_c'       => 'Ask the sibling whether the information may now be released, document the sibling\'s decision, and provide the full record only if the collateral source withdraws the confidentiality request in writing.',
		'option_d'       => 'Give the client a treatment summary that omits the sibling\'s information, explain that the original notes contain confidential collateral material, and retain the full internal record without producing it.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-041',
		'question_text'  => 'A client’s self-worth collapses after minor criticism. The client alternates between idealizing and devaluing important people and seeks constant reassurance and recognition. Which treatment plan is MOST consistent with self psychology?',
		'option_a'       => 'Identify criticism-related appraisals, test them through structured feedback, and develop balanced beliefs about psychological worth.',
		'option_b'       => 'Rank approval-seeking and idealization targets, analyze behavior chains, and teach regulation plus interpersonal skills directly.',
		'option_c'       => 'Employ empathic attunement, examine recurring disruptions in interpersonal support, and gradually develop a cohesive self-experience.',
		'option_d'       => 'Explore idealized and devalued representations, interpret them in the therapeutic relationship, and integrate conflicting views.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-042',
		'question_text'  => 'A client was assaulted during a bias-motivated attack. The client is now afraid to use public transportation, feels disconnected from the community, and reports guilt because another person was seriously injured. The client denies current suicidal intent and remains able to care for basic needs. Which intervention is BEST?',
		'option_a'       => 'Assess immediate safety and functioning, provide guilt-focused coping support, and plan gradual community reentry with trusted supports.',
		'option_b'       => 'Assess immediate safety and functioning, provide avoidance-focused coping support, and plan graded transportation reentry with trusted supports.',
		'option_c'       => 'Assess immediate safety and functioning, provide acute trauma support, and arrange urgent psychiatric evaluation before community reentry.',
		'option_d'       => 'Assess immediate safety and functioning, provide identity-aware trauma support, and strengthen culturally relevant community resources during recovery.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-043',
		'question_text'  => 'A client develops new difficulty concentrating and increased anxiety at the same time as unexplained weight change, tremulousness, and episodes of rapid heartbeat. The physical symptoms have not been medically evaluated. Which referral is MOST appropriate?',
		'option_a'       => 'Refer for psychiatric evaluation because new emotional and cognitive symptoms may indicate a mental disorder that requires specialized diagnostic or medication assessment.',
		'option_b'       => 'Refer for medical evaluation because the new psychological symptoms occur alongside unexplained physical changes that have not yet received a medical assessment.',
		'option_c'       => 'Refer for neurocognitive testing because the presence of cognitive complaints suggests a specialized assessment would be most informative.',
		'option_d'       => 'Continue psychological evaluation first and refer medically only if the symptoms persist after psychosocial explanations have been explored.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-044',
		'question_text'  => 'A couple agreed to use a structured de-escalation plan between sessions, but after two attempts they stopped using it. Both partners say the steps are hard to remember once an argument begins, although they still want a concrete way to interrupt escalation. Which intervention should the therapist use next?',
		'option_a'       => 'Ask the couple to recommit to the original sequence for two weeks and review adherence at each session.',
		'option_b'       => 'Replace the structured plan with conflict journaling for one week and reintroduce the skill after the couple identifies recurring triggers.',
		'option_c'       => 'Have each partner independently rehearse the complete sequence before attempting it together during an imagined disagreement.',
		'option_d'       => 'Find where the plan fails, trim the steps, and rehearse the new version with a recent argument.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-045',
		'question_text'  => 'A client in a depressive episode has stopped joining a spouse for evening activities and usually goes to bed soon after dinner. The spouse experiences the withdrawal as rejection, while the client says low energy—not loss of affection—is driving the change. Both want to reconnect without making the client feel overwhelmed. Which intervention should the therapist use?',
		'option_a'       => 'Choose a low-demand shared activity that fits current energy and frame the withdrawal as depression-related rather than relational rejection.',
		'option_b'       => 'Build independent behavioral activation around one personally rewarding activity and use the resulting energy data to decide how to add couple activities.',
		'option_c'       => 'Practice a brief check-in in which the spouse reflects and the client names internal experience when the urge to withdraw appears.',
		'option_d'       => 'Review relationship functioning before the depressive episode and identify which current changes are new versus longstanding.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-046',
		'question_text'  => 'A blended family seeks therapy because of conflict around household rules, parental authority, and children\'s loyalty to biological parents. Different family members describe the same household very differently. What should the therapist assess NEXT?',
		'option_a'       => 'Assess one child’s behavior, adjustment to remarriage, loyalty concerns, school functioning, and whether child symptoms are organizing broader family conflict.',
		'option_b'       => 'Assess the remarried couple’s alliance, parenting agreement, conflict, authority, and whether couple-level instability is driving household-role problems.',
		'option_c'       => 'Compare each parent’s discipline style, expectations, household rules, and whether inconsistency across adults explains the current authority disputes.',
		'option_d'       => 'Explore prior losses and relationships, household transitions, authority and loyalty patterns, and current blended-family interactions.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-047',
		'question_text'  => 'An individual psychotherapy client asks to bring a spouse to one upcoming session for emotional support while discussing a stressful family decision. The client does not want to convert treatment to couple therapy, and the therapist has not previously included the spouse. What should the therapist do BEFORE the spouse participates?',
		'option_a'       => 'Have the spouse sign participant paperwork, explain the existing client\'s role, treatment goals, confidentiality and records expectations, document the limited support purpose, and review communication boundaries before the session.',
		'option_b'       => 'Allow the spouse to attend, identify the individual client and support role at the start, review confidentiality and records expectations, and document clinically relevant collateral information.',
		'option_c'       => 'Clarify that the individual remains the therapy client, review confidentiality and records expectations, and agree on the spouse\'s limited support purpose before the session.',
		'option_d'       => 'Meet briefly with the spouse before the session, explain the client\'s role, confidentiality and records expectations, gather the spouse\'s perspective, and document what may enter treatment.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-048',
		'question_text'  => 'A client develops pain during sexual activity following a recent health change. The client has become increasingly anxious before sexual contact, and both partners now avoid initiating intimacy. Which assessment is BEST?',
		'option_a'       => 'Assess pain onset, medical changes, treatment, physical triggers, and whether discomfort occurs consistently across different forms of sexual activity.',
		'option_b'       => 'Assess anticipatory anxiety, fear of pain, avoidance, physiological arousal, and whether anxiety persists even when sexual activity is not attempted.',
		'option_c'       => 'Clarify how pain onset and health changes relate to anxiety, avoidance, partner responses, and sexual or relationship distress.',
		'option_d'       => 'Assess partner reactions, communication, initiation patterns, emotional closeness, and whether relationship tension increased before or after the pain began.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-049',
		'question_text'  => 'A client discloses a recent sexual assault and says the client already showered and changed clothes. The client believes this means seeking specialized medical or forensic care would now be pointless and asks whether any options remain. There is no current medical emergency. What should the therapist do NEXT?',
		'option_a'       => 'Assess immediate safety and medical needs, explain available forensic options, and support reporting before the client seeks specialized examination services promptly.',
		'option_b'       => 'Assess immediate safety and medical needs, explain available forensic options, and support contact with specialized medical-advocacy services despite prior showering.',
		'option_c'       => 'Assess immediate safety and medical needs, explain available forensic options, support detailed event review before recommending an examination, and document the client’s questions for follow-up.',
		'option_d'       => 'Assess immediate safety and medical needs, explain available forensic options, and support grounding before revisiting medical-forensic service decisions.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-050',
		'question_text'  => 'An adult client wants friendships but reports that conversations often end awkwardly. In session, the client speaks at length without noticing attempts to change topics and rarely asks follow-up questions. The client says, “I never know what people expect me to do differently.” Which intervention should the therapist use?',
		'option_a'       => 'Process rejection fears and use brief reflection before each social attempt so the client enters conversations with less self-focused anxiety.',
		'option_b'       => 'Use behavioral rehearsal of turn-taking, open questions, and reading conversational cues, followed by feedback and planned practice between sessions.',
		'option_c'       => 'Encourage participation in interest-based groups and track which social settings feel easiest before introducing more specific communication strategies.',
		'option_d'       => 'Challenge beliefs about being unlikeable, review recent conversations for missed cues, and test new responses during planned social interactions.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
);
