<?php
/**
 * LMFT California Clinical — Comprehensive Simulation Form B items 1–25 (PROMPT 07).
 * Learner-facing stems and choices only. Answer keys deferred to admin merge.
 *
 * @package CTA_LMS
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-001',
		'question_text'  => 'A service wants an ongoing therapy and psychoeducation group for adults recently diagnosed with chronic medical illnesses. Referrals arrive continuously, acute crises are treated elsewhere, and an eight-week modular curriculum repeats throughout the year. The goals are adjustment, self-management, and peer support. Which framework is MOST appropriate?',
		'option_a'       => 'Use rolling admission with full clinical screening; repeat orientation for every entrant; deliver the eight-week modular curriculum reliably under stable participation rules.',
		'option_b'       => 'Use closed eight-week cohorts with clinical screening; orient entrants before the start; deliver modules sequentially and delay admission until the next cycle.',
		'option_c'       => 'Use open drop-in attendance with broad eligibility screening; offer orientation to new members; let participants select topics without stable attendance expectations.',
		'option_d'       => 'Use rolling admission with routine and crisis-level members; screen members periodically; organize sessions around current needs rather than repeating the modular curriculum.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-002',
		'question_text'  => 'A client begins individual therapy and says, “I need you to tell me whether I should divorce my spouse. I keep going back and forth and can\'t decide.” What should the therapist do FIRST?',
		'option_a'       => 'Clarify the therapist’s role, the client’s values, concerns, and desired outcomes while supporting the client’s own decision process.',
		'option_b'       => 'Use decisional balance to compare anticipated gains, losses, uncertainties, and information needed before choosing a direction.',
		'option_c'       => 'Review relationship strengths, recurring injuries, repair attempts, and current supports to determine whether more information is needed.',
		'option_d'       => 'Assess urgency, coercion or safety concerns, external pressure, and timeframe before structuring the decision work.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-003',
		'question_text'  => 'A therapist believes that strict consequences are the best approach to parenting adolescents. An adult client wants help developing a more collaborative parenting style. The therapist notices repeatedly steering the client toward harsher consequences even when the client says those recommendations do not fit the client\'s values or goals. What should the therapist do?',
		'option_a'       => 'Acknowledge the value difference, compare collaborative and consequence-based parenting strategies, and review clinical options through shared decision-making while keeping the client\'s goals central.',
		'option_b'       => 'Recognize the therapist\'s value interference, return treatment to the client\'s stated parenting goals, seek an outside perspective as needed, and check whether later recommendations remain consistently neutral.',
		'option_c'       => 'Acknowledge the value difference, explain the therapist\'s reasoning for stronger consequences, and keep offering both approaches while allowing the client to reject strategies that do not fit.',
		'option_d'       => 'Acknowledge the value mismatch, review the client\'s parenting goals, and offer referral if the therapist concludes that adequate neutrality cannot be maintained.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-004',
		'question_text'  => 'A client spends several hours each day preoccupied with the belief that the nose is “grotesquely deformed,” although others see no noticeable defect. The client repeatedly checks mirrors, compares photographs, seeks reassurance, and camouflages the nose. The concern has caused marked distress, repeated avoidance of social activities, and missed work. The concern is not focused on body weight. Which diagnosis is MOST supported?',
		'option_a'       => 'Body dysmorphic disorder',
		'option_b'       => 'Obsessive-compulsive disorder',
		'option_c'       => 'Delusional disorder, somatic type',
		'option_d'       => 'Anorexia nervosa',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-005',
		'question_text'  => 'A bisexual adult is considering telling the parents about a current same-sex relationship before an upcoming family gathering. The client wants a more open relationship with the parents but worries about rejection because they have made dismissive comments about bisexual people in the past. The client is not financially dependent on them and reports no current safety threat. Which intervention should the therapist use?',
		'option_a'       => 'Rehearse a disclosure conversation and help the client choose a calm private time, emphasizing that openness can support authenticity and closeness.',
		'option_b'       => 'Delay disclosure until the parents show more acceptance, while strengthening support from affirming friends and a supportive sibling.',
		'option_c'       => 'Clarify the client’s goals, likely family responses, support options, and timing, then let the client decide whether, when, and how to disclose.',
		'option_d'       => 'Explore how family beliefs shaped the client’s fears, strengthen self-acceptance, and revisit disclosure after the client feels less emotionally reactive.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-006',
		'question_text'  => 'A client has frequently described the therapist as “the only person who really understands me.” When the therapist must keep a previously discussed scheduling limit and cannot add an extra session, the client says, “You’re just like everyone else. I can’t rely on anyone,” and reports feeling suddenly empty and disorganized. The therapist is using a self-psychology approach. Which intervention should the therapist use?',
		'option_a'       => 'Acknowledge the injury and interpret how therapist idealization protects the client from shame when important others feel disappointing.',
		'option_b'       => 'Empathically explore the repercussions of the scheduling limit on the client’s sense of connection and self-cohesion before interpreting the rupture.',
		'option_c'       => 'Explore which selfobject functions the therapist has been serving and identify other relationships that might gradually provide similar experiences.',
		'option_d'       => 'Validate the disappointment, restate the scheduling limit, and strengthen independent coping so the client gradually relies less heavily on the therapist.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-007',
		'question_text'  => 'A perfectionistic client repeatedly states, “I must never disappoint anyone, and if I fail, it proves I am worthless.” Which treatment plan is MOST consistent with rational emotive behavior therapy?',
		'option_a'       => 'Identify habitual appraisals, examine evidence closely, and test balanced alternatives through behavioral practice across situations.',
		'option_b'       => 'Explore early criticism, examine evaluative transference closely, and interpret shame-based defenses within the clinical relationship.',
		'option_c'       => 'Offer empathic acceptance, clarify chosen values openly, and consistently support self-directed decisions without direct disputation.',
		'option_d'       => 'Identify demandingness and self-ratings, dispute these directly, and practice flexible rational beliefs with unconditional acceptance.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-008',
		'question_text'  => 'A client was referred to psychotherapy by probation. The client signed a written authorization allowing the therapist to verify attendance and whether the client is complying with the required number of sessions. The probation officer now asks for the client\'s diagnosis, symptoms, and details of what has been discussed in therapy. No court order or other disclosure authority is presented. What should the therapist do?',
		'option_a'       => 'Provide attendance plus a brief progress summary, limit the report to treatment-compliance concerns, document that diagnosis and session details were withheld, and explain that the report is limited to referral-monitoring purposes.',
		'option_b'       => 'Provide only the attendance and session-compliance information the client authorized; withhold diagnosis, symptoms, and treatment content unless another valid legal basis exists; document the limited disclosure.',
		'option_c'       => 'Refuse all probation communication despite the authorization, tell the client that confidentiality prevents any referral monitoring, and document the request and refusal clearly.',
		'option_d'       => 'Ask the client to broaden the authorization before responding further, withhold the already authorized attendance information, and document the request while the client decides.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-009',
		'question_text'  => 'A client with severe psychotic disorganization has repeatedly become lost in the community, has eaten very little for several days, has been sleeping outdoors despite available shelter, and cannot explain how food, shelter, or basic self-care will be maintained. Which action is BEST?',
		'option_a'       => 'Maintain observation, arrange same-day intensive case management, and provide meals, shelter, and continuous outreach.',
		'option_b'       => 'Maintain observation, arrange same-day medication-focused psychiatric stabilization, and provide supervised community supports.',
		'option_c'       => 'Maintain observation, transfer to a staffed crisis setting for same-day evaluation, and stabilize psychiatric and basic-needs functioning.',
		'option_d'       => 'Maintain observation, arrange supervised temporary housing, and obtain urgent psychiatric consultation with a scheduled next-day crisis reassessment.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-010',
		'question_text'  => 'A client abruptly stops attending and sends a brief message expressing dissatisfaction with treatment. No acute safety concern is known, and the client does not request additional contact. What should the therapist do?',
		'option_a'       => 'Send one respectful closure message with referrals and reentry information, then close the case after the standard response period without a reply, and document the closure rationale and referrals provided.',
		'option_b'       => 'Make several outreach attempts, offer a final session and referrals, and keep the case open until the client responds or enters other care.',
		'option_c'       => 'Send one feedback-focused message offering a final consultation and referrals, then close only after the client confirms the decision to stop.',
		'option_d'       => 'Make respectful outreach, offer a final session and continuity options, and document those efforts before closing if the client does not respond.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-011',
		'question_text'  => 'A first-year college student began skipping a statistics class after failing the first exam. Embarrassed by missing material, the client avoids classmates and the instructor, then misses assignments and feels increasingly overwhelmed. There is no acute safety issue, and the distress is largely tied to this academic pattern. Which intervention should the therapist use to improve academic functioning?',
		'option_a'       => 'Schedule independent study blocks and use a self-reward plan after each completed overdue assignment.',
		'option_b'       => 'Arrange peer study sessions and use them to rebuild mastery before returning to regular class attendance.',
		'option_c'       => 'Challenge predictions of being judged in class and rehearse a coping statement for attending the next lecture.',
		'option_d'       => 'Use a graded return-to-class plan that begins with attending the next lecture and contacting the instructor about missed work.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-012',
		'question_text'  => 'A client with a life-limiting illness says, “I’m not mainly afraid of dying. I’m afraid I spent my life doing what I was supposed to do and never figured out what mattered to me.” The client wants therapy to help make sense of the time that remains. The therapist is using a humanistic-existential approach. Which intervention should the therapist use?',
		'option_a'       => 'Explore what the client now experiences as meaningful and what choices remain for living the available time in closer alignment with those values.',
		'option_b'       => 'Invite the client to review major life decisions and identify where personal responsibility was avoided, accepted, or constrained by circumstances.',
		'option_c'       => 'Stay with the client’s awareness of mortality and examine how confronting finitude changes the meaning of relationships, commitments, and unfinished goals.',
		'option_d'       => 'Invite the client to design a legacy activity that expresses important values and creates a concrete sense of purpose during remaining time.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-013',
		'question_text'  => 'A client reports increasing cannabis use since a relationship ended six months ago. The client says cannabis “helps me shut everything off,” while work performance and contact with friends have declined. Which assessment is MOST appropriate?',
		'option_a'       => 'Assess breakup-related grief, depressive symptoms, loneliness, sleep, and whether cannabis use increases with distress.',
		'option_b'       => 'Assess tolerance, withdrawal, craving, impaired control, and continued use despite psychological or physical consequences.',
		'option_c'       => 'Review prior substance history, family substance history, peer use, beliefs about cannabis, earlier stress-related patterns, and previous periods of reduced use.',
		'option_d'       => 'Map amount and frequency of cannabis use, timing since the breakup, attempts to reduce use, and work and social functioning changes.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-014',
		'question_text'  => 'A client describes profound grief after the disappearance of a close family member whose status remains unknown. Friends have become less supportive because they say the client should “move on,” and the client reports difficulty explaining the loss to others. What should the therapist assess NEXT?',
		'option_a'       => 'Compare current symptoms, duration, role functioning, and social withdrawal with common bereavement patterns despite the uncertainty surrounding the loss.',
		'option_b'       => 'Assess whether family and friends recognize the loss, what support they provide, and whether invalidation has increased the client’s isolation.',
		'option_c'       => 'Explore the meaning of the ambiguous loss, social recognition, cultural context, available support, and changes in current functioning over time.',
		'option_d'       => 'Review previous experiences of unresolved loss, coping strategies, spiritual beliefs, and whether earlier uncertainty affects the client’s current response.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-015',
		'question_text'  => 'During an annual religious ritual, a client reports hearing the voice of a deceased ancestor offering guidance. The experience is recognized within the client\'s spiritual community. Outside that setting, the client reports no similar experiences, has organized thought and behavior, maintains stable functioning, and experiences no distress. Which formulation is MOST appropriate?',
		'option_a'       => 'Psychotic-spectrum perceptual experience, interpreted as inconsistent with recognized cultural or spiritual context.',
		'option_b'       => 'Delusional-spectrum perceptual experience requiring a primary psychotic-disorder formulation.',
		'option_c'       => 'Culturally sanctioned perceptual experience that does not support a primary psychotic diagnosis.',
		'option_d'       => 'Dissociative perceptual experience occurring within a recognized spiritual or religious practice context.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-016',
		'question_text'  => 'A client speaks intellectually about unresolved grief but repeatedly shifts away from present emotion and has difficulty noticing bodily reactions during sessions. Which treatment plan is MOST consistent with Gestalt therapy?',
		'option_a'       => 'Review present-moment contact, employ experiential awareness of physical and emotional signals, and integrate unresolved grief.',
		'option_b'       => 'Explore developmental loss patterns, interpret avoidance in therapy relationships, and connect grief with unconscious conflict.',
		'option_c'       => 'Identify grief-related appraisals, test them through evidence review, and use activity scheduling to restore routines.',
		'option_d'       => 'Separate grief from identity, identify outcomes, and develop an alternative relational story of continuing bonds.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-017',
		'question_text'  => 'A client recovering from a spinal injury has persistent pain and reduced stamina. On better days the client tries to complete all household chores, then spends the next day or two in bed. The client’s partner says, “I never know what you can actually do.” Medical rehabilitation is established. Which intervention should the therapist use?',
		'option_a'       => 'Use activity pacing and renegotiate household roles around predictable limits to reduce the couple’s boom-and-bust conflict.',
		'option_b'       => 'Use relaxation during pain flares and have the partner take extra chores on bad days.',
		'option_c'       => 'Process grief about lost physical capacity and postpone role negotiation until the client has greater acceptance of current limitations.',
		'option_d'       => 'Teach structured couple problem-solving for chore disagreements and leave physical pacing decisions to the established rehabilitation team.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-018',
		'question_text'  => 'A parent is ordered to attend therapy after a family-court matter and states, “I\'m doing this because the judge said I have to. I don\'t have anything I want to work on.” Which response is MOST appropriate?',
		'option_a'       => 'Clarify the court’s stated concerns, the client’s view of them, and whether areas of partial agreement could support an initial goal.',
		'option_b'       => 'Clarify the reporting boundaries, the client’s understanding of the referral, and whether sessions should focus primarily on court concerns.',
		'option_c'       => 'Clarify the court requirements, the client’s own perspective, and whether a personally meaningful goal can exist alongside mandated participation.',
		'option_d'       => 'Clarify consequences of nonparticipation, the client’s priorities, and whether a practical, parenting, or relationship goal could support engagement.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-019',
		'question_text'  => 'A 13-year-old begins living with an aunt after the mother requires prolonged medical treatment. In the family’s culture, care is commonly expressed through meals, shared chores, transportation, and dependable routines rather than frequent verbal affection. The adolescent says the aunt “doesn’t say much” but feels safest when those routines are maintained. After disagreements, both tend to retreat. Which intervention should the therapist use to strengthen attachment?',
		'option_a'       => 'Build conjoint work around the family’s established caregiving routines and add a way to reconnect after disagreements that fits their relational style.',
		'option_b'       => 'Compare caregiving practices across family and community contexts, then have both choose which expressions of closeness they want to strengthen.',
		'option_c'       => 'Introduce a structured verbal-affection routine alongside existing caregiving behaviors and review which forms feel most connecting to each person.',
		'option_d'       => 'Explore the adolescent’s caregiver disruption individually and use the aunt’s routines mainly as stabilization while trust develops.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-020',
		'question_text'  => 'A couple who recently retired after decades of full-time employment reports increased conflict about household roles, social activities, and how much time they should spend together. Which assessment would be MOST appropriate?',
		'option_a'       => 'Assess each partner’s mood, health, daily structure, and whether individual adjustment difficulties are contributing to the couple’s increased conflict.',
		'option_b'       => 'Assess changes in roles, routines, identity, intimacy, social connection, and expectations since both partners entered retirement.',
		'option_c'       => 'Assess financial changes, spending expectations, retirement resources, work loss, daily structure, and whether economic concerns are driving disagreements.',
		'option_d'       => 'Review pre-retirement relationship patterns, division of responsibilities, shared interests, and whether current disputes reflect longstanding couple dynamics.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-021',
		'question_text'  => 'Following a major loss, a family discusses events only in factual terms and quickly changes the subject when emotion appears. Family members say they want greater closeness but remain distant and highly controlled in sessions. Which treatment plan is MOST consistent with experiential family therapy?',
		'option_a'       => 'Clarify boundaries and hierarchy, shift family alliances, and reorganize interactions through planned enactments in session.',
		'option_b'       => 'Map multigenerational loss patterns, strengthen differentiation, and support direct contact with extended-family members during stress.',
		'option_c'       => 'Enhance immediate emotional contact, use experiential enactments, and support fully congruent interpersonal expression among relatives.',
		'option_d'       => 'Map the avoidance sequence, prescribe structured conversations, and carefully revise directives from observed interactional responses.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-022',
		'question_text'  => 'The estranged spouse of an adult psychotherapy client calls the therapist and says, "I know my spouse is seeing you. I only need you to confirm whether the appointments are actually happening." The client has not authorized disclosure to the spouse. What is the therapist\'s BEST response?',
		'option_a'       => 'Decline to confirm attendance or client status, explain the confidentiality limit, and document the spouse\'s request without disclosing protected treatment information.',
		'option_b'       => 'Confirm the appointment dates but withhold treatment content, explain the confidentiality limit on additional information, and document the limited scheduling disclosure to the spouse.',
		'option_c'       => 'Confirm that the person is an active client but withhold attendance details, explain the confidentiality limit, and direct further treatment questions back to the client.',
		'option_d'       => 'Decline to answer during the call, contact the client to ask whether attendance may be confirmed, document the request, and respond to the spouse later only if valid authorization is provided.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-023',
		'question_text'  => 'A client performs well at work and interacts comfortably with coworkers but reports repeated conflicts with friends and says, “I don’t seem to keep friendships very long.” Which assessment would be MOST useful?',
		'option_a'       => 'Use stable occupational relationships to compare how the client communicates, manages disagreement, and repairs tension differently with coworkers than with friends.',
		'option_b'       => 'Explore the most recent friendship rupture in detail, including expectations, communication, escalation, and whether the pattern resembles one earlier relationship.',
		'option_c'       => 'Review social history across friendships and close relationships, looking for recurring interaction patterns, ruptures, repair attempts, and periods of connection over time.',
		'option_d'       => 'Assess rejection sensitivity, social anxiety, emotion regulation, and interpersonal expectations to determine whether individual vulnerabilities contribute to repeated conflict.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-024',
		'question_text'  => 'An elementary-school client has the same pattern of refusing nonpreferred tasks at home, school, and in treatment. With appropriate authorization in place, the therapist learns that the parent, teacher, and therapist are using different definitions of the target behavior and different reinforcement responses. Progress is inconsistent across settings. Which collaboration strategy should the therapist use?',
		'option_a'       => 'Bring the parent, teacher, and therapist together to compare behavior data, align separate definitions with each setting, and plan reinforcement around each environment’s demands.',
		'option_b'       => 'Have the team standardize the target-behavior definition and reinforcement approach across home, school, and treatment.',
		'option_c'       => 'Bring the parent, teacher, and therapist together to review observations, revise the therapy plan, and maintain the current home and school approaches.',
		'option_d'       => 'Bring the parent, teacher, and therapist together to adopt the therapist’s behavior definition, plan common reinforcement, and apply that approach across home and school.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
	array(
		'question_code'  => 'CTA-LMFT-CA-FB-025',
		'question_text'  => 'An older adult wants to remain at home but is struggling with several practical barriers: preparing meals has become difficult, transportation to appointments is unreliable, and a family caregiver is increasingly overwhelmed. The client can still participate in treatment and does not require emergency intervention. Which community referral is most appropriate?',
		'option_a'       => 'Refer the client to a home-delivered meal program that can reduce meal-preparation demands and provide reliable nutrition at home.',
		'option_b'       => 'Refer the client to an accessible transportation program that can arrange reliable rides to health appointments and essential community destinations.',
		'option_c'       => 'Refer the client to an aging-services coordinator who can integrate the household’s needs and connect the family with several community programs.',
		'option_d'       => 'Refer the family caregiver to a respite program that can provide planned relief and reduce strain associated with continuing care at home.',
		'correct_option' => 'x',
		'explanation'    => '',
	),
);
