<?php
/**
 * CTA LPCC Law & Ethics EP - Practice Examination A (50 questions).
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
return array(
	array(
		'question_text' => 'An LPCC and an adult client agreed to supportive counseling. Six weeks later, the LPCC proposes a substantially different trauma-focused intervention with new risks and homework demands. What is the BEST response before beginning the new approach?',
		'option_a' => 'Terminate treatment because the client may decline the new intervention.',
		'option_b' => 'Begin because the client already consented to psychotherapy in general.',
		'option_c' => 'Reopen the informed-consent discussion, explain the material change, risks, benefits, reasonable alternatives, and questions, then document the client\'s informed choice.',
		'option_d' => 'Ask the client to sign a new form without discussing the change.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. Declining one intervention does not by itself require termination when other appropriate options may remain.\n\nB. Incorrect. General consent does not automatically cover every materially different later intervention.\n\nC. Correct. A material change in the nature or risks of treatment calls for renewed communication and an informed, voluntary decision rather than reliance on the original intake signature.\n\nD. Incorrect. A signature documents a process; it does not replace meaningful disclosure and understanding.\n\nCTA Exam Strategy: Identify authority, consent/confidentiality/privilege, the exact requester or decision-maker, and the required sequence before disclosing or acting.",
	),
	array(
		'question_text' => 'A mature 15-year-old asks an LPCC for outpatient counseling without a parent present. No emergency is present. The adolescent reports credible fear of retaliation if a parent is involved. What should the LPCC do FIRST?',
		'option_a' => 'Promise the minor that no parent can ever be contacted.',
		'option_b' => 'Assess and document whether the statutory self-consent criteria are met, consult the minor about parent involvement, determine whether involvement would be inappropriate, and explain confidentiality limits before treatment proceeds.',
		'option_c' => 'Begin treatment and postpone all consent and parent-involvement decisions until later.',
		'option_d' => 'Require parental consent because minors can never authorize outpatient counseling.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. Absolute secrecy cannot be promised; confidentiality has legal and safety limits.\n\nB. Correct. California law permits qualifying minors age 12 or older to consent to specified outpatient mental-health services when mature enough to participate intelligently, while requiring a documented parent-involvement analysis after consultation with the minor.\n\nC. Incorrect. Authority and confidentiality boundaries should be resolved at or before initiation, not deferred.\n\nD. Incorrect. California law provides a qualifying minor-consent pathway.\n\nCTA Exam Strategy: Identify authority, consent/confidentiality/privilege, the exact requester or decision-maker, and the required sequence before disclosing or acting.",
	),
	array(
		'question_text' => 'An adult client\'s parent pays the session fees and calls the LPCC demanding confirmation of the client\'s diagnosis and attendance. The client has not authorized disclosure. What should the LPCC do FIRST?',
		'option_a' => 'Confirm attendance but not diagnosis because attendance is administrative.',
		'option_b' => 'Identify the client and any lawful authorization or other legal basis for disclosure before confirming treatment or releasing information.',
		'option_c' => 'Provide a verbal summary because only written records require authorization.',
		'option_d' => 'Release the information because the payer is financially responsible.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. Confirming attendance can itself disclose the existence of a confidential treatment relationship.\n\nB. Correct. Payment does not make the payer the client, privilege holder, or automatic recipient of confidential treatment information.\n\nC. Incorrect. Verbal disclosures are still disclosures and require a lawful basis.\n\nD. Incorrect. Financial responsibility does not create treatment-information access rights.\n\nCTA Exam Strategy: Identify authority, consent/confidentiality/privilege, the exact requester or decision-maker, and the required sequence before disclosing or acting.",
	),
	array(
		'question_text' => 'At the start of a telehealth session, a returning client says, "I\'m at the usual place." What should the LPCC do under the current California telehealth regulation?',
		'option_a' => 'Skip location verification when the client has attended at least three prior sessions.',
		'option_b' => 'Document "usual location" because the permanent address is already in the chart.',
		'option_c' => 'Ask only for the city and state unless the client reports an emergency.',
		'option_d' => 'Verbally obtain and document the client\'s full name and address of the client\'s present location at the beginning of the session.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. The each-session requirement does not expire after a number of visits.\n\nB. Incorrect. A prior permanent address does not substitute for the required current-session location information.\n\nC. Incorrect. The regulation calls for the address of the present location, not only city and state.\n\nD. Correct. 16 CCR 1815.5 requires the clinician to obtain and document the client's full name and present-location address at the beginning of each telehealth session.\n\nCTA Exam Strategy: Identify authority, consent/confidentiality/privilege, the exact requester or decision-maker, and the required sequence before disclosing or acting.",
	),
	array(
		'question_text' => 'A client signs an authorization allowing the LPCC to send a treatment summary to a primary-care physician. The physician later asks for the entire psychotherapy record. What is the BEST response?',
		'option_a' => 'Refuse all communication because treatment records can never be shared.',
		'option_b' => 'Send the full record but mark it confidential.',
		'option_c' => 'Send the full record because a physician requested it for treatment.',
		'option_d' => 'Disclose only information authorized by the client and otherwise permitted by law, and obtain a new or revised authorization if broader disclosure is appropriate and desired.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. Properly authorized and lawful disclosures are permitted.\n\nB. Incorrect. A confidentiality label does not cure disclosure beyond the authorized scope.\n\nC. Incorrect. Recipient status does not automatically enlarge the authorization.\n\nD. Correct. An authorization is limited by its scope; a request from the recipient does not expand the client's authorization.\n\nCTA Exam Strategy: Identify authority, consent/confidentiality/privilege, the exact requester or decision-maker, and the required sequence before disclosing or acting.",
	),
	array(
		'question_text' => 'An LPCC treating an adult client receives a subpoena from opposing counsel demanding the complete record. The client instructs the LPCC not to disclose anything. What is the BEST initial legal-ethical approach?',
		'option_a' => 'Ignore the subpoena because psychotherapy records are always privileged.',
		'option_b' => 'Send the entire record because any subpoena eliminates privilege.',
		'option_c' => 'Preserve the treatment role, evaluate the subpoena and psychotherapist-patient privilege through the appropriate legal process, communicate accurately with the client, and disclose only if lawfully authorized or ordered.',
		'option_d' => 'Terminate therapy and then release the record because privilege ends at termination.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. Legal process should be addressed rather than ignored, even when privilege may apply.\n\nB. Incorrect. A subpoena does not automatically eliminate privilege or require unrestricted production.\n\nC. Correct. A subpoena is legal process that requires analysis; it is not automatically equivalent to a court order or blanket waiver of privilege.\n\nD. Incorrect. Termination does not automatically extinguish privilege or confidentiality obligations.\n\nCTA Exam Strategy: Identify authority, consent/confidentiality/privilege, the exact requester or decision-maker, and the required sequence before disclosing or acting.",
	),
	array(
		'question_text' => 'A person claiming to be an adult client\'s conservator asks an LPCC for the client\'s treatment records but provides no documentation of authority. What should the LPCC do FIRST?',
		'option_a' => 'Verify the requester\'s identity and legal authority and determine the applicable access rules before confirming or releasing protected information.',
		'option_b' => 'Confirm the client is in treatment but withhold the notes.',
		'option_c' => 'Release the records because conservators always have unrestricted access.',
		'option_d' => 'Ask the requester to describe the client\'s diagnosis to prove the relationship.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. Record access depends on the requester's actual legal authority and the applicable access/confidentiality rules, not merely on a claimed relationship.\n\nB. Incorrect. Confirming treatment is itself a disclosure that requires a lawful basis.\n\nC. Incorrect. Authority and scope must be verified; access can also be subject to specific legal limits.\n\nD. Incorrect. Knowledge of clinical details is not a substitute for legal authority and may invite further disclosure.\n\nCTA Exam Strategy: Identify authority, consent/confidentiality/privilege, the exact requester or decision-maker, and the required sequence before disclosing or acting.",
	),
	array(
		'question_text' => 'Which set of actions belongs to the California BBS telehealth initiation requirements for an LPCC beginning telehealth with a new client?',
		'option_a' => 'Obtain informed consent, discuss potential risks and limitations, provide the license type and number, and document reasonable efforts to identify relevant resources in the client\'s geographic area.',
		'option_b' => 'Require a separate document titled "Telehealth Consent Form" in every case.',
		'option_c' => 'Wait until the second session to discuss telehealth risks if the client prefers remote care.',
		'option_d' => 'Use a secure platform and obtain an emergency contact; no other initiation disclosures are required.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. These are the core initiation duties stated in 16 CCR 1815.5(c), in addition to other applicable informed-consent and privacy requirements.\n\nB. Incorrect. California requires the consent process and documentation, not a specific form title.\n\nC. Incorrect. The initiation duties apply when telehealth services are initiated.\n\nD. Incorrect. Platform security and emergency planning do not replace the listed BBS initiation duties.\n\nCTA Exam Strategy: Identify authority, consent/confidentiality/privilege, the exact requester or decision-maker, and the required sequence before disclosing or acting.",
	),
	array(
		'question_text' => 'During a counseling session, an APCC working under supervision develops reasonable suspicion that a child has been abused. The clinic director asks the APCC to wait until tomorrow\'s team meeting so the agency can decide whether to report. What should occur FIRST?',
		'option_a' => 'Wait for the director because supervisors control agency reporting decisions.',
		'option_b' => 'Investigate until the APCC can prove that abuse occurred.',
		'option_c' => 'Make the mandated report immediately or as soon as practicably possible and complete the written follow-up within the statutory period; internal procedures may not delay the individual duty.',
		'option_d' => 'Document the concern internally and allow the director to make the external report.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. Supervisors may not impede an individual mandated reporter's duty.\n\nB. Incorrect. Reasonable suspicion, not proof, is the reporting threshold.\n\nC. Correct. Penal Code 11166 uses reasonable suspicion as the threshold, requires an initial report immediately or as soon as practicably possible and a written follow-up within 36 hours, and makes the reporting duty individual.\n\nD. Incorrect. Internal notice does not substitute for the mandated report.\n\nCTA Exam Strategy: Identify the legal threshold, who has the duty, the required timing or protective step, and the narrow scope of any disclosure.",
	),
	array(
		'question_text' => 'An LPCC in an outpatient community clinic reasonably suspects financial abuse of an older adult client. The suspected abuse did not occur in a long-term-care facility, state mental hospital, or state developmental center. What is the BEST reporting sequence?',
		'option_a' => 'Notify the client\'s family and let them decide whether to contact authorities.',
		'option_b' => 'Report immediately or as soon as practicably possible to adult protective services or local law enforcement and, if the initial report is by telephone, send the required written report or confidential internet report within two working days.',
		'option_c' => 'Wait until the client provides documentary proof of the financial loss.',
		'option_d' => 'Report only to the client\'s bank because the concern is financial.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. Family consultation does not replace the mandated reporter's statutory duty.\n\nB. Correct. WIC 15630 requires prompt reporting and specifies the agency and follow-up timing for abuse occurring outside the special facility categories.\n\nC. Incorrect. Mandated reporting does not require proof beyond the statutory reporting threshold.\n\nD. Incorrect. The statutory reporting pathway is to APS or local law enforcement for this setting.\n\nCTA Exam Strategy: Identify the legal threshold, who has the duty, the required timing or protective step, and the narrow scope of any disclosure.",
	),
	array(
		'question_text' => 'An LPCC\'s client communicates a serious threat of physical violence against a specifically identified former supervisor and describes access to a weapon. What is the BEST response?',
		'option_a' => 'Warn only the client\'s family because they know the client best.',
		'option_b' => 'Assess immediacy and safety, take the protective actions required by California law, including reasonable efforts to communicate the threat to the identifiable victim and law enforcement when the statutory conditions are met, and document the response.',
		'option_c' => 'Wait until the threatened person contacts the therapist.',
		'option_d' => 'Maintain confidentiality because threats discussed in psychotherapy are always privileged.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. Family notification alone does not satisfy the statutory duty-to-protect framework.\n\nB. Correct. Civil Code 43.92 defines the limited duty-to-protect circumstances and provides a statutory method of discharging that duty; immediate safety assessment and documentation remain essential.\n\nC. Incorrect. The duty turns on the client's communicated serious threat and identifiable victim, not on a request from the potential victim.\n\nD. Incorrect. California law recognizes circumstances in which protective disclosure is required or permitted.\n\nCTA Exam Strategy: Identify the legal threshold, who has the duty, the required timing or protective step, and the narrow scope of any disclosure.",
	),
	array(
		'question_text' => 'A client tells an LPCC about current suicidal intent, a specific plan, and immediate access to lethal means. Which response BEST reflects the confidentiality and safety analysis?',
		'option_a' => 'Promise secrecy because the client disclosed the plan in psychotherapy.',
		'option_b' => 'Disclose the entire psychotherapy record to everyone involved in the response.',
		'option_c' => 'Address the imminent safety risk first, use the least necessary lawful disclosures and emergency resources to protect the client, and document the assessment, actions, and follow-up.',
		'option_d' => 'Wait for the next scheduled session because only threats to other people permit action.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. Absolute secrecy is not appropriate when serious safety exceptions may apply.\n\nB. Incorrect. Protective disclosure should be limited to what is lawful and reasonably necessary.\n\nC. Correct. Serious self-harm risk requires safety-focused action; Evidence Code 1024 recognizes a privilege exception when disclosure is necessary to prevent threatened danger.\n\nD. Incorrect. California privilege law also addresses danger to self, and clinical safety duties require immediate assessment.\n\nCTA Exam Strategy: Identify the legal threshold, who has the duty, the required timing or protective step, and the narrow scope of any disclosure.",
	),
	array(
		'question_text' => 'An LPCC evaluates a client who appears unable to provide for basic personal safety because of a severe mental disorder. The LPCC is not personally designated by the county to initiate a 5150 detention. What should the LPCC do FIRST?',
		'option_a' => 'Tell the client to return later if basic-needs problems continue for 72 hours.',
		'option_b' => 'Complete a 5150 application solely because the LPCC holds a California license.',
		'option_c' => 'Assess and document the factual risk, determine whether emergency evaluation is indicated, and activate the appropriate authorized county or emergency pathway rather than assuming detention authority the LPCC does not have.',
		'option_d' => 'Avoid emergency consultation because involuntary care is outside counseling practice.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. The decision depends on current risk and legal criteria, not an arbitrary waiting period.\n\nB. Incorrect. Licensure alone does not automatically confer county-designated detention authority.\n\nC. Correct. Crisis reasoning separates clinical assessment from legal authority. Section 5150 detention authority belongs to persons authorized by statute/county designation; the LPCC should protect the client while using the lawful pathway.\n\nD. Incorrect. An LPCC still has responsibility to assess risk and coordinate appropriate emergency care within role.\n\nCTA Exam Strategy: Identify the legal threshold, who has the duty, the required timing or protective step, and the narrow scope of any disclosure.",
	),
	array(
		'question_text' => 'Two mandated reporters jointly learn facts creating reasonable suspicion of child abuse and agree that one of them will make the report. What remains true for the other reporter?',
		'option_a' => 'If the designated reporter fails to make the report, the other mandated reporter who knows of the failure must make the report.',
		'option_b' => 'The other reporter must always make a duplicate report even after confirming the designated report was made.',
		'option_c' => 'Only the supervisor may decide whether a team report counts.',
		'option_d' => 'The other reporter has no further responsibility once the team agrees on a reporter.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. Penal Code 11166 permits a jointly selected reporter in specified circumstances but preserves individual responsibility when a designated reporter fails.\n\nB. Incorrect. A single jointly selected report may satisfy the reporting method when the statutory conditions are met.\n\nC. Incorrect. The reporting rules are statutory and the duty is individual; supervisor permission is not the controlling factor.\n\nD. Incorrect. The statute preserves a duty to act if the designated reporter fails.\n\nCTA Exam Strategy: Identify the legal threshold, who has the duty, the required timing or protective step, and the narrow scope of any disclosure.",
	),
	array(
		'question_text' => 'An LPCC must make a legally authorized safety disclosure. Which principle BEST guides how much confidential information to disclose?',
		'option_a' => 'Disclose the information reasonably necessary for the lawful protective purpose and avoid unrelated treatment details.',
		'option_b' => 'Release the entire record whenever any confidentiality exception applies.',
		'option_c' => 'Disclose nothing unless the client signs a release.',
		'option_d' => 'Post the concern in the shared organizational chat so the widest team can respond.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. A safety exception does not convert the entire record into unrestricted information; disclosure should remain tied to the authorized purpose.\n\nB. Incorrect. An exception is not a blanket authorization for unrelated information.\n\nC. Incorrect. Some protective disclosures are authorized or required without client authorization.\n\nD. Incorrect. Wider distribution is not automatically necessary or authorized.\n\nCTA Exam Strategy: Identify the legal threshold, who has the duty, the required timing or protective step, and the narrow scope of any disclosure.",
	),
	array(
		'question_text' => 'In litigation, counsel argues that every therapy communication is privileged and can never be disclosed, while another party argues that filing a lawsuit automatically waives all psychotherapy privilege. Which analysis is BEST?',
		'option_a' => 'The therapist should decide based only on which party appears more credible.',
		'option_b' => 'Privilege can never be limited once therapy begins.',
		'option_c' => 'Any lawsuit automatically makes the complete psychotherapy record discoverable.',
		'option_d' => 'Identify the holder of privilege, the specific issue and legal process, and any applicable statutory exception or waiver; avoid both blanket nondisclosure and blanket disclosure.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. Privilege and disclosure are governed by legal authority, not the therapist's preference between litigants.\n\nB. Incorrect. California Evidence Code includes specific exceptions.\n\nC. Incorrect. Filing litigation does not create a universal automatic waiver of every confidential communication.\n\nD. Correct. Psychotherapist-patient privilege is strong but subject to defined exceptions and waiver rules. The proper response is issue-specific legal analysis rather than an absolute rule.\n\nCTA Exam Strategy: Identify the legal threshold, who has the duty, the required timing or protective step, and the narrow scope of any disclosure.",
	),
	array(
		'question_text' => 'An APCC creates a professional directory profile that lists only "Jordan Lee, APCC" and a registration number. Which correction is BEST under the advertising rule operative April 1, 2026?',
		'option_a' => 'Remove all online advertising because APCCs may never advertise.',
		'option_b' => 'Keep the profile unchanged because a registration number alone proves supervised status.',
		'option_c' => 'Include the Board-filed first and last name, complete registration title when using APCC, registration number, employer or volunteer entity, and a statement that the APCC is supervised by a licensed person.',
		'option_d' => 'Add the supervisor\'s home address and personal phone number.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. Registrants may advertise when the applicable requirements are met.\n\nB. Incorrect. The regulation requires more than a number and does not allow supervised status to be inferred.\n\nC. Correct. 16 CCR 1811 requires identity, title, number, and additional employer/entity and supervised-status information for registrants; the APCC abbreviation has a complete-title condition.\n\nD. Incorrect. Those are not the minimum advertising elements required by the regulation.\n\nCTA Exam Strategy: Separate professional status, lawful setting/scope, representation, documentation, and conduct requirements; consent cannot expand legal authority.",
	),
	array(
		'question_text' => 'A private clinic offers an APCC a 1099 independent-contractor position. Clients would pay the APCC directly, the APCC would rent an office from the clinic, and a licensed clinician would be available for optional consultation. What is the BEST response?',
		'option_a' => 'Accept because a 1099 classification is allowed if supervision is available.',
		'option_b' => 'Accept if clients sign forms acknowledging that the APCC is unlicensed.',
		'option_c' => 'Decline or restructure the arrangement so the APCC works as a lawful employee or volunteer, receives compensation only through the employer if paid, has no prohibited proprietary/rental arrangement, and receives qualifying supervision.',
		'option_d' => 'Accept if the APCC does not count the hours toward licensure.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. Independent-contractor mental-health practice is prohibited for an APCC.\n\nB. Incorrect. Client disclosure does not legalize a prohibited employment/payment arrangement.\n\nC. Correct. BPC 4999.46.3 prohibits independent-contractor practice for an APCC, direct remuneration from clients, and specified proprietary/rental arrangements; consultation is not a substitute for required supervision.\n\nD. Incorrect. The restrictions apply to the performance of professional services, not only to hours claimed for licensure.\n\nCTA Exam Strategy: Separate professional status, lawful setting/scope, representation, documentation, and conduct requirements; consent cannot expand legal authority.",
	),
	array(
		'question_text' => 'An LPCC is asked to administer an individually administered intelligence test to answer a school-placement question. The LPCC is otherwise experienced with counseling assessments. What is the BEST response?',
		'option_a' => 'Administer it after reading the manual because competence is the only issue.',
		'option_b' => 'Decline the excluded testing activity and refer to an appropriately qualified professional rather than treating general assessment experience as authority for the test.',
		'option_c' => 'Administer the test because LPCC licensure authorizes every psychological assessment.',
		'option_d' => 'Administer it if the client signs informed consent.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. Training cannot convert an expressly excluded activity into LPCC scope.\n\nB. Correct. California's LPCC assessment definition includes many assessment activities but expressly excludes individually administered intelligence tests and other specified methods.\n\nC. Incorrect. The statute expressly excludes certain testing activities from LPCC assessment.\n\nD. Incorrect. Consent cannot expand statutory scope.\n\nCTA Exam Strategy: Separate professional status, lawful setting/scope, representation, documentation, and conduct requirements; consent cannot expand legal authority.",
	),
	array(
		'question_text' => 'A California LPCC closes a case with an adult client whose therapy ends in 2026. Which statement is most accurate about the statutory minimum record-retention rule?',
		'option_a' => 'The LPCC must retain the client\'s health-service records for at least seven years from the date therapy is terminated, subject to longer applicable legal holds or other controlling requirements.',
		'option_b' => 'Every record must be kept permanently.',
		'option_c' => 'The record can be destroyed after one year if the client receives a copy.',
		'option_d' => 'Records may be destroyed immediately after the final bill is paid.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. BPC 4999.75 establishes a seven-year minimum from termination for adult clients; other legal obligations can require preservation beyond the ordinary minimum.\n\nB. Incorrect. California law sets a minimum period but does not establish a universal permanent-retention rule.\n\nC. Incorrect. Giving a client a copy does not eliminate the professional retention duty.\n\nD. Incorrect. Payment status does not replace the statutory retention minimum.\n\nCTA Exam Strategy: Separate professional status, lawful setting/scope, representation, documentation, and conduct requirements; consent cannot expand legal authority.",
	),
	array(
		'question_text' => 'A current client tells an LPCC that the client wants to begin a consensual sexual relationship with the counselor outside the office. Which response is most accurate?',
		'option_a' => 'The relationship is allowed if the client initiates it.',
		'option_b' => 'The relationship is allowed if treatment is paused for one week.',
		'option_c' => 'The LPCC must maintain the professional boundary; client consent and an off-site setting do not make sexual conduct with a current client permissible.',
		'option_d' => 'The relationship is allowed if both parties sign a written waiver.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. Client initiation does not eliminate the professional prohibition and power imbalance.\n\nB. Incorrect. A brief pause does not transform a current therapeutic relationship into an ethically and legally acceptable sexual relationship.\n\nC. Correct. California professional-conduct law prohibits sexual misconduct with current patients/clients; consent and location do not cure the prohibition.\n\nD. Incorrect. A waiver cannot legalize prohibited professional conduct.\n\nCTA Exam Strategy: Separate professional status, lawful setting/scope, representation, documentation, and conduct requirements; consent cannot expand legal authority.",
	),
	array(
		'question_text' => 'An APCC discovers that several claims were submitted using a diagnosis not supported by the current assessment. A manager suggests changing earlier notes so the claims "match." What is the BEST response?',
		'option_a' => 'Do not falsify the record; promptly involve the supervisor and appropriate billing/compliance resources, verify the clinical facts, correct records or claims through lawful procedures, address client impact, and document completion.',
		'option_b' => 'Delete the original diagnostic information and replace it without an audit trail.',
		'option_c' => 'Change the notes because the billing error has already occurred.',
		'option_d' => 'Ignore the issue because billing staff submitted the claim.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. Accurate representation, supervision, record integrity, billing correction, and client impact must be handled together. Falsifying records would create additional professional misconduct.\n\nB. Incorrect. Concealed alteration undermines record integrity and accountability.\n\nC. Incorrect. A prior error does not justify creating inaccurate clinical documentation.\n\nD. Incorrect. A clinician who learns of a material discrepancy has professional responsibilities to address it.\n\nCTA Exam Strategy: Separate professional status, lawful setting/scope, representation, documentation, and conduct requirements; consent cannot expand legal authority.",
	),
	array(
		'question_text' => 'An LPCC wants to add an unfamiliar trauma intervention after attending a one-hour overview webinar. A client requests the method immediately. What should the LPCC do FIRST?',
		'option_a' => 'Use the intervention once and decide afterward whether more training is needed.',
		'option_b' => 'Refuse to learn any new method because competence can never expand after licensure.',
		'option_c' => 'Use the intervention because the client requested it.',
		'option_d' => 'Evaluate the competence required, obtain appropriate training, supervision or consultation, and use another competent approach or refer if adequate competence cannot be developed in time.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. Competence should be addressed before exposing the client to an unfamiliar intervention.\n\nB. Incorrect. Competence can develop through appropriate education, training, supervision, and experience.\n\nC. Incorrect. Client preference cannot substitute for counselor competence.\n\nD. Correct. Client request and a brief introduction do not establish competence. The counselor must protect client welfare while building or obtaining the required competence.\n\nCTA Exam Strategy: Focus on competence, integrity, bias, impairment, and proportional safeguards; do not confuse an internal reaction or diagnosis with demonstrated functional impairment.",
	),
	array(
		'question_text' => 'An LPCC notices increasing fatigue and reduced concentration but has not yet made a serious clinical error. Which response is BEST?',
		'option_a' => 'Continue unchanged until a client complains.',
		'option_b' => 'Tell every client the counselor\'s private health details.',
		'option_c' => 'Permanently leave the profession because any fatigue proves incompetence.',
		'option_d' => 'Assess current functioning, obtain support or consultation, adjust workload or duties as needed, and monitor client impact before harm occurs.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. Client protection calls for earlier attention to emerging functional decline.\n\nB. Incorrect. Clients generally do not need private diagnostic details to be protected from functional risk.\n\nC. Incorrect. The response should be proportionate to actual functioning and recovery, not stigmatizing or absolute.\n\nD. Correct. Ethical self-monitoring emphasizes current functioning and proportionate prevention rather than waiting for a complaint or assuming permanent incompetence.\n\nCTA Exam Strategy: Focus on competence, integrity, bias, impairment, and proportional safeguards; do not confuse an internal reaction or diagnosis with demonstrated functional impairment.",
	),
	array(
		'question_text' => 'After leave for burnout, an LPCC reports feeling much better and asks to resume a full crisis caseload. Trial duties still show late notes, missed risk cues, and difficulty making urgent decisions. What is the BEST response?',
		'option_a' => 'Ask clients to decide whether the LPCC is fit for crisis work.',
		'option_b' => 'Continue limited or supported duties and base fuller return on demonstrated restoration of professional functioning and risk-management ability.',
		'option_c' => 'Restore the full caseload because the LPCC reports feeling better.',
		'option_d' => 'Permanently exclude the LPCC from clinical work because burnout occurred once.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. Professional fitness and assignment decisions cannot be delegated to clients.\n\nB. Correct. Subjective improvement is encouraging, but actual performance and client safety should govern return-to-practice decisions.\n\nC. Incorrect. Self-report alone does not resolve observable performance concerns.\n\nD. Incorrect. Prior impairment does not establish permanent incapacity.\n\nCTA Exam Strategy: Focus on competence, integrity, bias, impairment, and proportional safeguards; do not confuse an internal reaction or diagnosis with demonstrated functional impairment.",
	),
	array(
		'question_text' => 'An LPCC notices feeling unusually protective and irritated with a client. Which statement is most accurate?',
		'option_a' => 'The LPCC should disclose every emotional reaction to the client.',
		'option_b' => 'The feelings themselves do not establish misconduct, but the LPCC should recognize and manage them if they could influence judgment, boundaries, or treatment.',
		'option_c' => 'Emotional reactions are irrelevant if the LPCC is licensed.',
		'option_d' => 'The LPCC has already committed a boundary violation by experiencing the feelings.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. Disclosure is not automatically helpful and may burden the client.\n\nB. Correct. Internal reactions are not automatically unethical; professional responsibility focuses on self-awareness and preventing those reactions from distorting care.\n\nC. Incorrect. Unexamined reactions can influence clinical judgment, boundaries, and decision-making.\n\nD. Incorrect. Internal emotion is not the same as professional misconduct.\n\nCTA Exam Strategy: Focus on competence, integrity, bias, impairment, and proportional safeguards; do not confuse an internal reaction or diagnosis with demonstrated functional impairment.",
	),
	array(
		'question_text' => 'An LPCC concludes that a client\'s unfamiliar spiritual experiences prove psychosis without asking about cultural meaning, distress, functional impairment, safety, or alternative explanations. When the client objects, the LPCC becomes defensive. What is the BEST response?',
		'option_a' => 'Retain the diagnosis because changing it would weaken professional authority.',
		'option_b' => 'Refer solely because clinician and client have different spiritual beliefs.',
		'option_c' => 'Ask a spiritual leader to make the psychiatric diagnosis.',
		'option_d' => 'Pause the unsupported conclusion, listen to the client, assess meaning and clinical impact in context, consider alternatives, obtain consultation or education, correct unsupported records when necessary, and repair the treatment relationship.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. Professional integrity requires correction when the evidence does not support a conclusion.\n\nB. Incorrect. Identity or belief difference alone does not establish incompetence or require referral.\n\nC. Incorrect. Cultural consultation may add context with permission, but clinical assessment remains the clinician's responsibility.\n\nD. Correct. Cultural humility and competence require individualized assessment rather than pathologizing unfamiliar experiences based on clinician assumptions.\n\nCTA Exam Strategy: Focus on competence, integrity, bias, impairment, and proportional safeguards; do not confuse an internal reaction or diagnosis with demonstrated functional impairment.",
	),
	array(
		'question_text' => 'An APCC says, "I meet with an experienced licensed colleague once a month for optional advice, so I do not need a formal supervisor." Which response is BEST?',
		'option_a' => 'Clarify that consultation can supplement practice but does not replace the legally required supervision structure for an APCC.',
		'option_b' => 'Tell the APCC that consultation is prohibited during supervised practice.',
		'option_c' => 'Agree because any licensed colleague can serve as a consultant instead of a supervisor.',
		'option_d' => 'Agree if the colleague has more years of experience than the APCC\'s former supervisor.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. Consultation and supervision serve different functions. APCC status requires qualifying supervision and related legal documentation/accountability.\n\nB. Incorrect. Consultation may be useful; it simply cannot replace required supervision.\n\nC. Incorrect. Optional advice does not create the legal supervisory relationship required for an APCC.\n\nD. Incorrect. Experience alone does not substitute for the legal qualifications and relationship requirements of supervision.\n\nCTA Exam Strategy: Focus on competence, integrity, bias, impairment, and proportional safeguards; do not confuse an internal reaction or diagnosis with demonstrated functional impairment.",
	),
	array(
		'question_text' => 'An LPCC considers using an assessment instrument informally translated by a colleague for a client whose primary language is not English. The LPCC has not reviewed validity evidence or cultural/linguistic limitations. What should occur FIRST?',
		'option_a' => 'Use it if the colleague says the translation is accurate.',
		'option_b' => 'Evaluate the instrument\'s purpose, evidence, cultural and linguistic fit, and the LPCC\'s competence; select an appropriate measure or refer if those conditions cannot be met.',
		'option_c' => 'Administer it and add a disclaimer after scoring.',
		'option_d' => 'Use it because the client asked for testing.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. Informal assurance is not a substitute for evidence about the instrument and its use.\n\nB. Correct. Ethical assessment begins with appropriate instrument selection and competence before administration or interpretation.\n\nC. Incorrect. A later disclaimer does not cure an unsound instrument-selection decision.\n\nD. Incorrect. Client preference does not establish validity, appropriateness, or competence.\n\nCTA Exam Strategy: Focus on competence, integrity, bias, impairment, and proportional safeguards; do not confuse an internal reaction or diagnosis with demonstrated functional impairment.",
	),
	array(
		'question_text' => 'An LPCC receives credible but incomplete information that a colleague may be practicing while impaired. No immediate client danger is established. What should the LPCC do FIRST?',
		'option_a' => 'Clarify facts within role, assess client risk and applicable duties, and obtain timely ethical, supervisory, legal, or organizational consultation before selecting the appropriate channel.',
		'option_b' => 'Publicly accuse the colleague so clients can protect themselves.',
		'option_c' => 'Ignore the concern because only a client may raise impairment issues.',
		'option_d' => 'File complaints with every possible agency immediately.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. In a nonurgent situation with incomplete information, a proportionate fact-based response protects clients without jumping to public accusation or indiscriminate reporting.\n\nB. Incorrect. Public accusation can spread unverified information and bypass proper processes.\n\nC. Incorrect. Credible information affecting client welfare may require professional attention.\n\nD. Incorrect. Indiscriminate reporting is not a substitute for identifying the applicable duty and authorized channel.\n\nCTA Exam Strategy: Focus on competence, integrity, bias, impairment, and proportional safeguards; do not confuse an internal reaction or diagnosis with demonstrated functional impairment.",
	),
	array(
		'question_text' => 'An adult client understands the LPCC\'s recommendation but chooses a different reasonable treatment option. No emergency or involuntary authority applies. What is the BEST response?',
		'option_a' => 'Implement the preferred intervention without consent because it is clinically beneficial.',
		'option_b' => 'Continue persuading until the client agrees with the LPCC.',
		'option_c' => 'Respect the informed choice, discuss benefits and limitations of reasonable options, and continue or arrange appropriate care consistent with client welfare.',
		'option_d' => 'Terminate immediately because disagreement proves noncompliance.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. Beneficence does not erase informed choice in voluntary treatment.\n\nB. Incorrect. Persistent pressure after informed decision-making can undermine voluntariness.\n\nC. Correct. Client welfare includes respect for informed self-determination; beneficence does not ordinarily authorize overriding a competent client's voluntary choice.\n\nD. Incorrect. Disagreement with one recommendation does not automatically require termination.\n\nCTA Exam Strategy: Center client welfare, autonomy, access, relationship power, and continuity; avoid both paternalistic overreach and passive under-response.",
	),
	array(
		'question_text' => 'A client wants to reduce anxiety enough to return to work. The LPCC personally believes the client should instead end a romantic relationship and repeatedly redirects sessions toward that goal. What is the BEST corrective response?',
		'option_a' => 'Terminate because counselor and client values differ.',
		'option_b' => 'Hide the counselor\'s agenda while continuing to steer the client toward the preferred choice.',
		'option_c' => 'Continue because counselors may substitute their values whenever they believe the client is making a poor life choice.',
		'option_d' => 'Return to the client-defined treatment goals, examine the counselor\'s values and influence, and revise the plan collaboratively unless safety, law, or another legitimate clinical issue requires a different focus.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. Value differences alone do not require termination when competent, fair care can be provided.\n\nB. Incorrect. Covert value imposition is inconsistent with client-centered practice and informed collaboration.\n\nC. Incorrect. Professional influence must not become value imposition.\n\nD. Correct. Counseling should not become a vehicle for imposing the counselor's personal values when the client's lawful, clinically appropriate goals can be pursued.\n\nCTA Exam Strategy: Center client welfare, autonomy, access, relationship power, and continuity; avoid both paternalistic overreach and passive under-response.",
	),
	array(
		'question_text' => 'An LPCC determines that treatment is no longer effective and that another provider has specialized expertise the client needs. The client is clinically stable. What is the BEST response?',
		'option_a' => 'Discuss the concern and options with the client, plan an appropriate referral or transfer, address records and communication with authorization, and protect continuity rather than ending abruptly.',
		'option_b' => 'Stop scheduling immediately so the client understands the need to find someone else.',
		'option_c' => 'Continue indefinitely because referral may feel rejecting.',
		'option_d' => 'Send the complete record to a specialist before discussing referral with the client.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. Ethical termination focuses on client welfare, communication, transition, and continuity rather than abandonment.\n\nB. Incorrect. Abrupt cessation can create avoidable continuity and abandonment concerns.\n\nC. Incorrect. Continuing ineffective care may also harm the client.\n\nD. Incorrect. Referral does not automatically authorize disclosure of the record.\n\nCTA Exam Strategy: Center client welfare, autonomy, access, relationship power, and continuity; avoid both paternalistic overreach and passive under-response.",
	),
	array(
		'question_text' => 'An LPCC in a small rural community is asked to serve on the only local disaster-response committee, where a current client also serves. Declining would leave the committee without any behavioral-health professional. What is the BEST response?',
		'option_a' => 'Ask the client to keep therapy secret from everyone on the committee.',
		'option_b' => 'Assess alternatives, discuss foreseeable role and confidentiality risks when appropriate, establish safeguards, document the reasoning, and monitor whether the overlap affects treatment or professional judgment.',
		'option_c' => 'Accept without analysis because community service is separate from therapy.',
		'option_d' => 'Terminate the client immediately before joining the committee.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. Secrecy does not resolve the role conflict and may increase shame or boundary strain.\n\nB. Correct. Some community overlaps may be difficult to avoid. The ethical task is contextual risk analysis and safeguards, not automatic acceptance or automatic termination.\n\nC. Incorrect. The overlap can still affect confidentiality, power, boundaries, and judgment.\n\nD. Incorrect. Termination may harm the client and does not necessarily erase the prior relationship or conflict.\n\nCTA Exam Strategy: Center client welfare, autonomy, access, relationship power, and continuity; avoid both paternalistic overreach and passive under-response.",
	),
	array(
		'question_text' => 'At the final session, a client offers an LPCC a valuable handmade object and explains that refusing it would carry significant cultural meaning. What is the BEST response?',
		'option_a' => 'Refuse immediately because every client gift is unethical.',
		'option_b' => 'Accept the gift and secretly donate it later.',
		'option_c' => 'Accept automatically because cultural respect always overrides boundary concerns.',
		'option_d' => 'Explore the meaning, value, timing, cultural context, treatment impact, policy, and exploitation/boundary risks, then respond in the way that best protects the client and professional relationship.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. A categorical rule can ignore context and may itself harm the relationship.\n\nB. Incorrect. Secretly changing the disposition does not address meaning, ownership, or boundary impact with the client.\n\nC. Incorrect. Cultural meaning matters but does not erase power, value, or exploitation risks.\n\nD. Correct. Gift decisions are contextual. Neither culture nor value alone controls; the counselor should assess meaning, power, policy, and treatment impact.\n\nCTA Exam Strategy: Center client welfare, autonomy, access, relationship power, and continuity; avoid both paternalistic overreach and passive under-response.",
	),
	array(
		'question_text' => 'An LPCC providing individual therapy to one partner is asked to add the other partner and convert the work into ongoing conjoint treatment. What should the LPCC do FIRST?',
		'option_a' => 'Begin conjoint sessions because the original client already consented to psychotherapy.',
		'option_b' => 'Tell the new participant that the original client controls all confidentiality decisions.',
		'option_c' => 'Clarify the proposed treatment purpose, who will be clients, each person\'s role, informed consent, confidentiality and record expectations, competence, and whether the role change is clinically appropriate before converting the treatment.',
		'option_d' => 'End individual therapy immediately and begin conjoint work the same day.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. The new participant and changed treatment structure require fresh role and consent analysis.\n\nB. Incorrect. Multi-person treatment requires a clear, lawful policy and cannot be resolved by assumption.\n\nC. Correct. Moving from individual to conjoint treatment can change the client unit, roles, confidentiality, records, expectations, and conflicts. Those issues should be addressed before the change.\n\nD. Incorrect. Abrupt role conversion does not resolve competence, consent, confidentiality, and continuity concerns.\n\nCTA Exam Strategy: Center client welfare, autonomy, access, relationship power, and continuity; avoid both paternalistic overreach and passive under-response.",
	),
	array(
		'question_text' => 'A current client sends an LPCC a friend request on the counselor\'s personal social-media account. What is the BEST response?',
		'option_a' => 'Ignore the request permanently because discussing it would be unethical.',
		'option_b' => 'Assess the boundary, confidentiality, treatment, policy, and client-welfare implications; follow the established policy and discuss the issue clinically when useful.',
		'option_c' => 'Accept automatically to avoid hurting the client\'s feelings.',
		'option_d' => 'Block the client and terminate treatment because any online contact is a prohibited dual relationship.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. A clinically appropriate discussion may clarify expectations and prevent misunderstanding.\n\nB. Correct. A thoughtful, policy-consistent response is stronger than automatic acceptance, blocking, or termination.\n\nC. Incorrect. Automatic acceptance can create confidentiality and boundary complications.\n\nD. Incorrect. A friend request does not automatically require termination or establish prohibited conduct.\n\nCTA Exam Strategy: Center client welfare, autonomy, access, relationship power, and continuity; avoid both paternalistic overreach and passive under-response.",
	),
	array(
		'question_text' => 'A long-term client loses insurance and says the current fee is no longer affordable. The LPCC\'s practice has limited reduced-fee capacity. What is the BEST response?',
		'option_a' => 'Discuss the financial change transparently, review available lawful options and resources, avoid coercive pressure, and plan continuity or referral if an affordable arrangement cannot be sustained.',
		'option_b' => 'Terminate immediately at the end of the current session.',
		'option_c' => 'Require the client to borrow money before discussing alternatives.',
		'option_d' => 'Continue indefinitely without discussing payment even if the practice cannot sustain it.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. Client welfare and access call for transparent discussion and proportionate continuity planning, not a promise the practice cannot keep or abrupt abandonment.\n\nB. Incorrect. Abrupt termination may create preventable continuity problems.\n\nC. Incorrect. Coercive financial pressure is inconsistent with client welfare and professional boundaries.\n\nD. Incorrect. Avoiding the financial issue can create later disruption and unclear expectations.\n\nCTA Exam Strategy: Center client welfare, autonomy, access, relationship power, and continuity; avoid both paternalistic overreach and passive under-response.",
	),
	array(
		'question_text' => 'After several months, outcome data and client feedback show that counseling is not improving the target problem and the alliance is worsening. What should the LPCC do NEXT?',
		'option_a' => 'Continue the same plan because changing course would undermine confidence.',
		'option_b' => 'Reassess the formulation, goals, intervention fit, client preferences, barriers, and competence; consult or modify, refer, or transfer as indicated rather than simply continuing unchanged.',
		'option_c' => 'Label the client resistant and document noncompliance without reassessment.',
		'option_d' => 'End treatment immediately without discussing the findings.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. Persisting despite poor response can increase harm and ignore feedback.\n\nB. Correct. Beneficence and nonmaleficence require attention to treatment response and willingness to revise a plan that is not working.\n\nC. Incorrect. A client-blaming label can obscure treatment mismatch and clinician factors.\n\nD. Incorrect. Reassessment and collaborative planning usually come before abrupt termination when no emergency requires immediate action.\n\nCTA Exam Strategy: Center client welfare, autonomy, access, relationship power, and continuity; avoid both paternalistic overreach and passive under-response.",
	),
	array(
		'question_text' => 'A competent adult client understands the material information and voluntarily refuses an LPCC\'s recommended intervention. No emergency or involuntary authority applies. What is the appropriate response?',
		'option_a' => 'Ask a family member to override the client\'s decision.',
		'option_b' => 'Respect the informed refusal, discuss reasonable alternatives and foreseeable consequences, and document the decision-making process.',
		'option_c' => 'Begin the intervention anyway because the LPCC believes it is best.',
		'option_d' => 'End all services because refusal of one intervention proves the client is unwilling to participate.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. Family preference does not replace the competent adult client's decision-making authority.\n\nB. Correct. In voluntary treatment, a competent client may generally refuse a proposed intervention after meaningful informed discussion.\n\nC. Incorrect. Professional preference does not ordinarily override a competent client's informed refusal.\n\nD. Incorrect. Other appropriate treatment options may remain.\n\nCTA Exam Strategy: Center client welfare, autonomy, access, relationship power, and continuity; avoid both paternalistic overreach and passive under-response.",
	),
	array(
		'question_text' => 'A clinic tells every client with limited English proficiency to bring a family member to interpret or the clinic will refuse service. An LPCC sees that this rule is preventing one client from discussing trauma safely. What is the BEST response?',
		'option_a' => 'Tell the family member to sign a confidentiality form and assume the problem is solved.',
		'option_b' => 'Terminate the client because the clinic lacks a bilingual clinician.',
		'option_c' => 'Follow the rule because applying the same policy to everyone is always fair.',
		'option_d' => 'Address the client\'s immediate communication and confidentiality needs using an appropriate language-access solution and raise the blanket policy for organizational review and correction.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. A form does not establish interpreter competence, neutrality, or freedom from coercion.\n\nB. Incorrect. Lack of a bilingual clinician does not automatically justify refusing care without exploring appropriate language-access options.\n\nC. Incorrect. A uniform policy can still create discriminatory or clinically unsafe barriers.\n\nD. Correct. The problem includes both individual access/confidentiality risk and a structural policy barrier. Equal rules are not always equitable when they prevent meaningful care.\n\nCTA Exam Strategy: Center client welfare, autonomy, access, relationship power, and continuity; avoid both paternalistic overreach and passive under-response.",
	),
	array(
		'question_text' => 'An LPCC wants to advocate for a client\'s workplace accommodation. The client has not authorized disclosure to the employer. What is the BEST approach?',
		'option_a' => 'Clarify the client\'s goals and preferred advocacy role, obtain appropriate authorization before disclosing protected information, and share only what is necessary for the agreed purpose.',
		'option_b' => 'Contact the employer immediately because advocacy always overrides confidentiality.',
		'option_c' => 'Refuse any advocacy because counselors may never communicate with employers.',
		'option_d' => 'Send the complete record so the employer understands the client\'s history.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. Advocacy supports client welfare and self-determination but does not eliminate confidentiality or authorization requirements.\n\nB. Incorrect. Advocacy must still operate within privacy and disclosure rules.\n\nC. Incorrect. Appropriate advocacy may be part of care when authorized and within role.\n\nD. Incorrect. Broad disclosure is unnecessary and risks violating confidentiality and client choice.\n\nCTA Exam Strategy: Center client welfare, autonomy, access, relationship power, and continuity; avoid both paternalistic overreach and passive under-response.",
	),
	array(
		'question_text' => 'An LPCC discovers that yesterday\'s progress note contains a material factual error. What is the BEST correction method?',
		'option_a' => 'Leave the error because completed notes can never be corrected.',
		'option_b' => 'Delete the original note and replace it without showing a change.',
		'option_c' => 'Ask administrative staff to edit the clinician\'s note under the staff member\'s login.',
		'option_d' => 'Preserve the original entry and add a dated, attributable correction or addendum that states the accurate information according to the record system\'s lawful procedure.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. Records can be corrected through a transparent, attributable method.\n\nB. Incorrect. Silent deletion can undermine record integrity and appear deceptive.\n\nC. Incorrect. Corrections should be attributable to the appropriate author and follow the record system's procedure.\n\nD. Correct. Transparent correction preserves record integrity and an audit trail rather than concealing the original entry.\n\nCTA Exam Strategy: Look for the practice-system response: clear policy, accurate records, lawful information flow, supervision, technology safeguards, and documented follow-through.",
	),
	array(
		'question_text' => 'A former client posts a harsh public review. The LPCC believes the review is false and wants to reply with dates of attendance and details of the treatment plan. What is the BEST response?',
		'option_a' => 'Post the diagnosis so readers can judge the review fairly.',
		'option_b' => 'Ask another client to respond publicly on the counselor\'s behalf.',
		'option_c' => 'Use a neutral response, if any, that does not confirm client status or disclose confidential information, and address reputational concerns through appropriate nonconfidential channels.',
		'option_d' => 'Disclose the treatment details because the client spoke first.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. This would compound the confidentiality problem.\n\nB. Incorrect. Recruiting clients into a public dispute creates additional boundary and confidentiality concerns.\n\nC. Correct. A client's public statement does not authorize the counselor to reveal attendance, treatment, diagnosis, or other confidential information in a public rebuttal.\n\nD. Incorrect. A public review does not waive confidentiality for the counselor.\n\nCTA Exam Strategy: Look for the practice-system response: clear policy, accurate records, lawful information flow, supervision, technology safeguards, and documented follow-through.",
	),
	array(
		'question_text' => 'During a telehealth session with a client reporting escalating suicidal thoughts, the video platform repeatedly fails. What should the LPCC do NEXT?',
		'option_a' => 'Continue reconnecting the video indefinitely before taking any other step.',
		'option_b' => 'End the session and send a routine scheduling message for next week.',
		'option_c' => 'Post the client\'s location in a public technical-support forum to obtain help.',
		'option_d' => 'Use the established backup and emergency procedures, verify the client\'s current location and immediate safety, restore reliable contact or activate local emergency resources as indicated, and document the response.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. Technical troubleshooting should not delay necessary safety action.\n\nB. Incorrect. Elevated risk requires active safety assessment and continuity planning.\n\nC. Incorrect. This would create unnecessary confidentiality and security risk.\n\nD. Correct. Elevated risk makes continuity and emergency planning more important, not less. The counselor should move to a safe backup pathway rather than spending the whole crisis troubleshooting technology.\n\nCTA Exam Strategy: Look for the practice-system response: clear policy, accurate records, lawful information flow, supervision, technology safeguards, and documented follow-through.",
	),
	array(
		'question_text' => 'An agency policy instructs APCCs to route all suspected child-abuse concerns to a supervisor and forbids staff from making external reports directly. What is the BEST response?',
		'option_a' => 'Wait until the supervisor gives written permission to report.',
		'option_b' => 'Follow the agency policy because employer rules control staff conduct.',
		'option_c' => 'Follow the individual mandated-reporting duty and use internal notification procedures only to the extent they do not impede or substitute for the required external report; raise the defective policy for correction.',
		'option_d' => 'Ignore the agency policy but never tell anyone it is defective.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. Supervisor permission is not required for an individual mandated report.\n\nB. Incorrect. Employer policy cannot authorize violation of a mandatory reporting statute.\n\nC. Correct. Organizational policy cannot override an individual statutory reporting duty, and the systemic policy problem should also be addressed.\n\nD. Incorrect. The immediate duty must be met, and a recurring policy risk should also be addressed through appropriate organizational channels.\n\nCTA Exam Strategy: Look for the practice-system response: clear policy, accurate records, lawful information flow, supervision, technology safeguards, and documented follow-through.",
	),
	array(
		'question_text' => 'An LPCC learns that a laptop containing client information may have been accessed by an unauthorized person. The facts are incomplete. What should occur FIRST?',
		'option_a' => 'Contain the incident, preserve relevant evidence, identify what information and systems may be affected, activate the organization\'s privacy/security response, and then determine notification obligations from the facts.',
		'option_b' => 'Delete system logs to reduce embarrassment.',
		'option_c' => 'Ignore the event because no client has complained.',
		'option_d' => 'Immediately tell every client that a reportable breach definitely occurred.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. A proportionate incident response begins with containment and factual assessment; notification decisions depend on the nature of the information, safeguards, access, and applicable law.\n\nB. Incorrect. Destroying evidence impairs investigation and accountability.\n\nC. Incorrect. Security obligations do not depend on receiving a complaint.\n\nD. Incorrect. Notification may be required, but the facts must first be assessed under the applicable rules.\n\nCTA Exam Strategy: Look for the practice-system response: clear policy, accurate records, lawful information flow, supervision, technology safeguards, and documented follow-through.",
	),
	array(
		'question_text' => 'An LPCC\'s intake agreement lists the session fee but does not mention a substantial late-cancellation charge. After the first missed appointment, the LPCC imposes the charge. What is the BEST concern?',
		'option_a' => 'Cancellation fees are always prohibited in counseling.',
		'option_b' => 'Fees have no connection to informed decision-making.',
		'option_c' => 'The fee is automatically valid because it appears on the practice website.',
		'option_d' => 'A significant financial policy that could affect participation was not communicated before it was enforced.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. The problem is the lack of advance transparency, not a universal prohibition on such fees.\n\nB. Incorrect. Significant financial terms can materially affect whether and how a client participates in treatment.\n\nC. Incorrect. A website posting does not necessarily establish that the client received and understood the material policy before enforcement.\n\nD. Correct. Transparent fee and practice policies support informed choice and reduce unfair surprise or coercion.\n\nCTA Exam Strategy: Look for the practice-system response: clear policy, accurate records, lawful information flow, supervision, technology safeguards, and documented follow-through.",
	),
	array(
		'question_text' => 'An APCC repeatedly omits direct suicide-risk assessment and documentation despite prior feedback, and several high-risk clients remain assigned. What is the BEST supervisory response?',
		'option_a' => 'Immediately end the APCC\'s career without assessment or authorized process.',
		'option_b' => 'Review affected client risk, take needed protective action, increase observation and supervision, limit or reassign high-risk work as appropriate, set a documented remediation plan with criteria and follow-up, and use gatekeeping if unsafe performance continues.',
		'option_c' => 'Wait until the annual evaluation so the APCC has time to improve independently.',
		'option_d' => 'Provide reassurance only because defensiveness is a normal developmental stage.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. Gatekeeping should be evidence-based, proportionate, and follow applicable supervision and organizational procedures.\n\nB. Correct. Effective supervision protects current clients while providing specific remediation, monitoring, and accountability rather than waiting passively or using unsupported punishment.\n\nC. Incorrect. Ongoing high-risk omissions require timely intervention.\n\nD. Incorrect. Support may help, but it does not replace client protection and remediation.\n\nCTA Exam Strategy: Look for the practice-system response: clear policy, accurate records, lawful information flow, supervision, technology safeguards, and documented follow-through.",
	),
	array(
		'question_text' => 'A school counselor asks an LPCC for "everything you have" about a shared adolescent client so the school team can plan accommodations. The client/family authorization permits coordination but is limited to information relevant to school functioning. What is the BEST response?',
		'option_a' => 'Clarify the purpose and recipient, share only information within the authorization and reasonably relevant to the coordination purpose, and document the disclosure.',
		'option_b' => 'Refuse all collaboration because school staff are not psychotherapists.',
		'option_c' => 'Ask the school to decide what the LPCC is legally allowed to disclose.',
		'option_d' => 'Send the complete psychotherapy record because the professionals are on the same team.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. Collaboration does not create unrestricted access; purpose, permission, minimum relevant information, and documentation should align.\n\nB. Incorrect. Authorized and appropriate coordination may support client welfare.\n\nC. Incorrect. The LPCC remains responsible for determining lawful, authorized disclosure within professional role.\n\nD. Incorrect. Team participation does not automatically authorize the full record.\n\nCTA Exam Strategy: Look for the practice-system response: clear policy, accurate records, lawful information flow, supervision, technology safeguards, and documented follow-through.",
	),
);
