<?php
/**
 * CTA LPCC Law & Ethics EP - Practice Examination B (50 questions).
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
return array(
	array(
		'question_text' => 'At an initial session, a new adult client says, "I signed the intake form, so we do not need to talk about consent." Which response by the LPCC BEST reflects informed-consent requirements?',
		'option_a' => 'Agree because a signed form completes the informed-consent process.',
		'option_b' => 'Discuss only confidentiality because all other treatment information can wait until the client asks.',
		'option_c' => 'Review the counseling relationship and process, including material risks, benefits, alternatives, fees, limits of confidentiality, and other information needed for an informed choice, and document the discussion.',
		'option_d' => 'Begin treatment first and provide the consent information only if the client later objects.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. A signature can document consent, but it does not replace the information-sharing and understanding that make consent informed.\n\nB. Incorrect. Confidentiality is important, but informed consent also includes the nature of services, risks, benefits, fees, alternatives, qualifications, and other material information.\n\nC. Correct. Informed consent is a communication process, not a one-time signature; the client needs accurate information about the counseling relationship and process before making an informed choice.\n\nD. Incorrect. Material consent information should be addressed at initiation, not deferred until a problem arises.\n\nCTA Exam Strategy: When the stem contrasts a signature with an informed process, choose the option that preserves disclosure, understanding, voluntariness, and documentation.",
	),
	array(
		'question_text' => 'A probation-referred client arrives for court-ordered counseling and asks, "Exactly what are you going to tell probation?" What should the LPCC do FIRST?',
		'option_a' => 'Promise that nothing will be disclosed without a new court order.',
		'option_b' => 'Tell the client that probation automatically receives the complete clinical record.',
		'option_c' => 'Wait until probation asks for information before discussing disclosure limits.',
		'option_d' => 'Explain before counseling what information is required or may be shared, with whom it may be shared, the limits of confidentiality, and the foreseeable consequences of refusing services.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. Mandated counseling can involve legally or contractually required disclosures, so an absolute promise of nondisclosure is unsafe.\n\nB. Incorrect. Court involvement does not automatically authorize unrestricted release of the entire clinical record.\n\nC. Incorrect. The client should understand disclosure expectations and consequences before treatment proceeds, not only after a request arrives.\n\nD. Correct. Mandated clients should receive clear advance information about confidentiality limits, required reporting channels, and the possible consequences of refusing the mandated service.\n\nCTA Exam Strategy: With mandated clients, identify the reporting relationship first. The best answer clarifies the specific disclosure pathway before treatment rather than promising secrecy or assuming unlimited access.",
	),
	array(
		'question_text' => 'An adult client previously signed a valid authorization allowing the LPCC to send monthly treatment summaries to an attorney. Before the next summary is sent, the client clearly revokes the authorization. What should the LPCC do?',
		'option_a' => 'Send the next summary because the original authorization was valid when signed.',
		'option_b' => 'Continue sending summaries until the attorney acknowledges the revocation.',
		'option_c' => 'Stop future disclosures under that authorization, document the revocation, and reassess whether any other lawful basis requires or permits disclosure.',
		'option_d' => 'Delete every record showing that earlier authorized disclosures occurred.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. A valid authorization does not create an unlimited right to continue future disclosures after a valid revocation.\n\nB. Incorrect. The client does not need the recipient's permission to revoke the client's authorization for future disclosures.\n\nC. Correct. The LPCC should stop relying on the revoked authorization for future disclosures, document the change, and separately evaluate any independent legal basis for disclosure.\n\nD. Incorrect. Records of prior lawful disclosures should not be erased merely because the client later revokes authorization.\n\nCTA Exam Strategy: Ask whether the disclosure authority is still active at the moment of the proposed disclosure. Do not confuse prior validity with continuing validity.",
	),
	array(
		'question_text' => 'A 15-year-old lawfully self-consented to outpatient counseling under California minor-consent law. The parent, who has not participated in treatment, later demands the complete counseling record. What should the LPCC do FIRST?',
		'option_a' => 'Determine who has legal access to the specific records at issue under the minor-consent and patient-record statutes before releasing anything.',
		'option_b' => 'Release the record because a parent always has access to a minor\'s mental-health record.',
		'option_c' => 'Refuse the request permanently because a parent can never receive records from a minor\'s treatment.',
		'option_d' => 'Ask the minor to destroy the record so there is nothing to release.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. When a minor lawfully consents to care, record-access rights can differ from ordinary parental access; the LPCC should identify the controlling legal authority before disclosure.\n\nB. Incorrect. Parental status does not automatically override every confidentiality or record-access rule when the minor independently consented to the care.\n\nC. Incorrect. An absolute rule against any parental access is also too broad; access depends on the controlling law and facts.\n\nD. Incorrect. Destroying a record to avoid a lawful access analysis would violate recordkeeping and integrity duties.\n\nCTA Exam Strategy: In minor questions, separate three issues: who consented, who controls confidentiality/privilege, and who may inspect or receive the records.",
	),
	array(
		'question_text' => 'A former adult client requests a copy of the treatment record but still owes the LPCC $600. Which response is MOST appropriate under California patient-record law?',
		'option_a' => 'Withhold the record until the account is paid in full.',
		'option_b' => 'Process the record request according to law and address the unpaid balance separately.',
		'option_c' => 'Release only the diagnosis page because the account is delinquent.',
		'option_d' => 'Require the client to sign a payment plan before the request can be processed.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. California law prohibits withholding patient records or summaries because of an unpaid bill for health-care services.\n\nB. Correct. Record-access obligations and fee collection are separate; the LPCC should comply with the lawful request while pursuing the balance through appropriate channels.\n\nC. Incorrect. Delinquency does not justify arbitrarily limiting the records to which the client is legally entitled.\n\nD. Incorrect. A payment plan may be discussed, but it cannot be used to frustrate a lawful record request.\n\nCTA Exam Strategy: When money and records are combined in a stem, test whether the fee issue actually changes the legal disclosure/access rule. Here, it does not.",
	),
	array(
		'question_text' => 'A mature 16-year-old lawfully self-consents to outpatient counseling. The parent has not participated in treatment. The clinic asks the LPCC whether it may automatically bill the parent for the sessions. Which answer is BEST?',
		'option_a' => 'Yes. Parents are always financially responsible for all health services received by a minor.',
		'option_b' => 'No. Under the minor-consent pathway, the parent is not liable for those counseling services unless the parent participates, and then only for services rendered with that participation.',
		'option_c' => 'Yes, but only if the minor refuses to provide insurance information.',
		'option_d' => 'No, because minors can never be charged for mental-health services.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. California's minor-consent statute creates a specific exception to automatic parental financial liability for services provided under that pathway.\n\nB. Correct. The statute provides that a parent or guardian is not liable for treatment authorized under the minor-consent provision unless the parent or guardian participates, and then only for the participating services.\n\nC. Incorrect. Insurance information does not create the statutory parental-payment rule described in the question.\n\nD. Incorrect. The law does not state that mental-health services for minors are categorically free.\n\nCTA Exam Strategy: When a statute creates a special consent route, check whether it also changes related duties such as parent involvement, payment, or records access.",
	),
	array(
		'question_text' => 'An LPCC licensed only in California has an established telehealth client who texts from Oregon: "I am here for three weeks. Can we keep our regular sessions?" What should the LPCC do FIRST?',
		'option_a' => 'Continue because the therapeutic relationship began in California.',
		'option_b' => 'Continue if the client signs a waiver accepting all jurisdictional risk.',
		'option_c' => 'Convert the session to telephone because telephone sessions do not cross jurisdictional lines.',
		'option_d' => 'Determine whether the LPCC is legally authorized to provide counseling to a client physically located in Oregon and whether Oregon permits that telehealth service before proceeding.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. Where the relationship began does not erase the law of the jurisdiction where the client is physically located during the service.\n\nB. Incorrect. A client waiver cannot authorize professional practice that the jurisdiction does not permit.\n\nC. Incorrect. Changing the communication medium does not eliminate the jurisdictional practice issue.\n\nD. Correct. California regulation requires a California licensee serving a client in another jurisdiction to meet that jurisdiction's legal requirements and for telehealth delivery to be permitted there.\n\nCTA Exam Strategy: For cross-border telehealth, locate the client first, then ask whether the clinician has legal authority to practice in that jurisdiction. Consent cannot cure lack of authority.",
	),
	array(
		'question_text' => 'An adult client submits a proper request for an electronic copy of records that the LPCC maintains electronically in a readily producible format. Which action BEST follows California patient-record law?',
		'option_a' => 'Wait 30 calendar days because all health-record requests have a 30-day response period.',
		'option_b' => 'Provide the requested copy in the readily producible electronic format and transmit it within the applicable 15-day period.',
		'option_c' => 'Require the client to inspect the records in person before receiving a copy.',
		'option_d' => 'Convert the records to paper because electronic delivery is never required.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. The general copy-transmission period in the cited California provision is 15 days after receipt of the request, not a universal 30 days.\n\nB. Correct. When the records are maintained electronically and the requested format is readily producible, the provider should supply that electronic format and meet the statutory transmission timeframe.\n\nC. Incorrect. Inspection is a separate right; the client need not inspect in person before receiving a copy.\n\nD. Incorrect. The statute expressly contemplates electronic copies when the records are maintained electronically.\n\nCTA Exam Strategy: Look for exact operational duties-who may request, what format is available, and the response deadline-rather than defaulting to generic HIPAA timelines.",
	),
	array(
		'question_text' => 'An LPCC develops reasonable suspicion of child abuse during a session. Which reporting sequence matches California CANRA?',
		'option_a' => 'Make the initial report by telephone immediately or as soon as practicably possible and send the written follow-up within 36 hours.',
		'option_b' => 'Wait for corroboration, then submit only a written report within seven days.',
		'option_c' => 'Notify the clinical supervisor and allow the supervisor to decide whether an external report is necessary.',
		'option_d' => 'Document the concern in the chart and report only if the child later confirms the abuse.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. CANRA requires an initial telephone report immediately or as soon as practicably possible, followed by the written report within 36 hours.\n\nB. Incorrect. Reasonable suspicion-not corroborated certainty-triggers the duty, and the standard sequence is not a seven-day written-only process.\n\nC. Incorrect. Internal consultation does not replace the mandated reporter's legal reporting duty.\n\nD. Incorrect. The reporter does not wait for later confirmation once reasonable suspicion exists.\n\nCTA Exam Strategy: In mandated-reporting items, identify the threshold first, then the timing and destination. Do not choose options that require proof before reporting.",
	),
	array(
		'question_text' => 'Two mandated reporters jointly learn facts creating reasonable suspicion of child abuse. They agree that one will make the required report. Later, the LPCC learns the designated reporter never did. What must the LPCC do?',
		'option_a' => 'Make the mandated report because a team member who learns the designated reporter failed must thereafter report.',
		'option_b' => 'Do nothing because the original team agreement permanently transferred the duty.',
		'option_c' => 'Only document that the colleague accepted responsibility.',
		'option_d' => 'Wait for the supervisor to decide whether the missed report should be corrected.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. California permits a jointly selected reporter, but any team member who learns that the designated reporter failed must thereafter make the report.\n\nB. Incorrect. The agreement does not extinguish each mandated reporter's responsibility if the selected reporter fails to act.\n\nC. Incorrect. Documentation alone does not cure the missed statutory report.\n\nD. Incorrect. A supervisor cannot substitute for or impede the mandated reporter's individual duty.\n\nCTA Exam Strategy: If a question mentions a joint report, ask what happens if the designated reporter fails. The duty returns to the team member who knows of the failure.",
	),
	array(
		'question_text' => 'During outpatient therapy, a 77-year-old client reports that a caregiver has been taking signed blank checks and withdrawing money without permission. The LPCC reasonably suspects financial abuse. What is the BEST legal response?',
		'option_a' => 'Maintain confidentiality because financial abuse is not reportable unless physical injury also occurred.',
		'option_b' => 'Ask the caregiver for an explanation before deciding whether to report.',
		'option_c' => 'Make the mandated report immediately or as soon as practicably possible to the appropriate adult protective services or law-enforcement agency and complete the required follow-up reporting.',
		'option_d' => 'Wait until the client obtains bank records proving the withdrawals.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. California elder/dependent-adult reporting law includes financial abuse among reportable categories.\n\nB. Incorrect. The mandated reporter does not investigate the suspected perpetrator before satisfying the reporting duty.\n\nC. Correct. Reasonable suspicion of elder financial abuse triggers prompt reporting; outside specified facilities, the report generally goes to adult protective services or local law enforcement, with the required follow-up if reported by telephone.\n\nD. Incorrect. The reporting threshold does not require documentary proof.\n\nCTA Exam Strategy: Do not narrow mandated abuse to physical abuse. Read the category in the stem and ask whether California law expressly includes it.",
	),
	array(
		'question_text' => 'A 16-year-old client tells an LPCC she is pregnant. No other facts suggesting abuse, coercion, exploitation, or unlawful sexual conduct are known. Which statement is MOST accurate for CANRA analysis?',
		'option_a' => 'Pregnancy of a minor, by itself, does not automatically create reasonable suspicion of sexual abuse; the LPCC should assess the surrounding facts and report if the legal threshold is met.',
		'option_b' => 'Pregnancy of any person under 18 automatically requires a child-abuse report.',
		'option_c' => 'Pregnancy can never be relevant to a mandated-reporting analysis.',
		'option_d' => 'The LPCC should contact the alleged partner before deciding whether reasonable suspicion exists.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. California law expressly states that a minor's pregnancy, standing alone, does not itself establish reasonable suspicion of sexual abuse; other facts may still create a reporting duty.\n\nB. Incorrect. The statute rejects an automatic-report rule based solely on pregnancy.\n\nC. Incorrect. Pregnancy may be relevant when combined with facts such as age differences, coercion, trafficking, or other abuse indicators.\n\nD. Incorrect. A mandated reporter should not investigate the alleged partner before determining and satisfying the reporting duty.\n\nCTA Exam Strategy: When the law names a fact that is insufficient by itself, avoid absolute answers. Assess the total facts and apply the statutory threshold.",
	),
	array(
		'question_text' => 'A client describes a specific, imminent plan to set fire to a neighbor\'s unoccupied vehicle. The LPCC has reasonable cause to believe the client is dangerous to another person\'s property and that disclosure is necessary to prevent the threatened danger. Which statement is BEST?',
		'option_a' => 'Psychotherapist-patient privilege absolutely bars any disclosure because no person was directly threatened.',
		'option_b' => 'California\'s dangerous-patient privilege exception can remove privilege when the patient is dangerous to self or to the person or property of another and disclosure is necessary to prevent the threatened danger.',
		'option_c' => 'The LPCC may disclose the entire psychotherapy record to anyone who asks about the threat.',
		'option_d' => 'The LPCC must wait until a crime has actually occurred before considering disclosure.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. Evidence Code 1024 is not limited to threats against a person; it also references danger to the property of another when the statutory conditions are met.\n\nB. Correct. The privilege exception applies when the psychotherapist has reasonable cause to believe the patient is dangerous to self or another's person or property and disclosure is necessary to prevent the threatened danger.\n\nC. Incorrect. An exception to privilege does not authorize indiscriminate release of the entire clinical record.\n\nD. Incorrect. The exception is preventive and does not require waiting for the threatened harm to occur.\n\nCTA Exam Strategy: Separate privilege from confidentiality and from the civil duty-to-protect statute. The question is asking whether privilege exists under the dangerous-patient exception.",
	),
	array(
		'question_text' => 'An 82-year-old outpatient client is repeatedly found without food, medications, or safe heat because the client is no longer able to provide basic care for themself. The LPCC reasonably suspects neglect. What is the BEST response?',
		'option_a' => 'Treat the issue only as a treatment-planning problem because neglect must be caused by another person.',
		'option_b' => 'Wait for the client to consent to an adult protective services report.',
		'option_c' => 'Report only if the client is first placed under conservatorship.',
		'option_d' => 'Follow the elder/dependent-adult mandated-reporting requirements for suspected neglect, including self-neglect when the statutory definition is met.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. California elder/dependent-adult law can include failure to provide basic care for oneself within the broader neglect framework.\n\nB. Incorrect. A mandated report does not depend on the client voluntarily authorizing it when the statutory duty applies.\n\nC. Incorrect. Conservatorship is not a prerequisite to mandated reporting of suspected elder or dependent-adult neglect.\n\nD. Correct. When facts reasonably indicate reportable neglect, the LPCC follows the applicable mandated-reporting process rather than treating the problem solely as a private clinical issue.\n\nCTA Exam Strategy: Do not assume \"abuse reporting\" always requires an abuser. California's elder/dependent-adult framework can include neglect arising from inability to meet basic needs.",
	),
	array(
		'question_text' => 'After developing reasonable suspicion of reportable child abuse, an LPCC worries that the parent has not signed a release of information to child protective services. What should the LPCC conclude?',
		'option_a' => 'A signed release is required before any mandated report can be made.',
		'option_b' => 'The LPCC should ask the alleged perpetrator to authorize the report.',
		'option_c' => 'The mandated-reporting statute supplies the legal basis for the required report; client authorization is not a prerequisite to making the mandated disclosure.',
		'option_d' => 'The LPCC may report only after a judge signs an order.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. Requiring a client release would defeat the mandatory nature of the reporting statute.\n\nB. Incorrect. The suspected perpetrator does not control whether a mandated reporter may satisfy the legal duty.\n\nC. Correct. When a mandated-reporting statute requires disclosure, the report is made under that legal authority rather than a client-signed authorization.\n\nD. Incorrect. A court order is not required before making a mandated child-abuse report.\n\nCTA Exam Strategy: When a stem asks whether an ROI is needed for a mandated disclosure, identify whether the law itself creates the disclosure authority and duty.",
	),
	array(
		'question_text' => 'An elder client diagnosed with dementia tells an LPCC that a neighbor stole millions of dollars from a nonexistent account. There is no independent corroborating evidence. After careful clinical assessment, the LPCC reasonably believes the alleged abuse did not occur. Which statement BEST reflects California elder/dependent-adult reporting law?',
		'option_a' => 'Every statement by an elder must be reported regardless of any statutory exception.',
		'option_b' => 'A narrow exception may apply to a psychotherapist when all statutory conditions are satisfied, including the diagnosed mental illness or dementia, no independent corroboration, and a clinical judgment that the abuse did not occur.',
		'option_c' => 'The LPCC must personally investigate the neighbor before deciding whether the exception applies.',
		'option_d' => 'The exception applies whenever an elder asks the counselor not to report.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. The statute contains a narrow psychotherapist/physician/nurse exception when every listed condition is present.\n\nB. Correct. California law recognizes a limited exception in this specific fact pattern; it does not create a broad discretionary right to ignore suspected abuse.\n\nC. Incorrect. The statute expressly states that it does not impose a duty to investigate suspected abuse.\n\nD. Incorrect. Client preference alone is not one of the statutory elements of the exception.\n\nCTA Exam Strategy: For narrow statutory exceptions, test each element one by one. Do not generalize the exception beyond the exact conditions stated in law.",
	),
	array(
		'question_text' => 'At the start of psychotherapy, which notice practice is required for an LPCC or APCC under current California law?',
		'option_a' => 'Provide only a verbal statement that the client may complain to the BBS.',
		'option_b' => 'Provide the required written BBS notice in at least 12-point type and include the practitioner\'s full name, license or registration number, type, and expiration date, with delivery documented.',
		'option_c' => 'Provide the BBS notice only if the client asks how to file a complaint.',
		'option_d' => 'Provide the notice only to clients seen in person, not telehealth clients.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. The statute requires a written notice and specifies content and documentation requirements.\n\nB. Correct. Current law requires the BBS complaint notice and, for services initiated on or after the operative date, the practitioner-identifying information and expiration date, with delivery documented.\n\nC. Incorrect. The notice is not contingent on a client request.\n\nD. Incorrect. The requirement is tied to initiating psychotherapy services, not limited to in-person delivery.\n\nCTA Exam Strategy: For board-required notices, watch for operative-date additions. Choose the option that includes the complete current notice rather than an older abbreviated version.",
	),
	array(
		'question_text' => 'A private group practice offers a registered APCC a 1099 independent-contractor position to provide psychotherapy while receiving weekly supervision. Which statement is MOST accurate?',
		'option_a' => 'The arrangement is permitted if the supervisor signs a supervision agreement.',
		'option_b' => 'The arrangement is permitted if the APCC carries malpractice insurance.',
		'option_c' => 'The arrangement is permitted if no more than half of the APCC\'s hours are paid on a 1099.',
		'option_d' => 'The arrangement is not permitted for qualifying supervised experience because an APCC may perform covered services only as an employee or volunteer, not as an independent contractor.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. A supervision agreement does not cure a prohibited employment classification.\n\nB. Incorrect. Malpractice insurance does not change the statutory employee-or-volunteer requirement.\n\nC. Incorrect. The law does not create a percentage exception allowing some independent-contractor hours.\n\nD. Correct. California law expressly prohibits associates from performing services or gaining qualifying experience as independent contractors.\n\nCTA Exam Strategy: When a stem gives excellent supervision but an invalid work status, the work-status rule still controls.",
	),
	array(
		'question_text' => 'An LPCC provides in-person psychotherapy at the counselor\'s primary office. What does California law require regarding the professional license?',
		'option_a' => 'The license must be carried in the counselor\'s wallet during each session.',
		'option_b' => 'The license must be displayed in a conspicuous place in the primary place of practice when rendering professional clinical services in person.',
		'option_c' => 'The license must be posted only on the counselor\'s website.',
		'option_d' => 'No display is required if clients can verify the license online.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. The statute describes display at the primary place of practice, not wallet possession.\n\nB. Correct. California law requires conspicuous display at the primary place of practice when the licensee is rendering in-person professional clinical services.\n\nC. Incorrect. Website information does not replace the statutory in-office display requirement.\n\nD. Incorrect. Online verification is useful but does not eliminate the display requirement.\n\nCTA Exam Strategy: Do not overthink a direct statute question. If the stem names the primary in-person practice location, recall the specific display requirement.",
	),
	array(
		'question_text' => 'An LPCC opens a solo practice under the fictitious business name "Clear Horizons Counseling." What additional California requirement applies before treatment begins?',
		'option_a' => 'The LPCC must obtain a separate mental-health license for the fictitious business name.',
		'option_b' => 'The LPCC must use only the LPCC\'s personal legal name and may never use a fictitious name.',
		'option_c' => 'The LPCC must disclose the names of every future contractor who might work for the business.',
		'option_d' => 'The business name must not be false, misleading, or deceptive, and the patient must be informed of the owner\'s name and license designation before treatment begins.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. The question concerns disclosure and truthful naming, not a separate professional license for the business name.\n\nB. Incorrect. California permits an LPCC to use a fictitious business name subject to statutory conditions.\n\nC. Incorrect. The cited rule focuses on the owner or owners and truthful business identity, not hypothetical future personnel.\n\nD. Correct. The statute requires a nonmisleading name and pre-treatment disclosure of the owner's name and license designation.\n\nCTA Exam Strategy: When a business-name question appears, look for truthfulness plus owner/license disclosure rather than assuming fictitious names are prohibited.",
	),
	array(
		'question_text' => 'A California LPCC is asked to administer an individually administered intelligence test as part of a comprehensive neuropsychological battery. Which response is MOST accurate?',
		'option_a' => 'The LPCC may do so whenever the test publisher sells the instrument to counselors.',
		'option_b' => 'The LPCC assessment definition does not include individually administered intelligence tests, projective personality techniques, or neuropsychological testing; the LPCC should stay within lawful scope and refer as needed.',
		'option_c' => 'The LPCC may do so if a client signs a scope-of-practice waiver.',
		'option_d' => 'The LPCC may perform any psychological test after one continuing-education course.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. Publisher access does not determine California statutory scope of practice.\n\nB. Correct. California's LPCC scope expressly excludes these assessment activities from the statutory assessment definition.\n\nC. Incorrect. Client consent cannot expand a professional license's legal scope.\n\nD. Incorrect. Training can improve competence, but it cannot authorize an activity the statute excludes from the profession's scope.\n\nCTA Exam Strategy: In scope questions, ask first \"Is the activity legally included?\" before asking whether the clinician is trained enough to perform it.",
	),
	array(
		'question_text' => 'An LPCC terminates therapy with a client when the client is 14 years old. Assuming no other law requires longer retention, through what minimum point must the LPCC retain the health-service record under BPC 4999.75?',
		'option_a' => 'Until the client reaches age 25.',
		'option_b' => 'Seven years from the termination date, regardless of the client\'s age.',
		'option_c' => 'Until the client reaches age 21.',
		'option_d' => 'Only until the client reaches age 18.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. For a minor, the LPCC must retain the record for at least seven years from the date the client reaches age 18, which in this scenario means through age 25.\n\nB. Incorrect. The minor-specific rule runs from the date the client reaches 18, not simply from the termination date.\n\nC. Incorrect. Age 21 is shorter than the seven-years-after-18 statutory minimum.\n\nD. Incorrect. Reaching majority starts the seven-year retention period; it does not end it.\n\nCTA Exam Strategy: When an exam question gives the minor's age, translate the rule into an endpoint: 18 + 7 years = age 25.",
	),
	array(
		'question_text' => 'An LPCC experienced in adult anxiety wants to begin treating eating disorders but has no specialized education, supervised experience, or consultation in that area. What is the BEST ethical next step?',
		'option_a' => 'Begin immediately because all psychotherapy falls within the same competence area.',
		'option_b' => 'Accept only the least severe eating-disorder cases without telling clients about the learning curve.',
		'option_c' => 'Obtain appropriate education, training, and supervised experience or consultation before practicing independently in the new specialty, while protecting clients from harm.',
		'option_d' => 'Rely on treatment manuals alone because written protocols substitute for specialty competence.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. A broad counseling license does not mean the counselor is competent in every specialty population or treatment area.\n\nB. Incorrect. Lower apparent severity does not remove the obligation to practice within competence and be transparent about limitations.\n\nC. Correct. ACA ethics requires appropriate preparation before practicing in a specialty area new to the counselor and reasonable steps to protect clients while skills are developing.\n\nD. Incorrect. Manuals can support training but do not substitute for appropriate education, training, and supervised experience.\n\nCTA Exam Strategy: When the counselor lacks a competency foundation, choose training/supervision before independent practice-not \"start carefully and learn as you go.\"",
	),
	array(
		'question_text' => 'An LPCC notices that several clients with similar concerns have stopped improving despite faithful use of the counselor\'s usual approach. What is the MOST ethical response?',
		'option_a' => 'Review effectiveness, seek peer consultation or supervision, and adjust practice when indicated.',
		'option_b' => 'Continue unchanged because using the same method consistently proves professional integrity.',
		'option_c' => 'Assume the clients are resistant and document that treatment failure is their responsibility.',
		'option_d' => 'Avoid discussing outcomes with colleagues because consultation signals incompetence.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. Counselors continually monitor professional effectiveness and take steps to improve, including peer supervision or consultation when useful.\n\nB. Incorrect. Consistency is not a substitute for evaluating whether treatment is working.\n\nC. Incorrect. Automatically attributing poor outcomes to clients bypasses clinical responsibility and outcome monitoring.\n\nD. Incorrect. Ethical practice encourages appropriate consultation; it is not evidence of incompetence.\n\nCTA Exam Strategy: When a stem shows repeated lack of progress, favor evaluation and consultation over defensiveness or rigid adherence to the same method.",
	),
	array(
		'question_text' => 'An LPCC begins a prescribed medication that causes significant sedation and slowed judgment. During two sessions the counselor loses track of important clinical details. No client has complained. What should the LPCC do FIRST?',
		'option_a' => 'Continue the full caseload until a client formally reports harm.',
		'option_b' => 'Ask clients to decide whether the counselor seems impaired enough to stop working.',
		'option_c' => 'Recognize the functional impairment, seek appropriate assistance, and limit or suspend professional duties until the counselor can practice safely.',
		'option_d' => 'Keep working but add a disclaimer to the informed-consent form about medication side effects.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. The counselor's duty to monitor impairment does not depend on receiving a client complaint.\n\nB. Incorrect. Clients should not be placed in the role of determining the counselor's fitness to practice.\n\nC. Correct. Ethical self-monitoring requires action when physical, mental, or emotional problems impair safe professional functioning, including limiting or suspending duties when necessary.\n\nD. Incorrect. Disclosure does not make impaired practice safe or ethically acceptable.\n\nCTA Exam Strategy: Focus on function, not diagnosis or cause. If judgment is impaired, reduce risk first, then address recovery and safe return to practice.",
	),
	array(
		'question_text' => 'An LPCC wants to use a standardized symptom measure with a client whose primary language is not English. The LPCC cannot locate a validated version and considers translating the items independently during the session and interpreting the score using English norms. What is the BEST response?',
		'option_a' => 'Translate the measure spontaneously because any translation is better than no assessment.',
		'option_b' => 'Use the English norms but lower the cutoff score to account for language differences.',
		'option_c' => 'Select an assessment approach that is linguistically and culturally appropriate and within competence, using validated tools or qualified resources when available rather than presenting an ad hoc translation as standardized.',
		'option_d' => 'Avoid all assessment with clients who do not speak English.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. An improvised translation can change item meaning and undermine the validity of a standardized score.\n\nB. Incorrect. Arbitrarily changing cutoffs does not repair invalid administration or inappropriate norms.\n\nC. Correct. Ethical assessment requires appropriate instruments, competence in their use, and attention to language and cultural factors that affect interpretation.\n\nD. Incorrect. Language difference calls for an appropriate assessment strategy, not abandonment of assessment altogether.\n\nCTA Exam Strategy: When the stem threatens test validity, choose the option that protects measurement integrity and cultural/linguistic appropriateness.",
	),
	array(
		'question_text' => 'A client describes a spiritual practice unfamiliar to the LPCC. The counselor initially wonders whether the experience is pathological but recognizes limited cultural knowledge. What is the BEST next step?',
		'option_a' => 'Immediately diagnose a psychotic-spectrum disorder because unusual beliefs are inherently pathological.',
		'option_b' => 'Explore the client\'s meaning and cultural context, examine the counselor\'s assumptions, and seek culturally informed consultation or training before drawing conclusions.',
		'option_c' => 'Avoid discussing the practice so cultural issues cannot influence treatment.',
		'option_d' => 'Ask the client to stop the practice until the counselor decides whether it is normal.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. Unfamiliarity does not establish psychopathology and can reflect counselor bias rather than client disorder.\n\nB. Correct. Cultural humility requires curiosity, self-awareness, and appropriate consultation before interpreting culturally situated experiences.\n\nC. Incorrect. Avoidance does not produce culturally responsive assessment and can leave clinically important meaning unexplored.\n\nD. Incorrect. Directing the client to stop a culturally meaningful practice without adequate assessment risks value imposition and harm.\n\nCTA Exam Strategy: When culture could change the meaning of a behavior, choose inquiry and self-examination before diagnosis or intervention.",
	),
	array(
		'question_text' => 'An LPCC learns credible information that another counselor has been intentionally falsifying clinical records in a way that has substantially harmed multiple clients. Informal discussion would not be appropriate or sufficient. What is the BEST ethical response?',
		'option_a' => 'Ignore the conduct because counselors should never become involved in a colleague\'s ethics.',
		'option_b' => 'Discuss the allegations casually with other clinicians so the community can decide what to do.',
		'option_c' => 'Confront the counselor privately and promise not to take any further action regardless of the response.',
		'option_d' => 'Take appropriate further action through applicable institutional, licensing, certification, or ethics channels while protecting client confidentiality.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. Serious ethical misconduct that substantially harms clients can require action beyond private concern.\n\nB. Incorrect. Informal gossip risks confidentiality and due-process problems and is not an ethical reporting pathway.\n\nC. Incorrect. The ACA framework distinguishes minor issues suitable for informal resolution from substantial harm that may warrant further action.\n\nD. Correct. When substantial harm has occurred or is likely and informal resolution is inappropriate or unsuccessful, counselors take further action through appropriate channels while considering confidentiality rights.\n\nCTA Exam Strategy: First decide whether the issue is minor and informally resolvable or substantially harmful. That classification changes the expected response.",
	),
	array(
		'question_text' => 'An LPCC has a master\'s degree in counseling and a doctorate in an unrelated field. In a counseling advertisement, the LPCC wants to use "Dr." without clarifying the doctorate\'s field. What is the MOST ethical approach?',
		'option_a' => 'Use "Dr." because any earned doctorate automatically represents doctoral-level counseling competence.',
		'option_b' => 'Avoid implying doctoral-level counseling competence and clearly represent the counselor\'s actual degrees and credentials.',
		'option_c' => 'Use "Dr." only on social media because advertising ethics do not apply there.',
		'option_d' => 'List "ABD" after the counseling degree to suggest advanced counseling training.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. An unrelated doctorate does not establish doctoral-level competence in counseling.\n\nB. Correct. Counselors accurately represent qualifications and avoid titles that misleadingly imply counseling competence they do not possess.\n\nC. Incorrect. Ethical accuracy applies to public professional representations, including online advertising.\n\nD. Incorrect. The ACA Code specifically cautions against \"ABD\" or similar terms used to imply competence.\n\nCTA Exam Strategy: Credential questions often test whether a technically true fact is presented in a misleading way. Choose clarity over status signaling.",
	),
	array(
		'question_text' => 'An LPCC faces an unusual dilemma for which agency policy, client wishes, and professional ethics point in different directions. No immediate emergency exists. What should the LPCC do FIRST?',
		'option_a' => 'Use a credible ethical decision-making process, identify applicable law and ethical standards, consult as needed, consider risks and benefits, and document the reasoning.',
		'option_b' => 'Follow the agency policy automatically because employer rules always control ethics.',
		'option_c' => 'Choose the option that creates the least paperwork.',
		'option_d' => 'Ask the client to decide which professional rule the LPCC should follow.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. Ethical dilemmas call for a deliberate, supportable process that integrates law, standards, consultation, alternatives, and client welfare.\n\nB. Incorrect. Organizational policy can matter but does not automatically override law or professional ethics.\n\nC. Incorrect. Administrative convenience is not an ethical decision-making criterion.\n\nD. Incorrect. Client preferences are important but the counselor retains responsibility for lawful and ethical professional judgment.\n\nCTA Exam Strategy: When several authorities conflict, do not jump to the loudest one. Use a structured hierarchy and document the reasoning.",
	),
	array(
		'question_text' => 'A client asks for help thinking through a reproductive-health decision that conflicts with the LPCC\'s personal beliefs. The LPCC is clinically competent to work with the concern. What is the BEST ethical response?',
		'option_a' => 'Support the client\'s informed decision-making without imposing the counselor\'s values, and seek consultation or training if personal reactions threaten objectivity.',
		'option_b' => 'Explain the counselor\'s moral position until the client adopts a safer value system.',
		'option_c' => 'Terminate immediately because any values difference makes counseling impossible.',
		'option_d' => 'Refer the client solely because the counselor disagrees with the client\'s possible choice.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. Counselors avoid imposing personal values and work to support client autonomy and welfare while managing their own reactions responsibly.\n\nB. Incorrect. Persuading the client to adopt the counselor's moral position is value imposition.\n\nC. Incorrect. A values difference does not automatically require termination when the counselor can practice competently and ethically.\n\nD. Incorrect. ACA ethics cautions against referral based solely on the counselor's personally held values.\n\nCTA Exam Strategy: When the conflict belongs to the counselor rather than the client, manage the counselor's reaction rather than transferring the cost to the client.",
	),
	array(
		'question_text' => 'A client in a rural community asks to exchange farm produce for part of the counseling fee, a practice commonly accepted by local professionals. Which response BEST reflects ACA ethics?',
		'option_a' => 'Bartering is always unethical in counseling.',
		'option_b' => 'Bartering may be considered if the client requests it, it is culturally and locally appropriate, and the arrangement does not create exploitation or harm.',
		'option_c' => 'Bartering is ethical whenever the goods have a clear market value, regardless of power dynamics.',
		'option_d' => 'Bartering is permitted only after treatment has ended.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. ACA ethics does not impose an absolute ban on bartering.\n\nB. Correct. The Code permits bartering under limited conditions that include client request, community acceptance, and protection from exploitation or harm, with attention to cultural implications.\n\nC. Incorrect. Market value alone does not address exploitation, power, or therapeutic impact.\n\nD. Incorrect. The standard addresses bartering during counseling and does not require waiting until termination.\n\nCTA Exam Strategy: Avoid absolute rules unless the code actually uses one. For bartering, look for safeguards rather than a categorical prohibition.",
	),
	array(
		'question_text' => 'An LPCC ended counseling with a former client three years ago. Both are now single, and the former client proposes a romantic relationship. Under the current working ACA Code of Ethics, what is the BEST response?',
		'option_a' => 'Begin the relationship because three years is sufficient if both adults consent.',
		'option_b' => 'Begin the relationship after documenting that the former client initiated contact.',
		'option_c' => 'Do not enter the romantic relationship because the ACA Code prohibits sexual or romantic relationships with former clients for five years after the last professional contact.',
		'option_d' => 'Begin the relationship if the LPCC obtains consultation and the former client signs a waiver.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. The current ACA Code establishes a five-year prohibition, so three years is not sufficient.\n\nB. Incorrect. Who initiated contact does not shorten the five-year prohibition.\n\nC. Correct. The current 2014 ACA Code-still the operative code while the 2026 revision is pending-prohibits sexual or romantic relationships with former clients for five years after last professional contact.\n\nD. Incorrect. Consultation or waiver cannot override the express five-year prohibition.\n\nCTA Exam Strategy: Distinguish boundary extensions, which may allow risk-benefit analysis, from expressly prohibited sexual or romantic relationships.",
	),
	array(
		'question_text' => 'A long-term adolescent client invites the LPCC to the client\'s public high-school graduation. The client believes attendance would mark an important therapeutic milestone. What is the BEST ethical response?',
		'option_a' => 'Decline automatically because any contact outside the office is a boundary violation.',
		'option_b' => 'Attend automatically because the client requested it.',
		'option_c' => 'Ask the client\'s parent to decide whether the boundary crossing is ethical.',
		'option_d' => 'Evaluate risks and benefits, cultural and therapeutic meaning, confidentiality and role concerns, consult as appropriate, and document the rationale if the boundary is extended.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. Not every boundary extension is automatically a violation; the ethical analysis is contextual.\n\nB. Incorrect. Client invitation alone does not establish that attendance is clinically appropriate or low risk.\n\nC. Incorrect. Family input may matter, but professional responsibility for the boundary decision remains with the counselor.\n\nD. Correct. ACA ethics directs counselors to consider risks and benefits and use safeguards such as informed consent, consultation, and documentation when extending boundaries.\n\nCTA Exam Strategy: When a boundary crossing may be beneficial, look for a structured risk-benefit analysis and documented safeguards.",
	),
	array(
		'question_text' => 'An LPCC is competent to counsel a gay client but feels personal religious discomfort with the client\'s relationship goals. The LPCC wants to refer the client solely because of that discomfort. What is the BEST ethical response?',
		'option_a' => 'Refer immediately because counselor comfort always takes priority over continuity of care.',
		'option_b' => 'Tell the client the counselor disapproves of the relationship and let the client decide whether to stay.',
		'option_c' => 'Continue only if the client agrees not to discuss the relationship.',
		'option_d' => 'Do not refer solely because of the counselor\'s personal values; address the risk of value imposition through supervision, consultation, training, and other steps that protect competent client-centered care.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. Counselor comfort is not the governing ethical priority when competent care can be provided.\n\nB. Incorrect. Disclosing disapproval can pressure the client and impose counselor values.\n\nC. Incorrect. Conditioning treatment on avoidance of a core client concern distorts the counseling relationship and client goals.\n\nD. Correct. ACA ethics directs counselors not to refer clients solely because of personal values and to seek training or support where values threaten ethical practice.\n\nCTA Exam Strategy: If the counselor is competent and the only barrier is personal values, referral is usually the distractor-not the ethical solution.",
	),
	array(
		'question_text' => 'An LPCC plans to retire in three months. Several clients will need ongoing treatment after the practice closes. Which action BEST protects client welfare?',
		'option_a' => 'Tell clients at the final session so they do not become anxious in advance.',
		'option_b' => 'Stop accepting payment now but continue indefinitely until every client independently terminates.',
		'option_c' => 'Give reasonable advance notice, discuss transition options and referrals, make an orderly plan for records and continuity, and avoid abrupt abandonment.',
		'option_d' => 'Transfer all records to another clinician without informing clients because continuity outweighs confidentiality.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. Delaying notice can impair client choice and continuity and increase abandonment risk.\n\nB. Incorrect. Retirement does not require indefinite continuation of practice; it requires an orderly transition.\n\nC. Correct. Planned closure should include timely notice, continuity/referral planning, and secure record arrangements so clients are not abandoned.\n\nD. Incorrect. Continuity planning does not erase confidentiality and authorization requirements for record transfer.\n\nCTA Exam Strategy: When the clinician is ending services for a foreseeable reason, choose advance planning and continuity rather than abrupt termination.",
	),
	array(
		'question_text' => 'An LPCC learns that a client is simultaneously receiving psychotherapy from another clinician for overlapping concerns. No emergency exists. What should the LPCC do FIRST?',
		'option_a' => 'Discuss the overlap with the client, request appropriate authorization to communicate with the other provider, and clarify roles to support coordinated care.',
		'option_b' => 'Contact the other clinician immediately and exchange full records without client authorization.',
		'option_c' => 'Terminate automatically because two therapists may never treat the same client.',
		'option_d' => 'Ignore the information because coordination is outside the LPCC\'s responsibility.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. Counselors should address overlapping professional relationships collaboratively, using client authorization and role clarification to reduce conflicting treatment.\n\nB. Incorrect. Coordination does not justify unrestricted disclosure without a lawful basis.\n\nC. Incorrect. Concurrent care is not automatically unethical; the issue is whether roles and treatment are coordinated appropriately.\n\nD. Incorrect. Ignoring potentially conflicting services can undermine treatment effectiveness and client welfare.\n\nCTA Exam Strategy: When another provider appears in the stem, do not jump directly to disclosure or termination. Clarify roles and obtain proper authorization.",
	),
	array(
		'question_text' => 'Before beginning a therapy group, what is the BEST way for the LPCC to address confidentiality?',
		'option_a' => 'Promise that everything said in group is legally privileged and can never be repeated by members.',
		'option_b' => 'Avoid discussing confidentiality because doing so may make members anxious.',
		'option_c' => 'Explain the importance and limits of confidentiality, establish expectations among members, and clarify that the counselor cannot guarantee that every member will keep information private.',
		'option_d' => 'Require members to sign a contract stating that any breach will automatically result in criminal charges.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. The counselor cannot guarantee the conduct of other group members or create legal privilege by promise.\n\nB. Incorrect. Group-specific confidentiality limits are material information that should be discussed, not avoided.\n\nC. Correct. Ethical group practice includes explaining confidentiality and its limits and establishing member expectations without making guarantees the counselor cannot enforce.\n\nD. Incorrect. A private group agreement does not automatically create criminal penalties.\n\nCTA Exam Strategy: Be suspicious of absolute confidentiality promises in group settings. The best answer acknowledges both expectations and limits.",
	),
	array(
		'question_text' => 'A new client has limited English proficiency and does not understand the LPCC\'s informed-consent explanation. The client\'s 12-year-old child offers to interpret. What is the BEST response?',
		'option_a' => 'Arrange qualified language assistance that protects accuracy and confidentiality and confirm the client\'s understanding, rather than automatically relying on the child.',
		'option_b' => 'Proceed with the child interpreting because family members are always the most culturally appropriate translators.',
		'option_c' => 'Ask the client to sign the English form anyway because a signature is sufficient.',
		'option_d' => 'Refuse treatment permanently because informed consent cannot be provided in another language.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. Counselors communicate consent information in understandable, culturally appropriate ways and use qualified interpretation or translation when needed.\n\nB. Incorrect. A minor family member can create accuracy, role, and confidentiality problems and should not be treated as the automatic solution.\n\nC. Incorrect. A signature without comprehension does not create meaningful informed consent.\n\nD. Incorrect. Language access is a service-delivery problem to solve, not a categorical reason to deny counseling.\n\nCTA Exam Strategy: If the client cannot understand the consent language, choose qualified access support-not a signature-only workaround.",
	),
	array(
		'question_text' => 'A client strongly requests a technique the LPCC knows is supported by substantial evidence of harm. The client states, "I accept the risk, so please do it." What is the BEST ethical response?',
		'option_a' => 'Provide the technique because informed consent transfers the risk to the client.',
		'option_b' => 'Provide the technique once, then evaluate whether harm occurs.',
		'option_c' => 'Have the client sign a waiver releasing the LPCC from responsibility.',
		'option_d' => 'Do not use a technique when substantial evidence suggests harm, even if the client requests it; instead discuss safer, ethically supportable alternatives.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. Client consent does not make a substantially harmful professional practice ethically acceptable.\n\nB. Incorrect. Ethical standards do not require exposing a client to known substantial risk in order to \"test\" whether harm occurs.\n\nC. Incorrect. A waiver does not transform an unethical or harmful technique into acceptable care.\n\nD. Correct. ACA ethics directs counselors not to use techniques when substantial evidence suggests harm, even when clients request them.\n\nCTA Exam Strategy: When the stem says substantial evidence of harm, informed consent is not the escape hatch. The technique itself is the problem.",
	),
	array(
		'question_text' => 'An LPCC has been treating a couple. After separation begins, one partner asks the LPCC to become that partner\'s individual therapist while the other partner remains involved in divorce litigation. What should the LPCC do FIRST?',
		'option_a' => 'Assess the proposed role change for conflicts, confidentiality and objectivity concerns, clarify the implications with the involved clients, and obtain informed consent if an ethically appropriate change is made.',
		'option_b' => 'Accept the individual immediately because the requesting partner was already a client.',
		'option_c' => 'Provide individual treatment secretly so the other partner is not upset.',
		'option_d' => 'Automatically destroy the couple record and start a new individual record.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. Role changes require careful analysis and informed consent, especially when prior conjoint treatment and active litigation can create competing duties and impaired objectivity.\n\nB. Incorrect. Prior client status does not eliminate conflicts created by changing from a conjoint role to an individual role.\n\nC. Incorrect. Secret role changes can undermine informed consent and create serious confidentiality and trust problems.\n\nD. Incorrect. Record destruction is not an ethical method of resolving role conflicts.\n\nCTA Exam Strategy: When the professional role changes, pause. Reassess conflicts, consent, confidentiality, and whether the new role can be performed objectively.",
	),
	array(
		'question_text' => 'At the end of a treatment milestone, a client offers the LPCC a modest handmade item that has important cultural meaning. What is the BEST ethical response?',
		'option_a' => 'Reject every gift because accepting any item from a client is unethical.',
		'option_b' => 'Consider the therapeutic relationship, the item\'s monetary value, the client\'s motivation, the counselor\'s motivation, and the cultural meaning before deciding whether acceptance is appropriate.',
		'option_c' => 'Accept every culturally meaningful gift to avoid appearing disrespectful.',
		'option_d' => 'Accept the gift only if the client agrees to extend treatment.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect. ACA ethics does not impose an absolute prohibition on receiving gifts.\n\nB. Correct. Gift decisions are contextual and should consider value, motivation, therapeutic effects, and cultural meaning.\n\nC. Incorrect. Cultural meaning is important but does not eliminate the need to consider boundaries and possible exploitation.\n\nD. Incorrect. Linking gift acceptance to continued treatment would create an inappropriate financial or relational contingency.\n\nCTA Exam Strategy: For gifts, look for a multi-factor boundary analysis rather than a blanket rule.",
	),
	array(
		'question_text' => 'A set of client records has reached the end of the applicable retention period and is eligible for destruction. Which method BEST reflects professional confidentiality duties?',
		'option_a' => 'Place paper files in ordinary recycling because the treatment has ended.',
		'option_b' => 'Give the files to an office employee to take home and dispose of later.',
		'option_c' => 'Use a secure destruction process, such as cross-cut shredding or secure professional destruction for paper and verified secure deletion for electronic records, consistent with applicable policy and law.',
		'option_d' => 'Leave the files in an unlocked storage area until enough records accumulate to justify disposal.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. Confidentiality survives termination and ordinary recycling can expose identifiable health information.\n\nB. Incorrect. Casual offsite disposal increases unauthorized access risk and lacks appropriate control.\n\nC. Correct. Destruction should render confidential information unreadable or unrecoverable through a controlled process appropriate to the record medium.\n\nD. Incorrect. Eligibility for destruction does not justify insecure interim storage.\n\nCTA Exam Strategy: When records are being destroyed, ask whether the method actually prevents reconstruction or unauthorized access.",
	),
	array(
		'question_text' => 'An LPCC wants an online presence for both personal interests and professional counseling information. Which approach BEST follows ACA social-media ethics?',
		'option_a' => 'Use one mixed profile so clients can see the counselor\'s complete personal life.',
		'option_b' => 'Create a personal account but invite all clients to follow it for convenience.',
		'option_c' => 'Avoid all social media because counselors may not have any online presence.',
		'option_d' => 'Maintain clearly separate professional and personal profiles and explain relevant social-media boundaries as part of informed consent.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. Mixing personal and professional identities can blur boundaries and increase confidentiality risk.\n\nB. Incorrect. Inviting current clients into a personal virtual relationship conflicts with professional-boundary standards.\n\nC. Incorrect. ACA ethics does not ban a professional online presence; it establishes safeguards.\n\nD. Correct. Separate professional and personal virtual presences help clarify boundaries, and social-media expectations should be addressed with clients.\n\nCTA Exam Strategy: For social-media questions, distinguish professional visibility from personal virtual relationships with clients.",
	),
	array(
		'question_text' => 'After completing a weekend trauma workshop that does not confer a recognized certification, an LPCC adds "Certified Trauma Specialist" to the practice website. What is the BEST response?',
		'option_a' => 'Keep the title because the workshop certificate proves specialist certification.',
		'option_b' => 'Keep the title if no client has complained.',
		'option_c' => 'Use the title only in paid advertisements, not on the website biography.',
		'option_d' => 'Remove or revise the claim so the website accurately describes the training without implying a credential the LPCC does not actually hold.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. A certificate of attendance is not automatically equivalent to a professional certification.\n\nB. Incorrect. Advertising must be accurate before a complaint occurs.\n\nC. Incorrect. Accuracy requirements apply across professional advertising formats.\n\nD. Correct. Counselors must represent credentials accurately and avoid false, misleading, or deceptive claims about qualifications.\n\nCTA Exam Strategy: In advertising questions, separate training from certification and competence from credentialing. Use the exact status that can be substantiated.",
	),
	array(
		'question_text' => 'A clinic director instructs an LPCC to document psychotherapy sessions that did not occur so the program can meet productivity targets. What should the LPCC do FIRST?',
		'option_a' => 'Follow the order because the director is responsible for agency compliance.',
		'option_b' => 'Enter the false notes but add a private memo explaining they were required by management.',
		'option_c' => 'Refuse to falsify the record, identify the legal and ethical conflict, use appropriate organizational or compliance channels, and protect accurate client documentation.',
		'option_d' => 'Delete all existing notes so no productivity comparison can be made.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. Employer authority does not excuse falsification of clinical records or other unlawful/unethical conduct.\n\nB. Incorrect. A private memo does not make a knowingly false clinical record truthful.\n\nC. Correct. The LPCC should preserve record integrity, make the conflict known through appropriate channels, and not participate in deceptive documentation.\n\nD. Incorrect. Destroying legitimate records would compound the integrity and legal problems.\n\nCTA Exam Strategy: When agency policy conflicts with law or ethics, do not assume hierarchy equals authority. Preserve lawful, accurate practice and escalate appropriately.",
	),
	array(
		'question_text' => 'An LPCC seeks consultation about a difficult case. The consultant does not need the client\'s identity to answer the clinical question. What is the BEST information-sharing approach?',
		'option_a' => 'Share only information germane to the consultation and protect the client\'s identity when it is not necessary for the professional purpose.',
		'option_b' => 'Send the entire record because consultants are automatically entitled to all client information.',
		'option_c' => 'Post the case anonymously in a large public online forum because the client\'s name is omitted.',
		'option_d' => 'Avoid consultation entirely because discussing any client information with another professional is unethical.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. Ethical consultation limits information to what is professionally relevant and protects identifying information when disclosure is unnecessary.\n\nB. Incorrect. Consultation does not create an automatic need or right to the entire clinical record.\n\nC. Incorrect. A public forum can create re-identification and confidentiality risks even without the client's name.\n\nD. Incorrect. Appropriate confidential consultation is an important professional competence and risk-management tool.\n\nCTA Exam Strategy: Use the minimum-relevant-information rule in consultation questions, especially when client identity is not necessary.",
	),
	array(
		'question_text' => 'An LPCC decides to increase the session fee for existing private-pay clients beginning next month. What is the BEST practice?',
		'option_a' => 'Apply the increase retroactively to sessions already completed.',
		'option_b' => 'Wait until clients receive a larger bill and explain the increase only if they complain.',
		'option_c' => 'Give clients reasonable advance notice, clearly explain the new fee and effective date, and address questions or continuity concerns before the change takes effect.',
		'option_d' => 'Avoid documenting the new fee because written fee policies create legal obligations.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect. Retroactive fee changes undermine informed financial agreements and can create billing disputes.\n\nB. Incorrect. Surprise billing is inconsistent with transparent informed consent and business practices.\n\nC. Correct. Fees are material treatment information; advance disclosure supports informed choice and allows clients to plan for continuity or alternatives.\n\nD. Incorrect. Clear documentation of fee arrangements is a safeguard, not a reason to avoid disclosure.\n\nCTA Exam Strategy: For fee-change questions, choose advance disclosure and client choice rather than surprise or retroactive billing.",
	),
	array(
		'question_text' => 'Which preparation BEST reflects an LPCC\'s ethical responsibility for client records if the counselor becomes incapacitated, dies, retires, or unexpectedly terminates practice?',
		'option_a' => 'Leave no plan so confidentiality is preserved by default.',
		'option_b' => 'Tell clients to keep their own copies because the counselor has no responsibility after practice closure.',
		'option_c' => 'Give passwords to several friends so someone can decide what to do later.',
		'option_d' => 'Maintain a secure continuity plan for transfer or dissemination of records, including an identified records custodian or other appropriate arrangement when needed.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. Lack of planning can make records inaccessible or insecure and can disrupt client continuity.\n\nB. Incorrect. Professional recordkeeping duties do not disappear because the practice closes.\n\nC. Incorrect. Unstructured password sharing creates serious confidentiality and access-control risks.\n\nD. Correct. Ethical practice includes planning for secure record continuity and access in the event the counselor can no longer manage the practice.\n\nCTA Exam Strategy: When a stem asks about incapacity or death, think records custodian, secure access, continuity, and advance planning.",
	),
	array(
		'question_text' => 'An LPCC is interviewed on a podcast about coping with grief. Which approach BEST reflects professional ethics?',
		'option_a' => 'Give individualized treatment instructions to callers and tell them a counseling relationship has been established.',
		'option_b' => 'Use dramatic claims that are likely to attract listeners even if the evidence is weak.',
		'option_c' => 'Present personal opinions as official positions of the counseling profession without clarification.',
		'option_d' => 'Provide general information grounded in appropriate professional literature and ethics, avoid misleading claims, and do not encourage listeners to believe a professional counseling relationship has been established.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect. General media education does not ordinarily create an individualized counseling relationship, and the counselor should not blur that boundary.\n\nB. Incorrect. Public professional statements should be accurate and grounded in appropriate knowledge rather than sensationalized.\n\nC. Incorrect. Counselors should clarify when public statements are personal and should not misrepresent them as official professional positions.\n\nD. Correct. Ethical media participation requires accurate, professionally grounded information and clear boundaries so recipients do not infer that counseling has begun.\n\nCTA Exam Strategy: In media questions, look for three controls: evidence-based accuracy, ethical consistency, and no false implication of a counseling relationship.",
	),
);
