<?php
/**
 * CTA LPCC Law & Ethics EP - License-Specific Module 25-Question Assessment.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
return array(
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of Authority hierarchy?',
		'option_a' => 'When sources conflict, controlling California law and regulation govern legal duties; ethics and policy operate within that lawful boundary.',
		'option_b' => 'LPCC assessment activities may be within statutory scope, but the statutory definition and express exclusions must be respected.',
		'option_c' => 'Websites, directories, social media, cards, and employer-created profiles can all function as advertising and must be reviewed for current compliance.',
		'option_d' => 'Client consent or initiation does not erase professional responsibility or statutory restrictions on sexual or exploitative conduct.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. When sources conflict, controlling California law and regulation govern legal duties; ethics and policy operate within that lawful boundary.\n\nB. Incorrect for this item. This option states the separate principle of Assessment is included but bounded; it does not answer the tested concept of Authority hierarchy.\n\nC. Incorrect for this item. This option states the separate principle of Advertising across platforms; it does not answer the tested concept of Authority hierarchy.\n\nD. Incorrect for this item. This option states the separate principle of Sexual and exploitative conduct; it does not answer the tested concept of Authority hierarchy.\n\nCTA Exam Strategy: Return to the license-specific module section on Authority hierarchy. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of Current source version?',
		'option_a' => 'Associate advertising must include current required identifying, employer/entity, and supervised-status information; one correct element does not cure an omitted requirement.',
		'option_b' => 'Competence, accurate representation, records, fees, referrals, sexual conduct, impairment, and other conduct rules are organized around public and client protection.',
		'option_c' => 'When sources conflict, controlling California law and regulation govern legal duties; ethics and policy operate within that lawful boundary.',
		'option_d' => 'Date and version matter because statutes, regulations, Board guidance, examination materials, and ethics standards can change.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect for this item. This option states the separate principle of APCC advertising elements; it does not answer the tested concept of Current source version.\n\nB. Incorrect for this item. This option states the separate principle of Professional conduct and public protection; it does not answer the tested concept of Current source version.\n\nC. Incorrect for this item. This option states the separate principle of Authority hierarchy; it does not answer the tested concept of Current source version.\n\nD. Correct. Date and version matter because statutes, regulations, Board guidance, examination materials, and ethics standards can change.\n\nCTA Exam Strategy: Return to the license-specific module section on Current source version. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of LPCC professional identity?',
		'option_a' => 'APCC services must occur in a lawful employment or volunteer structure with compliant payment and business-interest arrangements.',
		'option_b' => 'Candidates should use current BBS/Pearson instructions for retest, annual participation, and active-registration requirements rather than relying on old templates.',
		'option_c' => 'LPCC professional clinical counseling is a distinct statutory profession with its own scope, duties, and examination pathway.',
		'option_d' => 'LPCC assessment activities may be within statutory scope, but the statutory definition and express exclusions must be respected.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect for this item. This option states the separate principle of Lawful APCC work and payment; it does not answer the tested concept of LPCC professional identity.\n\nB. Incorrect for this item. This option states the separate principle of Retest and participation rules; it does not answer the tested concept of LPCC professional identity.\n\nC. Correct. LPCC professional clinical counseling is a distinct statutory profession with its own scope, duties, and examination pathway.\n\nD. Incorrect for this item. This option states the separate principle of Assessment is included but bounded; it does not answer the tested concept of LPCC professional identity.\n\nCTA Exam Strategy: Return to the license-specific module section on LPCC professional identity. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of Status and present authority?',
		'option_a' => 'The APCC pathway involves registration, supervised experience, Law and Ethics requirements, application milestones, and later examination steps in a defined sequence.',
		'option_b' => 'An APCC\'s registration and supervision status affects what the person may do now; profession-wide scope does not create independent authority.',
		'option_c' => 'Current LPCC analysis should use the current statutory scope rather than teach superseded profession-specific prerequisites.',
		'option_d' => 'Associate advertising must include current required identifying, employer/entity, and supervised-status information; one correct element does not cure an omitted requirement.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect for this item. This option states the separate principle of Registration and examination pathway; it does not answer the tested concept of Status and present authority.\n\nB. Correct. An APCC's registration and supervision status affects what the person may do now; profession-wide scope does not create independent authority.\n\nC. Incorrect for this item. This option states the separate principle of Couples and families; it does not answer the tested concept of Status and present authority.\n\nD. Incorrect for this item. This option states the separate principle of APCC advertising elements; it does not answer the tested concept of Status and present authority.\n\nCTA Exam Strategy: Return to the license-specific module section on Status and present authority. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of Couples and families?',
		'option_a' => 'Current LPCC analysis should use the current statutory scope rather than teach superseded profession-specific prerequisites.',
		'option_b' => 'Date and version matter because statutes, regulations, Board guidance, examination materials, and ethics standards can change.',
		'option_c' => 'Assessment information should be reported, stored, and used in a way that matches the instrument\'s purpose, protects confidentiality, and avoids misuse.',
		'option_d' => 'APCC services must occur in a lawful employment or volunteer structure with compliant payment and business-interest arrangements.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. Current LPCC analysis should use the current statutory scope rather than teach superseded profession-specific prerequisites.\n\nB. Incorrect for this item. This option states the separate principle of Current source version; it does not answer the tested concept of Couples and families.\n\nC. Incorrect for this item. This option states the separate principle of Assessment results and misuse prevention; it does not answer the tested concept of Couples and families.\n\nD. Incorrect for this item. This option states the separate principle of Lawful APCC work and payment; it does not answer the tested concept of Couples and families.\n\nCTA Exam Strategy: Return to the license-specific module section on Couples and families. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of Referral as scope safeguard?',
		'option_a' => 'A candidate must recognize activities the LPCC assessment definition excludes and refer when another professional service is required.',
		'option_b' => 'Clinical supervision is more than consultation; it includes responsibility for and control of service quality, monitoring, competence, records, and feedback.',
		'option_c' => 'The APCC pathway involves registration, supervised experience, Law and Ethics requirements, application milestones, and later examination steps in a defined sequence.',
		'option_d' => 'When a service falls outside lawful scope or cannot be provided competently, referral or another lawful alternative protects the client.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect for this item. This option states the separate principle of Assessment exclusions; it does not answer the tested concept of Referral as scope safeguard.\n\nB. Incorrect for this item. This option states the separate principle of Supervision means responsibility and control; it does not answer the tested concept of Referral as scope safeguard.\n\nC. Incorrect for this item. This option states the separate principle of Registration and examination pathway; it does not answer the tested concept of Referral as scope safeguard.\n\nD. Correct. When a service falls outside lawful scope or cannot be provided competently, referral or another lawful alternative protects the client.\n\nCTA Exam Strategy: Return to the license-specific module section on Referral as scope safeguard. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of Assessment is included but bounded?',
		'option_a' => 'Required client notices and relationship/process disclosures should be accurate, timely, and consistent with the clinician\'s actual status and role.',
		'option_b' => 'When functioning is impaired, protect clients first, stop or limit unsafe practice, obtain appropriate help and coverage, and document continuity steps.',
		'option_c' => 'LPCC assessment activities may be within statutory scope, but the statutory definition and express exclusions must be respected.',
		'option_d' => 'Date and version matter because statutes, regulations, Board guidance, examination materials, and ethics standards can change.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect for this item. This option states the separate principle of Client-facing disclosures; it does not answer the tested concept of Assessment is included but bounded.\n\nB. Incorrect for this item. This option states the separate principle of Impairment response; it does not answer the tested concept of Assessment is included but bounded.\n\nC. Correct. LPCC assessment activities may be within statutory scope, but the statutory definition and express exclusions must be respected.\n\nD. Incorrect for this item. This option states the separate principle of Current source version; it does not answer the tested concept of Assessment is included but bounded.\n\nCTA Exam Strategy: Return to the license-specific module section on Assessment is included but bounded. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of Assessment exclusions?',
		'option_a' => 'Consultation can support judgment but does not replace legally qualifying supervision or convert an unlawful practice arrangement into a lawful one.',
		'option_b' => 'A candidate must recognize activities the LPCC assessment definition excludes and refer when another professional service is required.',
		'option_c' => 'For multi-issue questions use STATUS -> SETTING -> SCOPE -> COMPETENCE -> SOURCE -> SAFEGUARD -> STEP -> RECORD.',
		'option_d' => 'LPCC assessment activities may be within statutory scope, but the statutory definition and express exclusions must be respected.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect for this item. This option states the separate principle of Consultation vs supervision; it does not answer the tested concept of Assessment exclusions.\n\nB. Correct. A candidate must recognize activities the LPCC assessment definition excludes and refer when another professional service is required.\n\nC. Incorrect for this item. This option states the separate principle of Integrated decision sequence; it does not answer the tested concept of Assessment exclusions.\n\nD. Incorrect for this item. This option states the separate principle of Assessment is included but bounded; it does not answer the tested concept of Assessment exclusions.\n\nCTA Exam Strategy: Return to the license-specific module section on Assessment exclusions. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of Instrument competence?',
		'option_a' => 'Authority to conduct assessment does not establish competence with every instrument; training, purpose, administration, scoring, and interpretation matter.',
		'option_b' => 'The California LPCC Law and Ethics Examination and the NCMHCE are separate examinations serving different points in the licensure pathway.',
		'option_c' => 'Current LPCC analysis should use the current statutory scope rather than teach superseded profession-specific prerequisites.',
		'option_d' => 'Required client notices and relationship/process disclosures should be accurate, timely, and consistent with the clinician\'s actual status and role.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. Authority to conduct assessment does not establish competence with every instrument; training, purpose, administration, scoring, and interpretation matter.\n\nB. Incorrect for this item. This option states the separate principle of Law and Ethics vs NCMHCE; it does not answer the tested concept of Instrument competence.\n\nC. Incorrect for this item. This option states the separate principle of Couples and families; it does not answer the tested concept of Instrument competence.\n\nD. Incorrect for this item. This option states the separate principle of Client-facing disclosures; it does not answer the tested concept of Instrument competence.\n\nCTA Exam Strategy: Return to the license-specific module section on Instrument competence. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of Assessment results and misuse prevention?',
		'option_a' => 'LPCC professional clinical counseling is a distinct statutory profession with its own scope, duties, and examination pathway.',
		'option_b' => 'A registered associate should use the complete accurate APCC title and avoid language that implies independent LPCC licensure.',
		'option_c' => 'Consultation can support judgment but does not replace legally qualifying supervision or convert an unlawful practice arrangement into a lawful one.',
		'option_d' => 'Assessment information should be reported, stored, and used in a way that matches the instrument\'s purpose, protects confidentiality, and avoids misuse.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect for this item. This option states the separate principle of LPCC professional identity; it does not answer the tested concept of Assessment results and misuse prevention.\n\nB. Incorrect for this item. This option states the separate principle of APCC title accuracy; it does not answer the tested concept of Assessment results and misuse prevention.\n\nC. Incorrect for this item. This option states the separate principle of Consultation vs supervision; it does not answer the tested concept of Assessment results and misuse prevention.\n\nD. Correct. Assessment information should be reported, stored, and used in a way that matches the instrument's purpose, protects confidentiality, and avoids misuse.\n\nCTA Exam Strategy: Return to the license-specific module section on Assessment results and misuse prevention. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of APCC title accuracy?',
		'option_a' => 'A candidate must recognize activities the LPCC assessment definition excludes and refer when another professional service is required.',
		'option_b' => 'APCC supervision analysis is specific to the week, setting, direct clinical counseling hours, recognized contact method, and lawful alternative arrangements.',
		'option_c' => 'A registered associate should use the complete accurate APCC title and avoid language that implies independent LPCC licensure.',
		'option_d' => 'The California LPCC Law and Ethics Examination and the NCMHCE are separate examinations serving different points in the licensure pathway.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect for this item. This option states the separate principle of Assessment exclusions; it does not answer the tested concept of APCC title accuracy.\n\nB. Incorrect for this item. This option states the separate principle of Direct supervisor contact; it does not answer the tested concept of APCC title accuracy.\n\nC. Correct. A registered associate should use the complete accurate APCC title and avoid language that implies independent LPCC licensure.\n\nD. Incorrect for this item. This option states the separate principle of Law and Ethics vs NCMHCE; it does not answer the tested concept of APCC title accuracy.\n\nCTA Exam Strategy: Return to the license-specific module section on APCC title accuracy. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of APCC advertising elements?',
		'option_a' => 'Websites, directories, social media, cards, and employer-created profiles can all function as advertising and must be reviewed for current compliance.',
		'option_b' => 'Associate advertising must include current required identifying, employer/entity, and supervised-status information; one correct element does not cure an omitted requirement.',
		'option_c' => 'Client consent or initiation does not erase professional responsibility or statutory restrictions on sexual or exploitative conduct.',
		'option_d' => 'LPCC professional clinical counseling is a distinct statutory profession with its own scope, duties, and examination pathway.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect for this item. This option states the separate principle of Advertising across platforms; it does not answer the tested concept of APCC advertising elements.\n\nB. Correct. Associate advertising must include current required identifying, employer/entity, and supervised-status information; one correct element does not cure an omitted requirement.\n\nC. Incorrect for this item. This option states the separate principle of Sexual and exploitative conduct; it does not answer the tested concept of APCC advertising elements.\n\nD. Incorrect for this item. This option states the separate principle of LPCC professional identity; it does not answer the tested concept of APCC advertising elements.\n\nCTA Exam Strategy: Return to the license-specific module section on APCC advertising elements. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of Client-facing disclosures?',
		'option_a' => 'Required client notices and relationship/process disclosures should be accurate, timely, and consistent with the clinician\'s actual status and role.',
		'option_b' => 'Competence, accurate representation, records, fees, referrals, sexual conduct, impairment, and other conduct rules are organized around public and client protection.',
		'option_c' => 'When sources conflict, controlling California law and regulation govern legal duties; ethics and policy operate within that lawful boundary.',
		'option_d' => 'A candidate must recognize activities the LPCC assessment definition excludes and refer when another professional service is required.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. Required client notices and relationship/process disclosures should be accurate, timely, and consistent with the clinician's actual status and role.\n\nB. Incorrect for this item. This option states the separate principle of Professional conduct and public protection; it does not answer the tested concept of Client-facing disclosures.\n\nC. Incorrect for this item. This option states the separate principle of Authority hierarchy; it does not answer the tested concept of Client-facing disclosures.\n\nD. Incorrect for this item. This option states the separate principle of Assessment exclusions; it does not answer the tested concept of Client-facing disclosures.\n\nCTA Exam Strategy: Return to the license-specific module section on Client-facing disclosures. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of Advertising across platforms?',
		'option_a' => 'Candidates should use current BBS/Pearson instructions for retest, annual participation, and active-registration requirements rather than relying on old templates.',
		'option_b' => 'When a service falls outside lawful scope or cannot be provided competently, referral or another lawful alternative protects the client.',
		'option_c' => 'Required client notices and relationship/process disclosures should be accurate, timely, and consistent with the clinician\'s actual status and role.',
		'option_d' => 'Websites, directories, social media, cards, and employer-created profiles can all function as advertising and must be reviewed for current compliance.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect for this item. This option states the separate principle of Retest and participation rules; it does not answer the tested concept of Advertising across platforms.\n\nB. Incorrect for this item. This option states the separate principle of Referral as scope safeguard; it does not answer the tested concept of Advertising across platforms.\n\nC. Incorrect for this item. This option states the separate principle of Client-facing disclosures; it does not answer the tested concept of Advertising across platforms.\n\nD. Correct. Websites, directories, social media, cards, and employer-created profiles can all function as advertising and must be reviewed for current compliance.\n\nCTA Exam Strategy: Return to the license-specific module section on Advertising across platforms. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of Supervision means responsibility and control?',
		'option_a' => 'An APCC\'s registration and supervision status affects what the person may do now; profession-wide scope does not create independent authority.',
		'option_b' => 'A registered associate should use the complete accurate APCC title and avoid language that implies independent LPCC licensure.',
		'option_c' => 'Clinical supervision is more than consultation; it includes responsibility for and control of service quality, monitoring, competence, records, and feedback.',
		'option_d' => 'Competence, accurate representation, records, fees, referrals, sexual conduct, impairment, and other conduct rules are organized around public and client protection.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect for this item. This option states the separate principle of Status and present authority; it does not answer the tested concept of Supervision means responsibility and control.\n\nB. Incorrect for this item. This option states the separate principle of APCC title accuracy; it does not answer the tested concept of Supervision means responsibility and control.\n\nC. Correct. Clinical supervision is more than consultation; it includes responsibility for and control of service quality, monitoring, competence, records, and feedback.\n\nD. Incorrect for this item. This option states the separate principle of Professional conduct and public protection; it does not answer the tested concept of Supervision means responsibility and control.\n\nCTA Exam Strategy: Return to the license-specific module section on Supervision means responsibility and control. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of Direct supervisor contact?',
		'option_a' => 'Authority to conduct assessment does not establish competence with every instrument; training, purpose, administration, scoring, and interpretation matter.',
		'option_b' => 'APCC supervision analysis is specific to the week, setting, direct clinical counseling hours, recognized contact method, and lawful alternative arrangements.',
		'option_c' => 'APCC services must occur in a lawful employment or volunteer structure with compliant payment and business-interest arrangements.',
		'option_d' => 'Candidates should use current BBS/Pearson instructions for retest, annual participation, and active-registration requirements rather than relying on old templates.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect for this item. This option states the separate principle of Instrument competence; it does not answer the tested concept of Direct supervisor contact.\n\nB. Correct. APCC supervision analysis is specific to the week, setting, direct clinical counseling hours, recognized contact method, and lawful alternative arrangements.\n\nC. Incorrect for this item. This option states the separate principle of Lawful APCC work and payment; it does not answer the tested concept of Direct supervisor contact.\n\nD. Incorrect for this item. This option states the separate principle of Retest and participation rules; it does not answer the tested concept of Direct supervisor contact.\n\nCTA Exam Strategy: Return to the license-specific module section on Direct supervisor contact. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of Lawful APCC work and payment?',
		'option_a' => 'APCC services must occur in a lawful employment or volunteer structure with compliant payment and business-interest arrangements.',
		'option_b' => 'Websites, directories, social media, cards, and employer-created profiles can all function as advertising and must be reviewed for current compliance.',
		'option_c' => 'The APCC pathway involves registration, supervised experience, Law and Ethics requirements, application milestones, and later examination steps in a defined sequence.',
		'option_d' => 'An APCC\'s registration and supervision status affects what the person may do now; profession-wide scope does not create independent authority.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. APCC services must occur in a lawful employment or volunteer structure with compliant payment and business-interest arrangements.\n\nB. Incorrect for this item. This option states the separate principle of Advertising across platforms; it does not answer the tested concept of Lawful APCC work and payment.\n\nC. Incorrect for this item. This option states the separate principle of Registration and examination pathway; it does not answer the tested concept of Lawful APCC work and payment.\n\nD. Incorrect for this item. This option states the separate principle of Status and present authority; it does not answer the tested concept of Lawful APCC work and payment.\n\nCTA Exam Strategy: Return to the license-specific module section on Lawful APCC work and payment. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of Consultation vs supervision?',
		'option_a' => 'When functioning is impaired, protect clients first, stop or limit unsafe practice, obtain appropriate help and coverage, and document continuity steps.',
		'option_b' => 'Date and version matter because statutes, regulations, Board guidance, examination materials, and ethics standards can change.',
		'option_c' => 'Authority to conduct assessment does not establish competence with every instrument; training, purpose, administration, scoring, and interpretation matter.',
		'option_d' => 'Consultation can support judgment but does not replace legally qualifying supervision or convert an unlawful practice arrangement into a lawful one.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect for this item. This option states the separate principle of Impairment response; it does not answer the tested concept of Consultation vs supervision.\n\nB. Incorrect for this item. This option states the separate principle of Current source version; it does not answer the tested concept of Consultation vs supervision.\n\nC. Incorrect for this item. This option states the separate principle of Instrument competence; it does not answer the tested concept of Consultation vs supervision.\n\nD. Correct. Consultation can support judgment but does not replace legally qualifying supervision or convert an unlawful practice arrangement into a lawful one.\n\nCTA Exam Strategy: Return to the license-specific module section on Consultation vs supervision. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of Professional conduct and public protection?',
		'option_a' => 'For multi-issue questions use STATUS -> SETTING -> SCOPE -> COMPETENCE -> SOURCE -> SAFEGUARD -> STEP -> RECORD.',
		'option_b' => 'LPCC assessment activities may be within statutory scope, but the statutory definition and express exclusions must be respected.',
		'option_c' => 'Competence, accurate representation, records, fees, referrals, sexual conduct, impairment, and other conduct rules are organized around public and client protection.',
		'option_d' => 'Websites, directories, social media, cards, and employer-created profiles can all function as advertising and must be reviewed for current compliance.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect for this item. This option states the separate principle of Integrated decision sequence; it does not answer the tested concept of Professional conduct and public protection.\n\nB. Incorrect for this item. This option states the separate principle of Assessment is included but bounded; it does not answer the tested concept of Professional conduct and public protection.\n\nC. Correct. Competence, accurate representation, records, fees, referrals, sexual conduct, impairment, and other conduct rules are organized around public and client protection.\n\nD. Incorrect for this item. This option states the separate principle of Advertising across platforms; it does not answer the tested concept of Professional conduct and public protection.\n\nCTA Exam Strategy: Return to the license-specific module section on Professional conduct and public protection. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of Impairment response?',
		'option_a' => 'Current LPCC analysis should use the current statutory scope rather than teach superseded profession-specific prerequisites.',
		'option_b' => 'When functioning is impaired, protect clients first, stop or limit unsafe practice, obtain appropriate help and coverage, and document continuity steps.',
		'option_c' => 'Associate advertising must include current required identifying, employer/entity, and supervised-status information; one correct element does not cure an omitted requirement.',
		'option_d' => 'Competence, accurate representation, records, fees, referrals, sexual conduct, impairment, and other conduct rules are organized around public and client protection.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect for this item. This option states the separate principle of Couples and families; it does not answer the tested concept of Impairment response.\n\nB. Correct. When functioning is impaired, protect clients first, stop or limit unsafe practice, obtain appropriate help and coverage, and document continuity steps.\n\nC. Incorrect for this item. This option states the separate principle of APCC advertising elements; it does not answer the tested concept of Impairment response.\n\nD. Incorrect for this item. This option states the separate principle of Professional conduct and public protection; it does not answer the tested concept of Impairment response.\n\nCTA Exam Strategy: Return to the license-specific module section on Impairment response. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of Sexual and exploitative conduct?',
		'option_a' => 'Client consent or initiation does not erase professional responsibility or statutory restrictions on sexual or exploitative conduct.',
		'option_b' => 'Assessment information should be reported, stored, and used in a way that matches the instrument\'s purpose, protects confidentiality, and avoids misuse.',
		'option_c' => 'APCC services must occur in a lawful employment or volunteer structure with compliant payment and business-interest arrangements.',
		'option_d' => 'For multi-issue questions use STATUS -> SETTING -> SCOPE -> COMPETENCE -> SOURCE -> SAFEGUARD -> STEP -> RECORD.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. Client consent or initiation does not erase professional responsibility or statutory restrictions on sexual or exploitative conduct.\n\nB. Incorrect for this item. This option states the separate principle of Assessment results and misuse prevention; it does not answer the tested concept of Sexual and exploitative conduct.\n\nC. Incorrect for this item. This option states the separate principle of Lawful APCC work and payment; it does not answer the tested concept of Sexual and exploitative conduct.\n\nD. Incorrect for this item. This option states the separate principle of Integrated decision sequence; it does not answer the tested concept of Sexual and exploitative conduct.\n\nCTA Exam Strategy: Return to the license-specific module section on Sexual and exploitative conduct. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of Registration and examination pathway?',
		'option_a' => 'Clinical supervision is more than consultation; it includes responsibility for and control of service quality, monitoring, competence, records, and feedback.',
		'option_b' => 'The California LPCC Law and Ethics Examination and the NCMHCE are separate examinations serving different points in the licensure pathway.',
		'option_c' => 'Current LPCC analysis should use the current statutory scope rather than teach superseded profession-specific prerequisites.',
		'option_d' => 'The APCC pathway involves registration, supervised experience, Law and Ethics requirements, application milestones, and later examination steps in a defined sequence.',
		'correct_option' => 'd',
		'explanation' => "A. Incorrect for this item. This option states the separate principle of Supervision means responsibility and control; it does not answer the tested concept of Registration and examination pathway.\n\nB. Incorrect for this item. This option states the separate principle of Law and Ethics vs NCMHCE; it does not answer the tested concept of Registration and examination pathway.\n\nC. Incorrect for this item. This option states the separate principle of Couples and families; it does not answer the tested concept of Registration and examination pathway.\n\nD. Correct. The APCC pathway involves registration, supervised experience, Law and Ethics requirements, application milestones, and later examination steps in a defined sequence.\n\nCTA Exam Strategy: Return to the license-specific module section on Registration and examination pathway. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of Law and Ethics vs NCMHCE?',
		'option_a' => 'When functioning is impaired, protect clients first, stop or limit unsafe practice, obtain appropriate help and coverage, and document continuity steps.',
		'option_b' => 'LPCC professional clinical counseling is a distinct statutory profession with its own scope, duties, and examination pathway.',
		'option_c' => 'The California LPCC Law and Ethics Examination and the NCMHCE are separate examinations serving different points in the licensure pathway.',
		'option_d' => 'Assessment information should be reported, stored, and used in a way that matches the instrument\'s purpose, protects confidentiality, and avoids misuse.',
		'correct_option' => 'c',
		'explanation' => "A. Incorrect for this item. This option states the separate principle of Impairment response; it does not answer the tested concept of Law and Ethics vs NCMHCE.\n\nB. Incorrect for this item. This option states the separate principle of LPCC professional identity; it does not answer the tested concept of Law and Ethics vs NCMHCE.\n\nC. Correct. The California LPCC Law and Ethics Examination and the NCMHCE are separate examinations serving different points in the licensure pathway.\n\nD. Incorrect for this item. This option states the separate principle of Assessment results and misuse prevention; it does not answer the tested concept of Law and Ethics vs NCMHCE.\n\nCTA Exam Strategy: Return to the license-specific module section on Law and Ethics vs NCMHCE. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of Retest and participation rules?',
		'option_a' => 'When sources conflict, controlling California law and regulation govern legal duties; ethics and policy operate within that lawful boundary.',
		'option_b' => 'Candidates should use current BBS/Pearson instructions for retest, annual participation, and active-registration requirements rather than relying on old templates.',
		'option_c' => 'A candidate must recognize activities the LPCC assessment definition excludes and refer when another professional service is required.',
		'option_d' => 'Clinical supervision is more than consultation; it includes responsibility for and control of service quality, monitoring, competence, records, and feedback.',
		'correct_option' => 'b',
		'explanation' => "A. Incorrect for this item. This option states the separate principle of Authority hierarchy; it does not answer the tested concept of Retest and participation rules.\n\nB. Correct. Candidates should use current BBS/Pearson instructions for retest, annual participation, and active-registration requirements rather than relying on old templates.\n\nC. Incorrect for this item. This option states the separate principle of Assessment exclusions; it does not answer the tested concept of Retest and participation rules.\n\nD. Incorrect for this item. This option states the separate principle of Supervision means responsibility and control; it does not answer the tested concept of Retest and participation rules.\n\nCTA Exam Strategy: Return to the license-specific module section on Retest and participation rules. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
	array(
		'question_text' => 'Which statement BEST reflects the LPCC/APCC principle of Integrated decision sequence?',
		'option_a' => 'For multi-issue questions use STATUS -> SETTING -> SCOPE -> COMPETENCE -> SOURCE -> SAFEGUARD -> STEP -> RECORD.',
		'option_b' => 'When a service falls outside lawful scope or cannot be provided competently, referral or another lawful alternative protects the client.',
		'option_c' => 'Required client notices and relationship/process disclosures should be accurate, timely, and consistent with the clinician\'s actual status and role.',
		'option_d' => 'When functioning is impaired, protect clients first, stop or limit unsafe practice, obtain appropriate help and coverage, and document continuity steps.',
		'correct_option' => 'a',
		'explanation' => "A. Correct. For multi-issue questions use STATUS -> SETTING -> SCOPE -> COMPETENCE -> SOURCE -> SAFEGUARD -> STEP -> RECORD.\n\nB. Incorrect for this item. This option states the separate principle of Referral as scope safeguard; it does not answer the tested concept of Integrated decision sequence.\n\nC. Incorrect for this item. This option states the separate principle of Client-facing disclosures; it does not answer the tested concept of Integrated decision sequence.\n\nD. Incorrect for this item. This option states the separate principle of Impairment response; it does not answer the tested concept of Integrated decision sequence.\n\nCTA Exam Strategy: Return to the license-specific module section on Integrated decision sequence. State the controlling rule in your own words, then explain why the strongest competing option addresses a different issue.",
	),
);
