<?php
/**
 * Advanced Suicide Risk Assessment (CTA-CE-003) final examination — learner questions only.
 *
 * Chunk 4: question stems and answer choices verbatim. No correct_option or explanation.
 * Secured answer keys and rationales are loaded in Chunk 5.
 *
 * @package CTA_LMS
 */

/**
 * @return array[]
 */
return array(
	array(
		'question_code'  => 'CTA-SRA-FE-001',
		'question_text'  => 'A client who has been depressed for several months suddenly gives away valued possessions, says goodbye to several friends, and begins searching online for a lethal method. Which finding is best classified as an acute warning sign rather than a background risk factor?',
		'option_a'       => 'A family history of suicide',
		'option_b'       => 'A longstanding depressive disorder',
		'option_c'       => 'The sudden farewell and preparatory behaviors',
		'option_d'       => 'A history of childhood trauma',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-002',
		'question_text'  => 'During a structured suicide inquiry, a client denies having a "plan" but reports buying a firearm yesterday, loading it, and placing it beside the bed. What should the clinician do next?',
		'option_a'       => 'Continue direct inquiry into intent, expected timing, access, preparatory behavior, prior suicidal behavior, current drivers, and protective factors',
		'option_b'       => 'Document that there is no plan and classify the client as low risk',
		'option_c'       => 'Administer a second screening tool and defer further interviewing until the score is available',
		'option_d'       => 'Ask the client to sign a no-suicide contract before discussing the firearm',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-003',
		'question_text'  => 'Which statement best explains why a no-harm or no-suicide contract should not be used as the primary suicide-safety intervention?',
		'option_a'       => 'A signed promise legally prevents the client from attempting suicide',
		'option_b'       => 'A contract allows the clinician to avoid asking about lethal means',
		'option_c'       => 'A contract is equivalent to a collaborative six-step safety plan',
		'option_d'       => 'A promise does not establish future safety, create coping steps, or replace assessment, intervention, and escalation when needed',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-004',
		'question_text'  => 'An outpatient clinician who is not personally designated by the county evaluates an adult who, as a result of a mental health disorder, is unable to obtain food, shelter, personal safety, or necessary medical care and will not accept voluntary evaluation. What is the most appropriate response?',
		'option_a'       => 'Personally issue a 72-hour detention and transport the client without using the county pathway',
		'option_b'       => 'Activate the county-authorized emergency-evaluation pathway, communicate the relevant facts to authorized personnel, and maintain safety while the response is arranged',
		'option_c'       => 'Wait until physical harm becomes imminent because grave disability cannot support emergency evaluation',
		'option_d'       => 'Disclose the client\'s entire record to every person involved in the response',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-005',
		'question_text'  => 'A progress note states only: "Risk low. Safety plan completed. Follow up next week." Which revision would most improve the note?',
		'option_a'       => 'Add that the therapist was careful and acted professionally',
		'option_b'       => 'Add only the total score from a structured tool',
		'option_c'       => 'Paste the entire safety plan into the progress note without explaining the clinical decision',
		'option_d'       => 'Document the assessment findings, acute and chronic formulation, rationale, interventions, lethal-means actions, client response, consultation or disposition, and follow-up plan',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-006',
		'question_text'  => 'A client survives a suicide attempt and is hospitalized. The practice organizes continuity planning, consultation, and support for the treating clinician. Which description is most accurate?',
		'option_a'       => 'This is suicide postvention because any suicide-related crisis is postvention',
		'option_b'       => 'This is routine discharge planning only and does not involve clinician support',
		'option_c'       => 'This is a critical-incident and clinician-support response after a nonfatal event, distinct from postvention following a suicide death',
		'option_d'       => 'This automatically establishes that the clinician is professionally impaired',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-007',
		'question_text'  => 'A client reports cutting the forearm to reduce emotional numbness, denies any wish to die, and did not expect the behavior to be lethal. Which interpretation is most accurate?',
		'option_a'       => 'The behavior is most consistent with non-suicidal self-injury based on its reported function and intent, while suicide risk still requires assessment',
		'option_b'       => 'Any self-inflicted injury is automatically a suicide attempt',
		'option_c'       => 'No further suicide-risk assessment is needed because the client denied intent',
		'option_d'       => 'The behavior should be labeled manipulative rather than clinically assessed',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-008',
		'question_text'  => 'Two clients receive the same C-SSRS ideation-category result. Client A has long-standing passive ideation that is unchanged from baseline, no access to lethal means, and reliable supports. Client B has new intent, immediate access to a lethal method, recent intoxication, and loss of usual supports. Which formulation is strongest?',
		'option_a'       => 'The clients have the same current risk because the category result is the same',
		'option_b'       => 'Client B shows greater acute risk, while Client A may have chronic risk; the formulation must integrate baseline, change, current drivers, means, supports, and uncertainty',
		'option_c'       => 'Client A is at greater acute risk because the ideation has lasted longer',
		'option_d'       => 'Neither client can be formulated because structured tools should never be used',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-009',
		'question_text'  => 'A safety plan instructs a client to go to a familiar cafe or call a friend to talk about sports without disclosing the crisis. Which safety-plan step does this represent?',
		'option_a'       => 'Internal coping strategies',
		'option_b'       => 'People who can provide direct help with the crisis',
		'option_c'       => 'Social settings or contacts used for distraction',
		'option_d'       => 'Professional and crisis resources',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-010',
		'question_text'  => 'An adult with significant suicidal ideation agrees to an immediate voluntary psychiatric evaluation. A supportive partner is present, safe transportation is available, and the clinician determines that safety can be maintained during transfer. What is the best next step?',
		'option_a'       => 'Use involuntary detention automatically because suicidal ideation is present',
		'option_b'       => 'Schedule routine follow-up and allow the client to leave without the evaluation',
		'option_c'       => 'Have the client drive alone so the process remains voluntary',
		'option_d'       => 'Arrange the immediate voluntary evaluation with appropriate safety supports and a contingency to escalate if cooperation or safety changes',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-011',
		'question_text'  => 'Which statement most accurately distinguishes California record duties from recommended suicide-risk documentation content?',
		'option_a'       => 'California law requires one universal suicide-risk note template with exact headings for every BBS profession and setting',
		'option_b'       => 'California law establishes recordkeeping and retention duties, while clinically useful suicide-risk notes often include broader assessment, rationale, intervention, response, and follow-up content rather than one universal template',
		'option_c'       => 'Only the final disposition needs to be documented in a suicide-risk case',
		'option_d'       => 'Using the course\'s recommended note elements replaces employer, agency, and setting-specific requirements',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-012',
		'question_text'  => 'After a client suicide, a clinician experiences persistent intrusive images, insomnia, concentration errors, and avoidance of similar cases. What is the most appropriate professional response?',
		'option_a'       => 'Obtain timely consultation and support, assess current functioning, and consider temporary workload modification or leave if safe practice is affected',
		'option_b'       => 'Ignore the reactions because common responses can never interfere with practice',
		'option_c'       => 'Share identifying client details with friends to obtain emotional support',
		'option_d'       => 'Permanently stop practicing because any strong reaction establishes impairment',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-013',
		'question_text'  => 'A client has described a passive wish to die for years. Today the client reports a specific method, intent to act on a chosen date, and immediate access to the method. How should this change be interpreted?',
		'option_a'       => 'It remains unchanged chronic ideation because the client has discussed death before',
		'option_b'       => 'It is non-suicidal self-injury because no injury has occurred yet',
		'option_c'       => 'Existing protective factors eliminate the significance of the new information',
		'option_d'       => 'It represents acute escalation above baseline because specificity, intent, proximity, and access have increased',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-014',
		'question_text'  => 'Which statement most accurately distinguishes the C-SSRS from SAFE-T?',
		'option_a'       => 'The C-SSRS independently determines disposition, while SAFE-T verifies the score',
		'option_b'       => 'SAFE-T is a psychometric test that replaces a clinical interview',
		'option_c'       => 'The C-SSRS structures inquiry into suicidal ideation and behavior, while SAFE-T is a broader five-step evaluation and triage framework; neither replaces clinical judgment',
		'option_d'       => 'Both tools predict individual suicide with certainty when administered correctly',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-015',
		'question_text'  => 'A client reports an active suicide plan and intent, has the method immediately available, cannot identify coping strategies or reachable supports, and states that the safety plan will not be used. What should the clinician do?',
		'option_a'       => 'Complete the safety-plan form and allow the client to leave because a plan is now documented',
		'option_b'       => 'Prioritize urgent emergency evaluation or a higher level of care; safety planning may supplement the response but cannot substitute for escalation',
		'option_c'       => 'Ask the client to sign a no-suicide contract and schedule a visit the next day',
		'option_d'       => 'Wait for the next routine appointment to determine whether the intent persists',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-016',
		'question_text'  => 'During telehealth, a client whose current location was verified reports active intent and immediate access to a lethal method. The connection then drops, and the clinician cannot re-establish contact. What is the best response?',
		'option_a'       => 'Activate the preplanned local emergency response using the verified location and emergency-contact information, disclose only what is reasonably necessary, and document and consult',
		'option_b'       => 'Send a general resource list by email and wait for the client to respond',
		'option_c'       => 'Wait 24 hours because the loss of connection may have been technical',
		'option_d'       => 'Call law enforcement in the clinician\'s own city regardless of the client\'s location',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-017',
		'question_text'  => 'A clinician obtains consultation about whether to escalate a client\'s level of care. Which documentation entry is most clinically useful?',
		'option_a'       => '"Consulted with colleague" without any additional information',
		'option_b'       => 'A detailed description of the consultant\'s unrelated personal and professional history',
		'option_c'       => 'The consultant\'s recommendation alone, without the treating clinician\'s decision or rationale',
		'option_d'       => 'The reason for consultation, relevant information shared, recommendation received, treating clinician\'s decision and rationale, actions taken, and follow-up plan',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-018',
		'question_text'  => 'Which statement best distinguishes secondary traumatic stress from burnout?',
		'option_a'       => 'Burnout always follows one specific traumatic client event',
		'option_b'       => 'Secondary traumatic stress automatically proves professional incompetence',
		'option_c'       => 'Secondary traumatic stress may involve trauma-like reactions after indirect exposure to another person\'s trauma, while burnout more often develops from chronic occupational demands',
		'option_d'       => 'The terms are interchangeable and require the same response in every case',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-019',
		'question_text'  => 'A client with chronic suicidal ideation is now intoxicated, recently lost housing, stopped taking prescribed medication, acquired a firearm, and cannot reach the usual support person. What is the best interpretation?',
		'option_a'       => 'The convergence of acute drivers, access to lethal means, and reduced protective supports represents significant elevation that requires immediate reassessment and intervention',
		'option_b'       => 'The chronic history means the presentation is unchanged and does not require a new response',
		'option_c'       => 'The psychiatric diagnosis alone is sufficient to assign a fixed risk level',
		'option_d'       => 'One statement about wanting to live would override the other information',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-020',
		'question_text'  => 'After an initial assessment and safety intervention, when should suicide risk be reassessed?',
		'option_a'       => 'Only during the annual treatment-plan review',
		'option_b'       => 'After subsequent suicidal behavior, increased ideation, or a pertinent clinical change, and according to the person-specific formulation and treatment setting',
		'option_c'       => 'Only when the client requests another assessment',
		'option_d'       => 'Never with the same tool because reassessment invalidates the original result',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-021',
		'question_text'  => 'A 15-year-old with limited reading ability, restricted phone access, and culturally important family supports is developing a safety plan. Which approach is best?',
		'option_a'       => 'Use the standard adult plan without modification so the process remains consistent',
		'option_b'       => 'Exclude all caregivers and family supports because minors always require complete secrecy',
		'option_c'       => 'List 988 as the only step because professional crisis resources are the most important component',
		'option_d'       => 'Use developmentally and linguistically accessible wording or visuals, identify supports consistent with the client\'s actual family and confidentiality context, and confirm that the plan is available and usable',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-022',
		'question_text'  => 'After arranging an emergency psychiatric evaluation, which documentation is most clinically useful?',
		'option_a'       => '"Sent to hospital" with no supporting information',
		'option_b'       => 'A verbatim transcript of every statement made during the encounter',
		'option_c'       => 'The assessment data, legal and clinical rationale, alternatives or interventions attempted, consultation, disposition, communications, and follow-up plan',
		'option_d'       => 'Only the name of the receiving facility',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-023',
		'question_text'  => 'During lethal-means counseling, a client declines one proposed storage option and the preferred support person is unavailable. What should the documentation show?',
		'option_a'       => 'Omit the declined and unavailable options so the note appears more successful',
		'option_b'       => 'Record the options offered, what was accepted, declined, or unavailable, the rationale, alternative safety steps, the client\'s response, and the reassessment and follow-up plan',
		'option_c'       => 'Label the client noncompliant without describing the conversation',
		'option_d'       => 'Use a generic phrase stating that means safety was addressed, without documenting the outcome',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-024',
		'question_text'  => 'Which agency protocol best reflects a balanced response after a client suicide death?',
		'option_a'       => 'Require an immediate group emotional debriefing and share detailed client information with all staff',
		'option_b'       => 'Complete an administrative review only and avoid offering clinician support',
		'option_c'       => 'Contact the family immediately without first considering authority, confidentiality, role, and organizational procedure',
		'option_d'       => 'Use a staged protocol that verifies information, preserves confidentiality, addresses immediate operational and continuity duties, provides consultation and optional individualized support, documents actions, and schedules follow-up',
	),
	array(
		'question_code'  => 'CTA-SRA-FE-025',
		'question_text'  => 'A client has a negative structured-screen result, but collateral information describes goodbye messages, giving away medication, and sharply increased alcohol use. What should the clinician conclude?',
		'option_a'       => 'The negative result does not override the concerning data; the clinician should continue comprehensive assessment and person-specific formulation',
		'option_b'       => 'The client has no suicide risk because the structured screen was negative',
		'option_c'       => 'Collateral information should be discarded because it did not come directly from the client',
		'option_d'       => 'The screen result alone determines that outpatient discharge is appropriate',
	),
);
