<?php
/**
 * Official Telehealth (CTA-CE-002) final examination question bank.
 *
 * Exact wording from CTA source documents — do not paraphrase.
 *
 * @package CTA_LMS
 */

/**
 * @return array[]
 */
return array(
	array(
		'question_text'  => 'A California LMFT learns at the beginning of a session that the client is temporarily attending from Nevada. What is the best next step?',
		'option_a'       => 'Continue routine treatment because the client permanently resides in California.',
		'option_b'       => 'Verify whether the clinician is authorized to provide services to a client located in Nevada before continuing routine treatment, while maintaining California professional duties and assessing any urgent safety needs.',
		'option_c'       => 'End the therapeutic relationship immediately without assessing risk or discussing continuity of care.',
		'option_d'       => 'Continue the session as long as the client gives verbal permission.',
		'correct_option' => 'b',
		'explanation'    => "Why B is correct: The client's physical location during the session creates the interstate-practice question. Before continuing routine treatment, the California clinician should verify whether Nevada law authorizes the service. California professional duties and Board jurisdiction do not disappear simply because the client is elsewhere. The clinician should also assess whether any immediate safety need requires a limited crisis response or continuity action while the legal question is being resolved.\n\nWhy A is incorrect: A California residence or treatment history does not automatically authorize practice when the client is physically located in another state.\n\nWhy C is incorrect: Immediate termination without assessing risk or planning continuity may create avoidable client-welfare and abandonment concerns. The appropriate response is a professional pause and verification process.\n\nWhy D is incorrect: Client permission is necessary for treatment but cannot create professional practice authority in another jurisdiction.\n\nCTA Clinical Takeaway: Verify the client's present location first, then determine what legal authority, safety response, and continuity steps apply.",
	),
	array(
		'question_text'  => 'Which set of actions is required when telehealth services are initiated under California Board of Behavioral Sciences standards?',
		'option_a'       => "Verify the client's full name and present-location address, assess appropriateness, and change the platform password.",
		'option_b'       => 'Obtain a photo identification card, identify an emergency contact, and secure a Business Associate Agreement for every vendor.',
		'option_c'       => "Obtain telehealth consent, explain potential risks and limitations, provide the clinician's license or registration type and number, and document reasonable efforts to identify relevant local resources.",
		'option_d'       => 'Verify insurance coverage, record the first session, and identify the nearest hospital.',
		'correct_option' => 'c',
		'explanation'    => "Why C is correct: California BBS standards identify a specific initiation set: obtain telehealth informed consent consistent with Business and Professions Code section 2290.5, explain the potential risks and limitations of telehealth, disclose the clinician's license or registration type and number, and document reasonable efforts to identify relevant resources, including emergency services, in the client's geographic area.\n\nWhy A is incorrect: Full-name and present-location verification and appropriateness assessment are each-session duties. Changing a platform password is a security practice, not part of the BBS initiation set.\n\nWhy B is incorrect: Photo identification and an emergency contact may be part of a practice policy, but they are not the universal initiation requirements listed by BBS. A BAA is conditional, not required for every vendor.\n\nWhy D is incorrect: Insurance verification, routine session recording, and identifying one hospital are not the required BBS initiation set. Recording may create additional privacy and consent concerns.\n\nCTA Clinical Takeaway: Keep initiation duties separate from each-session duties and from additional risk-management practices.",
	),
	array(
		'question_text'  => 'At the beginning of every telehealth session, a California BBS licensee or registrant must verbally obtain and document:',
		'option_a'       => 'A new written telehealth consent form.',
		'option_b'       => "The client's full name and address of present location.",
		'option_c'       => "The clinician's license number and professional biography.",
		'option_d'       => 'A newly selected emergency contact.',
		'correct_option' => 'b',
		'explanation'    => "Why B is correct: At the beginning of every telehealth session, the clinician must verbally obtain and document the client's full name and the address of the client's present location. The present-location address supports both legal analysis and emergency response and is more precise than asking whether the client is \"at home\" or \"still in California.\"\n\nWhy A is incorrect: Telehealth consent is obtained and documented at initiation; a new written form is not required at every session.\n\nWhy C is incorrect: The clinician's license or registration type and number are disclosed at initiation, not repeated as an each-session verification item.\n\nWhy D is incorrect: Emergency-contact information should be kept current according to risk and policy, but a newly selected contact is not required at every session.\n\nCTA Clinical Takeaway: Use a consistent opening prompt that obtains the client's full name and exact present-location address.",
	),
	array(
		'question_text'  => 'Which statement accurately describes California telehealth consent under Business and Professions Code section 2290.5?',
		'option_a'       => 'Consent must always be written and renewed annually.',
		'option_b'       => "The client's participation in the session automatically establishes sufficient consent.",
		'option_c'       => 'Consent may be obtained after the first telehealth session is completed.',
		'option_d'       => 'Before telehealth is delivered, the provider must inform the client about telehealth, obtain verbal or written consent, and document that consent.',
		'correct_option' => 'd',
		'explanation'    => "Why D is correct: Business and Professions Code section 2290.5 requires the provider to inform the client about the use of telehealth, obtain verbal or written consent before telehealth is delivered, and document that consent in the record. The statute permits either verbal or written consent; it does not require one universal form.\n\nWhy A is incorrect: The statute does not require that telehealth consent always be written or automatically renewed every year.\n\nWhy B is incorrect: Participation alone should not be treated as automatic consent. The provider must inform the client, obtain consent, and document it.\n\nWhy C is incorrect: Consent must be obtained before telehealth is delivered, not after the first session has already occurred.\n\nCTA Clinical Takeaway: Telehealth consent may be verbal or written, but it must be informed, obtained in advance, and documented.",
	),
	array(
		'question_text'  => 'A long-term client reports that they moved to Arizona one month ago, and the clinician had not previously recognized the location change. What is the most appropriate response?',
		'option_a'       => 'Continue all routine sessions while checking Arizona requirements later.',
		'option_b'       => 'Terminate services immediately without assessing risk or planning continuity.',
		'option_c'       => "Verify the client's exact present location and immediate risk, pause routine treatment until lawful practice authority is confirmed, and document the continuity plan.",
		'option_d'       => 'Ask the client to keep using a California mailing address in the clinical record.',
		'correct_option' => 'c',
		'explanation'    => "Why C is correct: The clinician should first establish the client's exact present location and assess immediate risk. Routine treatment should pause until the clinician confirms lawful authority to serve a client in Arizona. The clinician should document when the move was learned, what legal and clinical questions were identified, what consultation or verification occurred, and how continuity of care will be protected.\n\nWhy A is incorrect: Continuing routine treatment while postponing the legal review repeats the underlying problem and may extend unauthorized practice.\n\nWhy B is incorrect: Abrupt termination ignores risk assessment, transition planning, and continuity responsibilities. A lawful pause is not the same as abandonment.\n\nWhy D is incorrect: Using a California mailing address would create an inaccurate record and would not change where the client is physically receiving services.\n\nCTA Clinical Takeaway: When a location change is discovered late, gather facts, assess safety, pause routine care, verify authority, and document continuity steps.",
	),
	array(
		'question_text'  => "What is the primary reason to verify the client's present location during telehealth?",
		'option_a'       => 'It supports both jurisdictional analysis and emergency response.',
		'option_b'       => 'It is used only for insurance billing.',
		'option_c'       => 'It confirms that the client is participating from home.',
		'option_d'       => 'It improves the quality of the video connection.',
		'correct_option' => 'a',
		'explanation'    => "Why A is correct: Present location serves two central functions. It identifies the jurisdiction whose practice rules may apply, and it gives the clinician usable information if local emergency assistance is needed. These purposes remain important even when the client is clinically stable and usually attends from the same place.\n\nWhy B is incorrect: Payers may have location-related rules, but billing is not the primary clinical and legal purpose of each-session location verification.\n\nWhy C is incorrect: The client does not have to be at home. The clinician needs the actual location and must assess whether the environment is appropriate.\n\nWhy D is incorrect: Location verification does not improve bandwidth or video quality.\n\nCTA Clinical Takeaway: Location verification is a legal-and-safety procedure, not merely an administrative detail.",
	),
	array(
		'question_text'  => 'Which progress-note entry best documents a session in which the clinician learns that the client is temporarily out of state?',
		'option_a'       => '"Client out of state."',
		'option_b'       => "Omit the location because the client's permanent address is already in the record.",
		'option_c'       => '"Session held normally; no changes."',
		'option_d'       => 'Document the present location, risk and urgency assessment, practice-authority question, actions or consultation, continuity response, and follow-up plan.',
		'correct_option' => 'd',
		'explanation'    => "Why D is correct: A defensible note should show the clinician's reasoning and actions: the client's actual location, risk and urgency assessment, the interstate-practice question, consultation or verification steps, the immediate continuity response, and the follow-up plan. This record supports client welfare and demonstrates that the clinician did not simply ignore the change.\n\nWhy A is incorrect: \"Client out of state\" is too vague to establish location, risk, decisions, or next steps.\n\nWhy B is incorrect: The permanent address does not replace the present-location address and omitting the change removes information needed to reconstruct the decision.\n\nWhy C is incorrect: Stating that nothing changed is inaccurate when the client's location and legal context changed.\n\nCTA Clinical Takeaway: Document the facts, the clinical and legal analysis, the action taken, and the continuity plan.",
	),
	array(
		'question_text'  => 'Which item is a strong telehealth risk-management practice rather than the exact California BBS requirement that must occur at the beginning of every session?',
		'option_a'       => "Verbally obtain and document the client's full name and present-location address.",
		'option_b'       => 'Confirm a backup contact method and technology-failure plan when clinically or operationally indicated.',
		'option_c'       => 'Assess whether the client and the session are appropriate for telehealth.',
		'option_d'       => 'Comply with applicable privacy, confidentiality, and security requirements.',
		'correct_option' => 'b',
		'explanation'    => "Why B is correct: A backup contact method and a technology-failure plan are strong telehealth safety and continuity practices, especially when risk is elevated or the connection is unreliable. They are not the exact item that BBS requires clinicians to verbally obtain and document at the beginning of every session.\n\nWhy A is incorrect: Full name and present-location address are explicit each-session requirements and must be obtained at the beginning of the session.\n\nWhy C is incorrect: Assessing whether the client and the session are appropriate for telehealth is an each-session regulatory duty.\n\nWhy D is incorrect: Compliance with applicable privacy, confidentiality, and security requirements is also part of the telehealth standard, even though it is broader than a spoken opening question.\n\nCTA Clinical Takeaway: Teach learners which practices are mandated by regulation and which additional practices strengthen safety and risk management.",
	),
	array(
		'question_text'  => "Which item may appropriately be included in a practice's intake identity-verification policy but is not a universal California BBS requirement at every telehealth session?",
		'option_a'       => "Obtaining the client's full name and address of present location.",
		'option_b'       => 'Assessing whether telehealth is appropriate for the client and session.',
		'option_c'       => 'Reviewing a date of birth or photo identification when required by payer, agency, or practice policy.',
		'option_d'       => "Documenting the client's present-location address at the beginning of the session.",
		'correct_option' => 'c',
		'explanation'    => "Why C is correct: A practice may reasonably use date of birth, photo identification, payer verification, or another identity method during intake when required by policy, setting, payer, or circumstances. California BBS does not make photo ID or date-of-birth review a universal every-session requirement. The universal each-session focus is the client's full name and present-location address, along with appropriateness and privacy/security duties.\n\nWhy A is incorrect: Full name and present-location address are required at the beginning of every telehealth session.\n\nWhy B is incorrect: Appropriateness assessment is an each-session duty, not merely an optional intake procedure.\n\nWhy D is incorrect: Documenting the present-location address is explicitly required at the beginning of every session.\n\nCTA Clinical Takeaway: Separate a practice's broader identity-verification policy from the specific BBS each-session requirements.",
	),
	array(
		'question_text'  => 'Which sequence best reflects a structured opening for a routine telehealth session?',
		'option_a'       => "Confirm the client's full name and present location, assess privacy and appropriateness, and confirm the backup plan when indicated.",
		'option_b'       => 'Begin the clinical discussion immediately and verify location only if a crisis develops.',
		'option_c'       => "Ask only for the client's permanent home address.",
		'option_d'       => 'Verify location only for clients who have a documented history of high risk.',
		'correct_option' => 'a',
		'explanation'    => "Why A is correct: A structured opening collects the information needed before clinical work proceeds: identity and present location, privacy and telehealth appropriateness, and any backup or safety procedure indicated by the client's risk and technology conditions. Making these steps routine reduces reliance on memory and improves emergency readiness.\n\nWhy B is incorrect: Waiting for a crisis defeats the purpose of location and backup planning and can delay response.\n\nWhy C is incorrect: A permanent home address does not establish where the client is physically located today.\n\nWhy D is incorrect: Location verification applies to every telehealth session, not only to clients already classified as high risk.\n\nCTA Clinical Takeaway: The first minute of telehealth should be a consistent safety and appropriateness workflow.",
	),
	array(
		'question_text'  => 'When assessing whether telehealth is clinically appropriate, the clinician should consider:',
		'option_a'       => "Only the client's diagnosis.",
		'option_b'       => "Only the client's preference for remote care.",
		'option_c'       => "Only the speed of the client's internet connection.",
		'option_d'       => 'Clinical presentation and risk, privacy, technology reliability, engagement, supports, and whether the level of care is appropriate.',
		'correct_option' => 'd',
		'explanation'    => "Why D is correct: Appropriateness is a multidimensional and ongoing clinical judgment. The clinician should consider the client's presentation and current risk, privacy, technology reliability, ability to engage, available supports, emergency readiness, and whether telehealth can provide an appropriate level of care. No single factor determines the answer in every case.\n\nWhy A is incorrect: Diagnosis alone does not show current stability, privacy, engagement, support, or emergency-response capacity.\n\nWhy B is incorrect: Client preference is important but cannot override safety, lawful practice, or level-of-care concerns.\n\nWhy C is incorrect: Internet quality matters, but it is only one part of the appropriateness assessment.\n\nCTA Clinical Takeaway: Assess the whole telehealth context, not one diagnosis, preference, or technology feature.",
	),
	array(
		'question_text'  => 'A client joins from a parked car outside work. Coworkers repeatedly walk past, and the client becomes hesitant when sensitive topics arise. What is the best response?',
		'option_a'       => 'Continue without addressing privacy because the client selected the location.',
		'option_b'       => 'Discuss the privacy concern, assess whether the client can speak freely, and relocate, modify, or reschedule the session as clinically appropriate.',
		'option_c'       => 'Permanently discontinue telehealth services.',
		'option_d'       => 'Document that privacy was adequate because the client was inside a vehicle.',
		'correct_option' => 'b',
		'explanation'    => "Why B is correct: The clinician should address the observable privacy problem, determine whether the client can speak freely, and collaboratively identify a safer option. Depending on urgency and feasibility, the clinician might relocate the client, use headphones or a safer communication method, limit sensitive discussion, or reschedule. The response should be proportionate to the clinical circumstances.\n\nWhy A is incorrect: The client's choice of location does not eliminate the clinician's duty to assess privacy and appropriateness.\n\nWhy C is incorrect: One privacy problem does not automatically justify permanent discontinuation of telehealth; the clinician should first evaluate whether the problem can be corrected.\n\nWhy D is incorrect: A parked car is not automatically private, especially when others are nearby and the client's behavior suggests inhibition.\n\nCTA Clinical Takeaway: Privacy must be actively assessed and created on both sides of a telehealth session.",
	),
	array(
		'question_text'  => "Which statement best reflects the course's approach to higher-risk telehealth situations?",
		'option_a'       => 'Any increased risk automatically makes telehealth inappropriate.',
		'option_b'       => 'Client preference should control the decision regardless of safety conditions.',
		'option_c'       => 'Higher risk requires additional assessment, safeguards, consultation, documentation, and possible changes in modality or level of care.',
		'option_d'       => 'Risk planning is unnecessary when the video connection is reliable.',
		'correct_option' => 'c',
		'explanation'    => "Why C is correct: Higher risk calls for more assessment and structure, not an automatic all-or-nothing rule. The clinician may need enhanced safety planning, local resources, backup communication, consultation, documentation, greater treatment intensity, a different modality, or a higher level of care. The decision should be based on whether adequate safeguards can be established.\n\nWhy A is incorrect: Increased risk does not automatically make telehealth inappropriate in every case; circumstances and available safeguards matter.\n\nWhy B is incorrect: Client preference is considered, but it cannot be the sole controlling factor when safety or level of care is uncertain.\n\nWhy D is incorrect: A reliable video connection does not replace risk assessment, local response planning, or clinical judgment.\n\nCTA Clinical Takeaway: Avoid automatic exclusion and automatic continuation; use structured, documented clinical judgment.",
	),
	array(
		'question_text'  => 'Which documentation is most complete for a higher-risk telehealth session?',
		'option_a'       => 'Present location and modality, privacy and appropriateness assessment, risk assessment and protective factors, local resources, consultation, actions, rationale, and follow-up.',
		'option_b'       => "The client's diagnosis and billing code only.",
		'option_c'       => 'A statement that "the safety plan was reviewed" without further detail.',
		'option_d'       => 'The length of the session and the platform used.',
		'correct_option' => 'a',
		'explanation'    => "Why A is correct: The most complete note records the telehealth conditions and the clinician's reasoning: modality and present location, privacy and appropriateness, risk findings and protective factors, local resources, consultations, actions, rationale, and follow-up. The amount of detail should reflect the significance and complexity of the event.\n\nWhy B is incorrect: A diagnosis and billing code do not document the telehealth safety assessment or the clinician's response.\n\nWhy C is incorrect: A conclusory phrase such as \"safety plan reviewed\" does not show what was assessed, updated, or decided.\n\nWhy D is incorrect: Session length and platform identify logistics but not the risk assessment, decision-making, or continuity plan.\n\nCTA Clinical Takeaway: Higher-risk documentation should make the clinical reasoning and response understandable to a later reviewer.",
	),
	array(
		'question_text'  => 'Which plan most completely supports telehealth emergency response and continuity?',
		'option_a'       => "The client's home address and instructions to call 911.",
		'option_b'       => 'The name of one emergency contact.',
		'option_c'       => 'A national crisis-line number only.',
		'option_d'       => 'Present-location procedures, local emergency resources, a support contact, backup communication, escalation and continuity steps, and documentation and follow-up procedures.',
		'correct_option' => 'd',
		'explanation'    => "Why D is correct: A complete plan connects prevention, immediate response, and follow-up. It establishes how present location will be obtained, identifies local emergency resources and a nearby support contact, defines backup communication and escalation steps, and addresses documentation and continuity after the event. The plan should be individualized and accessible before a crisis occurs.\n\nWhy A is incorrect: A home address may be outdated or different from the current location, and \"call 911\" alone does not create a coordinated telehealth response.\n\nWhy B is incorrect: One emergency contact is useful but does not address location, local services, disconnection, escalation, or documentation.\n\nWhy C is incorrect: A national crisis line can support care but does not replace location-specific resources or a full continuity plan.\n\nCTA Clinical Takeaway: Telehealth emergency planning is a coordinated system, not a single phone number.",
	),
	array(
		'question_text'  => 'A rural client reports worsening depression, unreliable internet, limited support, and recent thoughts of self-harm. The client strongly prefers telehealth. What should the clinician do first?',
		'option_a'       => 'Continue the usual telehealth plan because client preference is the controlling factor.',
		'option_b'       => 'Complete a detailed risk assessment and evaluate whether sufficient safeguards and an appropriate level of care can be established.',
		'option_c'       => 'Terminate services immediately because telehealth is never appropriate when self-harm thoughts are present.',
		'option_d'       => 'Require the client to purchase a faster internet plan before discussing risk.',
		'correct_option' => 'b',
		'explanation'    => "Why B is correct: The first task is a detailed risk assessment that clarifies ideation, intent, plan, means, history, protective factors, substance use, supports, and ability to participate in a safety plan. The clinician can then determine whether telehealth can be made sufficiently safe through added safeguards or whether a different modality or level of care is needed.\n\nWhy A is incorrect: Client preference is important, especially when access is limited, but it cannot replace a current risk and level-of-care assessment.\n\nWhy C is incorrect: Self-harm thoughts do not make telehealth universally inappropriate. The severity, immediacy, supports, and response capacity must be evaluated.\n\nWhy D is incorrect: Technology reliability matters, but purchasing faster internet is not the first response to a possible suicide-risk escalation.\n\nCTA Clinical Takeaway: Assess risk first, then decide whether telehealth can safely continue with sufficient supports and response capacity.",
	),
	array(
		'question_text'  => "A client's emergency contact and local crisis resources have not been reviewed since intake six months ago. What is the best next step?",
		'option_a'       => 'Assume the information is unchanged unless the client reports a problem.',
		'option_b'       => 'Wait to review the information until a crisis occurs.',
		'option_c'       => 'Review and update safety-critical information according to current risk, policy, and circumstances.',
		'option_d'       => 'Delete the information because it is no longer recent.',
		'correct_option' => 'c',
		'explanation'    => "Why C is correct: Safety-critical information changes over time. The clinician should review and update emergency contacts, local resources, backup methods, and related plans according to the client's current risk, travel, living situation, technology, and practice policy. Waiting for a crisis leaves the clinician dependent on potentially unusable information.\n\nWhy A is incorrect: Assuming the information is unchanged creates preventable risk because clients move, travel, change contacts, and experience changes in support.\n\nWhy B is incorrect: A crisis is the worst time to discover that contact or resource information is outdated.\n\nWhy D is incorrect: Old information should be verified or replaced, not simply deleted without establishing current alternatives.\n\nCTA Clinical Takeaway: Emergency readiness is maintained through periodic review, not completed once at intake.",
	),
	array(
		'question_text'  => "A telehealth session disconnects during a suicide risk assessment, and no backup communication plan exists. What is the primary concern?",
		'option_a'       => 'The clinician may be unable to assess safety or reconnect promptly.',
		'option_b'       => 'The clinician may be unable to bill for a complete session.',
		'option_c'       => 'The client may be dissatisfied with the platform.',
		'option_d'       => 'The session may end earlier than scheduled.',
		'correct_option' => 'a',
		'explanation'    => "Why A is correct: During a suicide risk assessment, a disconnection can interrupt the clinician's ability to evaluate danger, maintain contact, and activate help. A prearranged backup method and escalation plan reduce uncertainty and allow the clinician to respond promptly when the client cannot be reached.\n\nWhy B is incorrect: Billing is secondary to the immediate clinical concern of safety and continuity.\n\nWhy C is incorrect: Client dissatisfaction may occur, but it is not the primary risk during an interrupted suicide assessment.\n\nWhy D is incorrect: A shortened session is less important than loss of assessment and response capacity.\n\nCTA Clinical Takeaway: A technology-failure plan becomes a clinical safety plan when risk is being assessed.",
	),
	array(
		'question_text'  => 'Which example is primarily an administrative safeguard for electronic client information?',
		'option_a'       => "Installing a privacy screen on a clinician's monitor.",
		'option_b'       => 'Using workforce training, access-management procedures, vendor review, and an incident-response policy.',
		'option_c'       => 'Using encryption during electronic transmission.',
		'option_d'       => 'Keeping the office door locked during sessions.',
		'correct_option' => 'b',
		'explanation'    => "Why B is correct: Administrative safeguards are policies, procedures, and management actions used to protect electronic information and guide workforce conduct. Training, access-management procedures, vendor review, and incident-response policies fit this category because they organize how the practice manages security risk.\n\nWhy A is incorrect: A privacy screen is primarily a physical safeguard because it limits visual access to information on a device.\n\nWhy C is incorrect: Encryption is a technical safeguard that protects information through technology.\n\nWhy D is incorrect: A locked office door is a physical safeguard that controls access to the workspace.\n\nCTA Clinical Takeaway: Administrative safeguards govern people and processes; physical safeguards protect spaces and devices; technical safeguards control electronic access and transmission.",
	),
	array(
		'question_text'  => 'Before adopting a new telehealth platform, what is the best approach?',
		'option_a'       => 'Use the platform that is most familiar to clients.',
		'option_b'       => 'Select the least expensive platform.',
		'option_c'       => 'Rely on marketing language that describes the platform as secure.',
		'option_d'       => "Review what information the platform handles, who can access it, recording and transcript settings, safeguards, configuration, vendor role, and the practice's risk analysis.",
		'correct_option' => 'd',
		'explanation'    => "Why D is correct: A responsible platform decision begins with a documented review of the information the system creates, receives, transmits, or stores; who can access it; whether recordings, transcripts, chat, or tracking features are enabled; the available safeguards and configuration; the vendor's role; and the practice's risk analysis. Security depends on both product features and actual use.\n\nWhy A is incorrect: Familiarity can improve usability but does not establish privacy, security, or legal suitability.\n\nWhy B is incorrect: Price is not a compliance or security test. A low-cost or free platform may or may not be appropriate depending on its functions and safeguards.\n\nWhy C is incorrect: Marketing terms such as \"secure\" are not a substitute for reviewing documentation, settings, data handling, and contractual responsibilities.\n\nCTA Clinical Takeaway: Evaluate what the technology actually does and how it will be configured—not its popularity, price, or advertising.",
	),
	array(
		'question_text'  => 'Which example most clearly represents protected client information in the context of this course?',
		'option_a'       => 'A publicly available article about psychotherapy.',
		'option_b'       => 'A blank intake form with no client information.',
		'option_c'       => "A client's name linked to a diagnosis and treatment note in the practice's electronic record.",
		'option_d'       => 'The public address of a mental health office.',
		'correct_option' => 'c',
		'explanation'    => "Why C is correct: A client's name linked to a diagnosis and treatment note is individually identifiable health information connected to care. In a HIPAA-covered practice or business-associate context, it is PHI, and when maintained electronically it is ePHI. Even outside federal HIPAA status, the information remains confidential client information subject to applicable professional and state protections.\n\nWhy A is incorrect: A public article is not information about an identifiable client receiving care.\n\nWhy B is incorrect: A blank form contains no identifiable client information.\n\nWhy D is incorrect: A publicly listed office address is not an identifiable client's health or treatment information.\n\nCTA Clinical Takeaway: Think about the combination of identity and care-related information, not isolated words or documents.",
	),
	array(
		'question_text'  => 'A client joins a telehealth session from a shared family laptop in an open room. What is the best response?',
		'option_a'       => 'Discuss privacy risks, determine who may be nearby or have device access, and use a private location, headphones, or another appropriate adjustment.',
		'option_b'       => 'Assume the platform alone protects confidentiality.',
		'option_c'       => 'Permanently terminate telehealth services.',
		'option_d'       => 'Record the session so there is a complete record of the privacy concern.',
		'correct_option' => 'a',
		'explanation'    => "Why A is correct: The clinician should assess both environmental and device privacy. A shared laptop may expose saved passwords, notifications, browser history, portal access, or session information, while an open room may allow others to overhear. Collaborative adjustments can include a private location, headphones, another device, closing notifications, or rescheduling when privacy is inadequate.\n\nWhy B is incorrect: A secure platform cannot control who is in the client's room or who has access to the client's device.\n\nWhy C is incorrect: Shared-device risk does not automatically require permanent termination; the clinician should first determine whether reasonable safeguards can be implemented.\n\nWhy D is incorrect: Recording introduces additional privacy and storage risk and does not correct the open-room or shared-device problem.\n\nCTA Clinical Takeaway: Platform security is only one layer; telehealth privacy also depends on the client's environment and device practices.",
	),
	array(
		'question_text'  => 'A HIPAA-covered practice uses a vendor that stores protected health information on the practice\'s behalf. What is the best action?',
		'option_a'       => 'No vendor review is needed if the product is widely used.',
		'option_b'       => 'A Business Associate Agreement is required with every vendor, regardless of what the vendor does.',
		'option_c'       => 'A Business Associate Agreement makes a separate security review unnecessary.',
		'option_d'       => "Determine whether the vendor is acting as a business associate, obtain a Business Associate Agreement when required, and also review the vendor's safeguards and system configuration.",
		'correct_option' => 'd',
		'explanation'    => "Why D is correct: A vendor that stores PHI for a HIPAA-covered practice may be acting as a business associate. The practice should determine the vendor's role, obtain the required written assurances through a BAA when the definition is met, and separately evaluate the vendor's security safeguards and system configuration. A contract and a security review serve related but different purposes.\n\nWhy A is incorrect: Popularity does not establish a vendor's legal role or demonstrate appropriate safeguards.\n\nWhy B is incorrect: A BAA is not required with every vendor. It depends on whether the vendor performs functions or services involving PHI on behalf of the covered entity or business associate.\n\nWhy C is incorrect: A BAA allocates responsibilities and required assurances, but it does not replace risk analysis, appropriate configuration, access controls, or ongoing vendor oversight.\n\nCTA Clinical Takeaway: Determine whether a BAA is required, then continue the broader privacy and security review.",
	),
	array(
		'question_text'  => "A client sends detailed suicidal thoughts to a clinician's scheduling-only phone after hours. What is the most important prevention lesson?",
		'option_a'       => 'Clinicians should never allow any form of text messaging.',
		'option_b'       => 'Communication policies must define approved channels, response times, emergency procedures, and documentation expectations.',
		'option_c'       => 'Clinicians must monitor all electronic channels continuously.',
		'option_d'       => 'The message should be deleted because the channel was not approved for clinical content.',
		'correct_option' => 'b',
		'explanation'    => "Why B is correct: The scenario reveals a mismatch between the clinician's intended use of the channel and the client's expectations. A clear communication policy should identify approved channels, typical response times, after-hours and emergency procedures, what content should not be sent through ordinary text, and how clinically significant messages will be documented and addressed.\n\nWhy A is incorrect: A total ban on texting is not required for every practice. Texting may be used for limited purposes when risks and expectations are clearly managed.\n\nWhy C is incorrect: Clinicians are not required to monitor every electronic channel continuously, and implying continuous monitoring can create unsafe expectations.\n\nWhy D is incorrect: Deleting a safety-related message because it arrived through the wrong channel could destroy clinically important information and does not address the client's risk or the policy failure.\n\nCTA Clinical Takeaway: Digital convenience requires explicit boundaries, response expectations, emergency instructions, and documentation procedures.",
	),
	array(
		'question_text'  => 'Which technology-failure plan best supports privacy, safety, and continuity of care?',
		'option_a'       => 'Tell the client to try logging in again later.',
		'option_b'       => 'Instruct every client to call 911 after any disconnection.',
		'option_c'       => 'Agree on reconnection steps, a backup communication method, a safety check, criteria for escalation, and documentation and follow-up procedures.',
		'option_d'       => 'Move the conversation to a personal social-media account if the platform fails.',
		'correct_option' => 'c',
		'explanation'    => "Why C is correct: A strong disruption plan defines what both parties will do: attempt reconnection, use an agreed backup method, check safety, determine when escalation is necessary, and document the interruption, actions, outcome, and follow-up. The details should be proportionate to the client's risk and known technology conditions.\n\nWhy A is incorrect: Simply trying again later provides no safety check, alternate contact, or escalation process.\n\nWhy B is incorrect: Calling 911 after every disconnection is disproportionate and ignores the client's circumstances, risk level, location, and local response options.\n\nWhy D is incorrect: A personal social-media account creates boundary and privacy concerns and is not an appropriate default clinical backup channel.\n\nCTA Clinical Takeaway: A predetermined, professional backup plan protects privacy, safety, and continuity when technology fails.",
	),
);
