<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	array(
		'match_titles'            => array(
			'Alcoholism & Other Chemical Substance Dependency: Assessment, Treatment, Recovery, & Clinical Practice',
			'Alcoholism & Other Chemical Substance Dependency',
		),
		'title'                   => 'Alcoholism & Other Chemical Substance Dependency: Assessment, Treatment, Recovery, & Clinical Practice',
		'ce_hours'                => 15.0,
		'price'                   => 149.00,
		'category'                => 'Alcoholism & Other Chemical Substance Dependency',
		'description'             => 'This asynchronous continuing education course provides structured clinical training in Alcoholism & Other Chemical Substance Dependency: Assessment, Treatment, Recovery, & Clinical Practice. It is designed for LMFTs, LCSWs, LPCCs, LEPs, and Registered Associates and combines online text, instructional video modules, downloadable resources, case studies, and clinical application exercises.',
		'course_level'            => 'Intermediate to Advanced',
		'target_audience'         => 'LMFTs, LCSWs, LPCCs, LEPs, and Registered Associates',
		'instructional_method'    => 'Asynchronous Distance Learning (online text, instructional video modules, downloadable resources, case studies, and clinical application exercises)',
		'presenter'               => 'Candice Fuimaono, MS, LMFT',
		'educational_goals'       => array(
			'Strengthen an integrated understanding of the biological, psychological, social, environmental, and recovery-related factors associated with substance use disorders.',
			'Enhance clinical competence in substance-specific assessment, DSM-5-TR diagnosis, screening, referral, and level-of-care decision-making.',
			'Expand practical skill in Motivational Interviewing, Cognitive Behavioral Therapy, Contingency Management, harm reduction, treatment planning, and relapse prevention.',
			'Improve the integration of mental health and substance use treatment for clients with co-occurring conditions.',
			'Increase ethical and professional decision-making related to documentation, scope of competence, risk management, and clinician impairment.',
			'Support recovery-oriented care that respects multiple pathways to change and promotes client safety, engagement, and long-term wellness.',
		),
		'learning_objectives'     => array(
			'Describe four biological, psychological, social, and environmental factors that contribute to the development or maintenance of substance use disorders.',
			'Identify the clinical effects, intoxication or withdrawal risks, and treatment considerations associated with at least five major classes of psychoactive substances.',
			'Apply DSM-5-TR criteria to determine the presence and severity of a substance use disorder in a clinical case example.',
			'Apply at least two evidence-based screening tools, such as the AUDIT, AUDIT-C, DAST-10, or CAGE-AID, and explain how the results inform referral and level-of-care decisions.',
			'Apply at least three Motivational Interviewing strategies to increase engagement and support behavior change.',
			'Select appropriate evidence-based interventions from Cognitive Behavioral Therapy, Contingency Management, harm reduction, and recovery-oriented care based on a client case.',
			'Prepare an integrated treatment and relapse-prevention plan that includes at least five components addressing clinical needs, co-occurring conditions, supports, risk, and continuing care.',
			'Identify four indicators of professional impairment and select appropriate consultation, documentation, referral, and public-protection responses.',
		),
		'completion_requirements' => array(
			'Complete all required instructional modules and embedded learning activities.',
			'Earn a score of at least 70% on the final examination. Participants may repeat the examination until the passing score is achieved.',
			'Complete the course-specific evaluation, including a rating for each measurable learning objective.',
			'Submit the required course-completion attestation for asynchronous distance learning.',
			'A CE certificate is issued only after all completion requirements are satisfied.',
		),
		'references'              => array(
			'American Psychiatric Association. (2022). Diagnostic and statistical manual of mental disorders (5th ed., text rev.).',
			'California Board of Behavioral Sciences. (2025). Statutes and regulations relating to the practice of marriage and family therapy, licensed clinical social work, licensed educational psychology, and professional clinical counseling.',
			'Inaba, D. S., & Cohen, W. E. (2019). Uppers, downers, all arounders: Physical and mental effects of psychoactive drugs (9th ed.).',
			'Marlatt, G. A., & Donovan, D. M. (Eds.). (2005). Relapse prevention: Maintenance strategies in the treatment of addictive behaviors (2nd ed.).',
			'McHugh, R. K., Hearon, B. A., & Otto, M. W. (2010). Cognitive behavioral therapy for substance use disorders. Psychiatric Clinics of North America, 33(3), 511-525.',
			'Miller, W. R., & Rollnick, S. (2023). Motivational interviewing: Helping people change and grow (4th ed.).',
			'Substance Abuse and Mental Health Services Administration. (2020). Treatment Improvement Protocol 35: Enhancing motivation for change in substance use disorder treatment.',
			'Substance Abuse and Mental Health Services Administration. (2024). Treatment Improvement Protocol 42: Substance use disorder treatment for people with co-occurring disorders.',
			'Substance Abuse and Mental Health Services Administration. (2024). Treatment Improvement Protocol 63: Medications for opioid use disorder.',
			'Substance Abuse and Mental Health Services Administration. (2023). Screening, brief intervention, and referral to treatment (SBIRT).',
		),
		'development_draft'       => true,
		'modules'                 => array(
			array(
				'title'          => 'Foundations of Addiction Science',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Historical perspectives on addiction and the evolution of treatment',
					'Stigma, language, and common misconceptions',
					'Current prevalence and public-health considerations',
					'Biopsychosocial and environmental contributors',
					'Risk factors, protective factors, and recovery capital',
					'Substance use disorder as a chronic and treatable condition',
					'Recovery-oriented systems of care and multiple pathways to change',
				),
			),
			array(
				'title'          => 'Neurobiology of Addiction and Recovery',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Brain reward pathways, dopamine, and reinforcement',
					'Tolerance, withdrawal, craving, and neuroadaptation',
					'Executive functioning, decision-making, and behavioral control',
					'Effects of chronic substance use on brain and behavior',
					'Stress, learning, memory, and cue reactivity',
					'Neuroplasticity and recovery implications',
					'Clinical implications for engagement and treatment planning',
				),
			),
			array(
				'title'          => 'Alcohol Use Disorder',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Alcohol pharmacology and patterns of use',
					'Prevalence, risk factors, and protective factors',
					'DSM-5-TR diagnostic considerations',
					'Alcohol intoxication and withdrawal syndromes',
					'Recognition of medical emergencies, including delirium tremens',
					'Screening, assessment, and referral considerations',
					'Evidence-based treatment and relapse-prevention approaches',
				),
			),
			array(
				'title'          => 'Opioid Use Disorders',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Prescription opioid misuse, heroin, fentanyl, and counterfeit substances',
					'Opioid intoxication, withdrawal, and overdose recognition',
					'Naloxone education and overdose-response principles',
					'Medication for Opioid Use Disorder (MOUD)',
					'Harm-reduction strategies and public-health considerations',
					'Evidence-based treatment and recovery supports',
					'Clinical coordination and referral responsibilities',
				),
			),
			array(
				'title'          => 'Stimulants and Emerging Drug Trends',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Methamphetamine, cocaine, and other stimulant-related disorders',
					'Stimulant intoxication, withdrawal, and psychiatric complications',
					'Synthetic substances and designer-drug trends',
					'Polysubstance use and unpredictable interaction risks',
					'Vaping products and nicotine-related concerns',
					'Clinical assessment and treatment considerations',
					'Current trends and implications for prevention and care',
				),
			),
			array(
				'title'          => 'Cannabis, Sedatives, Hallucinogens, Inhalants, and Other Substance Classes',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Cannabis-related disorders and clinical considerations',
					'Sedative, hypnotic, and anxiolytic use disorders',
					'Hallucinogen- and inhalant-related concerns',
					'Nicotine and tobacco use disorders',
					'Substance-induced psychiatric symptoms',
					'Intoxication, withdrawal, and medical-risk indicators',
					'Referral, consultation, and scope-of-competence considerations',
				),
			),
			array(
				'title'          => 'DSM-5-TR Diagnosis and Clinical Formulation',
				'duration_mins'  => 60,
				'summary_points' => array(
					'DSM-5-TR substance use disorder criteria',
					'Severity, remission, and controlled-environment specifiers',
					'Substance-induced disorders versus independent mental disorders',
					'Differential diagnosis and diagnostic uncertainty',
					'Medical, developmental, cultural, and contextual considerations',
					'Clinical formulation beyond the diagnostic label',
					'Documentation of diagnostic reasoning',
				),
			),
			array(
				'title'          => 'Screening, SBIRT, Risk Assessment, and Levels of Care',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Clinical interviewing and readiness-for-change assessment',
					'AUDIT, AUDIT-C, DAST-10, and CAGE-AID',
					'Screening, Brief Intervention, and Referral to Treatment (SBIRT)',
					'Assessment of overdose, withdrawal, suicide, and violence risk',
					'Treatment matching and level-of-care considerations',
					'Medical detoxification and emergency referral indicators',
					'Care coordination and documentation of referral decisions',
				),
			),
			array(
				'title'          => 'Motivational Interviewing and Engagement',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Motivational Interviewing spirit and core principles',
					'Open questions, affirmations, reflections, and summaries (OARS)',
					'Change talk, sustain talk, and ambivalence',
					'Engaging clients who are uncertain about change',
					'Developing discrepancy without confrontation',
					'Supporting autonomy and collaborative planning',
					'Applying Motivational Interviewing across stages of change',
				),
			),
			array(
				'title'          => 'Cognitive Behavioral Therapy and Contingency Management',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Functional analysis of substance use behavior',
					'Triggers, thoughts, emotions, urges, and consequences',
					'Cognitive and behavioral coping strategies',
					'Skill rehearsal and behavioral planning',
					'Contingency Management principles and applications',
					'Monitoring progress and reinforcing recovery behaviors',
					'Integrating interventions with client goals and context',
				),
			),
			array(
				'title'          => 'Treatment Planning, Relapse Prevention, and Continuing Care',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Collaborative and individualized treatment planning',
					'Measurable goals, objectives, and interventions',
					'High-risk situations, triggers, and early-warning signs',
					'Relapse-prevention and return-to-use response planning',
					'Recovery capital, social support, and continuing care',
					'Documentation of progress and treatment-plan revision',
					'Long-term recovery and transition planning',
				),
			),
			array(
				'title'          => 'Co-Occurring Mental Health and Substance Use Disorders',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Depression, anxiety, trauma-related disorders, and substance use',
					'Bipolar disorders, psychosis, and diagnostic complexity',
					'Suicide risk and substance-related disinhibition',
					'Differential diagnosis and symptom timelines',
					'Integrated assessment and treatment planning',
					'Coordination with medical and psychiatric providers',
					'Evidence-based approaches for co-occurring conditions',
				),
			),
			array(
				'title'          => 'Harm Reduction, Recovery Supports, and Multiple Pathways to Change',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Harm-reduction principles and clinical applications',
					'Overdose prevention and safer-use education',
					'Abstinence-based and non-abstinence treatment goals',
					'Mutual-help, peer support, and community recovery resources',
					'Medication-supported recovery and interdisciplinary care',
					'Client choice, cultural context, and recovery identity',
					'Continuing care and long-term wellness planning',
				),
			),
			array(
				'title'          => 'Professional Impairment and Therapist Substance Use',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Recognition of professional impairment',
					'Therapist substance use and fitness-to-practice concerns',
					'Self-assessment, wellness, and early intervention',
					'Consultation, supervision, and referral',
					'Public-protection responsibilities and professional accountability',
					'Recovery monitoring and return-to-practice considerations',
					'Lessons from California disciplinary cases',
				),
			),
			array(
				'title'          => 'Ethics, Documentation, Risk Management, and Clinical Decision-Making',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Ethical decision-making frameworks',
					'Scope of practice and scope of competence',
					'Documentation and informed-consent considerations',
					'Referral, consultation, and interdisciplinary coordination',
					'Risk management and duty-to-protect responsibilities',
					'Professional boundaries and accountability',
					'Application through clinical and disciplinary case analysis',
				),
			),
		),
	),
	array(
		'match_titles'            => array( 'Child Abuse Assessment & Mandated Reporting' ),
		'title'                   => 'Child Abuse Assessment & Mandated Reporting',
		'ce_hours'                => 7.0,
		'price'                   => 89.00,
		'category'                => 'Law & Ethics',
		'description'             => 'This asynchronous continuing education course provides structured clinical training in Child Abuse Assessment & Mandated Reporting. It is designed for LMFTs, LCSWs, LPCCs, LEPs, and Registered Associates and combines online text, instructional video modules, downloadable resources, case studies, and clinical application exercises.',
		'course_level'            => 'Intermediate',
		'target_audience'         => 'LMFTs, LCSWs, LPCCs, LEPs, and Registered Associates',
		'instructional_method'    => 'Asynchronous Distance Learning (online text, instructional video modules, downloadable resources, case studies, and clinical application exercises)',
		'presenter'               => 'Candice Fuimaono, MS, LMFT',
		'educational_goals'       => array(
			'Strengthen the ability to recognize, assess, document, and respond to suspected child abuse and neglect.',
			'Enhance trauma-informed and developmentally responsive clinical practice with children and families affected by maltreatment.',
			'Improve application of California mandated-reporting requirements and reasonable-suspicion standards.',
			'Expand objective documentation and professional decision-making in complex child-protection situations.',
			'Increase confidence in managing caregiver reactions, ethical dilemmas, consultation needs, and post-report treatment responsibilities.',
			'Support child safety while preserving appropriate therapeutic boundaries and continuity of care.',
		),
		'learning_objectives'     => array(
			'Identify at least six physical, behavioral, emotional, developmental, or disclosure-based indicators associated with child abuse or neglect.',
			'Select three developmentally appropriate assessment adaptations for infants, young children, nonverbal children, children with disabilities, or adolescents.',
			'Apply three non-leading response strategies when a child discloses possible maltreatment and distinguish clinical assessment from investigative interviewing.',
			'Prepare objective clinical documentation that includes observations, exact statements, clinical reasoning, actions taken, and consultation or reporting decisions.',
			'Explain the difference between reasonable suspicion and proof under California\'s Child Abuse and Neglect Reporting Act (CANRA).',
			'List the required sequence and timelines for verbal and written mandated reports in California.',
			'Select at least three post-report clinical, consultation, and risk-management strategies that support the child, family, and ongoing treatment.',
		),
		'completion_requirements' => array(
			'Complete all required instructional modules and embedded learning activities.',
			'Earn a score of at least 70% on the final examination. Participants may repeat the examination until the passing score is achieved.',
			'Complete the course-specific evaluation, including a rating for each measurable learning objective.',
			'Submit the required course-completion attestation for asynchronous distance learning.',
			'A CE certificate is issued only after all completion requirements are satisfied.',
		),
		'references'              => array(
			'California Department of Social Services. (2023). The California mandated reporter handbook. State of California.',
			'Cross, T. P., Mathews, B., & Jones, L. M. (2021). Improving the clinical response to child maltreatment: Legal frameworks and reporting protocols for mental health practitioners. Routledge.',
			'Mathews, B., & Bross, D. C. (2020). Mandatory reporting laws and children\'s rights: An international and comparative analysis. Springer Publishing.',
			'Myers, J. E. B. (2023). A practitioner\'s guide to child abuse and neglect (9th ed.). Sage Publications.',
			'Kellogg, N. D. (2021). The evaluation of suspected child physical abuse. American Academy of Pediatrics.',
		),
		'development_draft'       => false,
		'modules'                 => array(
			array(
				'title'          => 'Foundations of Child Abuse Assessment',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Overview of child maltreatment in clinical practice',
					'Prevalence, risk factors, and developmental impact',
					'Trauma-informed assessment principles',
					'Professional responsibilities in child protection',
					'Role of mental health professionals in recognition and response',
					'Common misconceptions regarding abuse recognition and reporting',
					'Child safety, therapeutic care, and professional accountability',
				),
			),
			array(
				'title'          => 'Recognizing Physical, Behavioral, Emotional, and Disclosure Indicators',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Physical indicators of abuse and neglect',
					'Behavioral, emotional, and developmental warning signs',
					'Differentiating accidental injury from concerning presentations',
					'Trauma-related responses and changes in functioning',
					'Disclosure patterns, delayed disclosure, and recantation',
					'Clinical observation and documentation',
					'Application through case examples',
				),
			),
			array(
				'title'          => 'Special Populations and Complex Child-Protection Cases',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Infants and very young children',
					'Children with developmental disabilities or communication challenges',
					'Nonverbal children and limited disclosures',
					'Adolescent disclosure patterns and delayed reporting',
					'Domestic violence, caregiver substance use, and child safety',
					'Cultural considerations and bias awareness',
					'Advanced case conceptualization in high-risk situations',
				),
			),
			array(
				'title'          => 'Assessment, Documentation, and Child Disclosures',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Developmentally appropriate assessment approaches',
					'Responding to disclosures without leading or investigating',
					'Clinical assessment versus forensic interviewing',
					'Objective and defensible documentation',
					'Recording exact statements, observations, and clinical rationale',
					'Common documentation errors',
					'Consultation and decision-support practices',
				),
			),
			array(
				'title'          => 'California Mandated Reporting and CANRA',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Overview of the Child Abuse and Neglect Reporting Act',
					'Mandated-reporter responsibilities',
					'Reportable categories of abuse and neglect',
					'Reasonable-suspicion standards and reporting thresholds',
					'Verbal and written reporting timelines',
					'Reporting procedures and documentation',
					'Common legal misconceptions and practice errors',
				),
			),
			array(
				'title'          => 'Difficult Reporting Decisions and Ethical Challenges',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Managing uncertainty and incomplete information',
					'Caregiver resistance, anger, and requests for secrecy',
					'Confidentiality and informed-consent considerations',
					'Professional boundaries during investigations',
					'Cultural humility and bias awareness',
					'Ethical decision-making frameworks',
					'Consultation, supervision, and risk-management resources',
				),
			),
			array(
				'title'          => 'After the Report: Clinical Care and Professional Protection',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Supporting children after a mandated report',
					'Maintaining the therapeutic relationship',
					'Understanding investigative responses and procedures',
					'Collaboration with Child Protective Services and other agencies',
					'Post-report documentation and treatment planning',
					'Professional risk management and consultation',
					'Clinician self-care and emotional-impact management',
				),
			),
		),
	),
	array(
		'match_titles'            => array(
			'HIV/AIDS and Mental Health: Clinical Implications, Stigma, and Ethical Practice',
			'HIV/AIDS and Mental Health',
		),
		'title'                   => 'HIV/AIDS and Mental Health: Clinical Implications, Stigma, and Ethical Practice',
		'ce_hours'                => 7.0,
		'price'                   => 89.00,
		'category'                => 'Clinical Skills',
		'description'             => 'This asynchronous continuing education course provides structured clinical training in HIV/AIDS and Mental Health: Clinical Implications, Stigma, and Ethical Practice. It is designed for LMFTs, LCSWs, LPCCs, LEPs, associates, trainees, supervisors, and other behavioral health professionals and combines online text, instructional video modules, downloadable resources, case studies, and clinical application exercises.',
		'course_level'            => 'Intermediate',
		'target_audience'         => 'LMFTs, LCSWs, LPCCs, LEPs, associates, trainees, supervisors, and other behavioral health professionals',
		'instructional_method'    => 'Asynchronous Distance Learning (online text, instructional video modules, downloadable resources, case studies, and clinical application exercises)',
		'presenter'               => 'Candice Fuimaono, MS, LMFT',
		'educational_goals'       => array(
			'Strengthen knowledge of HIV epidemiology, transmission, prevention, and current medical management relevant to behavioral health practice.',
			'Enhance clinical responsiveness to the psychological, emotional, neurocognitive, and behavioral health concerns experienced by people living with HIV.',
			'Increase culturally responsive and stigma-informed care across diverse identities, communities, and healthcare contexts.',
			'Improve assessment, treatment planning, intervention, and interdisciplinary collaboration for HIV-related behavioral health needs.',
			'Expand knowledge of California confidentiality, documentation, and ethical responsibilities involving HIV-related information.',
			'Promote resilience, self-advocacy, wellness, and long-term quality of life.',
		),
		'learning_objectives'     => array(
			'Identify three HIV transmission pathways, three prevention strategies, and the role of current medical management in supporting health outcomes.',
			'Describe four common psychological, emotional, or behavioral health concerns experienced by people living with HIV/AIDS.',
			'Identify three ways stigma, minority stress, discrimination, or social determinants of health may affect treatment access, engagement, or outcomes.',
			'Apply an evidence-based assessment and treatment-planning process to a clinical case involving HIV-related mental health concerns.',
			'Identify at least three clinical features that may indicate HIV-Associated Neurocognitive Disorders or co-occurring behavioral health concerns and select appropriate referral or consultation steps.',
			'Identify at least four California confidentiality, informed-consent, release-of-information, or documentation requirements related to HIV information.',
			'Apply an ethical decision-making framework to a case involving disclosure, confidentiality, partner-notification concerns, or client welfare.',
			'Design a wellness and multidisciplinary-care plan that includes at least three supports for resilience, self-advocacy, and long-term quality of life.',
		),
		'completion_requirements' => array(
			'Complete all required instructional modules and embedded learning activities.',
			'Earn a score of at least 70% on the final examination. Participants may repeat the examination until the passing score is achieved.',
			'Complete the course-specific evaluation, including a rating for each measurable learning objective.',
			'Submit the required course-completion attestation for asynchronous distance learning.',
			'A CE certificate is issued only after all completion requirements are satisfied.',
		),
		'references'              => array(
			'American Psychiatric Association. (2022). Diagnostic and statistical manual of mental disorders (5th ed., text rev.).',
			'Centers for Disease Control and Prevention. (2025). HIV basics. U.S. Department of Health and Human Services.',
			'Centers for Disease Control and Prevention. (2025). HIV risk and prevention. U.S. Department of Health and Human Services.',
			'California Department of Public Health. (2025). Office of AIDS program resources.',
			'California Health and Safety Code. HIV confidentiality and disclosure provisions.',
			'Substance Abuse and Mental Health Services Administration. (2024). Behavioral health and HIV care integration resources.',
			'Meyer, I. H. (2003). Prejudice, social stress, and mental health in lesbian, gay, and bisexual populations: Conceptual issues and research evidence. Psychological Bulletin, 129(5), 674-697.',
			'World Health Organization. (2024). HIV and mental health resources.',
		),
		'development_draft'       => false,
		'modules'                 => array(
			array(
				'title'          => 'Foundations of HIV/AIDS for Mental Health Professionals',
				'duration_mins'  => 60,
				'summary_points' => array(
					'HIV epidemiology and prevalence trends',
					'Transmission pathways and non-transmission misconceptions',
					'Prevention strategies and risk reduction',
					'Viral load, CD4 count, and treatment basics',
					'Undetectable = Untransmittable (U=U)',
					'Pre-Exposure Prophylaxis (PrEP) and Post-Exposure Prophylaxis (PEP)',
					'Role of mental health professionals in HIV care',
				),
			),
			array(
				'title'          => 'Psychological and Behavioral Health Impact of HIV',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Emotional responses to diagnosis',
					'Depression, anxiety, and adjustment difficulties',
					'Trauma, grief, and chronic-illness adaptation',
					'HIV-Associated Neurocognitive Disorders (HAND)',
					'Substance use and co-occurring concerns',
					'Resilience, coping, and protective factors',
					'Long-term psychological well-being',
				),
			),
			array(
				'title'          => 'HIV, Stigma, Minority Stress, and Health Disparities',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Historical and contemporary HIV stigma',
					'Minority Stress Theory',
					'LGBTQ+ populations and HIV',
					'Racial, ethnic, and healthcare disparities',
					'Cultural humility in clinical practice',
					'Social determinants of health',
					'Effects of stigma on engagement and outcomes',
				),
			),
			array(
				'title'          => 'Assessment, Treatment Planning, and Clinical Intervention',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Mental health and substance use assessment considerations',
					'Depression, anxiety, trauma, suicide, and cognitive screening',
					'Strengths-based and culturally responsive treatment planning',
					'Cognitive Behavioral Therapy and Acceptance and Commitment Therapy',
					'Supportive counseling and family-systems approaches',
					'Referral and interdisciplinary collaboration',
					'Documentation and continuity of care',
				),
			),
			array(
				'title'          => 'Confidentiality, Ethics, and California Law',
				'duration_mins'  => 60,
				'summary_points' => array(
					'California confidentiality statutes and HIV privacy protections',
					'Informed consent and release-of-information procedures',
					'Documentation and electronic-record considerations',
					'Ethical responsibilities in HIV care',
					'Managing sensitive medical and mental health information',
					'Consultation and interdisciplinary communication',
					'Application through clinical scenarios',
				),
			),
			array(
				'title'          => 'Complex Clinical Decision-Making',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Disclosure-related ethical dilemmas',
					'Partner-notification concerns',
					'High-risk behavioral situations',
					'Substance use and HIV risk',
					'Confidentiality challenges and client welfare',
					'Professional consultation and risk management',
					'Ethical decision-making frameworks',
				),
			),
			array(
				'title'          => 'Long-Term Wellness and Clinical Integration',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Long-term adaptation and resilience',
					'Recovery-oriented and strengths-based care',
					'Quality-of-life and wellness planning',
					'Multidisciplinary collaboration',
					'Community resources and support systems',
					'Patient self-advocacy',
					'Comprehensive case integration',
				),
			),
		),
	),
	array(
		'match_titles'            => array(
			'Human Sexuality & Clinical Practice: Biological, Psychological, and Cultural Perspectives',
			'Human Sexuality & Clinical Practice',
		),
		'title'                   => 'Human Sexuality & Clinical Practice: Biological, Psychological, and Cultural Perspectives',
		'ce_hours'                => 10.0,
		'price'                   => 99.00,
		'category'                => 'Clinical Skills',
		'description'             => 'This asynchronous continuing education course provides structured clinical training in Human Sexuality & Clinical Practice: Biological, Psychological, and Cultural Perspectives. It is designed for LMFTs, LCSWs, LPCCs, and Registered Associates and combines online text, instructional video modules, downloadable resources, case studies, and clinical application exercises.',
		'course_level'            => 'Intermediate',
		'target_audience'         => 'LMFTs, LCSWs, LPCCs, and Registered Associates',
		'instructional_method'    => 'Asynchronous Distance Learning (online text, instructional video modules, downloadable resources, case studies, and clinical application exercises)',
		'presenter'               => 'Candice Fuimaono, MS, LMFT',
		'educational_goals'       => array(
			'Strengthen an integrated understanding of human sexuality across biological, psychological, developmental, relational, and cultural domains.',
			'Enhance competence in sexual-health assessment and treatment planning within general mental health practice.',
			'Increase confidence in conducting affirming, culturally responsive, and trauma-informed discussions of sexuality.',
			'Expand knowledge of evidence-based interventions for sexual dysfunction, intimacy concerns, and sexual anxiety.',
			'Improve responsiveness to identity development, minority stress, stigma, trauma, and diverse relationship structures.',
			'Strengthen ethical decision-making related to boundaries, clinician bias, erotic transference, countertransference, and dual relationships.',
		),
		'learning_objectives'     => array(
			'Identify the four phases of the human sexual response cycle and one physiological marker associated with each phase.',
			'Apply DSM-5-TR criteria and differential-assessment principles to distinguish sexual dysfunction diagnoses from medical, medication-related, psychological, and relational contributors.',
			'Apply a structured sexual-history intake framework during a clinical assessment.',
			'List three evidence-based therapeutic interventions used to address intimacy concerns, sexual anxiety, or sexual dysfunction.',
			'Describe three ways developmental trauma, minority stress, stigma, or identity development may affect adult sexual expression and well-being.',
			'Apply at least two culturally responsive and affirming practices when working with diverse sexual orientations, gender identities, consensual non-monogamy, kink, or BDSM.',
			'Identify three ethical boundary requirements related to sexual attraction, erotic transference, countertransference, or dual relationships and select appropriate consultation or documentation responses.',
		),
		'completion_requirements' => array(
			'Complete all required instructional modules and embedded learning activities.',
			'Earn a score of at least 70% on the final examination. Participants may repeat the examination until the passing score is achieved.',
			'Complete the course-specific evaluation, including a rating for each measurable learning objective.',
			'Submit the required course-completion attestation for asynchronous distance learning.',
			'A CE certificate is issued only after all completion requirements are satisfied.',
		),
		'references'              => array(
			'American Psychiatric Association. (2022). Diagnostic and statistical manual of mental disorders (5th ed., text rev.).',
			'Hertlein, K. M., Weeks, G. R., & Sendak, S. K. (2020). Systemic sex therapy (3rd ed.). Routledge.',
			'Kleinplatz, P. J. (2022). Magnificent sex: Lessons from extraordinary lovers. Routledge.',
		),
		'development_draft'       => false,
		'modules'                 => array(
			array(
				'title'          => 'Foundations of Human Sexuality',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Historical perspectives on human sexuality',
					'Sexual health as a component of overall wellness',
					'Cultural influences on attitudes and beliefs',
					'Diversity in sexual expression and identity',
					'Common myths and misconceptions',
					'Language, values, and clinician self-awareness',
					'Role of mental health professionals in sexual-health discussions',
				),
			),
			array(
				'title'          => 'Physiological Foundations of Sexual Functioning',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Human sexual response cycle',
					'Desire, arousal, orgasm, and resolution',
					'Neurobiology and hormonal influences',
					'Impact of medications on sexual functioning',
					'Chronic illness, disability, and aging',
					'Medical contributors and referral considerations',
					'Integration of biological and psychological factors',
				),
			),
			array(
				'title'          => 'Psychosexual Development Across the Lifespan',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Development of sexual identity',
					'Lifespan perspectives on sexuality',
					'Attachment and relational influences',
					'Family, cultural, and societal factors',
					'Developmental milestones and challenges',
					'Sexual wellness across life stages',
					'Clinical implications for assessment and treatment',
				),
			),
			array(
				'title'          => 'Clinical Assessment and Sexual-History Taking',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Creating a safe and affirming assessment environment',
					'Structured sexual-history intake procedures',
					'Communication strategies for sensitive topics',
					'Assessment of sexual concerns and functioning',
					'Relational, cultural, and contextual factors',
					'Consent, safety, and trauma considerations',
					'Documentation and referral practices',
				),
			),
			array(
				'title'          => 'Sexual Dysfunctions and Diagnostic Considerations',
				'duration_mins'  => 60,
				'summary_points' => array(
					'DSM-5-TR sexual dysfunction diagnoses',
					'Medical, medication-related, psychological, and relational contributors',
					'Primary versus secondary presentations',
					'Situational versus generalized presentations',
					'Differential assessment and diagnostic uncertainty',
					'Treatment planning and interdisciplinary collaboration',
					'Referral to medical and specialized providers',
				),
			),
			array(
				'title'          => 'Identity, Diversity, and Minority Stress',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Gender identity and sexual orientation diversity',
					'LGBTQ+ affirmative practice',
					'Minority Stress Theory',
					'Consensual non-monogamy, kink, and BDSM-informed care',
					'Cultural humility and inclusive language',
					'Clinician bias and assumptions',
					'Health disparities and barriers to care',
				),
			),
			array(
				'title'          => 'Trauma, Intimacy, and Sexual Well-Being',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Impact of developmental and interpersonal trauma on sexuality',
					'Sexual assault and recovery considerations',
					'Body image and sexual self-concept',
					'Intimacy and relationship challenges',
					'Shame, stigma, and avoidance',
					'Trauma-informed pacing and consent',
					'Clinical interventions and referral considerations',
				),
			),
			array(
				'title'          => 'Evidence-Based Treatment Approaches',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Cognitive Behavioral Therapy for sexual concerns',
					'Sensate Focus interventions',
					'Couples-based and systemic approaches',
					'Anxiety-reduction and exposure-based strategies',
					'Communication and intimacy enhancement',
					'Strengths-based treatment planning',
					'Monitoring progress and adapting intervention',
				),
			),
			array(
				'title'          => 'Ethics, Boundaries, and Professional Practice',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Ethical responsibilities related to sexuality',
					'Professional boundaries and dual relationships',
					'Erotic transference and countertransference',
					'Managing clinician discomfort, attraction, and bias',
					'Consultation, referral, and scope of competence',
					'Risk management and documentation',
					'Application through clinical scenarios',
				),
			),
			array(
				'title'          => 'Clinical Integration and Final Review',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Integration of biological, psychological, relational, and cultural perspectives',
					'Complex case conceptualization',
					'Clinical decision-making exercises',
					'Ethical consultation and referral considerations',
					'Treatment planning across diverse presentations',
					'Review of major course concepts',
					'Professional-development and resource planning',
				),
			),
		),
	),
	array(
		'match_titles'            => array(
			'California Law & Ethics for Mental Health Professionals: Navigating the Evolving Clinical Landscape',
			'California Law & Ethics for Mental Health Professionals',
		),
		'title'                   => 'California Law & Ethics for Mental Health Professionals: Navigating the Evolving Clinical Landscape',
		'ce_hours'                => 6.0,
		'price'                   => 79.00,
		'category'                => 'Law & Ethics',
		'description'             => 'This asynchronous continuing education course provides structured clinical training in California Law & Ethics for Mental Health Professionals: Navigating the Evolving Clinical Landscape. It is designed for LMFTs, LCSWs, LPCCs, LEPs, and Registered Associates and combines online text, instructional video modules, downloadable resources, case studies, and clinical application exercises.',
		'course_level'            => 'Introductory to Intermediate',
		'target_audience'         => 'LMFTs, LCSWs, LPCCs, LEPs, and Registered Associates',
		'instructional_method'    => 'Asynchronous Distance Learning',
		'course_code'             => 'CTA-CE-001',
		'presenter'               => 'Candice Fuimaono, MS, LMFT',
		'image_alt'               => 'California Law & Ethics for Mental Health Professionals course image from Clinical Training and Supervision Academy',
		// Thumbnail applied by CTA_Law_Ethics_Module_Sync::sync_thumbnail() (bundled Course Image JPG).
		'educational_goals'       => array(
			'Strengthen the ability to identify and respond to legal and ethical issues encountered in California mental health practice.',
			'Enhance knowledge of California laws, regulations, professional standards, and Board of Behavioral Sciences expectations.',
			'Improve informed-consent, confidentiality, privilege, documentation, record-management, and risk-management practices.',
			'Increase confidence in making legally and ethically sound decisions involving minors, digital practice, crisis response, and professional boundaries.',
			'Support client welfare, professional accountability, and continuity of care across private and organizational settings.',
		),
		'learning_objectives'     => array(
			'Identify four California legal, regulatory, or ethical sources that govern mental health practice and distinguish scope of practice from scope of competence.',
			'Prepare an informed-consent checklist that includes required fee, privacy, telehealth, digital-communication, and professional-boundary elements.',
			'Distinguish confidentiality, psychotherapist-patient privilege, and lawful disclosure and select an appropriate response to a subpoena or request for records.',
			'Apply California minor-consent, parental-involvement, custody, and mandated-reporting standards to a clinical case example.',
			'Apply California duty-to-protect, crisis-intervention, and documentation standards to a case involving suicide risk or a serious threat of violence.',
			'Prepare a record-management and practice-continuity plan that addresses client access, retention, security, practice closure, professional wills, and licensure or business-risk concerns.',
		),
		'completion_requirements' => array(
			'Complete all required instructional modules, including the Course Integration Capstone, and embedded learning activities.',
			'Earn a score of at least 70% on the final examination. Participants may repeat the examination until the passing score is achieved.',
			'Complete the course-specific evaluation, including a rating for each measurable learning objective.',
			'Submit the required course-completion attestation for asynchronous distance learning.',
			'A CE certificate is issued only after all completion requirements are satisfied.',
		),
		'references'              => array(
			'California Association of Marriage and Family Therapists. (2019). CAMFT code of ethics. CAMFT.',
			'Caldwell, B. E. (2020). User\'s guide to the 2019 CAMFT code of ethics. Ben Caldwell Labs.',
			'Zur, O. (2021). Digital ethics and telehealth in psychotherapy: Navigating the boundaries of remote care. Routledge.',
		),
		'development_draft'       => false,
		// Mid-course knowledge check (after Module 3) is administrative — not CE instructional time.
		'mid_course_knowledge_check_note' => 'Mid-course knowledge check — administrative activity. Not counted toward CE instructional minutes.',
		'modules'                 => array(
			array(
				'title'            => 'Module 1: California Regulatory Frameworks, BBS Requirements, and Professional Competence',
				'duration_runtime' => '60:07',
				'duration_mins'    => 60,
				'video_url'        => 'https://vimeo.com/1214611219',
				'summary_points'   => array(
					'California regulatory updates and Board of Behavioral Sciences requirements',
					'Scope of competence and ethical practice standards in California mental health practice',
					'Professional ethical standards for clinical practice',
					'Common disciplinary concerns and risk factors',
					'Regulatory sources that govern mental health practice',
					'Application of current BBS expectations',
				),
			),
			array(
				'title'            => 'Module 2: Informed Consent, Telehealth, and Digital Boundaries',
				'duration_runtime' => '58:08',
				'duration_mins'    => 58,
				'video_url'        => 'https://vimeo.com/1214902641',
				'summary_points'   => array(
					'Legal and ethical requirements for informed consent',
					'Fee, privacy, telehealth, and professional-boundary disclosures',
					'Digital practice boundaries and electronic communication',
					'Consultation, referral, and documentation of competence decisions',
				),
			),
			array(
				'title'            => 'Module 3: Confidentiality, Privilege, and Lawful Disclosure',
				'duration_runtime' => '62:35',
				'duration_mins'    => 62,
				'video_url'        => 'https://vimeo.com/1214856706',
				'summary_points'   => array(
					'Legal and ethical foundations of confidentiality',
					'Psychotherapist-patient privilege considerations',
					'Mandatory and permissive disclosure exceptions',
					'Mandated reporting standards and thresholds',
					'Application through confidentiality and reporting scenarios',
				),
			),
			array(
				'title'            => 'Module 4: Working with Minors: Consent, Parents, Custody, and Reporting',
				'duration_runtime' => '58:18',
				'duration_mins'    => 58,
				'video_url'        => 'https://vimeo.com/1214861621',
				'summary_points'   => array(
					'Minor-consent treatment regulations',
					'Parental rights and involvement considerations',
					'Confidentiality considerations when treating minors',
					'Application through minor-consent case examples',
				),
			),
			array(
				'title'            => 'Module 5: Crisis Management, Tarasoff Duties, and Professional Liability',
				'duration_runtime' => '53:21',
				'duration_mins'    => 53,
				'video_url'        => 'https://vimeo.com/1214876352',
				'summary_points'   => array(
					'Tarasoff duty-to-protect requirements',
					'Crisis management and emergency-response procedures',
					'Documentation of risk assessment and protective actions',
					'Application through crisis case examples',
				),
			),
			array(
				'title'            => 'Module 6: Record Keeping, Business Ethics, and Practice Continuity',
				'duration_runtime' => '55:03',
				'duration_mins'    => 55,
				'video_url'        => 'https://vimeo.com/1215024927',
				'summary_points'   => array(
					'Defensible clinical documentation standards',
					'Record-retention and security requirements',
					'Risk-management strategies for clinicians',
					'Licensure maintenance and professional practice ethics',
					'Professional wills and practice closure considerations',
				),
			),
			array(
				'title'            => 'Required Course Integration Capstone: Applying California Law and Ethics in Complex Clinical Decisions',
				'duration_runtime' => '14:05',
				'duration_mins'    => 14,
				'video_url'        => 'https://vimeo.com/1214922839',
				'summary_points'   => array(
					'Integrate legal and ethical decision-making across Modules 1–6',
					'Apply California Law & Ethics standards to complex clinical scenarios',
					'Prepare for the final examination with structured clinical reasoning',
				),
			),
		),
	),
	array(
		'match_titles'            => array(
			'Advanced Suicide Risk Assessment: Evidence-Based Intervention and Ethical Documentation',
			'Advanced Suicide Risk Assessment',
		),
		'title'                   => 'Advanced Suicide Risk Assessment: Evidence-Based Intervention and Ethical Documentation',
		'slug'                    => 'advanced-suicide-risk-assessment',
		'ce_hours'                => 6.0,
		'price'                   => 79.00,
		'category'                => 'Clinical Skills',
		'short_description'       => 'Strengthen clinical judgment in suicide-risk assessment, formulation, safety planning, escalation, documentation, and postvention. This six-hour asynchronous course helps California mental health professionals use structured tools appropriately, develop person-specific formulations, apply collaborative safety-planning and lethal-means-safety principles, navigate level-of-care decisions, and document high-risk care clearly.',
		'description'             => array(
			'This course provides mental health professionals with advanced training in the assessment, formulation, management, documentation, and postvention of suicide risk across diverse clinical settings. Participants examine evidence-informed approaches to identifying warning signs and risk factors, conducting structured suicide inquiry, using the C-SSRS and SAFE-T appropriately, developing person-specific risk formulations, implementing collaborative safety planning and lethal-means safety, and responding to psychiatric emergencies.',
			'Emphasis is placed on clinical decision-making, ethical responsibilities, California legal considerations, consultation, level-of-care decisions, continuity of care, and documentation practices that support client safety and professional accountability. The course also addresses clinician reactions, critical-incident support, postvention following suicide death, and professional recovery.',
		),
		'course_code'             => 'CTA-CE-003',
		'course_code_status'      => 'provisional_pending_final_approval',
		'course_classification'   => 'Core Tier Continuing Education Course',
		'course_level'            => 'Intermediate to Advanced',
		'target_audience'         => 'LMFTs, LCSWs, LPCCs, and Registered Associates',
		'instructional_method'    => 'Asynchronous Distance Learning',
		'presenter'               => 'Candice Fuimaono, MS, LMFT',
		'provider'                => 'Clinical Training and Supervision Academy',
		'active_instructional_minutes_planned' => 360,
		'active_instructional_minutes_note' => 'Final recorded runtime remains controlling.',
		// OWNER DECISION REQUIRED — do not set access_period_months until client confirms.
		'access_period_pending'   => true,
		'access_period_status'    => 'pending_business_decision',
		'publication_status'      => 'under_review_not_approved_for_publication',
		'seo_title'               => 'Advanced Suicide Risk Assessment CE Course | CTA',
		'meta_description'        => 'A six-hour asynchronous CE course on suicide-risk assessment, person-specific formulation, safety planning, California escalation pathways, documentation, and postvention.',
		'primary_keyword'         => 'advanced suicide risk assessment continuing education',
		'secondary_keywords'      => array(
			'suicide safety planning CE',
			'California suicide risk course',
			'suicide documentation training',
			'clinician postvention',
		),
		'image_alt'               => 'Advanced Suicide Risk Assessment course image from Clinical Training and Supervision Academy',
		'educational_notice'      => 'Educational material only. This course does not provide legal advice, determine whether any individual meets emergency-detention criteria, establish a universal standard of care, or replace clinical supervision, consultation, current law, employer policy, emergency services, or case-specific legal counsel.',
		'who_this_course_is_for'  => array(
			'Licensed Marriage and Family Therapists',
			'Licensed Clinical Social Workers',
			'Licensed Professional Clinical Counselors',
			'Registered associates and other behavioral health professionals seeking advanced suicide-risk training, subject to provider and licensure rules',
		),
		'included_materials'      => array(
			'Six instructional video modules',
			'Embedded formative knowledge checks with immediate feedback',
			'25-question final examination',
			'Course-specific evaluation and completion attestation',
			'Clinician-facing learner resource toolkit',
			'Downloadable transcript or narration materials as approved',
			'CE certificate after all requirements are satisfied',
		),
		'learning_objectives'     => array(
			'Identify at least five warning signs, risk factors, or protective factors associated with suicide risk and distinguish chronic suicidal ideation, acute suicidal intent, and non-suicidal self-injury.',
			'Apply the Columbia-Suicide Severity Rating Scale and the SAFE-T framework to a clinical case and classify information needed for a comprehensive suicide-risk formulation.',
			'Prepare a collaborative six-step safety plan that includes warning signs, coping strategies, social supports, professional resources, and lethal-means safety.',
			'Identify three clinical or legal factors relevant to a California danger-to-self determination and select an appropriate crisis-response or level-of-care action.',
			'Write a suicide-risk documentation note that includes at least four elements supporting clinical rationale, consultation, intervention, and follow-up.',
			'Design a postvention and clinician-support protocol that addresses continuity of care, consultation, countertransference, secondary traumatic stress, and professional wellness.',
		),
		'certificate_title'       => 'Advanced Suicide Risk Assessment: Evidence-Based Intervention and Ethical Documentation',
		'certificate_completion_statement' => 'The participant completed all required instructional modules, passed the 25-question final examination with a score of at least 70%, submitted the course-specific evaluation, and completed the required attestation.',
		// Thumbnail applied by CTA_Suicide_Risk_Certificate_Sync::sync_thumbnail() (bundled PNG + Media Library Suicide.png).
		'completion_requirements' => array(
			'Complete all required instructional modules and embedded learning activities.',
			'Earn a score of at least 70% on the final examination. Participants may repeat the examination until the passing score is achieved.',
			'Complete the course-specific evaluation, including a rating for each measurable learning objective.',
			'Submit the required course-completion attestation for asynchronous distance learning.',
			'A CE certificate is issued only after all completion requirements are satisfied.',
		),
		'references'              => array(
			'Boudreaux, E. D., & Camargo, C. A. (2021). Managing suicidal risk in the modern clinical setting: Tools for screening and stabilization. Oxford University Press.',
			'Bryan, C. J. (2022). Rethinking suicide: Why prevention fails, and how we can do better. Oxford University Press.',
			'Stanley, B., & Brown, G. K. (2020). Safety planning intervention: A brief intervention to mitigate suicide risk. Journal of Clinical Psychiatry, 81(2), 11-19.',
		),
		'development_draft'       => true,
		'modules'                 => array(
			array(
				'title'          => 'The Epidemiology and Phenomenology of Suicide',
				'duration_mins'  => 60,
				'summary_points' => array(
					'National and regional suicide statistics',
					'Trends across demographic and clinical groups',
					'Mental illness, substance use, and suicide risk',
					'Psychosocial stressors and high-risk transitions',
					'Chronic suicidal ideation versus acute intent',
					'Non-suicidal self-injury versus suicidal behavior',
					'Continuum and context of suicide risk',
				),
			),
			array(
				'title'          => 'Standardized Assessment and Comprehensive Risk Formulation',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Importance and limitations of structured tools',
					'Columbia-Suicide Severity Rating Scale',
					'SAFE-T framework',
					'Warning signs, risk factors, and protective factors',
					'Assessment beyond intuition or a single score',
					'Risk formulation and clinical decision-making',
					'Translating findings into treatment and disposition decisions',
				),
			),
			array(
				'title'          => 'Moving Beyond No-Harm Contracts to Collaborative Safety Planning',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Limitations of no-harm or no-suicide contracts',
					'Evidence supporting collaborative safety planning',
					'Stanley-Brown Safety Planning Intervention',
					'Personal warning signs and internal coping strategies',
					'Social supports and environmental distractions',
					'Professional resources and crisis contacts',
					'Lethal-means safety and collaborative implementation',
				),
			),
			array(
				'title'          => 'Involuntary Evaluation, Hospitalization, and Legal Thresholds',
				'duration_mins'  => 60,
				'summary_points' => array(
					'California Welfare and Institutions Code section 5150',
					'Danger-to-self considerations',
					'Clinical indicators supporting emergency evaluation',
					'When hospitalization may be clinically appropriate',
					'Coordination with mobile crisis, emergency departments, and law enforcement',
					'Voluntary alternatives and least-restrictive care',
					'Legal and ethical considerations involving minors',
				),
			),
			array(
				'title'          => 'Clinical Documentation, Consultation, and Liability Management',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Documentation of risk and protective factors',
					'Recording assessment findings and clinical rationale',
					'Incorporating standardized tools into progress notes',
					'Consultation and supervision documentation',
					'Interventions considered, selected, and declined',
					'Follow-up, continuity of care, and communication',
					'Defensible standards of care and risk management',
				),
			),
			array(
				'title'          => 'Postvention, Clinician Wellness, and Professional Recovery',
				'duration_mins'  => 60,
				'summary_points' => array(
					'Clinical and emotional impact of suicide-related cases',
					'Response following attempts or suicide deaths',
					'Postvention, continuity of care, and communication',
					'Peer consultation and professional support',
					'Secondary traumatic stress and compassion fatigue',
					'Countertransference awareness and management',
					'Long-term clinician wellness and professional recovery',
				),
			),
		),
	),
	array(
		'match_titles'            => array(
			'Clinical and Ethical Excellence in Telehealth: The Essential California Framework',
			'Clinical and Ethical Excellence in Telehealth',
		),
		'title'                   => 'Clinical and Ethical Excellence in Telehealth: The Essential California Framework',
		'slug'                    => 'clinical-ethical-excellence-telehealth-california',
		'ce_hours'                => 3.0,
		'price'                   => 45.00,
		'category'                => 'Clinical Skills',
		'short_description'       => 'Strengthen the legal, ethical, clinical, privacy, and crisis-response systems needed to provide safer and more effective telehealth services in California mental health practice.',
		'description'             => array(
			'This three-hour asynchronous course provides California mental health professionals with a practical framework for delivering legally informed, ethically sound, and clinically effective telehealth services. Participants examine current California telehealth requirements, jurisdiction and interstate-practice concerns, informed consent, each-session identity and location procedures, telehealth appropriateness, crisis-response planning, electronic privacy and security safeguards, digital communication, professional boundaries, and technology-failure continuity.',
			'Through realistic scenarios, knowledge checks, structured decision-making, and a downloadable clinical resource toolkit, learners strengthen the systems they use to protect client welfare, support continuity of care, document professional reasoning, and respond when remote practice conditions change.',
		),
		'course_level'            => 'Introductory to Intermediate',
		'target_audience'         => 'LMFTs, LCSWs, LPCCs, and Registered Associates',
		'instructional_method'    => 'Asynchronous Distance Learning',
		'course_code'             => 'CTA-CE-002',
		'course_classification'   => 'Foundational CE Course',
		'presenter'               => 'Candice Fuimaono, MS, LMFT',
		'seo_title'               => 'Clinical and Ethical Excellence in Telehealth | 3 CE Hours | CTA',
		'meta_description'        => 'A 3-hour California telehealth CE course covering legal requirements, jurisdiction, intake, crisis planning, privacy, security, digital communication, and continuity of care.',
		'image_alt'               => 'Clinical and Ethical Excellence in Telehealth course thumbnail from Clinical Training and Supervision Academy',
		// OWNER DECISION REQUIRED — do not set access_period_months here.
		// Thumbnail applied by CTA_Telehealth_Exam_Sync::sync_thumbnail() (Media Library Telehealth.png).
		'educational_goals'       => array(),
		'learning_objectives'     => array(
			'Identify at least four California legal or ethical requirements governing telehealth initiation, informed consent, jurisdiction, and each-session safety procedures.',
			'Apply a telehealth intake and session-opening protocol that includes identity verification, present-location verification, appropriateness assessment, and documentation.',
			'Design a telehealth emergency-response plan that includes local resources, an emergency contact, present-location procedures, backup communication, and continuity steps.',
			'Identify at least three administrative, physical, or technical safeguards that protect electronic client information during telehealth services.',
			'Apply procedures for managing technology disruptions and electronic communications while maintaining privacy, continuity of care, and professional boundaries.',
		),
		'key_topics'              => array(
			'California telehealth law and BBS practice standards',
			'Jurisdiction and interstate-practice verification',
			'Telehealth consent, initiation, and each-session procedures',
			'Identity and present-location verification',
			'Telehealth appropriateness and higher-risk planning',
			'Emergency resources, backup communication, and continuity',
			'Privacy and security safeguards for electronic client information',
			'Technology and vendor review, including BAAs when applicable',
			'Digital communication and professional boundaries',
			'Technology-failure response and documentation',
		),
		'completion_requirements' => array(
			'Complete all three instructional modules and required learning activities; earn at least 70% (18 of 25) on the final examination; complete the course-specific evaluation; and submit the completion attestation. Examination attempts are unlimited and there is no examination time limit. The certificate becomes available only after all requirements are satisfied.',
		),
		'educational_notice'      => 'This course is educational and does not replace clinical judgment, supervision, legal consultation, emergency consultation, organizational policy, or verification of current laws and regulations. Requirements may change; clinicians remain responsible for confirming the rules that apply to their profession, setting, client location, and circumstances.',
		'references'              => array(
			'Board of Behavioral Sciences. (2023). Statutes and regulations relating to the practice of marriage and family therapy, licensed clinical social work, and licensed professional clinical counseling. State of California.',
			'Maheu, M. M., Drude, K. P., & Hertlein, K. M. (2020). The telehealth professions: Principles and practices for mental health and substance use disorders. Springer Publishing Company.',
			'Zur, O. (2021). Digital ethics and telehealth in psychotherapy: Navigating the boundaries of remote care. Routledge.',
		),
		'development_draft'       => false,
		'modules'                 => array(
			array(
				'title'          => 'California Legal Foundations and Jurisdictional Boundaries',
				'duration_mins'  => 60,
				'video_url'      => 'https://vimeo.com/1213776719',
				'summary_points' => array(
					'California telehealth law and BBS practice standards',
					'Jurisdiction and interstate-practice verification',
					'Telehealth consent, initiation, and each-session procedures',
				),
			),
			array(
				'title'          => 'Intake, Identity and Location Verification, and Crisis Protocols',
				'duration_mins'  => 60,
				'video_url'      => 'https://vimeo.com/1213835801',
				'summary_points' => array(
					'Identity and present-location verification',
					'Telehealth appropriateness and higher-risk planning',
					'Emergency resources, backup communication, and continuity',
				),
			),
			array(
				'title'          => 'HIPAA Safeguards, Digital Privacy, and Professional Boundaries',
				'duration_mins'  => 60,
				'video_url'      => 'https://vimeo.com/1214204058',
				'summary_points' => array(
					'Privacy and security safeguards for electronic client information',
					'Technology and vendor review, including BAAs when applicable',
					'Digital communication and professional boundaries',
					'Technology-failure response and documentation',
				),
			),
		),
	),
);
